apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ocs
  namespace: local
spec:
  sourceType: internal
  configMap: ocs
  displayName: Couchbase Cloud Services
  publisher: Couchbase
