//go:build apitest
// +build apitest

package couchbaseutil

import (
	"context"
	"strings"
	"testing"
	"time"

	"github.com/couchbase/couchbase-operator/pkg/metrics"
)

var defaultHost = "http://localhost:8091"

func InitTest() *Client {
	metrics.InitMetrics()

	client := New(context.Background(), "cb-example", "Administrator", "password")

	return client
}

func TestGetPoolsDefault(t *testing.T) {
	client := InitTest()

	var pools PoolsInfo

	if err := GetPools(&pools).On(client, defaultHost); err != nil {
		t.Fatal(err)
	}
}

var TestKeys = []EncryptionKey{
	{
		Type:  EncryptionKeyTypeCBServerManagedAES256,
		Name:  "testKey",
		Usage: []string{EncryptionKeyUsageBucketEncryptionAll},
		AutoGenerated: &AutoGeneratedKeyData{
			AutoRotation: false,
			EncryptWith:  EncryptionKeyEncryptWithNodeSecretManager,
		},
	},
	{
		Type:  EncryptionKeyTypeCBServerManagedAES256,
		Name:  "testKeyAutoRotation",
		Usage: []string{EncryptionKeyUsageBucketEncryptionAll},
		AutoGenerated: &AutoGeneratedKeyData{
			AutoRotation:           true,
			RotationIntervalInDays: 30,
			NextRotationTime:       time.Now().Add(30 * 24 * time.Hour).Format(time.RFC3339),
			EncryptWith:            EncryptionKeyEncryptWithNodeSecretManager,
		},
	},
	{
		Type:  EncryptionKeyTypeCBServerManagedAES256,
		Name:  "testKeyAllUsage",
		Usage: []string{EncryptionKeyUsageBucketEncryptionAll, EncryptionKeyUsageConfigEncryption, EncryptionKeyUsageKEKEncryption, EncryptionKeyUsageLogsEncryption, EncryptionKeyUsageAuditEncryption},
		AutoGenerated: &AutoGeneratedKeyData{
			AutoRotation: false,
			EncryptWith:  EncryptionKeyEncryptWithNodeSecretManager,
		},
	},
	{
		Type:  EncryptionKeyTypeCBServerManagedAES256,
		Name:  "testKeyCanBeCached",
		Usage: []string{EncryptionKeyUsageBucketEncryptionAll},
		AutoGenerated: &AutoGeneratedKeyData{
			CanBeCached: true,
			EncryptWith: EncryptionKeyEncryptWithNodeSecretManager,
		},
	},
}

func TestCreateEncryptionKeys(t *testing.T) {
	client := InitTest()

	// Delete any existing keys
	MustDeleteTestKeys(t, client)

	// Defer the deletion of the created test keys at the end of the test
	defer MustDeleteTestKeys(t, client)

	// Create the test keys
	for _, key := range TestKeys {
		if err := CreateEncryptionKey(&key).On(client, defaultHost); err != nil {
			t.Fatal(err)
		}
	}

}

func TestDeleteAllKeys(t *testing.T) {
	client := InitTest()

	var keys EncryptionKeyList

	if err := ListEncryptionKeys(&keys).On(client, defaultHost); err != nil {
		t.Fatal(err)
	}

	for _, key := range keys {
		if err := DeleteEncryptionKey(key.ID).On(client, defaultHost); err != nil {
			t.Fatal(err)
		}
	}
}

func MustDeleteTestKeys(t *testing.T, client *Client) {
	var keys EncryptionKeyList

	if err := ListEncryptionKeys(&keys).On(client, defaultHost); err != nil {
		t.Fatal(err)
	}

	for _, key := range keys {
		if !strings.HasPrefix(key.Name, "testKey") {
			continue
		}

		if err := DeleteEncryptionKey(key.ID).On(client, defaultHost); err != nil {
			t.Fatal(err)
		}
	}
}

func TestUpdateConfigurationEncryptionSettings(t *testing.T) {
	client := InitTest()

	settings := EncryptionAtRestSettings{
		EncryptionMethod:    EncryptionMethodNodeSecretManager,
		DEKLifetime:         211 * 24 * 60 * 60,
		DEKRotationInterval: 43 * 24 * 60 * 60,
		EncryptionKeyID:     -1,
	}

	if err := UpdateConfigurationEncryptionSettings(&settings).On(client, defaultHost); err != nil {
		t.Fatal(err)
	}
}
