apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: default
---
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-example
spec:
  image: couchbase/server:6.6.2
  security:
    adminSecret: cb-example-auth
  buckets:
    managed: true
  servers:
    - size: 3
      name: all_services
      services:
        - data
        - index
        - query
        - search
        - eventing
        - analytics
      volumeMounts:
        default: couchbase
        data:  couchbase
        index: couchbase
        analytics:
          - couchbase
          - couchbase
  securityContext:
    fsGroup: 1000
  volumeClaimTemplates:
    - metadata:
        name: couchbase
      spec:
        storageClassName: "standard"
        resources:
          requests:
            storage: 1Gi
