---
apiVersion: batch/v1
kind: Job
metadata:
  name: collect-info
spec:
  template:
    metadata:
      name: collect
    spec:
      containers:
      - name: collect-info
        image: sequoiatools/couchbase-cli:v5.0.1
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "couchbase-cli-secure collect-logs-start
                              -c ${CLUSTER_NAME}
                              -u {auth.admin.username}
                              -p {auth.admin.password}
                              --all-nodes"]
        env:
          - name: CLUSTER_NAME
            value: cb-example
        volumeMounts:
          - name: cb-admin
            mountPath: "/auth/admin"
      volumes:
        - name: cb-admin
          secret:
            secretName: cb-example-auth
      restartPolicy: Never
