apiVersion: "couchbase.database.couchbase.com/v1beta1"
kind: "CouchbaseCluster"
metadata:
  name: "cb-example"
spec:
  size: 3
  baseImage: couchbase/server
  version: "enterprise-4.5.1"
  cluster:
    username: "Administrator"
    password: "password"
    services: "kv,index,n1ql"
    dataServiceMemoryQuota: 256
    indexServiceMemoryQuota: 256
    searchServiceMemoryQuota: 256
    indexStorageSetting: default
  buckets:
    - name: default
      type: couchbase
      memoryQuota: 128
      replicas: 0
      ioPriority: high
      evictionPolicy: fullEviction
      conflictResolution: sequence
      enableFlush: true
      enableIndexReplica: false
