apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: default
spec:
  memoryQuota: 128
  replicas: 1
  ioPriority: high
  evictionPolicy: fullEviction
  conflictResolution: seqno
  enableFlush: true
  enableIndexReplica: false
  compressionMode: passive
---
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-example
spec:
  image: couchbase/server:enterprise-6.0.1
  security:
    adminSecret: cb-example-auth
    rbac:
      managed: true
  networking:
    exposeAdminConsole: true
    adminConsoleServices:
      - data
    exposedFeatures:
      - xdcr
    exposedFeatureServiceType: NodePort
    adminConsoleServiceType: NodePort
  cluster:
    dataServiceMemoryQuota: 256
    indexServiceMemoryQuota: 256
    searchServiceMemoryQuota: 256
    eventingServiceMemoryQuota: 256
    analyticsServiceMemoryQuota: 1024
    indexStorageSetting: memory_optimized
    autoFailoverTimeout: 120
    autoFailoverMaxCount: 3
    autoFailoverOnDataDiskIssues: true
    autoFailoverOnDataDiskIssuesTimePeriod: 120
    autoFailoverServerGroup: false
  buckets:
    managed: true
  servers:
    - size: 3
      name: all_services
      services:
        - data
        - index
        - query
        - search
        - eventing
        - analytics
