---
apiVersion: couchbase.com/v2
kind: CouchbaseUser
metadata:
  name: admin-user
spec:
  fullName: Administrator
  authDomain: local
  authSecret: cb-example-auth
---
apiVersion: couchbase.com/v2
kind: CouchbaseGroup
metadata:
  name: ldap-group
spec:
  ldapGroupRef: cn=mygroup,ou=Groups,dc=example,dc=com
---
apiVersion: couchbase.com/v2
kind: CouchbaseRole
metadata:
  name: admin-role
spec:
  roles:
  - name: cluster_admin
  - name: bucket_admin
    bucket: default
---
apiVersion: couchbase.com/v2
kind: CouchbaseRoleBinding
metadata:
  name: admin-role-binding
spec:
  roleRef:
    kind: CouchbaseRole
    name: admin-role
  subjects:
  - kind: CouchbaseUser
    name: admin-user
  - kind: CouchbaseGroup
    name: ldap-group
