# Copyright 2018-Present Couchbase, Inc.
#
# Use of this software is governed by the Business Source License included in
# the file licenses/BSL-Couchbase.txt.  As of the Change Date specified in that
# file, in accordance with the Business Source License, use of this software
# will be governed by the Apache License, Version 2.0, included in the file
# licenses/APL2.txt.

apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: default
---
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-example
spec:
  image: couchbase/server:6.5.0
  security:
    adminSecret: cb-example-auth
  serverGroups:
    - us-east-1a
    - us-east-1b
    - us-east-1c
  buckets:
    managed: true
  servers:
    - name: data
      size: 3
      services:
        - data
        - index
    - name: query
      size: 2
      services:
        - query
        - search
      serverGroups:
        - us-east-1a
        - us-east-1b
