# Copyright 2019-Present Couchbase, Inc.
#
# Use of this software is governed by the Business Source License included in
# the file licenses/BSL-Couchbase.txt.  As of the Change Date specified in that
# file, in accordance with the Business Source License, use of this software
# will be governed by the Apache License, Version 2.0, included in the file
# licenses/APL2.txt.

version: "2"

run:
  timeout: 5m

linters:
  default: all
  settings:
    dupl:
      threshold: 300
  disable:
    - dupword
    - embeddedstructfieldcheck
    - funcorder
    - godoclint
    - iotamixing
    - lll
    - modernize
    - noinlineerr
    - gomodguard
    - unqueryvet
    - usetesting
    - varnamelen
    - exhaustruct
    - contextcheck
    - nosprintfhostport
    - nonamedreturns
    - nilnil
    - maintidx
    - ireturn
    - containedctx
    - gosec
    - nestif
    - mnd
    - testpackage
    - godox
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - prealloc
    - nakedret
    - exhaustive
    - paralleltest
    - nlreturn
    - noctx
    - wrapcheck
    - forbidigo
    - promlinter
    - cyclop
    - nilerr
    - forcetypeassert
    - tagliatelle
    - predeclared
    - thelper
    - durationcheck
    - depguard
    - tagalign
    - mirror
    - nolintlint
    - usestdlibvars
    - staticcheck
    - reassign
    - musttag
    - loggercheck
    - interfacebloat
    - revive
    - inamedparam
    - perfsprint
    - err113
    - recvcheck
    - govet
    - intrange
    - nilnesserr
    - protogetter
    - testifylint
    - unparam
    - wsl_v5
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: ST1016
      - linters:
          - unparam
        text: always receives
      - linters:
          - gocritic
        text: appendAssign
      - linters:
          - gocritic
        text: deprecatedComment
      - linters:
          - err113
          - gocognit
          - gocyclo
        path: test/.*
      - linters:
          - err113
        path: cmd/.*
      - linters:
          - err113
        path: pkg/admission/.*
      - linters:
          - err113
        path: pkg/config/.*
      - linters:
          - err113
        path: pkg/info/.*
      - linters:
          - err113
        path: pkg/validator/.*
    paths:
      - '^pkg/generated/'
      - '.*zz_generated\\.deepcopy\\.go$'
      - third_party$
      - builtin$
      - examples$

formatters:
  # enable:
    # - gofmt
    # - goimports
    # - gofumpt
  exclusions:
    generated: lax
    paths:
      - '^pkg/generated/'
      - '.*zz_generated\\.deepcopy\\.go$'
      - third_party$
      - builtin$
      - examples$
