ARG GO_VERSION=1.17.2
FROM golang:${GO_VERSION}-alpine

ENV CGO_ENABLED=0
ENV GOCACHE=/go/cache

ADD scripts/passwd /etc/passwd

ADD docs/License.txt /License.txt
ADD docs/README.txt /README.txt

# git is required for go to fetch dependencies
RUN apk update && apk add --no-cache \
    git && \
    go get github.com/go-delve/delve/cmd/dlv

RUN chown -R non-root /go
USER 8453
WORKDIR /go/src/github.com/couchbase/couchbase-operator

COPY . .

RUN go mod download
