PREFIX ?= $(shell pwd)
SOURCE = $(shell find . -name *.go -type f)
OPERATOR_BINARY = build/bin/couchbase-operator
ADMISSION_BINARY = build/bin/couchbase-operator-admission
CBOPCFG_BINARY = build/bin/cbopcfg
CBOPINFO_BINARY = build/bin/cbopinfo
ARTIFACTS = build/artifacts
OPERATOR_ARTIFACTS = $(ARTIFACTS)/couchbase-operator
ADMISSION_ARTIFACTS = $(ARTIFACTS)/couchbase-admission-controller

kubeconfig = $(if $(KUBECONFIG),$(KUBECONFIG),$(HOME)/.kube/config)
operatorImage = $(if $(OPERATOR_IMAGE),$(OPERATOR_IMAGE),couchbase/couchbase-operator:v1)
namespace = $(if $(KUBENAMESPACE),$(KUBENAMESPACE),default)
deploymentSpec = $(if $(DEPLOYMENTSPEC),$(DEPLOYMENTSPEC),$(PREFIX)/example/deployment.yaml)
bldNum = $(if $(BLD_NUM),$(BLD_NUM),999)
version = $(if $(VERSION),$(VERSION),2.2.0)
testname = $(E2E_TEST)

# This allows the container tags to be explicitly set.
DOCKER_USER = couchbase
DOCKER_TAG = v1

# Set this to, for example beta1, for a beta release.
# This will affect the "-v" version strings and docker images.
# This is analogous to revisions in DEB and RPM archives.
revision = $(if $(REVISION),$(REVISION),)

# Revisioned version is used for package creation.
ifeq ($(revision),)
revisionedVersion = $(version)
revisionedProductVersion = $(version)-$(bldNum)
else
revisionedVersion = $(version)-$(revision)
revisionedProductVersion = $(version)-$(revision)-$(bldNum)
endif

# What exact revision is this?
GIT_REVISION := $(shell git rev-parse HEAD)

# Common flags for all builds.
GOENV = CGO_ENABLED=0

# Flags for containerized builds.
CONTAINER_GOENV = $(GOENV) GOOS=linux GOARCH=amd64

# These are propagated into each binary so we can tell for sure the exact build
# that a binary came from.
LDFLAGS = "-X github.com/couchbase/couchbase-operator/pkg/version.Version=$(version) -X github.com/couchbase/couchbase-operator/pkg/version.Revision=$(revision) -X github.com/couchbase/couchbase-operator/pkg/version.BuildNumber=$(bldNum) -X github.com/couchbase/couchbase-operator/pkg/revision.gitRevision=$(GIT_REVISION)"

.PHONY: all generated binaries crd build-test lint container container-clean container-public dist test test-indv docs docs-lint

all: binaries crd

# These files define the V2 Kubernetes API.
APISRC_V2 = pkg/apis/couchbase/v2/doc.go \
	pkg/apis/couchbase/v2/types.go

# Modifying these files triggers a rebuild of kubernetes clients and informers.
APISRC = $(APISRC_V2)

# This is this module's name.
PACKAGE_BASE = github.com/couchbase/couchbase-operator

# This is the bsae of all kubernetes APIs we define.
API_PACKAGE_BASE = $(PACKAGE_BASE)/pkg/apis

# This is the set of directories we consider as autogenerated inputs (must be comma separated).
API_PACKAGE_V2 = $(API_PACKAGE_BASE)/couchbase/v2

# Clientset name (change me!)
CLIENTSET_NAME = versioned

# Go include path for generated content.
GENERATED_PACKAGE_BASE = $(PACKAGE_BASE)/pkg/generated
CLIENTSET_PACKAGE = $(GENERATED_PACKAGE_BASE)/clientset
LISTERS_PACKAGE = $(GENERATED_PACKAGE_BASE)/listers
INFORMERS_PACKAGE = $(GENERATED_PACKAGE_BASE)/informers

# Common arguments for the Kubernetes code generator tool chain.
CODEGEN_ARGS = --go-header-file scripts/codegen/boilerplate.go.txt --output-base ../../..

# CRD file target, contains all the CRDs.
CRD_FILE = example/crd.yaml

# These files (and directories) are auto generated.
GENERATED_FILES = pkg/apis/couchbase/v2/zz_generated.deepcopy.go \
	pkg/generated/clientset \
	pkg/generated/listers \
	pkg/generated/informers

# Build target to generate source.
generated: $(GENERATED_FILES)

# Timestamps aren't preserved by a git checkout, so the ordering is random as far
# as we're concerned.  This 'fixes' generated target timestamps after checkout to
# inhibit rebuilds.
touch-generated:
	touch ${GENERATED_FILES}

# Build the V2 deep copy functions when the API source changes.
pkg/apis/couchbase/v2/zz_generated.deepcopy.go: $(APISRC_V2)
	go run k8s.io/code-generator/cmd/deepcopy-gen --input-dirs $(API_PACKAGE_V2) -O zz_generated.deepcopy --bounding-dirs $(API_PACKAGE_BASE) $(CODEGEN_ARGS)

# Build the couchbase kubernetes client when any API source changes.
pkg/generated/clientset: $(APISRC)
	@rm -rf $@
	go run k8s.io/code-generator/cmd/client-gen --clientset-name $(CLIENTSET_NAME) --input-base "" --input $(API_PACKAGE_V2) --output-package $(CLIENTSET_PACKAGE) $(CODEGEN_ARGS)

# Build the couchbase kubernetes listers when any API source changes.
pkg/generated/listers: $(APISRC)
	@rm -rf $@
	go run k8s.io/code-generator/cmd/lister-gen --input-dirs $(API_PACKAGE_V2) --output-package $(LISTERS_PACKAGE) $(CODEGEN_ARGS)

# Build the couchbase kubernetes informers when the clients or listers update.
pkg/generated/informers: pkg/generated/clientset pkg/generated/listers
	@rm -rf $@
	go run k8s.io/code-generator/cmd/informer-gen --input-dirs $(API_PACKAGE_V2) --versioned-clientset-package $(CLIENTSET_PACKAGE)/$(CLIENTSET_NAME) --listers-package $(LISTERS_PACKAGE) --output-package $(INFORMERS_PACKAGE) $(CODEGEN_ARGS)

# Make the main binaries
binaries: $(OPERATOR_BINARY) $(ADMISSION_BINARY) $(CBOPCFG_BINARY) $(CBOPINFO_BINARY)

# Operator binary build target.
$(OPERATOR_BINARY): $(GENERATED_FILES) $(SOURCE)
	$(CONTAINER_GOENV) go build -o $@ -ldflags $(LDFLAGS) ./cmd/operator

# DAC binary build target.
$(ADMISSION_BINARY): $(GENERATED_FILES) $(SOURCE)
	$(CONTAINER_GOENV) go build -o $@ -ldflags $(LDFLAGS) ./cmd/admission

# cbopcfg binary build target.
$(CBOPCFG_BINARY): $(GENERATED_FILES) $(SOURCE)
	$(GOENV) go build -o $@ -ldflags $(LDFLAGS) ./cmd/cbopcfg

# cbopinfo binary build target.
$(CBOPINFO_BINARY): $(GENERATED_FILES) $(SOURCE)
	$(GOENV) go build -o $@ -ldflags $(LDFLAGS) ./cmd/cbopinfo

# Build target for the CRD files.
crd: $(CRD_FILE)

# Build the CRDs from the binary when the binary updates.
$(CRD_FILE): $(APISRC_V2)
	go run sigs.k8s.io/controller-tools/cmd/controller-gen crd:crdVersions=v1 paths=./pkg/apis/couchbase/v2 output:dir=example
	@cat example/couchbase.com_*.yaml > $@
	go run scripts/crd-transform.go -in $@ -out $@
	@rm example/couchbase.com_*.yaml

# Build target to test that e2e testing compiles.
build-test: $(GENERATED_FILES) $(SOURCE)
	go test -c $(PACKAGE_BASE)/test/e2e

# Lint target to test source code compliance.
lint: $(GENERATED_FILES)
	go run github.com/golangci/golangci-lint/cmd/golangci-lint run ./pkg/... ./cmd/... ./test/...

# Lint python scripts for dodgy code.
lint-python:
	scripts/pylinter

# NOTE: This target is only for local development. While we use this Dockerfile
# (for now), the actual "docker build" command is located in the Jenkins job
# "couchbase-operator-docker". We could make use of this Makefile there as
# well, but it is quite possible in future that the canonical Dockerfile will
# need to be moved to a separate repo in which case the "docker build" command
# can't be here anyway.
container: $(OPERATOR_BINARY) $(ADMISSION_BINARY) crd
	docker build -f Dockerfile -t ${DOCKER_USER}/couchbase-operator:${DOCKER_TAG} .
	docker build -f Dockerfile.admission -t ${DOCKER_USER}/couchbase-operator-admission:${DOCKER_TAG} .

# Clean up any images for this build, useful for CI jobs.
container-clean:
	docker rmi -f ${DOCKER_USER}/couchbase-operator:${DOCKER_TAG}
	docker rmi -f ${DOCKER_USER}/couchbase-operator-admission:${DOCKER_TAG}

# This target pushes the containers to a public repository.
# A typical one liner to deploy to the cloud would be:
# 	make container-public -e DOCKER_USER=couchbase DOCKER_TAG=2.0.0
container-public: container
	docker push ${DOCKER_USER}/couchbase-operator:${DOCKER_TAG}
	docker push ${DOCKER_USER}/couchbase-operator-admission:${DOCKER_TAG}

# NOTE: This target is only for local development. While we use this Dockerfile
# (for now), the actual "docker build" command is located in the Jenkins job
# "couchbase-operator-docker". We could make use of this Makefile there as
# well, but it is quite possible in future that the canonical Dockerfile will
# need to be moved to a separate repo in which case the "docker build" command
# can't be here anyway.
container-rhel: binaries crd
	docker build -f Dockerfile.rhel --build-arg OPERATOR_BUILD=$(OPERATOR_BUILD) --build-arg OS_BUILD=$(BUILD) --build-arg PROD_VERSION=$(VERSION) -t couchbase/couchbase-operator-rhel:v1 .
	docker build -f Dockerfile.admission-rhel --build-arg OPERATOR_BUILD=$(OPERATOR_BUILD) --build-arg OS_BUILD=$(BUILD) --build-arg PROD_VERSION=$(VERSION) -t couchbase/couchbase-operator-admission-rhel:v1 .

tools-kubernetes: PLATFORM=kubernetes
tools-kubernetes: tools-platform-specific

tools-openshift: PLATFORM=openshift
tools-openshift: GO_BUILD_FLAGS=-tags redhat
tools-openshift: tools-platform-specific

tools: generated
	$(MAKE) tools-kubernetes
	$(MAKE) tools-openshift
	GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -o build/darwin/x86_64/bin/cbopinfo -ldflags $(LDFLAGS) ./cmd/cbopinfo/
	GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -o build/darwin/arm64/bin/cbopinfo -ldflags $(LDFLAGS) ./cmd/cbopinfo/
	GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o build/linux/x86_64/bin/cbopinfo -ldflags $(LDFLAGS) ./cmd/cbopinfo/
	GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -o build/windows/amd64/bin/cbopinfo.exe -ldflags $(LDFLAGS) ./cmd/cbopinfo/

tools-platform-specific:
	GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -o build/${PLATFORM}/darwin/x86_64/bin/cbopcfg -ldflags $(LDFLAGS) ${GO_BUILD_FLAGS} ./cmd/cbopcfg/
	GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -o build/${PLATFORM}/darwin/arm64/bin/cbopcfg -ldflags $(LDFLAGS) ${GO_BUILD_FLAGS} ./cmd/cbopcfg/
	GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o build/${PLATFORM}/linux/x86_64/bin/cbopcfg -ldflags $(LDFLAGS) ${GO_BUILD_FLAGS} ./cmd/cbopcfg/
	GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -o build/${PLATFORM}/windows/amd64/bin/cbopcfg.exe -ldflags $(LDFLAGS) ${GO_BUILD_FLAGS} ./cmd/cbopcfg/

artifacts: tools crd
	WORKSPACE_DIR=$(PREFIX) ./scripts/artifact_gen.sh --platform kubernetes --os darwin --arch x86_64 --version $(revisionedVersion) --bld_num $(bldNum)
	WORKSPACE_DIR=$(PREFIX) ./scripts/artifact_gen.sh --platform kubernetes --os darwin --arch arm64 --version $(revisionedVersion) --bld_num $(bldNum)
	WORKSPACE_DIR=$(PREFIX) ./scripts/artifact_gen.sh --platform kubernetes --os linux --arch x86_64 --version $(revisionedVersion) --bld_num $(bldNum)
	WORKSPACE_DIR=$(PREFIX) ./scripts/artifact_gen.sh --platform kubernetes --os windows --arch amd64 --version $(revisionedVersion) --bld_num $(bldNum)
	WORKSPACE_DIR=$(PREFIX) ./scripts/artifact_gen.sh --platform openshift --os darwin --arch x86_64 --version $(revisionedVersion) --bld_num $(bldNum)
	WORKSPACE_DIR=$(PREFIX) ./scripts/artifact_gen.sh --platform openshift --os darwin --arch arm64 --version $(revisionedVersion) --bld_num $(bldNum)
	WORKSPACE_DIR=$(PREFIX) ./scripts/artifact_gen.sh --platform openshift --os linux --arch x86_64 --version $(revisionedVersion) --bld_num $(bldNum)
	WORKSPACE_DIR=$(PREFIX) ./scripts/artifact_gen.sh --platform openshift --os windows --arch amd64 --version $(revisionedVersion) --bld_num $(bldNum)

image-artifacts: binaries
	# Create a subdirectory for the operator docker build
	mkdir -p $(OPERATOR_ARTIFACTS)/docs
	mkdir -p $(OPERATOR_ARTIFACTS)/scripts
	mkdir -p $(OPERATOR_ARTIFACTS)/build/bin
	cp scripts/passwd $(OPERATOR_ARTIFACTS)/scripts/passwd
	cp docs/License.txt $(OPERATOR_ARTIFACTS)/docs/License.txt
	cp docs/README.txt $(OPERATOR_ARTIFACTS)/docs/README.txt
	cp $(OPERATOR_BINARY) $(OPERATOR_ARTIFACTS)/$(OPERATOR_BINARY)
	cp Dockerfile $(OPERATOR_ARTIFACTS)/Dockerfile
	cp Dockerfile.rhel $(OPERATOR_ARTIFACTS)/Dockerfile.rhel
	# Create a subdirectory for the admission controller docker build
	mkdir -p $(ADMISSION_ARTIFACTS)/docs
	mkdir -p $(ADMISSION_ARTIFACTS)/scripts
	mkdir -p $(ADMISSION_ARTIFACTS)/build/bin
	cp scripts/passwd $(ADMISSION_ARTIFACTS)/scripts/passwd
	cp docs/License.txt $(ADMISSION_ARTIFACTS)/docs/License.txt
	cp docs/README.txt $(ADMISSION_ARTIFACTS)/docs/README.txt
	cp $(ADMISSION_BINARY) $(ADMISSION_ARTIFACTS)/$(ADMISSION_BINARY)
	cp Dockerfile.admission $(ADMISSION_ARTIFACTS)/Dockerfile
	cp Dockerfile.admission-rhel $(ADMISSION_ARTIFACTS)/Dockerfile.rhel
	# Create the archive
	tar -C $(ARTIFACTS) -czf build/couchbase-operator-image_$(revisionedProductVersion).tgz .
	rm -rf $(ARTIFACTS)

# This target (and only this target) is invoked by the production build job.
# This job will archive all files that end up in the dist/ directory.
dist: touch-generated artifacts image-artifacts
	rm -rf dist
	mkdir dist
	cp build/couchbase-operator-image_*.tgz dist
	cp build/couchbase-autonomous-operator-*.tar.gz dist
	cp build/couchbase-autonomous-operator-*.zip dist

prod: container tools artifacts

prod-rhel: container-rhel tools-rhel artifacts

test-operator: $(GENERATED_FILES)
	go test github.com/couchbase/couchbase-operator/test/e2e -run TestOperator -v --race -timeout 240m

test-unit:
	go test -v ./pkg/...

test-helm:
	ct install --charts helm/test-resources/ --namespace ci-testnamespace

# Docs are partially auto-generated from the CRD.
docs: $(CRD_FILE)
	scripts/asciidoc-gen --version v2
	scripts/asciidoc-link
	go run scripts/mangen.go

docs-lint:
	scripts/asciidoc-lint
