---
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-example
spec:
  image: couchbase/server:6.5.0
  security:
    adminSecret: cb-example-auth
    rbac:
      managed: true
    ldap:
      hosts:
      - ldap.example.com
      port: 389
      encryption: None
      bindSecret: cb-example-auth
      bindDN: "cn=admin,dc=example,dc=com"
      authenticationEnabled: true
      userDNMapping:
      - template: "uid={0},ou=People,dc=example,dc=com"
        re: "(.+)"
      authorizationEnabled: true
      groupsQuery: "cn=mygroup,ou=Groups,dc=example,dc=com??base?"
  networking:
    exposeAdminConsole: true
    adminConsoleServices:
      - data
    exposedFeatures:
      - xdcr
    exposedFeatureServiceType: NodePort
    adminConsoleServiceType: NodePort
  cluster:
    dataServiceMemoryQuota: 256
    indexServiceMemoryQuota: 256
    searchServiceMemoryQuota: 256
    eventingServiceMemoryQuota: 256
    analyticsServiceMemoryQuota: 1024
    indexStorageSetting: memory_optimized
    autoFailoverTimeout: 120
    autoFailoverMaxCount: 3
    autoFailoverOnDataDiskIssues: true
    autoFailoverOnDataDiskIssuesTimePeriod: 120
    autoFailoverServerGroup: false
  buckets:
    managed: true
  servers:
    - size: 1
      name: all_services
      services:
        - data
        - index
