package v2

import (
	"strings"

	couchbasev2 "github.com/couchbase/couchbase-operator/pkg/apis/couchbase/v2"
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	"testing"
)

func TestCheckChangeConstraintsMigration(t *testing.T) {
	testcases := []struct {
		name                 string
		currentMigrationSpec *couchbasev2.ClusterAssimilationSpec
		updatedMigrationSpec *couchbasev2.ClusterAssimilationSpec
		migratingCondition   v1.ConditionStatus
		expectedErr          string
	}{
		{
			name:                 "reject adding migration to existing cluster",
			currentMigrationSpec: nil,
			updatedMigrationSpec: &couchbasev2.ClusterAssimilationSpec{},
			migratingCondition:   v1.ConditionFalse,
			expectedErr:          "spec.migration cannot be added to a pre-existing cluster",
		},
		{
			name:                 "reject removing migration field during migration",
			currentMigrationSpec: &couchbasev2.ClusterAssimilationSpec{},
			updatedMigrationSpec: nil,
			migratingCondition:   v1.ConditionTrue,
			expectedErr:          "spec.migration cannot be removed during migration",
		},
		{
			name: "reject changing host name during migration",
			currentMigrationSpec: &couchbasev2.ClusterAssimilationSpec{
				UnmanagedClusterHost: "some.host.name",
			},
			updatedMigrationSpec: &couchbasev2.ClusterAssimilationSpec{
				UnmanagedClusterHost: "different.host.name",
			},
			migratingCondition: v1.ConditionTrue,
			expectedErr:        "spec.migration.unmanagedClusterHost cannot be changed during migration",
		},
		{
			name: "allow increasing numUnmanagedNodes during migration",
			currentMigrationSpec: &couchbasev2.ClusterAssimilationSpec{
				UnmanagedClusterHost: "some.host.name",
				NumUnmanagedNodes:    2,
			},
			updatedMigrationSpec: &couchbasev2.ClusterAssimilationSpec{
				UnmanagedClusterHost: "some.host.name",
				NumUnmanagedNodes:    4,
			},
			migratingCondition: v1.ConditionTrue,
			expectedErr:        "",
		},
	}

	for _, testcase := range testcases {
		status := couchbasev2.ClusterStatus{Conditions: []couchbasev2.ClusterCondition{{Status: testcase.migratingCondition, Type: couchbasev2.ClusterConditionMigrating}}}

		currentCluster := &couchbasev2.CouchbaseCluster{
			Spec: couchbasev2.ClusterSpec{Migration: testcase.currentMigrationSpec,
				Image: "couchbase/server:7.6.2"},
			Status: status,
		}

		updatedCluster := &couchbasev2.CouchbaseCluster{
			Spec: couchbasev2.ClusterSpec{Migration: testcase.updatedMigrationSpec,
				Image: "couchbase/server:7.6.2"},
		}

		err := checkChangeConstraintsMigration(nil, currentCluster, updatedCluster)

		if (err == nil && testcase.expectedErr != "") || (err != nil && (testcase.expectedErr == "" || err.Error() != testcase.expectedErr)) {
			t.Errorf("test %s failed, expected error %s, got %s", testcase.name, testcase.expectedErr, err)
		}
	}
}

func TestCheckForVersionChange(t *testing.T) {
	testcases := []struct {
		name           string
		currentVersion string
		updatedVersion string
		expectedChange bool
		expectedError  string
	}{
		{
			name:           "has version downgrade",
			currentVersion: "couchbase/server:7.6.2",
			updatedVersion: "couchbase/server:7.6.1",
			expectedChange: true,
			expectedError:  "",
		},
		{
			name:           "has version upgrade",
			currentVersion: "couchbase/server:7.6.0",
			updatedVersion: "couchbase/server:7.6.2",
			expectedChange: true,
			expectedError:  "",
		},
		{
			name:           "no version change",
			currentVersion: "couchbase/server:7.6.2",
			updatedVersion: "couchbase/server:7.6.2",
			expectedChange: false,
			expectedError:  "",
		},
		{
			name:           "invalid version string",
			currentVersion: "couchbase/server:7.6.2",
			updatedVersion: "couchbase/server",
			expectedChange: false,
			expectedError:  "version error: invalid image string couchbase/server",
		},
	}

	for _, testcase := range testcases {
		res, err := checkForVersionChange(
			&couchbasev2.CouchbaseCluster{Spec: couchbasev2.ClusterSpec{Image: testcase.currentVersion}},
			&couchbasev2.CouchbaseCluster{Spec: couchbasev2.ClusterSpec{Image: testcase.updatedVersion}})
		if res != testcase.expectedChange || (err == nil && testcase.expectedError != "") || (err != nil && (testcase.expectedError == "" || err.Error() != testcase.expectedError)) {
			t.Errorf("%s failed, expected check to return %t with error %s, got %t with error %s", testcase.name, testcase.expectedChange, testcase.expectedError, res, err)
		}
	}
}

func TestValidateEncryptionKeyCircularDependencies(t *testing.T) {
	testcases := []struct {
		name          string
		keyMap        map[string]*couchbasev2.CouchbaseEncryptionKey
		expectedError string
		shouldFail    bool
	}{
		{
			name: "no dependencies - should pass",
			keyMap: createKeyMap([]keySpec{
				{name: "key-a", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated},
				{name: "key-b", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated},
			}),
			shouldFail: false,
		},
		{
			name: "linear chain - should pass",
			keyMap: createKeyMap([]keySpec{
				{name: "key-a", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated, encryptWith: "key-b"},
				{name: "key-b", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated, encryptWith: "key-c"},
				{name: "key-c", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated},
			}),
			shouldFail: false,
		},
		{
			name: "simple cycle A->B->A - should fail",
			keyMap: createKeyMap([]keySpec{
				{name: "key-a", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated, encryptWith: "key-b"},
				{name: "key-b", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated, encryptWith: "key-a"},
			}),
			expectedError: "circular dependency detected in encryption keys",
			shouldFail:    true,
		},
		{
			name: "self-reference - should fail",
			keyMap: createKeyMap([]keySpec{
				{name: "key-a", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated, encryptWith: "key-a"},
			}),
			expectedError: "circular dependency detected in encryption keys",
			shouldFail:    true,
		},
		{
			name: "complex cycle A->B->C->A - should fail",
			keyMap: createKeyMap([]keySpec{
				{name: "key-a", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated, encryptWith: "key-b"},
				{name: "key-b", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated, encryptWith: "key-c"},
				{name: "key-c", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated, encryptWith: "key-a"},
			}),
			expectedError: "circular dependency detected in encryption keys:",
			shouldFail:    true,
		},
		{
			name: "multiple separate cycles - should fail",
			keyMap: createKeyMap([]keySpec{
				{name: "key-a", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated, encryptWith: "key-b"},
				{name: "key-b", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated, encryptWith: "key-a"},
				{name: "key-c", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated, encryptWith: "key-d"},
				{name: "key-d", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated, encryptWith: "key-c"},
			}),
			expectedError: "circular dependency detected in encryption keys:",
			shouldFail:    true,
		},
		{
			name: "mixed auto-generated and AWS keys - should pass",
			keyMap: createKeyMap([]keySpec{
				{name: "key-a", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated, encryptWith: "key-b"},
				{name: "key-b", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAWS}, // Non-auto-generated keys don't participate in dependency checks
			}),
			shouldFail: false,
		},
	}

	for _, testcase := range testcases {
		t.Run(testcase.name, func(t *testing.T) {
			err := validateEncryptionKeyCircularDependencies(testcase.keyMap)

			if testcase.shouldFail {
				if err == nil {
					t.Errorf("expected validation to fail but it passed")
					return
				}
				if testcase.expectedError != "" && !strings.Contains(err.Error(), testcase.expectedError) {
					t.Errorf("expected error to contain '%s', got '%s'", testcase.expectedError, err.Error())
				}
			} else if err != nil {
				t.Errorf("expected validation to pass but got error: %s", err.Error())
			}
		})
	}
}

func TestCheckConstraintLoggingSidecarTLS(t *testing.T) {
	testcases := []struct {
		name        string
		clusterSpec *couchbasev2.CouchbaseCluster
		expectedErr string
	}{
		{
			name: "should reject usage of logging sidecar TLS in 2.9.0",
			clusterSpec: &couchbasev2.CouchbaseCluster{
				Spec: couchbasev2.ClusterSpec{
					Logging: couchbasev2.CouchbaseClusterLoggingSpec{
						Server: &couchbasev2.CouchbaseClusterLoggingConfigurationSpec{
							Sidecar: &couchbasev2.LogShipperSidecarSpec{
								TLS: &couchbasev2.LogShipperSidecarTLSSpec{
									MountPath:   "/fluent-bit/certs/",
									SecretNames: []string{"fluent-bit-ca", "fluent-bit-client-cert"},
								},
							},
						},
					},
				},
			},
			expectedErr: "spec.logging.server.sidecar.tls is not implemented in this operator version; available in 2.9.1+",
		},
		{
			name: "should allow if logging sidecar TLS is nil",
			clusterSpec: &couchbasev2.CouchbaseCluster{
				Spec: couchbasev2.ClusterSpec{
					Logging: couchbasev2.CouchbaseClusterLoggingSpec{
						Server: &couchbasev2.CouchbaseClusterLoggingConfigurationSpec{
							Sidecar: &couchbasev2.LogShipperSidecarSpec{},
						},
					},
				},
			},
			expectedErr: "",
		},
		{
			name: "should allow if logging server is nil",
			clusterSpec: &couchbasev2.CouchbaseCluster{
				Spec: couchbasev2.ClusterSpec{
					Logging: couchbasev2.CouchbaseClusterLoggingSpec{},
				},
			},
			expectedErr: "",
		},
		{
			name: "should allow if logging is nil",
			clusterSpec: &couchbasev2.CouchbaseCluster{
				Spec: couchbasev2.ClusterSpec{},
			},
			expectedErr: "",
		},
	}

	for _, testcase := range testcases {
		t.Run(testcase.name, func(t *testing.T) {
			err := checkConstraintLoggingSidecarTLS(nil, testcase.clusterSpec)

			if (err == nil && testcase.expectedErr != "") || (err != nil && err.Error() != testcase.expectedErr) {
				t.Errorf("test %s failed, expected error %s, got %s", testcase.name, testcase.expectedErr, err)
			}
		})
	}
}

// keySpec is a helper struct for creating test encryption keys.
type keySpec struct {
	name        string
	keyType     couchbasev2.CouchbaseEncryptionKeyType
	encryptWith string
}

// createKeyMap creates a map of encryption keys for testing.
func createKeyMap(specs []keySpec) map[string]*couchbasev2.CouchbaseEncryptionKey {
	keyMap := make(map[string]*couchbasev2.CouchbaseEncryptionKey)

	for _, spec := range specs {
		key := &couchbasev2.CouchbaseEncryptionKey{
			ObjectMeta: metav1.ObjectMeta{
				Name: spec.name,
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType: spec.keyType,
			},
		}

		if spec.keyType == couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated {
			key.Spec.AutoGenerated = &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{}
			if spec.encryptWith != "" {
				key.Spec.AutoGenerated.EncryptWithKey = spec.encryptWith
			}
		}

		keyMap[spec.name] = key
	}

	return keyMap
}
