package v2

import (
	"strings"

	couchbasev2 "github.com/couchbase/couchbase-operator/pkg/apis/couchbase/v2"
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	"testing"
)

func TestCheckChangeConstraintsMigration(t *testing.T) {
	testcases := []struct {
		name                 string
		currentMigrationSpec *couchbasev2.ClusterAssimilationSpec
		updatedMigrationSpec *couchbasev2.ClusterAssimilationSpec
		migratingCondition   v1.ConditionStatus
		expectedErr          string
	}{
		{
			name:                 "reject adding migration to existing cluster",
			currentMigrationSpec: nil,
			updatedMigrationSpec: &couchbasev2.ClusterAssimilationSpec{},
			migratingCondition:   v1.ConditionFalse,
			expectedErr:          "spec.migration cannot be added to a pre-existing cluster",
		},
		{
			name:                 "reject removing migration field during migration",
			currentMigrationSpec: &couchbasev2.ClusterAssimilationSpec{},
			updatedMigrationSpec: nil,
			migratingCondition:   v1.ConditionTrue,
			expectedErr:          "spec.migration cannot be removed during migration",
		},
		{
			name: "reject changing host name during migration",
			currentMigrationSpec: &couchbasev2.ClusterAssimilationSpec{
				UnmanagedClusterHost: "some.host.name",
			},
			updatedMigrationSpec: &couchbasev2.ClusterAssimilationSpec{
				UnmanagedClusterHost: "different.host.name",
			},
			migratingCondition: v1.ConditionTrue,
			expectedErr:        "spec.migration.unmanagedClusterHost cannot be changed during migration",
		},
		{
			name: "allow increasing numUnmanagedNodes during migration",
			currentMigrationSpec: &couchbasev2.ClusterAssimilationSpec{
				UnmanagedClusterHost: "some.host.name",
				NumUnmanagedNodes:    2,
			},
			updatedMigrationSpec: &couchbasev2.ClusterAssimilationSpec{
				UnmanagedClusterHost: "some.host.name",
				NumUnmanagedNodes:    4,
			},
			migratingCondition: v1.ConditionTrue,
			expectedErr:        "",
		},
	}

	for _, testcase := range testcases {
		status := couchbasev2.ClusterStatus{Conditions: []couchbasev2.ClusterCondition{{Status: testcase.migratingCondition, Type: couchbasev2.ClusterConditionMigrating}}}

		currentCluster := &couchbasev2.CouchbaseCluster{
			Spec: couchbasev2.ClusterSpec{Migration: testcase.currentMigrationSpec,
				Image: "couchbase/server:7.6.2"},
			Status: status,
		}

		updatedCluster := &couchbasev2.CouchbaseCluster{
			Spec: couchbasev2.ClusterSpec{Migration: testcase.updatedMigrationSpec,
				Image: "couchbase/server:7.6.2"},
		}

		err := checkChangeConstraintsMigration(nil, currentCluster, updatedCluster)

		if (err == nil && testcase.expectedErr != "") || (err != nil && (testcase.expectedErr == "" || err.Error() != testcase.expectedErr)) {
			t.Errorf("test %s failed, expected error %s, got %s", testcase.name, testcase.expectedErr, err)
		}
	}
}

func TestCheckForVersionChange(t *testing.T) {
	testcases := []struct {
		name           string
		currentVersion string
		updatedVersion string
		expectedChange bool
		expectedError  string
	}{
		{
			name:           "has version downgrade",
			currentVersion: "couchbase/server:7.6.2",
			updatedVersion: "couchbase/server:7.6.1",
			expectedChange: true,
			expectedError:  "",
		},
		{
			name:           "has version upgrade",
			currentVersion: "couchbase/server:7.6.0",
			updatedVersion: "couchbase/server:7.6.2",
			expectedChange: true,
			expectedError:  "",
		},
		{
			name:           "no version change",
			currentVersion: "couchbase/server:7.6.2",
			updatedVersion: "couchbase/server:7.6.2",
			expectedChange: false,
			expectedError:  "",
		},
		{
			name:           "invalid version string",
			currentVersion: "couchbase/server:7.6.2",
			updatedVersion: "couchbase/server",
			expectedChange: false,
			expectedError:  "version error: invalid image string couchbase/server",
		},
	}

	for _, testcase := range testcases {
		res, err := checkForVersionChange(
			&couchbasev2.CouchbaseCluster{Spec: couchbasev2.ClusterSpec{Image: testcase.currentVersion}},
			&couchbasev2.CouchbaseCluster{Spec: couchbasev2.ClusterSpec{Image: testcase.updatedVersion}})
		if res != testcase.expectedChange || (err == nil && testcase.expectedError != "") || (err != nil && (testcase.expectedError == "" || err.Error() != testcase.expectedError)) {
			t.Errorf("%s failed, expected check to return %t with error %s, got %t with error %s", testcase.name, testcase.expectedChange, testcase.expectedError, res, err)
		}
	}
}

func TestValidateEncryptionKeyCircularDependencies(t *testing.T) {
	testcases := []struct {
		name          string
		keyMap        map[string]*couchbasev2.CouchbaseEncryptionKey
		expectedError string
		shouldFail    bool
	}{
		{
			name: "no dependencies - should pass",
			keyMap: createKeyMap([]keySpec{
				{name: "key-a", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated},
				{name: "key-b", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated},
			}),
			shouldFail: false,
		},
		{
			name: "linear chain - should pass",
			keyMap: createKeyMap([]keySpec{
				{name: "key-a", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated, encryptWith: "key-b"},
				{name: "key-b", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated, encryptWith: "key-c"},
				{name: "key-c", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated},
			}),
			shouldFail: false,
		},
		{
			name: "simple cycle A->B->A - should fail",
			keyMap: createKeyMap([]keySpec{
				{name: "key-a", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated, encryptWith: "key-b"},
				{name: "key-b", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated, encryptWith: "key-a"},
			}),
			expectedError: "circular dependency detected in encryption keys",
			shouldFail:    true,
		},
		{
			name: "self-reference - should fail",
			keyMap: createKeyMap([]keySpec{
				{name: "key-a", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated, encryptWith: "key-a"},
			}),
			expectedError: "circular dependency detected in encryption keys",
			shouldFail:    true,
		},
		{
			name: "complex cycle A->B->C->A - should fail",
			keyMap: createKeyMap([]keySpec{
				{name: "key-a", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated, encryptWith: "key-b"},
				{name: "key-b", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated, encryptWith: "key-c"},
				{name: "key-c", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated, encryptWith: "key-a"},
			}),
			expectedError: "circular dependency detected in encryption keys:",
			shouldFail:    true,
		},
		{
			name: "multiple separate cycles - should fail",
			keyMap: createKeyMap([]keySpec{
				{name: "key-a", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated, encryptWith: "key-b"},
				{name: "key-b", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated, encryptWith: "key-a"},
				{name: "key-c", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated, encryptWith: "key-d"},
				{name: "key-d", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated, encryptWith: "key-c"},
			}),
			expectedError: "circular dependency detected in encryption keys:",
			shouldFail:    true,
		},
		{
			name: "mixed auto-generated and AWS keys - should pass",
			keyMap: createKeyMap([]keySpec{
				{name: "key-a", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated, encryptWith: "key-b"},
				{name: "key-b", keyType: couchbasev2.CouchbaseEncryptionKeyTypeAWS}, // Non-auto-generated keys don't participate in dependency checks
			}),
			shouldFail: false,
		},
	}

	for _, testcase := range testcases {
		t.Run(testcase.name, func(t *testing.T) {
			err := validateEncryptionKeyCircularDependencies(testcase.keyMap)

			if testcase.shouldFail {
				if err == nil {
					t.Errorf("expected validation to fail but it passed")
					return
				}
				if testcase.expectedError != "" && !strings.Contains(err.Error(), testcase.expectedError) {
					t.Errorf("expected error to contain '%s', got '%s'", testcase.expectedError, err.Error())
				}
			} else if err != nil {
				t.Errorf("expected validation to pass but got error: %s", err.Error())
			}
		})
	}
}

func TestCheckConstraintLoggingSidecarTLS(t *testing.T) {
	testcases := []struct {
		name        string
		clusterSpec *couchbasev2.CouchbaseCluster
		expectedErr string
	}{
		{
			name: "should allow valid TLS configuration with secrets",
			clusterSpec: &couchbasev2.CouchbaseCluster{
				Spec: couchbasev2.ClusterSpec{
					Logging: couchbasev2.CouchbaseClusterLoggingSpec{
						Server: &couchbasev2.CouchbaseClusterLoggingConfigurationSpec{
							Sidecar: &couchbasev2.LogShipperSidecarSpec{
								TLS: &couchbasev2.LogShipperSidecarTLSSpec{
									MountPath:   "/fluent-bit/certs/",
									SecretNames: []string{"fluent-bit-ca", "fluent-bit-client-cert"},
								},
							},
						},
					},
				},
			},
			expectedErr: "",
		},
		{
			name: "should reject TLS configuration without secret names",
			clusterSpec: &couchbasev2.CouchbaseCluster{
				Spec: couchbasev2.ClusterSpec{
					Logging: couchbasev2.CouchbaseClusterLoggingSpec{
						Server: &couchbasev2.CouchbaseClusterLoggingConfigurationSpec{
							Sidecar: &couchbasev2.LogShipperSidecarSpec{
								TLS: &couchbasev2.LogShipperSidecarTLSSpec{
									MountPath:   "/fluent-bit/certs/",
									SecretNames: []string{},
								},
							},
						},
					},
				},
			},
			expectedErr: "spec.logging.server.sidecar.tls.secretNames must contain at least one secret when TLS is configured",
		},
		{
			name: "should reject TLS configuration with empty mount path",
			clusterSpec: &couchbasev2.CouchbaseCluster{
				Spec: couchbasev2.ClusterSpec{
					Logging: couchbasev2.CouchbaseClusterLoggingSpec{
						Server: &couchbasev2.CouchbaseClusterLoggingConfigurationSpec{
							Sidecar: &couchbasev2.LogShipperSidecarSpec{
								TLS: &couchbasev2.LogShipperSidecarTLSSpec{
									MountPath:   "",
									SecretNames: []string{"fluent-bit-ca"},
								},
							},
						},
					},
				},
			},
			expectedErr: "spec.logging.server.sidecar.tls.mountPath cannot be empty when TLS is configured",
		},
		{
			name: "should allow if logging sidecar TLS is nil",
			clusterSpec: &couchbasev2.CouchbaseCluster{
				Spec: couchbasev2.ClusterSpec{
					Logging: couchbasev2.CouchbaseClusterLoggingSpec{
						Server: &couchbasev2.CouchbaseClusterLoggingConfigurationSpec{
							Sidecar: &couchbasev2.LogShipperSidecarSpec{},
						},
					},
				},
			},
			expectedErr: "",
		},
		{
			name: "should allow if logging server is nil",
			clusterSpec: &couchbasev2.CouchbaseCluster{
				Spec: couchbasev2.ClusterSpec{
					Logging: couchbasev2.CouchbaseClusterLoggingSpec{},
				},
			},
			expectedErr: "",
		},
		{
			name: "should allow if logging is nil",
			clusterSpec: &couchbasev2.CouchbaseCluster{
				Spec: couchbasev2.ClusterSpec{},
			},
			expectedErr: "",
		},
	}

	for _, testcase := range testcases {
		t.Run(testcase.name, func(t *testing.T) {
			err := checkConstraintLoggingSidecarTLS(nil, testcase.clusterSpec)

			if (err == nil && testcase.expectedErr != "") || (err != nil && err.Error() != testcase.expectedErr) {
				t.Errorf("test %s failed, expected error %s, got %s", testcase.name, testcase.expectedErr, err)
			}
		})
	}
}

// keySpec is a helper struct for creating test encryption keys.
type keySpec struct {
	name        string
	keyType     couchbasev2.CouchbaseEncryptionKeyType
	encryptWith string
}

// createKeyMap creates a map of encryption keys for testing.
func createKeyMap(specs []keySpec) map[string]*couchbasev2.CouchbaseEncryptionKey {
	keyMap := make(map[string]*couchbasev2.CouchbaseEncryptionKey)

	for _, spec := range specs {
		key := &couchbasev2.CouchbaseEncryptionKey{
			ObjectMeta: metav1.ObjectMeta{
				Name: spec.name,
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType: spec.keyType,
			},
		}

		if spec.keyType == couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated {
			key.Spec.AutoGenerated = &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{}
			if spec.encryptWith != "" {
				key.Spec.AutoGenerated.EncryptWithKey = spec.encryptWith
			}
		}

		keyMap[spec.name] = key
	}

	return keyMap
}

func TestValidateAWSKeyARN(t *testing.T) {
	testcases := []struct {
		keyARN string
		valid  bool
	}{
		{
			keyARN: "arn:aws:kms:us-west-2:123456789012:key/1234abcd-12ab-34cd-56ef-1234567890ab",
			valid:  true,
		},
		{
			keyARN: "arn:aws:kms:eu-west-2:111122223333:key/1234abcd-12ab-34cd-56ef-1234567890ab",
			valid:  true,
		},
		{
			keyARN: "arn:aws:kms:us-west-2:111122223333:key/mrk-1234abcd12ab34cd56ef1234567890ab",
			valid:  true,
		},
		{
			keyARN: "arnald:aws:kms:us-west-2:111122223333:key/mrk-1234abcd12ab34cd56ef1234567890ab",
			valid:  false,
		},
		{
			keyARN: "arn:aWS:kms:us-west-2:111122223333:key/mrk-1234abcd12ab34cd56ef1234567890ab",
			valid:  false,
		},
		{
			keyARN: "arn:aws:iam:us-west-2:111122223333:key/mrk-1234abcd12ab34cd56ef1234567890ab",
			valid:  false,
		},
		{
			keyARN: "arn:aws:kms:us-west-2:11112 2223333:key/mrk-1234abcd12ab34cd56ef1234567890ab",
			valid:  false,
		},
		{
			keyARN: "arn:aws:kms:us-west-2:1112223333:key/mrk-1234abcd12ab34cd56ef1234567890ab",
			valid:  false,
		},
		{
			keyARN: "arn:aws:kms:us-west-2:11112223333:key/mrk-1234abcd12ab34cd56ef1234567890ab",
			valid:  false,
		},
		{
			keyARN: "arn:aws:kms:us-west-2:1111222233333:key/mrk-1234abcd12ab34cd56ef1234567890ab",
			valid:  false,
		},
		{
			keyARN: "arn:aws:kms:us-west-2:111122223333:app/mrk-1234abcd12ab34cd56ef1234567890ab",
			valid:  false,
		},
		{
			keyARN: "arn:aws:kms:us-west-2:111122223333:key/mrk-1234abcd12ab34cd 56ef1234567890ab",
			valid:  false,
		},
		{
			keyARN: "arn:aws:kms:us-west-2:111122223333:key/mrk/1234abcd12ab34cd56ef1234567890ab",
			valid:  false,
		},
		{
			keyARN: "arn:aws:kms:us-west-2:111122223333:key/mrk-1234abcd12ab34cd56ef1234567890ab!",
			valid:  false,
		},
		{
			keyARN: "",
			valid:  false,
		},
	}

	for _, testcase := range testcases {
		err := validateAWSKeyARN(testcase.keyARN)
		if testcase.valid && err != nil {
			t.Errorf("expected validation to pass but got error: %s", err)
		}

		if !testcase.valid && err == nil {
			t.Errorf("expected validation to fail but it passed")
		}
	}
}

func TestIsFullyUpgraded(t *testing.T) {
	testcases := []struct {
		name           string
		specImage      string
		statusVersion  string
		mixedMode      v1.ConditionStatus
		expectedResult bool
	}{
		{
			name:           "fully upgraded - spec matches status, no mixed mode",
			specImage:      "couchbase/server:7.6.7",
			statusVersion:  "7.6.7",
			mixedMode:      v1.ConditionFalse,
			expectedResult: true,
		},
		{
			name:           "not fully upgraded - spec doesn't match status",
			specImage:      "couchbase/server:8.0.0",
			statusVersion:  "7.6.7",
			mixedMode:      v1.ConditionFalse,
			expectedResult: false,
		},
		{
			name:           "not fully upgraded - in mixed mode",
			specImage:      "couchbase/server:7.6.7",
			statusVersion:  "7.6.7",
			mixedMode:      v1.ConditionTrue,
			expectedResult: false,
		},
		{
			name:           "not fully upgraded - spec matches status but in mixed mode",
			specImage:      "couchbase/server:8.0.0",
			statusVersion:  "8.0.0",
			mixedMode:      v1.ConditionTrue,
			expectedResult: false,
		},
		{
			name:           "unknown cluster version - trust the user",
			specImage:      "couchbase/server@sha256:8485d9a4f6a9f288e0b1bac2c89383387f1091cf3b53c22f667748e2b4c5dd33",
			statusVersion:  "8.0.0",
			mixedMode:      v1.ConditionFalse,
			expectedResult: true,
		},
	}

	for _, tc := range testcases {
		t.Run(tc.name, func(t *testing.T) {
			cluster := &couchbasev2.CouchbaseCluster{
				Spec: couchbasev2.ClusterSpec{
					Image: tc.specImage,
				},
				Status: couchbasev2.ClusterStatus{
					CurrentVersion: tc.statusVersion,
				},
			}

			// Set mixed mode condition if needed
			if tc.mixedMode != "" {
				cluster.Status.Conditions = []couchbasev2.ClusterCondition{
					{
						Type:   couchbasev2.ClusterConditionMixedMode,
						Status: tc.mixedMode,
					},
				}
			}

			result, err := isFullyUpgraded(cluster)
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}

			if result != tc.expectedResult {
				t.Errorf("expected %v, got %v", tc.expectedResult, result)
			}
		})
	}
}

func TestCheckConstraintAutoFailoverOnDataDiskNonResponsiveness(t *testing.T) {
	testcases := []struct {
		name        string
		image       string
		enabled     bool
		expectedErr string
	}{
		{
			name:        "should allow disk non-responsiveness on 8.0.0+",
			image:       "couchbase/server:8.0.0",
			enabled:     true,
			expectedErr: "",
		},
		{
			name:        "should allow disk non-responsiveness disabled on any version",
			image:       "couchbase/server:7.6.0",
			enabled:     false,
			expectedErr: "",
		},
		{
			name:        "should reject disk non-responsiveness on 7.6.0",
			image:       "couchbase/server:7.6.0",
			enabled:     true,
			expectedErr: "annotation cao.couchbase.com/autoFailoverOnDataDiskNonResponsiveness is not supported in Couchbase Server versions lower than 8.0.0",
		},
		{
			name:        "should reject disk non-responsiveness on 7.2.0",
			image:       "couchbase/server:7.2.0",
			enabled:     true,
			expectedErr: "annotation cao.couchbase.com/autoFailoverOnDataDiskNonResponsiveness is not supported in Couchbase Server versions lower than 8.0.0",
		},
		{
			name:        "should allow on 8.0.1+",
			image:       "couchbase/server:8.0.1",
			enabled:     true,
			expectedErr: "",
		},
	}

	for _, testcase := range testcases {
		t.Run(testcase.name, func(t *testing.T) {
			cluster := &couchbasev2.CouchbaseCluster{
				Spec: couchbasev2.ClusterSpec{
					Image: testcase.image,
					ClusterSettings: couchbasev2.ClusterConfig{
						AutoFailoverOnDataDiskNonResponsiveness: testcase.enabled,
					},
				},
			}

			err := checkConstraintAutoFailoverOnDataDiskNonResponsiveness(nil, cluster)

			if testcase.expectedErr == "" {
				if err != nil {
					t.Errorf("expected no error but got: %s", err.Error())
				}
			} else {
				if err == nil {
					t.Errorf("expected error containing '%s' but got none", testcase.expectedErr)
				} else if !strings.Contains(err.Error(), testcase.expectedErr) {
					t.Errorf("expected error containing '%s' but got '%s'", testcase.expectedErr, err.Error())
				}
			}
		})
	}
}

func TestCheckConstraintAutoFailoverOnDataDiskNonResponsivenessTimePeriod(t *testing.T) {
	testcases := []struct {
		name        string
		enabled     bool
		timePeriod  *metav1.Duration
		expectedErr string
	}{
		{
			name:        "should allow 5 seconds (minimum)",
			enabled:     true,
			timePeriod:  &metav1.Duration{Duration: 5 * 1e9},
			expectedErr: "",
		},
		{
			name:        "should allow 120 seconds",
			enabled:     true,
			timePeriod:  &metav1.Duration{Duration: 120 * 1e9},
			expectedErr: "",
		},
		{
			name:        "should allow 3600 seconds (maximum)",
			enabled:     true,
			timePeriod:  &metav1.Duration{Duration: 3600 * 1e9},
			expectedErr: "",
		},
		{
			name:        "should reject 4 seconds (below minimum)",
			enabled:     true,
			timePeriod:  &metav1.Duration{Duration: 4 * 1e9},
			expectedErr: "annotation cao.couchbase.com/autoFailoverOnDataDiskNonResponsivenessTimePeriod in body should be greater than or equal to 5s",
		},
		{
			name:        "should reject 3601 seconds (above maximum)",
			enabled:     true,
			timePeriod:  &metav1.Duration{Duration: 3601 * 1e9},
			expectedErr: "annotation cao.couchbase.com/autoFailoverOnDataDiskNonResponsivenessTimePeriod in body should be less than or equal to 3600s",
		},
		{
			name:        "should reject nil when enabled",
			enabled:     true,
			timePeriod:  nil,
			expectedErr: "annotation cao.couchbase.com/autoFailoverOnDataDiskNonResponsivenessTimePeriod in body is required",
		},
		{
			name:        "should skip validation when feature is disabled",
			enabled:     false,
			timePeriod:  nil,
			expectedErr: "",
		},
	}

	for _, testcase := range testcases {
		t.Run(testcase.name, func(t *testing.T) {
			cluster := &couchbasev2.CouchbaseCluster{
				Spec: couchbasev2.ClusterSpec{
					ClusterSettings: couchbasev2.ClusterConfig{
						AutoFailoverOnDataDiskNonResponsiveness:           testcase.enabled,
						AutoFailoverOnDataDiskNonResponsivenessTimePeriod: testcase.timePeriod,
					},
				},
			}

			err := checkConstraintAutoFailoverOnDataDiskNonResponsivenessTimePeriod(nil, cluster)

			if testcase.expectedErr == "" {
				if err != nil {
					t.Errorf("expected no error but got: %s", err.Error())
				}
			} else {
				if err == nil {
					t.Errorf("expected error containing '%s' but got none", testcase.expectedErr)
				} else if !strings.Contains(err.Error(), testcase.expectedErr) {
					t.Errorf("expected error containing '%s' but got '%s'", testcase.expectedErr, err.Error())
				}
			}
		})
	}
}
