#!/usr/bin/env python

# Copyright 2019-Present Couchbase, Inc.
#
# Use of this software is governed by the Business Source License included in
# the file licenses/BSL-Couchbase.txt.  As of the Change Date specified in that
# file, in accordance with the Business Source License, use of this software
# will be governed by the Apache License, Version 2.0, included in the file
# licenses/APL2.txt.

"""
Description:
    Automates the long and manual process of setting up clusters in EKS.
    Required are to have setup a EKS service role and ECS key pair to allow SSH access beforehand.
    This only needs to be done once.

Usage:
    eks start eks-service-role
    eks stop

Options:
    eks-service-role                    Required. Name of the IAM Role to allow EKS and the
                                        K8S control plane to manage AWS resources.

    -n name                             Optional. Sets the name of the EKS Clusters.
                                        Defaults will be - EKS Clusters: cluster1 and cluster2
                                        If name is set the EKS clusters will be named
                                        by appending a number.
                                        E.g. if name is "x" then: x1, x2
                                        VPCs will always be named controlplane1, controlplane2,
                                        workernodes1, workernodes2.

    -c --cidr-block                     Optional. Accepts either 1 or 2 CIDR blocks as a list.
                                        Sets the VPC block network(s).
                                        E.g --cidr-block 192.168.0.0/16 --cidr-block 172.16.0.0/16
                                        Default: 192.168.0.0/16, 172.16.0.0/16

    -t --two                            Optional. Flag to set if two clusters are to be
                                        created instead of just the one.
                                        Required for XDCR. If true then the
                                        -c --cidr-block argument will expect 2 inputs.
                                        Options are either True or False (case-insensitive).
                                        Alternatively 1 or 0 can be used.
                                        Default is False.
"""

from __future__ import print_function
import argparse
import subprocess
import sys
import time
import json
import ipaddress

CONTROLPLANE_TEMPLATE = \
    "https://amazon-eks.s3-us-west-2.amazonaws.com/" \
    "cloudformation/2019-01-09/amazon-eks-vpc-sample.yaml"
WORKERNODES_TEMPLATE = \
    "https://amazon-eks.s3-us-west-2.amazonaws.com/" \
    "cloudformation/2019-01-09/amazon-eks-nodegroup.yaml"
AWS_AUTH_CM_YAML = \
    "https://amazon-eks.s3-us-west-2.amazonaws.com/" \
    "cloudformation/2019-01-09/aws-auth-cm.yaml"

CAPABILITY_IAM = "CAPABILITY_IAM"

NAME = "cluster"
CONTROLPLANE_NAME = "controlplane"
WORKERNODES_NAME = "workernodes"
CIDR_BLOCK = ["192.168.0.0/16", "172.16.0.0/16"]

NODEGROUP_NAME = "nodeGroup"
NODE_AMIS = {"eu-west-1": "ami-01e08d22b9439c15a",
             "eu-west-2": "ami-0d69ab00cb41d6eda",
             "us-east-1": "ami-0c24db5df6badc35a",
             "us-east-2": "ami-0c2e8d28b1f854c68",
             "us-west-2": "ami-0a2abab4107669c1b"}

CREATE_COMPLETE = "CREATE_COMPLETE"
ROLLBACK_IN_PROGRESS = "ROLLBACK_IN_PROGRESS"
ROLLBACK_COMPLETE = "ROLLBACK_COMPLETE"
DELETE_IN_PROGRESS = "DELETE_IN_PROGRESS"
DELETE_COMPLETE = "DELETE_COMPLETE"


def aws(*cmd, **kwargs):
    """Runs a aws command"""
    proc = subprocess.Popen(["aws"] + list(cmd), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    stdout, stderr = proc.communicate()
    if proc.returncode != 0:
        if "ResourceNotFoundException" in stderr and kwargs.get("mode") == "delete":
            print("Cluster deletion complete.")
            sys.exit(0)
        else:
            print(stderr)
            raise RuntimeError
    return stdout


def kubectl(*cmd):
    """Runs a kubectl command raising an exception on error"""
    return str(subprocess.check_output(["kubectl"] + list(cmd))).strip()


def get_region():
    """Get the AWS region we are currently working in. Debug purposes only"""
    return aws("configure", "get", "region").strip().decode("utf-8")


def create_controlplane_vpc(control_plane_vpc, cidr_block, subnets):
    """
    Creates the first VPC that hosts the K8S control plane, takes
    optional arguments to rename the CloudFormation Stack and
    set the CIDR Block and Subnets.
    """
    parameters = [
        {"ParameterKey": "VpcBlock", "ParameterValue": cidr_block},
        {"ParameterKey": "Subnet01Block", "ParameterValue": subnets[0]},
        {"ParameterKey": "Subnet02Block", "ParameterValue": subnets[1]},
        {"ParameterKey": "Subnet03Block", "ParameterValue": subnets[2]}
    ]

    print(aws("cloudformation", "create-stack",
              "--stack-name", control_plane_vpc,
              "--template-url", CONTROLPLANE_TEMPLATE,
              "--parameters", json.dumps(parameters)
              ))


def create_eks_cluster(eks_name, eks_service_role, vpc_config_string):
    """Creates the actual EKS cluster."""
    return aws("eks", "create-cluster", "--name", eks_name,
               "--role-arn", eks_service_role,
               "--resources-vpc-config", vpc_config_string)


def get_vpc_id(vpc_name):
    """returns the vpc-id given the vpc name"""
    return str(json.loads(
        aws("cloudformation", "describe-stack-resources", "--stack-name",
            vpc_name, "--logical-resource-id", "VPC",
            "--output", "json"))["StackResources"][0]["PhysicalResourceId"])


def get_subnet_ids(control_plane_vpc):
    """Return the AWS format subnet-xxxxx id for the three subnets"""
    subnet1 = json.loads(
        aws("cloudformation", "describe-stack-resources",
            "--stack-name", control_plane_vpc,
            "--logical-resource-id", "Subnet01",
            "--output", "json"))["StackResources"][0]["PhysicalResourceId"]
    subnet2 = json.loads(
        aws("cloudformation", "describe-stack-resources",
            "--stack-name", control_plane_vpc,
            "--logical-resource-id", "Subnet02",
            "--output", "json"))["StackResources"][0]["PhysicalResourceId"]
    subnet3 = json.loads(
        aws("cloudformation", "describe-stack-resources",
            "--stack-name", control_plane_vpc,
            "--logical-resource-id", "Subnet03",
            "--output", "json"))["StackResources"][0]["PhysicalResourceId"]
    subnet_ids = subnet1 + "," + subnet2 + "," + subnet3
    return subnet_ids


def get_security_group_id(control_plane_vpc):
    """Return the security group ID"""
    return json.loads(aws("cloudformation", "describe-stack-resources",
                          "--stack-name", control_plane_vpc,
                          "--logical-resource-id", "ControlPlaneSecurityGroup",
                          "--output", "json"))["StackResources"][0]["PhysicalResourceId"]


def create_workernode_vpc(node_group_name, security_group_id, subnet_ids, args, number):
    """Creates the second VPC after the EKS Cluster is created"""
    eks_name = args.name + str(number)
    control_plane_vpc = CONTROLPLANE_NAME + str(number)
    worker_nodes_vpc = WORKERNODES_NAME + str(number)

    # create an ephemeral key-pair
    key = json.loads(aws("ec2", "create-key-pair", "--key-name", control_plane_vpc))

    parameters = [
        {"ParameterKey": "ClusterName", "ParameterValue": eks_name},
        {"ParameterKey": "ClusterControlPlaneSecurityGroup",
         "ParameterValue": security_group_id},
        {"ParameterKey": "NodeGroupName", "ParameterValue": node_group_name},
        {"ParameterKey": "KeyName", "ParameterValue": key["KeyName"]},
        {"ParameterKey": "VpcId", "ParameterValue": get_vpc_id(control_plane_vpc)},
        {"ParameterKey": "NodeImageId",
         "ParameterValue": get_node_image_id(args.region)},
        {"ParameterKey": "Subnets", "ParameterValue": subnet_ids}
    ]

    aws("cloudformation", "create-stack", "--stack-name", worker_nodes_vpc,
        "--template-url", WORKERNODES_TEMPLATE,
        "--capabilities", CAPABILITY_IAM,
        "--parameters", json.dumps(parameters)
        )


def get_node_image_id(region):
    """
    The worker nodes VPC requires a specific AMI for specific regions.
    This returns that AMI ID.
    """
    return NODE_AMIS[region]


def get_eks_cluster_status(eks_cluster_name, mode):
    """
    Return the status of a specified EKS Cluster. If mode is delete then check for
    ResourceNotFoundException to confirm deletion completion.
    """
    return json.loads(aws("eks", "describe-cluster",
                          "--name", eks_cluster_name,
                          "--output", "json", mode=mode))["cluster"]["status"]


def poll_eks_cluster(eks_cluster_name, mode):
    """Polls the EKS Cluster status until ACTIVE"""
    time_start = time.time()
    if mode == "create":
        while get_eks_cluster_status(eks_cluster_name, mode) != "ACTIVE":
            if time.time() - time_start > 900:
                print("15 minutes is longer than expected for creation of EKS Cluster."
                      "Please investigate. Abort.")
                sys.exit(1)
            time.sleep(60)
    if mode == "delete":
        while get_eks_cluster_status(eks_cluster_name, mode) == "DELETING":
            time.sleep(60)

    return time.time() - time_start


def get_node_instance_role_arn(workernodes_vpc_name):
    """Return the Node Instance Role ARN to apply to the config map"""
    role = json.loads(
        aws("cloudformation", "describe-stack-resources",
            "--stack-name", workernodes_vpc_name,
            "--logical-resource-id", "NodeInstanceRole",
            "--output", "json"))["StackResources"][0]["PhysicalResourceId"]
    return json.loads(aws("iam", "get-role", "--role-name", role,
                          "--output", "json"))["Role"]["Arn"]


def poll_worker_nodes():
    """
    Poll worker nodes until they are ready for deployment.
    If we timeout due to no nodes being found or the nodes never turn
    from NotReady to Ready, return False. Otherwise return True.
    """
    time_start = time.time()
    while kubectl("get", "nodes") == "No resources found.":
        time.sleep(5)
        time_passed = time.time() - time_start
        if time_passed > 300:
            print("Nodes are unable to be found. Check your config.")
            return False

    time_start = time.time()
    while kubectl("get", "nodes").find("NotReady") != -1:
        time.sleep(10)
        time_passed = time.time() - time_start
        if time_passed > 300:
            print("Nodes are still NotReady still after 5 minutes.")
            return False

    return True


def poll_vpc(vpc_name, target_status):
    """WIP Poll a VPC until ready"""
    ready = False
    time_start = time.time()
    print("Polling " + vpc_name + " started at: " + str(time.asctime(time.localtime(time_start))))
    while not ready:
        output = json.loads(aws("cloudformation", "describe-stack-events",
                                "--stack-name", vpc_name, "--max-items", "1", "--output", "json"))
        logical_id = str(output["StackEvents"][0]["LogicalResourceId"])
        status = str(output["StackEvents"][0]["ResourceStatus"])

        if status in (ROLLBACK_IN_PROGRESS, ROLLBACK_COMPLETE):
            print("Error in VPC configuration. "
                  "Please refer to the stack events. "
                  "Make sure to delete stack manually")
            sys.exit(1)
        if logical_id == vpc_name and status == target_status:
            ready = True
            print("Operation took " + str(time.time() - time_start) + " seconds")
            return ready

        time.sleep(20)
        time_passed = time.time() - time_start
        if time_passed > 600:
            print("VPCs creation timeout.")
            sys.exit(1)


def create_cluster(args, number):
    """Setup for creating an EKS Cluster with three nodes"""
    eks_name = args.name + str(number)
    control_plane_vpc = CONTROLPLANE_NAME + str(number)
    worker_nodes_vpc = WORKERNODES_NAME + str(number)

    cidr_block = args.cidr_block[number-1]
    print("CIDR Block: " + cidr_block)

    network = ipaddress.ip_network(cidr_block.decode("utf-8"))
    subnets = [str(s) for s in network.subnets(prefixlen_diff=2)][1:]

    print("Subnets: " + str(subnets))

    security_group_id, subnets_string, vpc_config_string \
        = setup_control_plane(cidr_block, control_plane_vpc, subnets)

    setup_eks_cluster(args, eks_name, vpc_config_string)

    setup_worker_nodes(args, number, security_group_id, subnets_string, worker_nodes_vpc)


def setup_control_plane(cidr_block, control_plane_vpc, subnets):
    """Sets up the control plane for an EKS Cluster."""
    print("=======Creating Control Plane VPC '" + control_plane_vpc + "'========")
    create_controlplane_vpc(control_plane_vpc, cidr_block, subnets)
    subnets_string = ""
    if poll_vpc(control_plane_vpc, CREATE_COMPLETE):
        subnets_string = get_subnet_ids(control_plane_vpc)
    print(get_security_group_id(control_plane_vpc))
    security_group_id = get_security_group_id(control_plane_vpc)
    vpc_config_string = "subnetIds=" + subnets_string + "," \
                        + "securityGroupIds=" + security_group_id
    return security_group_id, subnets_string, vpc_config_string


def setup_eks_cluster(args, eks_name, vpc_config_string):
    """Sets up the EKS Cluster itself and updates kubeconfig"""
    print("=======Creating EKS Cluster '" + eks_name + "'========")
    print("Creation started at " + str(time.asctime(time.localtime(time.time()))))
    print(create_eks_cluster(eks_name, args.eks_service_role, vpc_config_string))
    print("Wait at least 10-15 minutes until EKS cluster is ready "
          "before proceeding to the next step")
    eks_creation_time = poll_eks_cluster(eks_name, "create")
    mins, secs = divmod(eks_creation_time, 60)
    print("EKS cluster creation time took " + str(mins) + " minutes and " + str(secs) + " seconds")
    # update your local kube-config
    aws("eks", "update-kubeconfig", "--name", eks_name)


def setup_worker_nodes(args, number, security_group_id, subnets_string, worker_nodes_vpc):
    """
    Sets up the worker nodes for the EKS Cluster and applies
    configuration for these worker nodes to be discovered. Then
    waits for nodes and completes the whole EKS cluster creation process.
    """
    print("=======Creating Worker Nodes VPC '" + worker_nodes_vpc + "'========")
    create_workernode_vpc(NODEGROUP_NAME, security_group_id, subnets_string, args, number)
    # wait for the worker nodes vpc to actually finish creation
    print("waiting for worker nodes vpc to be ready")
    poll_vpc(worker_nodes_vpc, CREATE_COMPLETE)
    print("retrieving ARN to apply config map")
    # download aws-auth-cm.yaml, edit and write to file
    aws_yaml = subprocess.check_output(["curl"] + [AWS_AUTH_CM_YAML])
    print("name of the Worker Nodes VPC: " + worker_nodes_vpc)
    arn = get_node_instance_role_arn(worker_nodes_vpc)
    if not arn:
        print("FATAL: Unable to get NodeInstanceRole ARN.")
        sys.exit(1)
    print(arn)
    aws_yaml = str.replace(aws_yaml, "<ARN of instance role (not instance profile)>", arn)
    file_to_write = open("aws-auth-cm.yaml", "w")
    file_to_write.write(aws_yaml)
    file_to_write.close()
    # apply config map to find worker nodes
    kubectl("apply", "-f", "aws-auth-cm.yaml")
    if poll_worker_nodes():
        print(kubectl("get", "nodes", "-o", "wide"))
        print("EKS Cluster and relevant VPCs setup, now ready to deploy onto.")
    else:
        print("No ready worker nodes found. Abort.")
        sys.exit(1)


def xdcr_setup(args):
    """Sets up networking in order to create a working XDCR connection"""
    vpc_id_1 = get_vpc_id(CONTROLPLANE_NAME + str(1))
    vpc_id_2 = get_vpc_id(CONTROLPLANE_NAME + str(2))

    # create connection
    aws("ec2", "create-vpc-peering-connection", "--vpc-id", vpc_id_1, "--peer-vpc-id", vpc_id_2)

    pcx_id = str(get_peering_connection_id(args))
    print(pcx_id)

    # accept connection
    aws("ec2", "accept-vpc-peering-connection", "--vpc-peering-connection-id", pcx_id)

    # get route-table-ids
    route_table_id1 = json.loads(aws("ec2", "describe-route-tables", "--output", "json",
                                     "--filters", "Name=vpc-id,Values=" + vpc_id_1,
                                     "Name=tag:Name,Values="
                                     + "\"Public Subnets\""))["RouteTables"][0]["RouteTableId"]

    route_table_id2 = json.loads(aws("ec2", "describe-route-tables", "--output", "json",
                                     "--filters", "Name=vpc-id,Values=" + vpc_id_2,
                                     "Name=tag:Name,Values="
                                     + "\"Public Subnets\""))["RouteTables"][0]["RouteTableId"]

    # create new routes in both
    print("Editing route table " + route_table_id1 + " for " + vpc_id_1)
    print(aws("ec2", "create-route", "--destination-cidr-block", args.cidr_block[1],
              "--route-table-id", route_table_id1, "--vpc-peering-connection-id", pcx_id))
    print("Editing route table " + route_table_id2 + " for " + vpc_id_2)
    print(aws("ec2", "create-route", "--destination-cidr-block", args.cidr_block[0],
              "--route-table-id", route_table_id2, "--vpc-peering-connection-id", pcx_id))

    # get security-group-ids for the WORKER NODES
    security_group_id1 = json.loads(
        aws("ec2", "describe-security-groups", "--output", "json", "--filters",
            "Name=vpc-id,Values=" + vpc_id_1,
            "Name=description,Values="
            + "\"Security group for all nodes in the cluster\""))["SecurityGroups"][0]["GroupId"]
    security_group_id2 = json.loads(
        aws("ec2", "describe-security-groups", "--output", "json", "--filters",
            "Name=vpc-id,Values=" + vpc_id_2,
            "Name=description,Values="
            + "\"Security group for all nodes in the cluster\""))["SecurityGroups"][0]["GroupId"]

    # create the new rules in both
    aws("ec2", "authorize-security-group-ingress", "--group-id", security_group_id1,
        "--protocol", "tcp", "--port", "30000-32767", "--cidr", args.cidr_block[1])
    aws("ec2", "authorize-security-group-ingress", "--group-id", security_group_id2,
        "--protocol", "tcp", "--port", "30000-32767", "--cidr", args.cidr_block[0])


def get_peering_connection(args, vpc_id_1):
    """Return the correct Peering Connection linking the two specified VPCs"""
    return json.loads(aws("ec2", "describe-vpc-peering-connections", "--output", "json",
                          "--filters", "Name=requester-vpc-info.cidr-block,Values="
                          + args.cidr_block[0] + ",Name=requester-vpc-info.vpc-id,Values="
                          + vpc_id_1))


def get_peering_connection_id(args):
    """Return the correct ID of the Peering Connection linking the two specified VPCs"""
    vpc_id_1 = get_vpc_id(CONTROLPLANE_NAME + str(1))
    return get_peering_connection(args,
                                  vpc_id_1)["VpcPeeringConnections"][0]["VpcPeeringConnectionId"]


def start(args):
    """Entry point for creating cluster(s)"""
    print("starting...")

    args.region = get_region()
    print("Current AWS Region is " + str(args.region))

    print("Creating cluster")
    create_cluster(args, 1)
    if args.two:
        print("Creating second cluster")
        create_cluster(args, 2)
        xdcr_setup(args)


def stop(args):
    """Teardown the VPCs and EKS Cluster(s)."""
    if args.two:
        # delete peering connection first!
        pcx = get_peering_connection_id(args)
        print(pcx)
        aws("ec2", "delete-vpc-peering-connection", "--vpc-peering-connection-id", pcx)

        control_plane_vpc = CONTROLPLANE_NAME + str(2)
        time_start = time.time()
        name = args.name + str(2)
        print("Teardown for " + name + " started at "
              + str(time.asctime(time.localtime(time_start))))
        print("Deleting worker nodes VPC")
        aws("cloudformation", "delete-stack", "--stack-name", WORKERNODES_NAME + str(2))
        print("Deleting EKS Cluster")
        aws("eks", "delete-cluster", "--name", name)
        print("Deleting control plane VPC")
        aws("cloudformation", "delete-stack", "--stack-name", control_plane_vpc)
        aws("ec2", "delete-key-pair", "--key-name", control_plane_vpc)

    control_plane_vpc = CONTROLPLANE_NAME + str(1)
    time_start = time.time()
    name = args.name + str(1)
    print("Teardown for " + name + " started at "
          + str(time.asctime(time.localtime(time_start))))
    print("Deleting worker nodes VPC")
    aws("cloudformation", "delete-stack", "--stack-name", WORKERNODES_NAME + str(1))
    print("Deleting EKS Cluster")
    aws("eks", "delete-cluster", "--name", name)
    print("Deleting control plane VPC")
    aws("cloudformation", "delete-stack", "--stack-name", control_plane_vpc)
    aws("ec2", "delete-key-pair", "--key-name", control_plane_vpc)

    poll_eks_cluster(name, "delete")

    print("Teardown should be complete, but double-check the EKS Cluster.")
    sys.exit(0)


def main():
    """Main entry point"""
    # Parse CLI arguments.
    parser = argparse.ArgumentParser()
    parser.add_argument("command")
    parser.add_argument("eks_service_role",
                        help="Required. Name of the IAM Role to allow EKS "
                             "and the K8S control plane to manage AWS resources.")

    parser.add_argument("-n", "--name", default=NAME,
                        help="Optional. Generates the names of the EKS Clusters. "
                             "Defaults are cluster1, cluster2 for the EKS Clusters.")
    parser.add_argument("-c", "--cidr-block", action="append",
                        help="Accepts either 1 or 2 CIDR blocks as a list. "
                             "Sets the VPC block network(s). "
                             "E.g --cidr-block 192.168.0.0/16 --cidr-block 172.16.0.0/16. "
                             "Default is 192.168.0.0/16 with the addition "
                             "of 172.16.0.0/16 if two clusters are requested.")
    parser.add_argument("-t", "--two", default=False,
                        help="Enable the creation of a second cluster for XDCR purposes. "
                             "Default is False.")

    args = parser.parse_args()
    if not args.cidr_block:
        setattr(args, "cidr_block", CIDR_BLOCK)

    if args.two:
        if len(args.cidr_block) < 2:
            print("Expected 2 unique CIDR Blocks, actual " + str(len(args.cidr_block)))
            sys.exit(1)

        ad1 = ipaddress.IPv4Network(args.cidr_block[0].decode("utf-8"))
        if ad1.overlaps(ipaddress.IPv4Network(args.cidr_block[1].decode("utf-8"))):
            print("CIDR Blocks overlap, please correct.")
            sys.exit(1)

    if args.command == "start":
        start(args)
    elif args.command == "stop":
        stop(args)
    else:
        print("invalid command {}".format(args.command))
        sys.exit(1)


if __name__ == "__main__":
    main()
# vi: ts=4 et:
