pipeline {
  agent {
    label 'cao_testrunner'
  }

  options {
    timestamps()

    buildDiscarder(
      logRotator(
        artifactDaysToKeepStr: '30',
        artifactNumToKeepStr: '100',
        daysToKeepStr: '30',
        numToKeepStr: '100',
      )
    )

    // Concurrent builds are enabled because each test creates its own kubectl in its workspace.
    // disableConcurrentBuilds()
  }

  parameters {
    string(name: 'GIT_CMD', defaultValue:'')
    string(name: 'SCENARIO_FILE', defaultValue: 'scenarios/deploy/data_node_couchase.yaml')
    string(name: 'OPERATOR_IMAGE', defaultValue: 'ghcr.io/cb-vanilla/operator:latest')
    string(name: 'ADMISSION_IMAGE', defaultValue: 'ghcr.io/cb-vanilla/admission-controller:latest')
    string(name: 'CAO_VERSION', defaultValue: '2.7.0-211')
    string(name: 'KUBECTL_VERSION', defaultValue: '1.27.0')
    string(name: 'EKS_REGION', defaultValue: 'us-east-2')
    string(name: 'AKS_REGION', defaultValue: 'eastus')
    string(name: 'GKE_REGION', defaultValue: 'us-central1')
  }

  environment {
    GOVERSION = '1.22.5'
    KUBECTL_PATH = "${env.WORKSPACE}/kubectl"
    PATH = "${env.WORKSPACE}/go/bin:${env.WORKSPACE}/bin:$PATH"
    GOROOT = "${env.WORKSPACE}/go"
    IMAGE_REGISTRY_SERVER = credentials('cloud-native-image-registry-server')
    IMAGE_REGISTRY_USERNAME = credentials('cloud-native-image-registry-username')
    IMAGE_REGISTRY_PASSWORD = credentials('cloud-native-image-registry-password')
    IMAGE_REGISTRY_EMAIL = credentials('cloud-native-image-registry-email')
    EKS_ACCESS_KEY = credentials('cloud-native-aws-access-id')
    EKS_SECRET_KEY = credentials('cloud-native-aws-access-secret-key')
    EKS_ACCOUNT_ID = credentials('cloud-native-aws-account-id')
    KUBECONFIG = "/root/.kube/config"
    AKS_SUBSCRIPTION_ID = credentials('cloud-native-azure-subscription-id')
    AKS_SERVICE_PRINCIPAL_ID = credentials('cloud-native-azure-principal-id')
    AKS_SERVICE_PRINCIPAL_SECRET_ID = credentials('cloud-native-azure-principal-secret-id')
    AKS_TENANT_ID = credentials('cloud-native-azure-tenant-id')
    GKE_CREDENTIALS_JSON_PATH = credentials('cloud-native-gcp-credentials')
    GKE_PROJECT_ID = "couchbase-qe"
    CLUSTER_NAME = "${env.JOB_NAME}-${env.BUILD_NUMBER}"
    OPERATING_SYSTEM = "linux"
    ARCHITECTURE= "amd64"
    GO111MODULE="auto"
    OPERATOR_IMAGE = "${params.OPERATOR_IMAGE}"
    ADMISSION_CONTROLLER_IMAGE = "${params.ADMISSION_IMAGE}"
    OPERATOR_VERSION = "${params.CAO_VERSION}"
    EKS_REGION = "${params.EKS_REGION}"
    AKS_REGION = "${params.AKS_REGION}"
    GKE_REGION = "${params.GKE_REGION}"
  }

  stages {

    stage('Prerequisite Installs') {
      steps {
        sh "mkdir -p ${env.WORKSPACE}/bin"

        sh "wget -q -O- https://dl.google.com/go/go${env.GOVERSION}.linux-amd64.tar.gz | tar xz"

        sh "wget -q https://dl.k8s.io/release/v${params.KUBECTL_VERSION}/bin/linux/amd64/kubectl"
        sh "chmod +x kubectl"
        sh "mv kubectl ${env.WORKSPACE}/bin/"

        sh 'wget -q https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64'
        sh 'chmod +x jq-linux64'
        sh "mv jq-linux64 ${env.WORKSPACE}/bin/jq"
      }
    }

 stage('Git Operations') {
     when {
        expression { params.GIT_CMD.trim() != '' }
    }
    steps {
        script {
            sh "${params.GIT_CMD}"
        }
    }
}

    stage('Test CAO Testrunner') {
      steps {
        dir("./test/cao_test_runner") {
            script {
              try {
                  sh """
                     go mod tidy
                     go run . scenario --scenario ${params.SCENARIO_FILE}
                     """
              }
              catch (e) {
                  currentBuild.result = 'UNSTABLE'
              }
            }
        }
      }
    }
  }

  post {
    always {
      sh 'docker system prune --force' // Clean up docker - optimise disk usage
      cleanWs()
    }
  }
}
