pipeline {
  agent {
    label 'k8'
  }

  options {
    timestamps()

    buildDiscarder(
      logRotator(
        artifactDaysToKeepStr: '14',
        artifactNumToKeepStr: '20',
        daysToKeepStr: '14',
        numToKeepStr: '20',
      )
    )

    // Concurrent builds are enabled because each test creates its own kubectl in its workspace.
    // disableConcurrentBuilds()
  }

  parameters {
    string(name: 'git_cmd', defaultValue:'')
    string(name: 'scenario_file', defaultValue: 'scenarios/deploy/data_node_couchase.yaml')
    string(name: 'operator_image', defaultValue: 'ghcr.io/cb-vanilla/operator:latest')
    string(name: 'admission_image', defaultValue: 'ghcr.io/cb-vanilla/admission-controller:latest')
    string(name: 'cao_version', defaultValue: '2.7.0-211')
    string(name: 'kubectl_version', defaultValue: '1.27.0')
    string(name: 'eks_region', defaultValue: 'us-east-2')
    string(name: 'aks_region', defaultValue: 'eastus')
    string(name: 'gke_region', defaultValue: 'us-central1')
  }

  environment {
    GOVERSION = '1.22.5'
    GOROOT = "${env.WORKSPACE}/go"
    KUBECTL_PATH = "${env.WORKSPACE}/kubectl"
    PATH = "${env.WORKSPACE}/go/bin:${env.WORKSPACE}/bin:$PATH"
    DOCKER_CREDENTIALS = credentials('couchbaseqe-dockerhub')
    GITLAB_CREDENTIALS = credentials('couchbaseqe-gitlab')
    GHCR_CREDENTIALS = credentials('couchbaseqe-ghrc')
    S3_ACCESS_KEY = credentials('cbqe-s3-access-key')
    S3_SECRET_ID = credentials('cbqe-s3-secret-id')
    EKS_ACCESS_KEY = credentials('couchbaseqe-aws-access-id')
    EKS_SECRET_KEY = credentials('couchbaseqe-aws-access-secret')
    EKS_REGION = "${params.eks_region}"
    AKS_REGION = "${params.aks_region}"
    GKE_REGION = "${params.gke_region}"
    AKS_SUBSCRIPTION_ID = credentials('azure-subscription-id')
    AZURE_CREDENTIALS = credentials('couchbaseqe-azure')
    AKS_SERVICE_PRINCIPAL_ID = "${env.AZURE_CREDENTIALS_USR}"
    AKS_SERVICE_PRINCIPAL_SECRET_ID = "${env.AZURE_CREDENTIALS_PSW}"
    AKS_TENANT_ID = credentials('azure-tenant-id')
    GKE_CREDENTIALS_JSON = credentials('couchbaseqe-gcp')
    GKE_PROJECT_ID = "couchbase-qe"
    CLUSTER_NAME = "${env.JOB_NAME}-${env.BUILD_NUMBER}"
    OPERATOR_IMAGE = "${params.operator_image}"
    ADMISSION_CONTROLLER_IMAGE = "${params.admission_image}"
    OPERATOR_VERSION = "${params.cao_version}"
    OPERATING_SYSTEM = "linux"
    ARCHITECTURE= "amd64"
  }

  stages {

    stage('Prerequisite Installs') {
      steps {
        sh "mkdir -p ${env.WORKSPACE}/bin"

        sh "wget -q -O- https://dl.google.com/go/go${env.GOVERSION}.linux-amd64.tar.gz | tar xz"

        sh "wget -q https://dl.k8s.io/release/v${params.kubectl_version}/bin/linux/amd64/kubectl"
        sh "chmod +x kubectl"
        sh "mv kubectl ${env.WORKSPACE}/bin/"

        sh 'wget -q https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64'
        sh 'chmod +x jq-linux64'
        sh "mv jq-linux64 ${env.WORKSPACE}/bin/jq"
      }
    }

 stage('Git Operations') {
     when {
        expression { params.git_cmd.trim() != '' }
    }
    steps {
        script {
            sh "${params.git_cmd}"
        }
    }
}

    stage('Test CAO Testrunner') {
      steps {
        dir("./test/cao_test_runner") {
            script {
              // Set google credentials here
              sh "echo ${env.GKE_CREDENTIALS_JSON} > credentials.json"
              env.GKE_CREDENTIALS_JSON_PATH = "${env.WORKSPACE}/test/cao_test_runner/credentials.json"

              try {
                  sh "go run . scenario --scenario ${params.scenario_file}"
              }
              catch (e) {
                  currentBuild.result = 'UNSTABLE'
              }
            }
        }
      }
    }
  }

  post {
    always {
      sh 'docker system prune --force' // Clean up docker - optimise disk usage
      cleanWs()
    }
  }
}
