#!/usr/bin/env python3

# Copyright 2021-Present Couchbase, Inc.
#
# Use of this software is governed by the Business Source License included in
# the file licenses/BSL-Couchbase.txt.  As of the Change Date specified in that
# file, in accordance with the Business Source License, use of this software
# will be governed by the Apache License, Version 2.0, included in the file
# licenses/APL2.txt.

"""
istio_provision

Description:
    This install istio with the desired version
    on the kubernetes cluster specified and then verifies the
    installation process

Usage:
    istio_provision start

Options:
    --kubeconfig KUBECONFIG         Specifies the kubeconfig string of the cluster
                                    on which istio needs to be installed
"""

import argparse
import subprocess
import sys
import tempfile

OPERATORPEERAUTHENTICATION = """
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: peer-authentication-cluster
  namespace: istio-system
spec:
  mtls:
    mode: STRICT
"""

EXPORTERPEERAUTHENTICATION="""
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: peer-authentication-metrics
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: couchbase
  portLevelMtls:
    9091:
      mode: PERMISSIVE
"""

DACPEERAUTHENTICATION="""
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: peer-authentication-dac
  namespace: default
spec:
  selector:
    matchLabels:
      app: couchbase-operator-admission
  mtls:
    mode: PERMISSIVE
"""

CERTIFICATIONPEERAUTHENTICATION = """
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: peer-authentication-certification
  namespace: default
spec:
  selector:
    matchLabels:
      app: certification
  mtls:
    mode: STRICT
"""

def kubectl(*cmd):
    """Runs a kubectl command raising an exception on error"""

    return subprocess.check_output(['kubectl'] + list(cmd)).decode().strip()

def apply_operator_peer_authentication(args):
    """Runs a kubectl command raising an exception on error"""
    with tempfile.NamedTemporaryFile() as manifest:
        manifest.write(OPERATORPEERAUTHENTICATION.encode())
        manifest.flush()

        kubectl('apply', '-f', manifest.name,
                '--kubeconfig', args.kubeconfig)

def apply_exporter_peer_authentication(args):
    """Runs a kubectl command raising an exception on error"""
    with tempfile.NamedTemporaryFile() as manifest:
        manifest.write(EXPORTERPEERAUTHENTICATION.encode())
        manifest.flush()

        kubectl('apply', '-f', manifest.name,
                '--kubeconfig', args.kubeconfig)

def apply_dac_peer_authentication(args):
    """Runs a kubectl command raising an exception on error"""
    with tempfile.NamedTemporaryFile() as manifest:
        manifest.write(DACPEERAUTHENTICATION.encode())
        manifest.flush()

        kubectl('apply', '-f', manifest.name,
                '--kubeconfig', args.kubeconfig)

def apply_certification_peer_authentication(args):
    """Runs a kubectl command raising an exception on error"""
    with tempfile.NamedTemporaryFile() as manifest:
        manifest.write(CERTIFICATIONPEERAUTHENTICATION.encode())
        manifest.flush()

        kubectl('apply', '-f', manifest.name,
                '--kubeconfig', args.kubeconfig)

def istioctl(*cmd):
    """Runs a istioctl command raising an exception on error"""
    try:
        return subprocess.check_output(['istioctl'] + list(cmd)).decode().strip()
    except subprocess.CalledProcessError as err:
        raise RuntimeError(f"command '{err.cmd}' failed") from err

def start(args):
    """
    Run istioctl command with required parameters
    """
    istioctl('install', '-y', '--kubeconfig' , args.kubeconfig)
    # Mark default namespace with istio-injection.
    kubectl('label', 'namespace', 'default', 'istio-injection=enabled', '--overwrite')
    istioctl('verify-install', '--kubeconfig' , args.kubeconfig)
    if args.mode == 'strict':
        apply_dac_peer_authentication(args)
        apply_certification_peer_authentication(args)
        apply_operator_peer_authentication(args)
        apply_exporter_peer_authentication(args)

def main():
    """Main entry point"""

    # Parse CLI arguments.
    parser = argparse.ArgumentParser()
    parser.add_argument('command')
    parser.add_argument('-c', '--kubeconfig', required=True)
    parser.add_argument('-m', '--mode', default='permissive')

    args = parser.parse_args()

    if args.command == 'start' and not args.kubeconfig:
        print('istio provision error: cluster config file')
        sys.exit(1)

    if args.command == 'start':
        start(args)
    else:
        print(f'invalid command {args.command}')
        sys.exit(1)


if __name__ == '__main__':
    main()
