# Copyright 2020-Present Couchbase, Inc.
#
# Use of this software is governed by the Business Source License included in
# the file licenses/BSL-Couchbase.txt.  As of the Change Date specified in that
# file, in accordance with the Business Source License, use of this software
# will be governed by the Apache License, Version 2.0, included in the file
# licenses/APL2.txt.

apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
data:
  # Configuration:
  # * "remote.svc.cluster.local" refers to a DNS zone for a namespace in a remote cluster
  #   reachable by flat L3 networking (SNAT is allowed from the local to the remote, but not
  #   DNAT anywhere in the path.  Change "remote" to the remote namespace.
  # * "10.32.3.2" is the remote DNS server IP address, you can get this from the DNS service
  #   endpoints, but it's most likely better to provision a load balancer service that provides
  #   stable IP addressing.
  # * "10.39.240.10" is the local DNS server service.
  Corefile: |-
    remote.svc.cluster.local:5353 {
      forward . 10.32.3.2
    }
    .:5353 {
      forward . 10.39.240.10
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coredns
  template:
    metadata:
      labels:
        app: coredns
    spec:
      containers:
      - name: coredns
        image: coredns/coredns:1.6.6
        args:
        - '-conf'
        - '/etc/coredns/Corefile'
        ports:
        - name: dns
          containerPort: 5353
        volumeMounts:
        - name: config
          mountPath: /etc/coredns
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: coredns
---
apiVersion: v1
kind: Service
metadata:
  name: coredns
spec:
  selector:
    app: coredns
  ports:
  - name: dns
    protocol: UDP
    port: 53
    targetPort: 5353
  - name: dns-tcp
    protocol: TCP
    port: 53
    targetPort: 5353
