# Copyright 2020-Present Couchbase, Inc.
#
# Use of this software is governed by the Business Source License included in
# the file licenses/BSL-Couchbase.txt.  As of the Change Date specified in that
# file, in accordance with the Business Source License, use of this software
# will be governed by the Apache License, Version 2.0, included in the file
# licenses/APL2.txt.

apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: default
---
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-example
spec:
  image: couchbase/server:6.6.2
  security:
    adminSecret: cb-example-auth
  buckets:
    managed: true
  servers:
    - size: 3
      name: all_services
      services:
        - data
        - index
        - query
        - search
        - eventing
        - analytics
      pod:
        spec:
          dnsPolicy: None
          # Configuration:
          # * "10.39.255.231" is the local DNS service IP, as provisioned by local-coredns.yaml.
          dnsConfig:
            nameservers:
            - "10.39.255.231"
            searches:
            - remote.svc.cluster.local
            - svc.cluster.local
            - cluster.local
  xdcr:
    managed: true
    # Configuration:
    # * "cb-example-0000.cb-example.remote.svc" is a host in the remote DNS zone
    # * "5192c4cbba3cf377f3d6fec6ad0ec80d" is the UUID extracted from the remote
    #   clusters status field.
    remoteClusters:
    - authenticationSecret: cb-example-auth
      hostname: cb-example-srv.remote
      name: remote
      replications: {}
      uuid: 5192c4cbba3cf377f3d6fec6ad0ec80d
