// +build !ignore_autogenerated

/* Copyright (C) Couchbase, Inc 2018 - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */

// Code generated by deepcopy-gen. DO NOT EDIT.

package v2

import (
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoCompaction) DeepCopyInto(out *AutoCompaction) {
	*out = *in
	in.DatabaseFragmentationThreshold.DeepCopyInto(&out.DatabaseFragmentationThreshold)
	in.ViewFragmentationThreshold.DeepCopyInto(&out.ViewFragmentationThreshold)
	out.TimeWindow = in.TimeWindow
	if in.TombstonePurgeInterval != nil {
		in, out := &in.TombstonePurgeInterval, &out.TombstonePurgeInterval
		*out = new(v1.Duration)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoCompaction.
func (in *AutoCompaction) DeepCopy() *AutoCompaction {
	if in == nil {
		return nil
	}
	out := new(AutoCompaction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Backup) DeepCopyInto(out *Backup) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Backup.
func (in *Backup) DeepCopy() *Backup {
	if in == nil {
		return nil
	}
	out := new(Backup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupStatus) DeepCopyInto(out *BackupStatus) {
	*out = *in
	if in.Incrementals != nil {
		in, out := &in.Incrementals, &out.Incrementals
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupStatus.
func (in *BackupStatus) DeepCopy() *BackupStatus {
	if in == nil {
		return nil
	}
	out := new(BackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BucketStatus) DeepCopyInto(out *BucketStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BucketStatus.
func (in *BucketStatus) DeepCopy() *BucketStatus {
	if in == nil {
		return nil
	}
	out := new(BucketStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Buckets) DeepCopyInto(out *Buckets) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Buckets.
func (in *Buckets) DeepCopy() *Buckets {
	if in == nil {
		return nil
	}
	out := new(Buckets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientCertificatePath) DeepCopyInto(out *ClientCertificatePath) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientCertificatePath.
func (in *ClientCertificatePath) DeepCopy() *ClientCertificatePath {
	if in == nil {
		return nil
	}
	out := new(ClientCertificatePath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCondition) DeepCopyInto(out *ClusterCondition) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCondition.
func (in *ClusterCondition) DeepCopy() *ClusterCondition {
	if in == nil {
		return nil
	}
	out := new(ClusterCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterConfig) DeepCopyInto(out *ClusterConfig) {
	*out = *in
	if in.DataServiceMemQuota != nil {
		in, out := &in.DataServiceMemQuota, &out.DataServiceMemQuota
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.IndexServiceMemQuota != nil {
		in, out := &in.IndexServiceMemQuota, &out.IndexServiceMemQuota
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.SearchServiceMemQuota != nil {
		in, out := &in.SearchServiceMemQuota, &out.SearchServiceMemQuota
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.EventingServiceMemQuota != nil {
		in, out := &in.EventingServiceMemQuota, &out.EventingServiceMemQuota
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.AnalyticsServiceMemQuota != nil {
		in, out := &in.AnalyticsServiceMemQuota, &out.AnalyticsServiceMemQuota
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.AutoFailoverTimeout != nil {
		in, out := &in.AutoFailoverTimeout, &out.AutoFailoverTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.AutoFailoverOnDataDiskIssuesTimePeriod != nil {
		in, out := &in.AutoFailoverOnDataDiskIssuesTimePeriod, &out.AutoFailoverOnDataDiskIssuesTimePeriod
		*out = new(v1.Duration)
		**out = **in
	}
	if in.AutoCompaction != nil {
		in, out := &in.AutoCompaction, &out.AutoCompaction
		*out = new(AutoCompaction)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterConfig.
func (in *ClusterConfig) DeepCopy() *ClusterConfig {
	if in == nil {
		return nil
	}
	out := new(ClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSpec) DeepCopyInto(out *ClusterSpec) {
	*out = *in
	if in.HibernationStrategy != nil {
		in, out := &in.HibernationStrategy, &out.HibernationStrategy
		*out = new(HibernationStrategy)
		**out = **in
	}
	if in.RecoveryPolicy != nil {
		in, out := &in.RecoveryPolicy, &out.RecoveryPolicy
		*out = new(RecoveryPolicy)
		**out = **in
	}
	if in.UpgradeStrategy != nil {
		in, out := &in.UpgradeStrategy, &out.UpgradeStrategy
		*out = new(UpgradeStrategy)
		**out = **in
	}
	in.ClusterSettings.DeepCopyInto(&out.ClusterSettings)
	if in.VolumeClaimTemplates != nil {
		in, out := &in.VolumeClaimTemplates, &out.VolumeClaimTemplates
		*out = make([]corev1.PersistentVolumeClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServerGroups != nil {
		in, out := &in.ServerGroups, &out.ServerGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(corev1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	in.Security.DeepCopyInto(&out.Security)
	in.Networking.DeepCopyInto(&out.Networking)
	out.Logging = in.Logging
	if in.Servers != nil {
		in, out := &in.Servers, &out.Servers
		*out = make([]ServerConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Buckets.DeepCopyInto(&out.Buckets)
	in.XDCR.DeepCopyInto(&out.XDCR)
	if in.Monitoring != nil {
		in, out := &in.Monitoring, &out.Monitoring
		*out = new(CouchbaseClusterMonitoringSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Backup.DeepCopyInto(&out.Backup)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpec.
func (in *ClusterSpec) DeepCopy() *ClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStatus) DeepCopyInto(out *ClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ClusterCondition, len(*in))
		copy(*out, *in)
	}
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = new(MembersStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Buckets != nil {
		in, out := &in.Buckets, &out.Buckets
		*out = make([]BucketStatus, len(*in))
		copy(*out, *in)
	}
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatus.
func (in *ClusterStatus) DeepCopy() *ClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseBackup) DeepCopyInto(out *CouchbaseBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseBackup.
func (in *CouchbaseBackup) DeepCopy() *CouchbaseBackup {
	if in == nil {
		return nil
	}
	out := new(CouchbaseBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CouchbaseBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseBackupList) DeepCopyInto(out *CouchbaseBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CouchbaseBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseBackupList.
func (in *CouchbaseBackupList) DeepCopy() *CouchbaseBackupList {
	if in == nil {
		return nil
	}
	out := new(CouchbaseBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CouchbaseBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseBackupRestore) DeepCopyInto(out *CouchbaseBackupRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseBackupRestore.
func (in *CouchbaseBackupRestore) DeepCopy() *CouchbaseBackupRestore {
	if in == nil {
		return nil
	}
	out := new(CouchbaseBackupRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CouchbaseBackupRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseBackupRestoreList) DeepCopyInto(out *CouchbaseBackupRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CouchbaseBackupRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseBackupRestoreList.
func (in *CouchbaseBackupRestoreList) DeepCopy() *CouchbaseBackupRestoreList {
	if in == nil {
		return nil
	}
	out := new(CouchbaseBackupRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CouchbaseBackupRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseBackupRestoreSpec) DeepCopyInto(out *CouchbaseBackupRestoreSpec) {
	*out = *in
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = new(StrOrInt)
		(*in).DeepCopyInto(*out)
	}
	if in.End != nil {
		in, out := &in.End, &out.End
		*out = new(StrOrInt)
		(*in).DeepCopyInto(*out)
	}
	if in.LogRetention != nil {
		in, out := &in.LogRetention, &out.LogRetention
		*out = new(v1.Duration)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseBackupRestoreSpec.
func (in *CouchbaseBackupRestoreSpec) DeepCopy() *CouchbaseBackupRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(CouchbaseBackupRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseBackupRestoreStatus) DeepCopyInto(out *CouchbaseBackupRestoreStatus) {
	*out = *in
	if in.Backups != nil {
		in, out := &in.Backups, &out.Backups
		*out = make([]BackupStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.LastFailure != nil {
		in, out := &in.LastFailure, &out.LastFailure
		*out = (*in).DeepCopy()
	}
	if in.LastSuccess != nil {
		in, out := &in.LastSuccess, &out.LastSuccess
		*out = (*in).DeepCopy()
	}
	if in.LastRun != nil {
		in, out := &in.LastRun, &out.LastRun
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseBackupRestoreStatus.
func (in *CouchbaseBackupRestoreStatus) DeepCopy() *CouchbaseBackupRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(CouchbaseBackupRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseBackupSchedule) DeepCopyInto(out *CouchbaseBackupSchedule) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseBackupSchedule.
func (in *CouchbaseBackupSchedule) DeepCopy() *CouchbaseBackupSchedule {
	if in == nil {
		return nil
	}
	out := new(CouchbaseBackupSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseBackupSpec) DeepCopyInto(out *CouchbaseBackupSpec) {
	*out = *in
	if in.Incremental != nil {
		in, out := &in.Incremental, &out.Incremental
		*out = new(CouchbaseBackupSchedule)
		**out = **in
	}
	if in.Full != nil {
		in, out := &in.Full, &out.Full
		*out = new(CouchbaseBackupSchedule)
		**out = **in
	}
	if in.BackupRetention != nil {
		in, out := &in.BackupRetention, &out.BackupRetention
		*out = new(v1.Duration)
		**out = **in
	}
	if in.LogRetention != nil {
		in, out := &in.LogRetention, &out.LogRetention
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		x := (*in).DeepCopy()
		*out = &x
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseBackupSpec.
func (in *CouchbaseBackupSpec) DeepCopy() *CouchbaseBackupSpec {
	if in == nil {
		return nil
	}
	out := new(CouchbaseBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseBackupStatus) DeepCopyInto(out *CouchbaseBackupStatus) {
	*out = *in
	if in.CapacityUsed != nil {
		in, out := &in.CapacityUsed, &out.CapacityUsed
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Backups != nil {
		in, out := &in.Backups, &out.Backups
		*out = make([]BackupStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.LastFailure != nil {
		in, out := &in.LastFailure, &out.LastFailure
		*out = (*in).DeepCopy()
	}
	if in.LastSuccess != nil {
		in, out := &in.LastSuccess, &out.LastSuccess
		*out = (*in).DeepCopy()
	}
	if in.LastRun != nil {
		in, out := &in.LastRun, &out.LastRun
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseBackupStatus.
func (in *CouchbaseBackupStatus) DeepCopy() *CouchbaseBackupStatus {
	if in == nil {
		return nil
	}
	out := new(CouchbaseBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseBucket) DeepCopyInto(out *CouchbaseBucket) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseBucket.
func (in *CouchbaseBucket) DeepCopy() *CouchbaseBucket {
	if in == nil {
		return nil
	}
	out := new(CouchbaseBucket)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CouchbaseBucket) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseBucketList) DeepCopyInto(out *CouchbaseBucketList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CouchbaseBucket, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseBucketList.
func (in *CouchbaseBucketList) DeepCopy() *CouchbaseBucketList {
	if in == nil {
		return nil
	}
	out := new(CouchbaseBucketList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CouchbaseBucketList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseBucketSpec) DeepCopyInto(out *CouchbaseBucketSpec) {
	*out = *in
	if in.MemoryQuota != nil {
		in, out := &in.MemoryQuota, &out.MemoryQuota
		x := (*in).DeepCopy()
		*out = &x
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseBucketSpec.
func (in *CouchbaseBucketSpec) DeepCopy() *CouchbaseBucketSpec {
	if in == nil {
		return nil
	}
	out := new(CouchbaseBucketSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseCluster) DeepCopyInto(out *CouchbaseCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseCluster.
func (in *CouchbaseCluster) DeepCopy() *CouchbaseCluster {
	if in == nil {
		return nil
	}
	out := new(CouchbaseCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CouchbaseCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseClusterLDAPSpec) DeepCopyInto(out *CouchbaseClusterLDAPSpec) {
	*out = *in
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.UserDNMapping = in.UserDNMapping
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseClusterLDAPSpec.
func (in *CouchbaseClusterLDAPSpec) DeepCopy() *CouchbaseClusterLDAPSpec {
	if in == nil {
		return nil
	}
	out := new(CouchbaseClusterLDAPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseClusterList) DeepCopyInto(out *CouchbaseClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CouchbaseCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseClusterList.
func (in *CouchbaseClusterList) DeepCopy() *CouchbaseClusterList {
	if in == nil {
		return nil
	}
	out := new(CouchbaseClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CouchbaseClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseClusterLoggingSpec) DeepCopyInto(out *CouchbaseClusterLoggingSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseClusterLoggingSpec.
func (in *CouchbaseClusterLoggingSpec) DeepCopy() *CouchbaseClusterLoggingSpec {
	if in == nil {
		return nil
	}
	out := new(CouchbaseClusterLoggingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseClusterMonitoringPrometheusSpec) DeepCopyInto(out *CouchbaseClusterMonitoringPrometheusSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthorizationSecret != nil {
		in, out := &in.AuthorizationSecret, &out.AuthorizationSecret
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseClusterMonitoringPrometheusSpec.
func (in *CouchbaseClusterMonitoringPrometheusSpec) DeepCopy() *CouchbaseClusterMonitoringPrometheusSpec {
	if in == nil {
		return nil
	}
	out := new(CouchbaseClusterMonitoringPrometheusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseClusterMonitoringSpec) DeepCopyInto(out *CouchbaseClusterMonitoringSpec) {
	*out = *in
	if in.Prometheus != nil {
		in, out := &in.Prometheus, &out.Prometheus
		*out = new(CouchbaseClusterMonitoringPrometheusSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseClusterMonitoringSpec.
func (in *CouchbaseClusterMonitoringSpec) DeepCopy() *CouchbaseClusterMonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(CouchbaseClusterMonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseClusterNetworkingSpec) DeepCopyInto(out *CouchbaseClusterNetworkingSpec) {
	*out = *in
	if in.AdminConsoleServices != nil {
		in, out := &in.AdminConsoleServices, &out.AdminConsoleServices
		*out = make(ServiceList, len(*in))
		copy(*out, *in)
	}
	if in.AdminConsoleServiceTemplate != nil {
		in, out := &in.AdminConsoleServiceTemplate, &out.AdminConsoleServiceTemplate
		*out = new(ServiceTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ExposedFeatures != nil {
		in, out := &in.ExposedFeatures, &out.ExposedFeatures
		*out = make(ExposedFeatureList, len(*in))
		copy(*out, *in)
	}
	if in.ExposedFeatureServiceTemplate != nil {
		in, out := &in.ExposedFeatureServiceTemplate, &out.ExposedFeatureServiceTemplate
		*out = new(ServiceTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ExposedFeatureTrafficPolicy != nil {
		in, out := &in.ExposedFeatureTrafficPolicy, &out.ExposedFeatureTrafficPolicy
		*out = new(corev1.ServiceExternalTrafficPolicyType)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = new(DNS)
		**out = **in
	}
	if in.ServiceAnnotations != nil {
		in, out := &in.ServiceAnnotations, &out.ServiceAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LoadBalancerSourceRanges != nil {
		in, out := &in.LoadBalancerSourceRanges, &out.LoadBalancerSourceRanges
		*out = make(IPV4PrefixList, len(*in))
		copy(*out, *in)
	}
	if in.NetworkPlatform != nil {
		in, out := &in.NetworkPlatform, &out.NetworkPlatform
		*out = new(NetworkPlatform)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseClusterNetworkingSpec.
func (in *CouchbaseClusterNetworkingSpec) DeepCopy() *CouchbaseClusterNetworkingSpec {
	if in == nil {
		return nil
	}
	out := new(CouchbaseClusterNetworkingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseClusterSecuritySpec) DeepCopyInto(out *CouchbaseClusterSecuritySpec) {
	*out = *in
	in.RBAC.DeepCopyInto(&out.RBAC)
	if in.LDAP != nil {
		in, out := &in.LDAP, &out.LDAP
		*out = new(CouchbaseClusterLDAPSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseClusterSecuritySpec.
func (in *CouchbaseClusterSecuritySpec) DeepCopy() *CouchbaseClusterSecuritySpec {
	if in == nil {
		return nil
	}
	out := new(CouchbaseClusterSecuritySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseEphemeralBucket) DeepCopyInto(out *CouchbaseEphemeralBucket) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseEphemeralBucket.
func (in *CouchbaseEphemeralBucket) DeepCopy() *CouchbaseEphemeralBucket {
	if in == nil {
		return nil
	}
	out := new(CouchbaseEphemeralBucket)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CouchbaseEphemeralBucket) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseEphemeralBucketList) DeepCopyInto(out *CouchbaseEphemeralBucketList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CouchbaseEphemeralBucket, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseEphemeralBucketList.
func (in *CouchbaseEphemeralBucketList) DeepCopy() *CouchbaseEphemeralBucketList {
	if in == nil {
		return nil
	}
	out := new(CouchbaseEphemeralBucketList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CouchbaseEphemeralBucketList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseEphemeralBucketSpec) DeepCopyInto(out *CouchbaseEphemeralBucketSpec) {
	*out = *in
	if in.MemoryQuota != nil {
		in, out := &in.MemoryQuota, &out.MemoryQuota
		x := (*in).DeepCopy()
		*out = &x
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseEphemeralBucketSpec.
func (in *CouchbaseEphemeralBucketSpec) DeepCopy() *CouchbaseEphemeralBucketSpec {
	if in == nil {
		return nil
	}
	out := new(CouchbaseEphemeralBucketSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseGroup) DeepCopyInto(out *CouchbaseGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseGroup.
func (in *CouchbaseGroup) DeepCopy() *CouchbaseGroup {
	if in == nil {
		return nil
	}
	out := new(CouchbaseGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CouchbaseGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseGroupList) DeepCopyInto(out *CouchbaseGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CouchbaseGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseGroupList.
func (in *CouchbaseGroupList) DeepCopy() *CouchbaseGroupList {
	if in == nil {
		return nil
	}
	out := new(CouchbaseGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CouchbaseGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseGroupSpec) DeepCopyInto(out *CouchbaseGroupSpec) {
	*out = *in
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]Role, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseGroupSpec.
func (in *CouchbaseGroupSpec) DeepCopy() *CouchbaseGroupSpec {
	if in == nil {
		return nil
	}
	out := new(CouchbaseGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseMemcachedBucket) DeepCopyInto(out *CouchbaseMemcachedBucket) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseMemcachedBucket.
func (in *CouchbaseMemcachedBucket) DeepCopy() *CouchbaseMemcachedBucket {
	if in == nil {
		return nil
	}
	out := new(CouchbaseMemcachedBucket)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CouchbaseMemcachedBucket) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseMemcachedBucketList) DeepCopyInto(out *CouchbaseMemcachedBucketList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CouchbaseMemcachedBucket, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseMemcachedBucketList.
func (in *CouchbaseMemcachedBucketList) DeepCopy() *CouchbaseMemcachedBucketList {
	if in == nil {
		return nil
	}
	out := new(CouchbaseMemcachedBucketList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CouchbaseMemcachedBucketList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseMemcachedBucketSpec) DeepCopyInto(out *CouchbaseMemcachedBucketSpec) {
	*out = *in
	if in.MemoryQuota != nil {
		in, out := &in.MemoryQuota, &out.MemoryQuota
		x := (*in).DeepCopy()
		*out = &x
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseMemcachedBucketSpec.
func (in *CouchbaseMemcachedBucketSpec) DeepCopy() *CouchbaseMemcachedBucketSpec {
	if in == nil {
		return nil
	}
	out := new(CouchbaseMemcachedBucketSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseReplication) DeepCopyInto(out *CouchbaseReplication) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseReplication.
func (in *CouchbaseReplication) DeepCopy() *CouchbaseReplication {
	if in == nil {
		return nil
	}
	out := new(CouchbaseReplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CouchbaseReplication) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseReplicationList) DeepCopyInto(out *CouchbaseReplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CouchbaseReplication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseReplicationList.
func (in *CouchbaseReplicationList) DeepCopy() *CouchbaseReplicationList {
	if in == nil {
		return nil
	}
	out := new(CouchbaseReplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CouchbaseReplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseReplicationSpec) DeepCopyInto(out *CouchbaseReplicationSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseReplicationSpec.
func (in *CouchbaseReplicationSpec) DeepCopy() *CouchbaseReplicationSpec {
	if in == nil {
		return nil
	}
	out := new(CouchbaseReplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseRoleBinding) DeepCopyInto(out *CouchbaseRoleBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseRoleBinding.
func (in *CouchbaseRoleBinding) DeepCopy() *CouchbaseRoleBinding {
	if in == nil {
		return nil
	}
	out := new(CouchbaseRoleBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CouchbaseRoleBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseRoleBindingList) DeepCopyInto(out *CouchbaseRoleBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CouchbaseRoleBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseRoleBindingList.
func (in *CouchbaseRoleBindingList) DeepCopy() *CouchbaseRoleBindingList {
	if in == nil {
		return nil
	}
	out := new(CouchbaseRoleBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CouchbaseRoleBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseRoleBindingRef) DeepCopyInto(out *CouchbaseRoleBindingRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseRoleBindingRef.
func (in *CouchbaseRoleBindingRef) DeepCopy() *CouchbaseRoleBindingRef {
	if in == nil {
		return nil
	}
	out := new(CouchbaseRoleBindingRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseRoleBindingSpec) DeepCopyInto(out *CouchbaseRoleBindingSpec) {
	*out = *in
	if in.Subjects != nil {
		in, out := &in.Subjects, &out.Subjects
		*out = make([]CouchbaseRoleBindingSubject, len(*in))
		copy(*out, *in)
	}
	out.RoleRef = in.RoleRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseRoleBindingSpec.
func (in *CouchbaseRoleBindingSpec) DeepCopy() *CouchbaseRoleBindingSpec {
	if in == nil {
		return nil
	}
	out := new(CouchbaseRoleBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseRoleBindingSubject) DeepCopyInto(out *CouchbaseRoleBindingSubject) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseRoleBindingSubject.
func (in *CouchbaseRoleBindingSubject) DeepCopy() *CouchbaseRoleBindingSubject {
	if in == nil {
		return nil
	}
	out := new(CouchbaseRoleBindingSubject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseUser) DeepCopyInto(out *CouchbaseUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseUser.
func (in *CouchbaseUser) DeepCopy() *CouchbaseUser {
	if in == nil {
		return nil
	}
	out := new(CouchbaseUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CouchbaseUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseUserList) DeepCopyInto(out *CouchbaseUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CouchbaseUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseUserList.
func (in *CouchbaseUserList) DeepCopy() *CouchbaseUserList {
	if in == nil {
		return nil
	}
	out := new(CouchbaseUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CouchbaseUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouchbaseUserSpec) DeepCopyInto(out *CouchbaseUserSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouchbaseUserSpec.
func (in *CouchbaseUserSpec) DeepCopy() *CouchbaseUserSpec {
	if in == nil {
		return nil
	}
	out := new(CouchbaseUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNS) DeepCopyInto(out *DNS) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNS.
func (in *DNS) DeepCopy() *DNS {
	if in == nil {
		return nil
	}
	out := new(DNS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseFragmentationThreshold) DeepCopyInto(out *DatabaseFragmentationThreshold) {
	*out = *in
	if in.Percent != nil {
		in, out := &in.Percent, &out.Percent
		*out = new(int)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		x := (*in).DeepCopy()
		*out = &x
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseFragmentationThreshold.
func (in *DatabaseFragmentationThreshold) DeepCopy() *DatabaseFragmentationThreshold {
	if in == nil {
		return nil
	}
	out := new(DatabaseFragmentationThreshold)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ExposedFeatureList) DeepCopyInto(out *ExposedFeatureList) {
	{
		in := &in
		*out = make(ExposedFeatureList, len(*in))
		copy(*out, *in)
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExposedFeatureList.
func (in ExposedFeatureList) DeepCopy() ExposedFeatureList {
	if in == nil {
		return nil
	}
	out := new(ExposedFeatureList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in IPV4PrefixList) DeepCopyInto(out *IPV4PrefixList) {
	{
		in := &in
		*out = make(IPV4PrefixList, len(*in))
		copy(*out, *in)
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPV4PrefixList.
func (in IPV4PrefixList) DeepCopy() IPV4PrefixList {
	if in == nil {
		return nil
	}
	out := new(IPV4PrefixList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDAPUserDNMapping) DeepCopyInto(out *LDAPUserDNMapping) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDAPUserDNMapping.
func (in *LDAPUserDNMapping) DeepCopy() *LDAPUserDNMapping {
	if in == nil {
		return nil
	}
	out := new(LDAPUserDNMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in MemberStatusList) DeepCopyInto(out *MemberStatusList) {
	{
		in := &in
		*out = make(MemberStatusList, len(*in))
		copy(*out, *in)
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemberStatusList.
func (in MemberStatusList) DeepCopy() MemberStatusList {
	if in == nil {
		return nil
	}
	out := new(MemberStatusList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MembersStatus) DeepCopyInto(out *MembersStatus) {
	*out = *in
	if in.Ready != nil {
		in, out := &in.Ready, &out.Ready
		*out = make(MemberStatusList, len(*in))
		copy(*out, *in)
	}
	if in.Unready != nil {
		in, out := &in.Unready, &out.Unready
		*out = make(MemberStatusList, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MembersStatus.
func (in *MembersStatus) DeepCopy() *MembersStatus {
	if in == nil {
		return nil
	}
	out := new(MembersStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectMeta) DeepCopyInto(out *ObjectMeta) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectMeta.
func (in *ObjectMeta) DeepCopy() *ObjectMeta {
	if in == nil {
		return nil
	}
	out := new(ObjectMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBAC) DeepCopyInto(out *RBAC) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBAC.
func (in *RBAC) DeepCopy() *RBAC {
	if in == nil {
		return nil
	}
	out := new(RBAC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteCluster) DeepCopyInto(out *RemoteCluster) {
	*out = *in
	if in.AuthenticationSecret != nil {
		in, out := &in.AuthenticationSecret, &out.AuthenticationSecret
		*out = new(string)
		**out = **in
	}
	in.Replications.DeepCopyInto(&out.Replications)
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(RemoteClusterTLS)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteCluster.
func (in *RemoteCluster) DeepCopy() *RemoteCluster {
	if in == nil {
		return nil
	}
	out := new(RemoteCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteClusterTLS) DeepCopyInto(out *RemoteClusterTLS) {
	*out = *in
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteClusterTLS.
func (in *RemoteClusterTLS) DeepCopy() *RemoteClusterTLS {
	if in == nil {
		return nil
	}
	out := new(RemoteClusterTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Replications) DeepCopyInto(out *Replications) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Replications.
func (in *Replications) DeepCopy() *Replications {
	if in == nil {
		return nil
	}
	out := new(Replications)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Role) DeepCopyInto(out *Role) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Role.
func (in *Role) DeepCopy() *Role {
	if in == nil {
		return nil
	}
	out := new(Role)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerConfig) DeepCopyInto(out *ServerConfig) {
	*out = *in
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make(ServiceList, len(*in))
		copy(*out, *in)
	}
	if in.ServerGroups != nil {
		in, out := &in.ServerGroups, &out.ServerGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Pod != nil {
		in, out := &in.Pod, &out.Pod
		*out = new(corev1.PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = new(VolumeMounts)
		(*in).DeepCopyInto(*out)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]corev1.EnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerConfig.
func (in *ServerConfig) DeepCopy() *ServerConfig {
	if in == nil {
		return nil
	}
	out := new(ServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ServiceList) DeepCopyInto(out *ServiceList) {
	{
		in := &in
		*out = make(ServiceList, len(*in))
		copy(*out, *in)
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceList.
func (in ServiceList) DeepCopy() ServiceList {
	if in == nil {
		return nil
	}
	out := new(ServiceList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceTemplateSpec) DeepCopyInto(out *ServiceTemplateSpec) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(corev1.ServiceSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceTemplateSpec.
func (in *ServiceTemplateSpec) DeepCopy() *ServiceTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticTLS) DeepCopyInto(out *StaticTLS) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticTLS.
func (in *StaticTLS) DeepCopy() *StaticTLS {
	if in == nil {
		return nil
	}
	out := new(StaticTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StrOrInt) DeepCopyInto(out *StrOrInt) {
	*out = *in
	if in.Str != nil {
		in, out := &in.Str, &out.Str
		*out = new(string)
		**out = **in
	}
	if in.Int != nil {
		in, out := &in.Int, &out.Int
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StrOrInt.
func (in *StrOrInt) DeepCopy() *StrOrInt {
	if in == nil {
		return nil
	}
	out := new(StrOrInt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSPolicy) DeepCopyInto(out *TLSPolicy) {
	*out = *in
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = new(StaticTLS)
		**out = **in
	}
	if in.ClientCertificatePolicy != nil {
		in, out := &in.ClientCertificatePolicy, &out.ClientCertificatePolicy
		*out = new(ClientCertificatePolicy)
		**out = **in
	}
	if in.ClientCertificatePaths != nil {
		in, out := &in.ClientCertificatePaths, &out.ClientCertificatePaths
		*out = make([]ClientCertificatePath, len(*in))
		copy(*out, *in)
	}
	if in.NodeToNodeEncryption != nil {
		in, out := &in.NodeToNodeEncryption, &out.NodeToNodeEncryption
		*out = new(NodeToNodeEncryptionType)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSPolicy.
func (in *TLSPolicy) DeepCopy() *TLSPolicy {
	if in == nil {
		return nil
	}
	out := new(TLSPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeWindow) DeepCopyInto(out *TimeWindow) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeWindow.
func (in *TimeWindow) DeepCopy() *TimeWindow {
	if in == nil {
		return nil
	}
	out := new(TimeWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeStatus) DeepCopyInto(out *UpgradeStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeStatus.
func (in *UpgradeStatus) DeepCopy() *UpgradeStatus {
	if in == nil {
		return nil
	}
	out := new(UpgradeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViewFragmentationThreshold) DeepCopyInto(out *ViewFragmentationThreshold) {
	*out = *in
	if in.Percent != nil {
		in, out := &in.Percent, &out.Percent
		*out = new(int)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		x := (*in).DeepCopy()
		*out = &x
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViewFragmentationThreshold.
func (in *ViewFragmentationThreshold) DeepCopy() *ViewFragmentationThreshold {
	if in == nil {
		return nil
	}
	out := new(ViewFragmentationThreshold)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeMounts) DeepCopyInto(out *VolumeMounts) {
	*out = *in
	if in.AnalyticsClaims != nil {
		in, out := &in.AnalyticsClaims, &out.AnalyticsClaims
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeMounts.
func (in *VolumeMounts) DeepCopy() *VolumeMounts {
	if in == nil {
		return nil
	}
	out := new(VolumeMounts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XDCR) DeepCopyInto(out *XDCR) {
	*out = *in
	if in.RemoteClusters != nil {
		in, out := &in.RemoteClusters, &out.RemoteClusters
		*out = make([]RemoteCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XDCR.
func (in *XDCR) DeepCopy() *XDCR {
	if in == nil {
		return nil
	}
	out := new(XDCR)
	in.DeepCopyInto(out)
	return out
}
