= Development Quick Start Guide

In order to start working with the Couchbase Operator you first need to install Kubernetes. The easiest way to do so if you do not already have a Kubernetes cluster is with MiniKube. MiniKube handles deploying a single node Kubernetes cluster by using VirtualBox.  To install minikube follow https://kubernetes.io/docs/tasks/tools/install-minikube/[the official instructions] for various operating systems.

NOTE: The default version of Kubernetes installed is hard coded in Minikube.  You can always use the `--kubernetes-version` flag to set the version you require.  At the time of writing we support 1.9.0+ onwards, but the latest version is recommended given the fast paced nature of things.

Once MiniKube is installed you can run the command below to start MiniKube.

[source,bash]
----
minikube start --cpus 4 --memory 8192
----

NOTE: Although not needed, we recommend 4 VCPUs and 8 GiB of RAM.  When running acceptance tests it's not uncommon to see up to 8 containers running and Server does use a lot of processing power to rebalance.

== Running on MiniKube

To run this operator on minikube you first need to build a container image which can be deployed into the Kubernetes environment. Normally you would need to push your container image to a container registry (e.g. DockerHub) and then pull it into Kubernetes, but since you are using MiniKube you can build the image using the same container host as the Minikube VM. That way the images are automatically present. To do this, make sure you are using the Minikube Docker daemon:

[source,bash]
----
eval $(minikube docker-env)
----

Later when you no longer want to use the Docker host in the MiniKube VM you can undo this change by running the command below.

[source,bash]
----
eval $(minikube docker-env -u)
----

== Build Prerequsites

You will need the following from your favorite package manager:

* go (1.10.0+)
* dep (0.5.0+)
* git
* git-review
* make
* docker

=== Preparing the Environment

First you will need to configure your environment to allow Go to compile the code.  This involves creating the correct directory lay out and environment variables.

[source,bash]
----
mkdir -p ${HOME}/go/src/github.com/couchbase
cd ~/go/src/github.com/couchbase
git clone https://github.com/couchbase/couchbase-operator
cd couchbase-operator
export GOPATH=${HOME}/go
----

=== Preparing to Submit Code

To initialize Gerrit integration (necessary evil) run the following once per new repository:

[source,bash]
----
git review -s
----

Your work flow is entirely up to you however we recommend:

* Before doing anything create an issue in Jira so we have an ID for simple tracking e.g. K8S-836
* Create a feature branch `git checkout -b k8s_836_my_change master`
* Do your work and test it
* Commit the code with a message in the form
+
--
[source]
----
K8S-836: What My Change Does

A detailed description of WHAT you are changing and WHY.  The width of
lines should be kept to below 80 characters as Gerrit won't display it
very nicely otherwise.  Some clever editors will automatically do word
wrap for you e.g. vim.
----
--
* Submit your change to Gerrit `git review`
* To update your patch set do your changes and amend `git commit --amend` then review with `git review` preserving the `Change-ID` which was automatically added by the prior commit.

== Building the Operator

Run make command to build the container image.

[source,bash]
----
make container
----

You should see something similar to the following with the `docker images` command.  The make file will automatically tag the image with something sane.

[source,bash]
----
REPOSITORY                                            TAG                 IMAGE ID            CREATED             SIZE
couchbase/couchbase-operator                          v1                  859ad4bb3d38        2 weeks ago         45.7MB
alpine                                                3.6                 da579b235e92        2 months ago        4.03MB
k8s.gcr.io/kube-proxy-amd64                           v1.10.0             bfc21aadc7d3        5 months ago        97MB
k8s.gcr.io/kube-controller-manager-amd64              v1.10.0             ad86dbed1555        5 months ago        148MB
k8s.gcr.io/kube-apiserver-amd64                       v1.10.0             af20925d51a3        5 months ago        225MB
k8s.gcr.io/kube-scheduler-amd64                       v1.10.0             704ba848e69a        5 months ago        50.4MB
k8s.gcr.io/etcd-amd64                                 3.1.12              52920ad46f5b        6 months ago        193MB
k8s.gcr.io/kube-addon-manager                         v8.6                9c16409588eb        6 months ago        78.4MB
k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64                1.14.8              c2ce1ffb51ed        8 months ago        41MB
k8s.gcr.io/k8s-dns-sidecar-amd64                      1.14.8              6f7f2dc7fab5        8 months ago        42.2MB
k8s.gcr.io/k8s-dns-kube-dns-amd64                     1.14.8              80cc5ea4b547        8 months ago        50.5MB
k8s.gcr.io/pause-amd64                                3.1                 da86e6ba6ca1        9 months ago        742kB
k8s.gcr.io/kubernetes-dashboard-amd64                 v1.8.1              e94d2f21bc0c        9 months ago        121MB
gcr.io/k8s-minikube/storage-provisioner               v1.8.1              4689081edb10        10 months ago       80.8MB
busybox                                               1.27                6ad733544a63        10 months ago       1.13MB
----

NOTE: Make sure you tag your container image with something other than '`latest`' and use that tag while you pull the image. Otherwise, if you do not specify version of your image, it will be assumed as :latest, with pull image policy of Always correspondingly, which may eventually result in ErrImagePull as you may not have any versions of your container image out there in the default container registry (usually DockerHub) yet.

== Adding Dependencies

Add a source specifying the lower bound of supported version.  Go mandates backwards compatibility for later versions within the same major.

[source,bash]
----
dep ensure -add gihub.com/organization/repo@v1.0.0
----

See the `dep` documentation for full instructions.

== Updating Dependencies

Update a source specifying the new lower bound of supported version.

[source,bash]
----
dep ensure -update gihub.com/organization/repo@v1.1.0
----

This command will create a new `Gopkg.lock` and then checkout code into the `vendor` directory.

See the `dep` documentation for full instructions.

== Next Steps

Please consult the user documentation for instructions on how to deploy the Operator and a Couchbase cluster in Kubernetes, view cluster status and logs etc.

IMPORTANT: The main documentation refers to .yaml paths which are distributed in the main package.  Typically in development we will use the examples in the `examples` directory of the Operator source tree.

=== Selecting Couchbase Server Version

The containers used by couchbase-operator are hosted on Docker Hub.  You can modify the version to install by editing `example/couchbase-cluster.yaml` and altering the `/spec/version` value.  Valid container version tags are available on the https://hub.docker.com/r/couchbase/server/tags/[Couchbase Server Docker Hub].
