= Developing:

In order to start working with the Couchbase Operator you first need to install
Kubernetes. The easiest way to do so if you do not already have a Kubernetes
cluster is with MiniKube. MiniKube handles deploying a single node Kubernetes
cluster by using VirtualBox. Setup and installation varies based on OS, but if
you're using Mac OS X the easiest way to install MiniKube is with Homebrew. Once
MiniKube is installed you can run the command below to start MiniKube.

 $ minikube start

Once you have MiniKube running `cd` into the couchbase-operator root directory
and run the following command to pull in the couchbase-operator dependencies.

 $ glide install --strip-vendor

== Running on MiniKube:

To run this operator on minikube you first need to build a docker image which
can be deployed into the Kubernetes environment. Normally you would need to push
your docker image to a Docker Repository and then pull it into Kubernetes, but
since you are using MiniKube you can build the image using the same Docker host
as the Minikube VM. That way the images are automatically present. To do this,
make sure you are using the Minikube Docker daemon:

 $ eval $(minikube docker-env)

NOTE: Later when you no longer want to use the Docker host in the MiniKube VM
you can undo this change by running the command below.

 $ eval $(minikube docker-env -u)

== Configuring MiniKube:

NOTE: If you are not using MiniKube you can skip this step.

Building the code requires mounting your development directory inside a docker
container. This task is automated, but if your development directory is not
located inside your home directory then you may need to configure MiniKube's
docker to recognize your development directory as a shared folder.

If you need to mount your development directory then you will need to share the
root directory of your $GOPATH (ie../opt). This allows containers being started
within the VM to access your dev environment when generating helper code used to
build the operator.

Make sure minikube is stopped.

 $ minikube stop

Add the /opt directory as a shared folder to the MiniKube VM within VirtualBox.
	Settings -> Shared Folders -> (click '+' to add folder)
Set the 'Folder Path' to '/opt' and check the 'Auto-Mount' box.

Start minikube.

 $ minikube start

== Building the operator:

Run make command to build the docker image.

 $ make container

NOTE: Make sure you tag your Docker image with something other than '`latest`' and
use that tag while you pull the image. Otherwise, if you do not specify version
of your image, it will be assumed as :latest, with pull image policy of Always
correspondingly, which may eventually result in ErrImagePull as you may not have
any versions of your Docker image out there in the default docker registry
(usually DockerHub) yet.

== Creating a Couchbase Cluster

You should now have a Kubernetes cluster setup and a Docker image installed into
your Kubernetes environment that contains the Couchbase Operator binary. The
next step is to start the Couchbase Operator in your Kubernetes cluster so that
Kubernetes natively knows about and can handle CouchbaseCluster objects. This
can be done by running the following.

 $ kubectl create -f example/deployment.yaml

Before we create the Couchbase cluster we must install a secret into Kubernetes
which will be used to create our Administrator user and password.

 $ kubectl create -f example/secret.yaml

Now you can create Couchbase clusters by specifying configurations for the
CouchbaseCluster kind. We provide an example Couchbase cluster that you can
load into Kubernetes by running the command below.

 $ kubectl create -f example/couchbase-cluster.yaml

== Monitoring the Couchbase Cluster

Most of this should be fairly trivial if you are familiar with Kubernetes.
To view the pods that are on the system user the following:

 $ kubectl get pods -o wide

You should see the couchbase-operator pod and a number of Couchbase Server
pods as defined in your cluster configuration.  To view the state of your
cluser you can use the following:

 $ kubectl get couchbasecluster -o json

Finally if the previous command isn't sufficient to diagnose problems your
next port of call should be the logs from the operator echoed to standard
out.  With the full pod name you can interrogate the logs with something
similar to the following, substituting in your operator pod name.

 $ kubectl logs couchbase-operator-789c895556-87gq2

== Configuring the Couchbase Cluster

This section documents various tweaks to the example code which may be
required to support a specific customer or to enable development of a
specific feature.

=== Selecting Verions

The containers used by couchbase-operator are hosted on Docker Hub.  You
can modify the version to install by editing `example/couchbase-cluster.yaml`
and altering the `spec['version']` value.  Valid container version tags are
available at the following location:

https://hub.docker.com/r/couchbase/server/tags/[Couchbase Server Docker Hub]
