pipeline {
  agent {
    label 'docker'
  }

  environment {
    GOVERSION = '1.17.1'
    NODEVERSION = '14.15.4'
    PATH = "${env.WORKSPACE}/go/bin:${env.WORKSPACE}/node-v${env.NODEVERSION}-linux-x64/bin:${PATH}"
  }

  stages {
    stage('Go Install') {
      steps {
        sh 'wget -q -O- https://dl.google.com/go/go${GOVERSION}.linux-amd64.tar.gz | tar xz'
      }
    }
    stage('Node.js Install') {
      steps {
        sh 'wget -q -O- https://nodejs.org/dist/v${NODEVERSION}/node-v${NODEVERSION}-linux-x64.tar.xz | tar xJ'
      }
    }
    stage('Post Checkout') {
      steps {
        sh 'make touch-generated'
      }
    }
    stage('Go Lint') {
      steps {
        sh 'make lint'
      }
    }
    stage('Python Lint') {
      steps {
        sh 'python3 -m venv venv'
        sh '. venv/bin/activate && pip3 install -r scripts/requirements.txt'
        sh '. venv/bin/activate && make lint-python'
      }
    }
    // This should build only the stand alone binaries that are required by 
    // packaged downloads, and for all target platforms (don't bother with
    // architectures... yet)
    stage('Build Binaries') {
      steps {
        sh 'make cao clean'
        sh "make cao clean -e BUILDFLAGS='-trimpath -tags redhat'"
      }
    }
    // Build all containers that will be pushed to docker hub or RHCC.
    stage('Build Containers') {
      matrix {
        axes {
          axis {
            name 'dockerfile'
            values 'Dockerfile', 'Dockerfile.rhel', 'Dockerfile.admission', 'Dockerfile.admission-rhel', 'Dockerfile.qa', 'Dockerfile.qa-rhel'
          }
        }
        stages {
          stage('Build Container') {
            steps {
              sh 'DOCKER_BUILDKIT=1 docker build -f ${dockerfile} .'
            }
          }
        }
      }
    }
    stage('Unit Test') {
      steps {
        sh 'make test-unit'
      }
    }
    stage('Documentation') {
      steps {
        sh 'make docs-lint'
      }
    }
  }

  post {
    always {
      cleanWs()
    }
  }
}
