pipeline {
  agent {
    label 'ubuntu-1604 && master'
  }

  environment {
    GOVERSION = '1.13.3'
    GOROOT = "${env.WORKSPACE}/go"
    PATH = "${env.WORKSPACE}/go/bin:${PATH}"
  }

  stages {
    stage('Go Install') {
      steps {
        sh "wget -q -O- https://dl.google.com/go/go${env.GOVERSION}.linux-amd64.tar.gz | tar xz"
      }
    }
    stage('Post Checkout') {
      steps {
        sh 'make touch-generated'
      }
    }
    stage('Go Lint') {
      steps {
        sh 'make lint'
      }
    }
    stage('Build All') {
      steps {
        sh 'make'
      }
    }
    stage('Build Test') {
      steps {
        sh 'make build-test'
      }
    }
    stage('Unit Test') {
      steps {
        sh 'make test-unit'
      }
    }
  }

  post {
    always {
      cleanWs()
    }
  }
}
