dependencies:
  - name: couchbase-operator
    version: 0.1.2
    repository: "file://../couchbase-operator"
  - name: couchbase-cluster
    version: 0.1.2
    repository: "file://../couchbase-cluster"
