# Default values for test-resources.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""
enableServiceTest: true

# Optional test value to be added as a
# suffix to chart name for identifying
# which test is creating the resources
testID:

# rbac test roles.
# when `true`, roles are created that
# can be inherited by operator
rbac:
  create: true
  clusterRoleAccess: true
  serviceAccountName:

tls:
  # name of secret with tls info to create
  secretName:
  # importTLS provides custom certificate and key files
  importTLS: false

couchbase-operator:
  couchbaseOperator:
    image:
      repository: couchbase/couchbase-operator-internal
    imagePullPolicy: Always
    imagePullSecrets:
    - regcred
  admissionController:
    image:
      repository: couchbase/couchbase-admission-internal
    imagePullPolicy: Always

# place holder for overrides to cluster
couchbase-cluster:
  couchbaseCluster:
