---
kind: {{ printf "%sBinding" (include "test-resources.rbacRole" .) }}
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "test-resources.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "test-resources.name" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ template "test-resources.serviceaccount" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ template "test-resources.rbacRole" . }}
  name: {{ template "test-resources.fullname" . }}
