{{- if and .Values.enableServiceTest -}}
apiVersion: v1
kind: Pod
metadata:
  name: "{{ template "test-resources.fullname" . }}-service-test"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "test-resources.name" . }}
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: ct
      image: quay.io/helmpack/chart-testing
      command: ['curl']
      args:  ['--retry', '10', '--retry-delay', '5', '--retry-connrefused', '--connect-timeout', '10', 'ci-testcluster-ui:8091']
  restartPolicy: Never
{{- end }}
