{{- if and .Values.enableServiceTest -}}
apiVersion: v1
kind: Pod
metadata:
  name: {{ template "test-resources.ci-fullname" . }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "test-resources.name" . }}
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: ct
      image: quay.io/helmpack/chart-testing
      command: ["/bin/sh", "-c"]
      # INLINE SH: test admin console availability
      # Waits at least 1 minute for `cluster-ui` service
      # to publish an IP address, then attempts to get
      # console landing page as simple verification test.
      args:
      - for i in `seq 6`; do HOST=$(kubectl get svc | grep cluster-ui | awk '{print $3}');
          [ -n "$HOST" ] && break;
          echo "Waiting for admin service..." && sleep 10;
        done;
        echo $HOST;
        curl --retry 10 --retry-delay 5 --retry-connrefused --connect-timeout 10 $HOST:8091;
  restartPolicy: Never
  serviceAccountName:  {{ template "test-resources.ci-serviceaccount" . }}
{{- end }}

