---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "test-resources.serviceaccount" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "test-resources.name" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
