package config

import (
	"crypto/x509"
	"crypto/x509/pkix"
	"fmt"
	"time"

	couchbasev2 "github.com/couchbase/couchbase-operator/pkg/apis/couchbase/v2"
	util_x509 "github.com/couchbase/couchbase-operator/pkg/util/x509"

	admissionregistrationv1 "k8s.io/api/admissionregistration/v1"
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	rbacv1 "k8s.io/api/rbac/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
	"k8s.io/cli-runtime/pkg/genericclioptions"

	"github.com/spf13/cobra"
)

const (
	// AdmissionResourceName is the name used for all resources generated by the individual functions.
	AdmissionResourceName = "couchbase-operator-admission"
)

// generateAdmissionOptions defines options for creating the admission controller.
type generateAdmissionOptions struct {
	// image is the admission controller image name.
	image string

	// scope is the scope with which to generate the admission controller.
	scope scopeVar

	// imagePullSecret is the name of an image pull secret for authenticating image pulls.
	imagePullSecret imagePullSecretVar

	// namespaceSelector defines the namespace selector to apply API webhooks to when
	// using the admission controller in namespace scope.
	namespaceSelector LabelSelectorVar
}

// getGenerateAdmissionCommand creates YAML capable of creating the dynamic admission controller.
func getGenerateAdmissionCommand(flags *genericclioptions.ConfigFlags) *cobra.Command {
	o := &generateAdmissionOptions{
		scope: newScopeVar(scopeCluster),
	}

	cmd := &cobra.Command{
		Use:   "admission",
		Short: "Generates YAML for the dynamic admission controller.",
		Long: normalize(`
			Generates YAML for the dynamic admission controller.

			The DAC is designed to be deployed at the cluster scope (default).
			It monitors Couchbase resources as they are created and modified,
			accepting, or rejecting them, before they are persisted in etcd.

			Use of the DAC is encouraged as it will report any configuration
			errors that are specific to deployment of Couchbase resources that
			aren't available by default in the Kubernetes API.  For example,
			this includes validating memory quotas are satisfyable, TLS
			certificates are correctly configured, and any resources referenced
			actually exist.
		`),
		Example: normalize(`
			# Create admission controller (recommended).
			cbopcfg generate admission

			# Create admission controller scoped to a namespace.
			cbopcfg generate admission --scope namespace --namespace-selector key=value

			# Create admission controller with custom image and secure image registry.
			cbopcfg generate admission --image acme.corp/admission:1.0.0 --image-pull-secret secret-name
		`),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := o.validate(); err != nil {
				return err
			}

			resources, err := o.generate(flags)
			if err != nil {
				return err
			}

			if err := dumpResources(resources); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().Var(&o.scope, "scope", "Whether to scope the Operator to a 'namespace' or to the 'cluster'.")
	cmd.Flags().StringVar(&o.image, "image", admissionImageDefault, "Operator image to use")
	cmd.Flags().Var(&o.imagePullSecret, "image-pull-secret", "Image pull secret to allow access to the operator image")
	cmd.Flags().Var(&o.namespaceSelector, "namespace-selector", "Required namespace selector to use when scope is set to 'namespace'.  Format label=value[,label=value].")

	return cmd
}

// getCreateAdmissionCommand creates the admission controller.
func getCreateAdmissionCommand(flags *genericclioptions.ConfigFlags) *cobra.Command {
	o := &generateAdmissionOptions{
		scope: newScopeVar(scopeCluster),
	}

	cmd := &cobra.Command{
		Use:   "admission",
		Short: "Creates the dynamic admission controller.",
		Long: normalize(`
			Creates the dynamic admission controller.

                        The DAC is designed to be deployed at the cluster scope (default).
                        It monitors Couchbase resources as they are created and modified,
                        accepting, or rejecting them, before they are persisted in etcd.

                        Use of the DAC is encouraged as it will report any configuration
                        errors that are specific to deployment of Couchbase resources that
                        aren't available by default in the Kubernetes API.  For example,
                        this includes validating memory quotas are satisfyable, TLS
                        certificates are correctly configured, and any resources referenced
                        actually exist.
		`),
		Example: normalize(`
                        # Create admission controller (recommended).
                        cbopcfg create admission

                        # Create admission controller scoped to a namespace.
                        cbopcfg create admission --scope namespace --namespace-selector key=value

                        # Create admission controller with custom image and secure image registry.
                        cbopcfg create admission --image acme.corp/admission:1.0.0 --image-pull-secret secret-name
                `),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := o.validate(); err != nil {
				return err
			}

			resources, err := o.generate(flags)
			if err != nil {
				return err
			}

			if err := createResources(flags, resources); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().Var(&o.scope, "scope", "Whether to scope the Operator to a 'namespace' or to the 'cluster'.")
	cmd.Flags().StringVar(&o.image, "image", admissionImageDefault, "Operator image to use")
	cmd.Flags().Var(&o.imagePullSecret, "image-pull-secret", "Image pull secret to allow access to the operator image")
	cmd.Flags().Var(&o.namespaceSelector, "namespace-selector", "Required namespace selector to use when scope is set to 'namespace'.  Format label=value[,label=value].")

	return cmd
}

// getDeleteAdmissionCommand deletes the admission controller.
func getDeleteAdmissionCommand(flags *genericclioptions.ConfigFlags) *cobra.Command {
	o := &generateAdmissionOptions{
		scope: newScopeVar(scopeCluster),
	}

	cmd := &cobra.Command{
		Use:   "admission",
		Short: "Deletes the dynamic admission controller.",
		Long:  "Deletes the dynamic admission controller.",
		Example: normalize(`
			# Delete admission controller (recommended).
			cbopcfg delete admission

			# Delete admission controller scoped to a namespace.
			cbopcfg delete admission --scope namespace
		`),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := o.validate(); err != nil {
				return err
			}

			resources, err := o.generate(flags)
			if err != nil {
				return err
			}

			if err := deleteResources(flags, resources); err != nil {
				return err
			}

			return nil
		},
	}

	cmd.Flags().Var(&o.scope, "scope", "Whether to scope the Operator to a 'namespace' or to the 'cluster'.")

	return cmd
}

// validate performs any validation that cobra doesn't on options.
func (o *generateAdmissionOptions) validate() error {
	if o.scope.value.isNamespaceScope() && o.namespaceSelector.LabelSelector == nil {
		return fmt.Errorf("dynamic admission controller with namespace scope requires the --namespace-selector flag")
	}

	return nil
}

// generate dumps all admission controller resources to standard out.
func (o *generateAdmissionOptions) generate(flags *genericclioptions.ConfigFlags) ([]runtime.Object, error) {
	namespace, _, err := flags.ToRawKubeConfigLoader().Namespace()
	if err != nil {
		return nil, err
	}

	// Generate TLS configuration for the dynamic admission controller.
	validFrom := time.Now()
	validTo := time.Now().Add(24 * 365 * 10 * time.Hour)

	ca, err := util_x509.NewCertificateAuthority(util_x509.KeyTypeRSA, AdmissionResourceName+" CA", validFrom, validTo, util_x509.CertTypeCA)
	if err != nil {
		return nil, err
	}

	req := util_x509.KeyPairRequest{
		KeyType:   util_x509.KeyTypeRSA,
		CertType:  util_x509.CertTypeServer,
		ValidFrom: validFrom,
		ValidTo:   validTo,
		Req: &x509.CertificateRequest{
			Subject: pkix.Name{
				CommonName: AdmissionResourceName,
			},
			DNSNames: []string{
				AdmissionResourceName + "." + namespace + ".svc",
			},
		},
	}

	key, cert, err := req.Generate(ca)
	if err != nil {
		return nil, err
	}

	resources := []runtime.Object{
		GetAdmissionServiceAccount(),
		GetAdmissionRole(o.scope.value.isClusterScope()),
		GetAdmissionRoleBinding(namespace, o.scope.value.isClusterScope()),
		GetAdmissionSecret(key, cert),
		GetAdmissionDeployment(o.image, o.imagePullSecret.imagePullSecrets),
		GetAdmissionService(),
		GetAdmissionMutatingWebhook(namespace, ca.Certificate, o.scope.value.isClusterScope(), o.namespaceSelector.LabelSelector),
		GetAdmissionValidatingWebhook(namespace, ca.Certificate, o.scope.value.isClusterScope(), o.namespaceSelector.LabelSelector),
	}

	return resources, nil
}

// GetAdmissionRole return the (cluster) role to run with.
func GetAdmissionRole(cluster bool) runtime.Object {
	metadata := metav1.ObjectMeta{
		Name: AdmissionResourceName,
	}

	rules := []rbacv1.PolicyRule{
		{
			APIGroups: []string{
				couchbasev2.GroupName,
			},
			Resources: []string{
				couchbasev2.ClusterCRDResourcePlural,
				couchbasev2.BucketCRDResourcePlural,
				couchbasev2.EphemeralBucketCRDResourcePlural,
				couchbasev2.MemcachedBucketCRDResourcePlural,
				couchbasev2.ReplicationCRDResourcePlural,
				couchbasev2.UserCRDResourcePlural,
				couchbasev2.GroupCRDResourcePlural,
				couchbasev2.RoleBindingCRDResourcePlural,
				couchbasev2.BackupCRDResourcePlural,
				couchbasev2.BackupRestoreCRDResourcePlural,
				couchbasev2.AutoscalerCRDResourcePlural,
			},
			Verbs: []string{
				"list",
			},
		},
		{
			APIGroups: []string{
				"",
			},
			Resources: []string{
				"secrets",
			},
			Verbs: []string{
				"get",
			},
		},
	}

	if cluster {
		clusterRules := []rbacv1.PolicyRule{
			{
				APIGroups: []string{
					"",
				},
				Resources: []string{
					"namespaces",
				},
				Verbs: []string{
					"get",
				},
			},
			{
				APIGroups: []string{
					"storage.k8s.io",
				},
				Resources: []string{
					"storageclasses",
				},
				Verbs: []string{
					"get",
				},
			},
		}

		rules = append(rules, clusterRules...)

		return &rbacv1.ClusterRole{
			ObjectMeta: metadata,
			Rules:      rules,
		}
	}

	return &rbacv1.Role{
		ObjectMeta: metadata,
		Rules:      rules,
	}
}

// GetAdmissionServiceAccount get the service account to run as.
func GetAdmissionServiceAccount() *corev1.ServiceAccount {
	return &corev1.ServiceAccount{
		ObjectMeta: metav1.ObjectMeta{
			Name: AdmissionResourceName,
		},
	}
}

// GetAdmissionRoleBinding generates the (cluster) role binding linking the role to the service account.
func GetAdmissionRoleBinding(namespace string, cluster bool) runtime.Object {
	metadata := metav1.ObjectMeta{
		Name: AdmissionResourceName,
	}

	subjects := []rbacv1.Subject{
		{
			Kind:      "ServiceAccount",
			Name:      AdmissionResourceName,
			Namespace: namespace,
		},
	}

	if cluster {
		return &rbacv1.ClusterRoleBinding{
			ObjectMeta: metadata,
			Subjects:   subjects,
			RoleRef: rbacv1.RoleRef{
				APIGroup: "rbac.authorization.k8s.io",
				Kind:     "ClusterRole",
				Name:     AdmissionResourceName,
			},
		}
	}

	return &rbacv1.RoleBinding{
		ObjectMeta: metadata,
		Subjects:   subjects,
		RoleRef: rbacv1.RoleRef{
			APIGroup: "rbac.authorization.k8s.io",
			Kind:     "Role",
			Name:     AdmissionResourceName,
		},
	}
}

// GetAdmissionSecret generates the TLS secret providing server certificates.
func GetAdmissionSecret(key, cert []byte) *corev1.Secret {
	return &corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{
			Name: AdmissionResourceName,
		},
		Data: map[string][]byte{
			"tls-cert-file":        cert,
			"tls-private-key-file": key,
		},
	}
}

// GetAdmissionDeployment returns the canonical deployment for the admission controller.
func GetAdmissionDeployment(image string, imagePullSecrets []string, extraArgs ...string) *appsv1.Deployment {
	replicas := int32(1)
	deployment := &appsv1.Deployment{
		ObjectMeta: metav1.ObjectMeta{
			Name: AdmissionResourceName,
		},
		Spec: appsv1.DeploymentSpec{
			Replicas: &replicas,
			Selector: &metav1.LabelSelector{
				MatchLabels: map[string]string{
					"app": AdmissionResourceName,
				},
			},
			Template: corev1.PodTemplateSpec{
				ObjectMeta: metav1.ObjectMeta{
					Labels: map[string]string{
						"app": AdmissionResourceName,
					},
				},
				Spec: corev1.PodSpec{
					ServiceAccountName: AdmissionResourceName,
					Containers: []corev1.Container{
						{
							Name:  AdmissionResourceName,
							Image: image,
							Command: []string{
								"couchbase-operator-admission",
							},
							Args: append([]string{
								"--logtostderr",
								"--stderrthreshold", "0",
								"--tls-cert-file", "/var/run/secrets/couchbase.com/couchbase-operator-admission/tls-cert-file",
								"--tls-private-key-file", "/var/run/secrets/couchbase.com/couchbase-operator-admission/tls-private-key-file",
							}, extraArgs...),
							Ports: []corev1.ContainerPort{
								{
									Name:          "https",
									ContainerPort: 8443,
								},
							},
							ReadinessProbe: &corev1.Probe{
								Handler: corev1.Handler{
									HTTPGet: &corev1.HTTPGetAction{
										Path:   "/readyz",
										Port:   intstr.FromString("https"),
										Scheme: corev1.URISchemeHTTPS,
									},
								},
							},
							VolumeMounts: []corev1.VolumeMount{
								{
									Name:      AdmissionResourceName,
									MountPath: "/var/run/secrets/couchbase.com/couchbase-operator-admission",
									ReadOnly:  true,
								},
							},
						},
					},
					Volumes: []corev1.Volume{
						{
							Name: AdmissionResourceName,
							VolumeSource: corev1.VolumeSource{
								Secret: &corev1.SecretVolumeSource{
									SecretName: AdmissionResourceName,
								},
							},
						},
					},
				},
			},
		},
	}

	for _, secret := range imagePullSecrets {
		reference := corev1.LocalObjectReference{
			Name: secret,
		}

		deployment.Spec.Template.Spec.ImagePullSecrets = append(deployment.Spec.Template.Spec.ImagePullSecrets, reference)
	}

	return deployment
}

// GetAdmissionService returns a cluster service definition for the admission controller.
func GetAdmissionService() *corev1.Service {
	return &corev1.Service{
		ObjectMeta: metav1.ObjectMeta{
			Name: AdmissionResourceName,
		},
		Spec: corev1.ServiceSpec{
			Selector: map[string]string{
				"app": AdmissionResourceName,
			},
			Ports: []corev1.ServicePort{
				{
					Protocol:   corev1.ProtocolTCP,
					Port:       443,
					TargetPort: intstr.FromInt(8443),
				},
			},
		},
	}
}

// GetAdmissionMutatingWebhook creates a mutating webhook for the admission controller.
func GetAdmissionMutatingWebhook(namespace string, ca []byte, cluster bool, namespaceSelector *metav1.LabelSelector) *admissionregistrationv1.MutatingWebhookConfiguration {
	// You need a webhook per controller when running in namespaced mode.
	// IF we resued the same one each time, we'd need to aggregate the webhooks
	// and act as a client doing read/modify/write.  This is complex so instead
	// just name them deterministically (for deletion) and make many resources.
	name := AdmissionResourceName

	if !cluster {
		name = AdmissionResourceName + "-" + namespace
	}

	admissionControllerMutatePath := "/couchbaseclusters/mutate"

	failurePolicy := admissionregistrationv1.Fail
	sideEffectClass := admissionregistrationv1.SideEffectClassNone

	webhook := &admissionregistrationv1.MutatingWebhookConfiguration{
		ObjectMeta: metav1.ObjectMeta{
			Name: name,
		},
		Webhooks: []admissionregistrationv1.MutatingWebhook{
			{
				Name: AdmissionResourceName + "." + namespace + ".svc",
				Rules: []admissionregistrationv1.RuleWithOperations{
					{
						Rule: admissionregistrationv1.Rule{
							APIGroups: []string{
								couchbasev2.GroupName,
							},
							Resources: []string{
								couchbasev2.ClusterCRDResourcePlural,
								couchbasev2.BucketCRDResourcePlural,
								couchbasev2.EphemeralBucketCRDResourcePlural,
								couchbasev2.MemcachedBucketCRDResourcePlural,
								couchbasev2.ReplicationCRDResourcePlural,
								couchbasev2.UserCRDResourcePlural,
								couchbasev2.GroupCRDResourcePlural,
								couchbasev2.RoleBindingCRDResourcePlural,
								couchbasev2.BackupCRDResourcePlural,
								couchbasev2.BackupRestoreCRDResourcePlural,
								couchbasev2.AutoscalerCRDResourcePlural,
							},
							APIVersions: []string{
								"v1",
								"v2",
							},
						},
						Operations: []admissionregistrationv1.OperationType{
							admissionregistrationv1.Create,
							admissionregistrationv1.Update,
						},
					},
				},
				ClientConfig: admissionregistrationv1.WebhookClientConfig{
					Service: &admissionregistrationv1.ServiceReference{
						Namespace: namespace,
						Name:      AdmissionResourceName,
						Path:      &admissionControllerMutatePath,
					},
					CABundle: ca,
				},
				FailurePolicy: &failurePolicy,
				SideEffects:   &sideEffectClass,
				AdmissionReviewVersions: []string{
					"v1",
				},
			},
		},
	}

	// When in namespace scoped mode, the selector will be populated and must be
	// added to the webhook.
	if !cluster {
		webhook.Webhooks[0].NamespaceSelector = namespaceSelector
	}

	return webhook
}

// GetAdmissionValidatingWebhook creates a validating webhook for the admission controller.
func GetAdmissionValidatingWebhook(namespace string, ca []byte, cluster bool, namespaceSelector *metav1.LabelSelector) *admissionregistrationv1.ValidatingWebhookConfiguration {
	// You need a webhook per controller when running in namespaced mode.
	// IF we resued the same one each time, we'd need to aggregate the webhooks
	// and act as a client doing read/modify/write.  This is complex so instead
	// just name them deterministically (for deletion) and make many resources.
	name := AdmissionResourceName

	if !cluster {
		name = AdmissionResourceName + "-" + namespace
	}

	admissionControllerValidatePath := "/couchbaseclusters/validate"

	failurePolicy := admissionregistrationv1.Fail
	sideEffectClass := admissionregistrationv1.SideEffectClassNone

	webhook := &admissionregistrationv1.ValidatingWebhookConfiguration{
		ObjectMeta: metav1.ObjectMeta{
			Name: name,
		},
		Webhooks: []admissionregistrationv1.ValidatingWebhook{
			{
				Name: AdmissionResourceName + "." + namespace + ".svc",
				Rules: []admissionregistrationv1.RuleWithOperations{
					{
						Rule: admissionregistrationv1.Rule{
							APIGroups: []string{
								couchbasev2.GroupName,
							},
							Resources: []string{
								couchbasev2.ClusterCRDResourcePlural,
								couchbasev2.BucketCRDResourcePlural,
								couchbasev2.EphemeralBucketCRDResourcePlural,
								couchbasev2.MemcachedBucketCRDResourcePlural,
								couchbasev2.ReplicationCRDResourcePlural,
								couchbasev2.UserCRDResourcePlural,
								couchbasev2.GroupCRDResourcePlural,
								couchbasev2.RoleBindingCRDResourcePlural,
								couchbasev2.BackupCRDResourcePlural,
								couchbasev2.BackupRestoreCRDResourcePlural,
								couchbasev2.AutoscalerCRDResourcePlural,
							},
							APIVersions: []string{
								"v1",
								"v2",
							},
						},
						Operations: []admissionregistrationv1.OperationType{
							admissionregistrationv1.Create,
							admissionregistrationv1.Update,
						},
					},
				},
				ClientConfig: admissionregistrationv1.WebhookClientConfig{
					Service: &admissionregistrationv1.ServiceReference{
						Namespace: namespace,
						Name:      AdmissionResourceName,
						Path:      &admissionControllerValidatePath,
					},
					CABundle: ca,
				},
				FailurePolicy: &failurePolicy,
				SideEffects:   &sideEffectClass,
				AdmissionReviewVersions: []string{
					"v1",
				},
			},
		},
	}

	// When in namespace scoped mode, the selector will be populated and must be
	// added to the webhook.
	if !cluster {
		webhook.Webhooks[0].NamespaceSelector = namespaceSelector
	}

	return webhook
}
