package config

import (
	"context"
	"crypto/x509"
	"crypto/x509/pkix"
	"fmt"
	"strconv"
	"time"

	couchbasev2 "github.com/couchbase/couchbase-operator/pkg/apis/couchbase/v2"
	util_x509 "github.com/couchbase/couchbase-operator/pkg/util/x509"

	admissionregistrationv1 "k8s.io/api/admissionregistration/v1"
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	rbacv1 "k8s.io/api/rbac/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
	"k8s.io/cli-runtime/pkg/genericclioptions"
	"k8s.io/client-go/kubernetes"

	"github.com/spf13/cobra"
)

const (
	// AdmissionResourceName is the name used for all resources generated by the individual functions.
	AdmissionResourceName = "couchbase-operator-admission"

	// admissionDefaultLogLevel is what we expect people to use by default.
	admissionDefaultLogLevel = "info"

	// admissionDefaultCPURequest is the number of CPUs to schedule for.
	// On my laptop this is negligible.
	admissionDefaultCPURequest = "500m"

	// admissionDefaultCPULimit is the burst number of CPUs to kill the pod if exceeded.
	admissionDefaultCPULimit = "1"

	// admissionDefaultMemoryRequest is the amount of memory to schedule for.
	// On my laptop it uses ~25000 RSS, so more than enough.
	admissionDefaultMemoryRequest = "100Mi"

	// admissionDefaultMemoryLimit is the burst amount of memory to kill the pod if exceeded.
	admissionDefaultMemoryLimit = "200Mi"

	// admissionDefaultReplicas is the number of replicas in the deployment.
	admissionDefaultReplicas = 1

	// admissionDefaultPullPolicy is the pull policy to use when downloading the image.
	// By default images are only pulled if not already present.
	admissionDefaultPullPolicy = string(corev1.PullIfNotPresent)

	defaultExpirationTime = 10 * 365 * 24 * time.Hour
)

// generateAdmissionOptions defines options for creating the admission controller.
type generateAdmissionOptions struct {
	// image is the admission controller image name.
	image string

	// scope is the scope with which to generate the admission controller.
	scope scopeVar

	// imagePullSecret is the name of an image pull secret for authenticating image pulls.
	imagePullSecret imagePullSecretVar

	// imagePullPolicy is the pull policy to use when downloading the image.
	imagePullPolicy string

	// namespaceSelector defines the namespace selector to apply API webhooks to when
	// using the admission controller in namespace scope.
	namespaceSelector LabelSelectorVar

	// validateSecrets causes the validation of secrets and their contents.
	validateSecrets bool

	// validateStorageClasses causes the validation of storage classes.
	validateStorageClasses bool

	// logLevel allows the setting of the logging level.
	logLevel zapLogLevelVar

	// replicas is the number of replicas in the deployment.
	replicas int

	// withResources allows you to add resource requests and limits.
	withResources bool

	// cpuRequest is the number of CPUs to schedule for.
	cpuRequest quantityVar

	// cpuLimit is the burst number of CPUs to kill the pod if exceeded.
	cpuLimit quantityVar

	// memoryRequest is the amount of memory to schedule for.
	memoryRequest quantityVar

	// memoryLimit is the burst amount of memory to kill the pod if exceeded.
	memoryLimit quantityVar
}

// newGenerateAdmissionOptions returns a set of options with the defaults applied.
func newGenerateAdmissionOptions() *generateAdmissionOptions {
	return &generateAdmissionOptions{
		scope:         newScopeVar(scopeCluster),
		logLevel:      newZapLogLevelVar(admissionDefaultLogLevel),
		cpuRequest:    newQuantityVar(admissionDefaultCPURequest),
		cpuLimit:      newQuantityVar(admissionDefaultCPULimit),
		memoryRequest: newQuantityVar(admissionDefaultMemoryRequest),
		memoryLimit:   newQuantityVar(admissionDefaultMemoryLimit),
	}
}

// registerAdmissionGenerateFlags adds generic generation flags to the provided command.
func (o *generateAdmissionOptions) registerAdmissionGenerateFlags(cmd *cobra.Command) {
	cmd.Flags().Var(&o.scope, "scope", "Whether to scope the Operator to a 'namespace' or to the 'cluster'.")
	cmd.Flags().StringVar(&o.image, "image", admissionImageDefault, "Operator image to use")
	cmd.Flags().Var(&o.imagePullSecret, "image-pull-secret", "Image pull secret to allow access to the operator image")
	cmd.Flags().StringVar(&o.imagePullPolicy, "image-pull-policy", admissionDefaultPullPolicy, "Image pull policy to affect when the image is downloaded.")
	cmd.Flags().Var(&o.logLevel, "log-level", "Log level to generate logs at.  \"info\", or \"0\", prints basic operations. \"debug\", or \"1\" prints extended information.")
	cmd.Flags().Var(&o.namespaceSelector, "namespace-selector", "Required namespace selector to use when scope is set to 'namespace'.  Format label=value[,label=value].")
	cmd.Flags().BoolVar(&o.validateSecrets, "validate-secrets", true, "Validates secrets referenced by Couchbase resources, and their contents e.g. TLS configuration, for validity")
	cmd.Flags().BoolVar(&o.validateStorageClasses, "validate-storage-classes", true, "Validates storage classes referenced by Couchbase resources")

	cmd.Flags().IntVar(&o.replicas, "replicas", admissionDefaultReplicas, "The number of replicas in the deployment")
	cmd.Flags().BoolVar(&o.withResources, "with-resources", false, "Populates pod resource requests and limits")
	cmd.Flags().Var(&o.cpuRequest, "cpu-request", "CPU requested for scheduling, only valid when used with --with-resources")
	cmd.Flags().Var(&o.cpuLimit, "cpu-limit", "CPU limit for constraining, only valid when used with --with-resources")
	cmd.Flags().Var(&o.memoryRequest, "memory-request", "Memory requested for scheduling, only valid when used with --with-resources")
	cmd.Flags().Var(&o.memoryLimit, "memory-limit", "Memory limit for constraining, only valid when used with --with-resources")
}

// getGenerateAdmissionCommand creates YAML capable of creating the dynamic admission controller.
func getGenerateAdmissionCommand(command string, flags *genericclioptions.ConfigFlags) *cobra.Command {
	o := newGenerateAdmissionOptions()

	cmd := &cobra.Command{
		Use:   "admission",
		Short: "Generates YAML for the dynamic admission controller.",
		Long: normalize(`
			Generates YAML for the dynamic admission controller.

			The DAC is designed to be deployed at the cluster scope (default).
			It monitors Couchbase resources as they are created and modified,
			accepting, or rejecting them, before they are persisted in etcd.

			Use of the DAC is encouraged as it will report any configuration
			errors that are specific to deployment of Couchbase resources that
			aren't available by default in the Kubernetes API.  For example,
			this includes validating memory quotas are satisfiable, TLS
			certificates are correctly configured, and any resources referenced
			actually exist.
		`),
		Example: normalize(fmt.Sprintf(`
			# Create admission controller (recommended).
			%[1]s generate admission

			# Create admission controller scoped to a namespace.
			%[1]s generate admission --scope namespace --namespace-selector key=value

			# Create admission controller with custom image and secure image registry.
			%[1]s generate admission --image acme.corp/admission:1.0.0 --image-pull-secret secret-name

                        # Create admission controller without secret access.
                        %[1]s generate admission --validate-secrets=false

                        # Create admission controller with debug logging.
                        %[1]s generate admission --log-level debug
		`, command)),
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := o.validate(GenerateCmd); err != nil {
				return err
			}

			resources, err := o.generate(flags)
			if err != nil {
				return err
			}

			return dumpResources(resources)
		},
	}

	o.registerAdmissionGenerateFlags(cmd)

	return cmd
}

// getCreateAdmissionCommand creates the admission controller.
func getCreateAdmissionCommand(command string, flags *genericclioptions.ConfigFlags) *cobra.Command {
	o := newGenerateAdmissionOptions()

	cmd := &cobra.Command{
		Use:   "admission",
		Short: "Creates the dynamic admission controller.",
		Long: normalize(`
			Creates the dynamic admission controller.

                        The DAC is designed to be deployed at the cluster scope (default).
                        It monitors Couchbase resources as they are created and modified,
                        accepting, or rejecting them, before they are persisted in etcd.

                        Use of the DAC is encouraged as it will report any configuration
                        errors that are specific to deployment of Couchbase resources that
                        aren't available by default in the Kubernetes API.  For example,
                        this includes validating memory quotas are satisfiable, TLS
                        certificates are correctly configured, and any resources referenced
                        actually exist.
		`),
		Example: normalize(fmt.Sprintf(`
                        # Create admission controller (recommended).
                        %[1]s create admission

                        # Create admission controller scoped to a namespace.
                        %[1]s create admission --scope namespace --namespace-selector key=value

                        # Create admission controller with custom image and secure image registry.
                        %[1]s create admission --image acme.corp/admission:1.0.0 --image-pull-secret secret-name

			# Create admission controller without secret access.
			%[1]s create admission --validate-secrets=false

                        # Create admission controller with debug logging.
                        %[1]s create admission --log-level debug
                `, command)),
		RunE: func(cmd *cobra.Command, args []string) error {
			if command != caoBinaryName {
				genDeprecatedWarning("https://docs.couchbase.com/operator/current/tools/cao.html#cao-create-admission-flags")
			}

			if err := o.validate(CreateCmd); err != nil {
				return err
			}

			resources, err := o.generate(flags)
			if err != nil {
				return err
			}

			return createResources(flags, resources)
		},
	}

	o.registerAdmissionGenerateFlags(cmd)

	return cmd
}

// getDeleteAdmissionCommand deletes the admission controller.
func getDeleteAdmissionCommand(command string, flags *genericclioptions.ConfigFlags) *cobra.Command {
	o := newGenerateAdmissionOptions()

	cmd := &cobra.Command{
		Use:   "admission",
		Short: "Deletes the dynamic admission controller.",
		Long:  "Deletes the dynamic admission controller.",
		Example: normalize(fmt.Sprintf(`
			# Delete admission controller (recommended).
			%[1]s delete admission

			# Delete admission controller scoped to a namespace.
			%[1]s delete admission --scope namespace
		`, command)),
		RunE: func(cmd *cobra.Command, args []string) error {
			if command != caoBinaryName {
				genDeprecatedWarning("https://docs.couchbase.com/operator/current/tools/cao.html#cao-delete-admission-flags")
			}

			if err := o.validate(DeleteCmd); err != nil {
				return err
			}

			resources, err := o.generate(flags)
			if err != nil {
				return err
			}

			return deleteResources(flags, resources)
		},
	}

	cmd.Flags().Var(&o.scope, "scope", "Whether to scope the Operator to a 'namespace' or to the 'cluster'.")

	return cmd
}

func getUpdateAdmissionCommand(command string, flags *genericclioptions.ConfigFlags) *cobra.Command {
	o := newGenerateAdmissionOptions()

	cmd := &cobra.Command{
		Use:   "webhook",
		Short: "refreshes the self signed certificate used by the validating webhook.",
		Long:  "refreshes the self signed certificate used by the validating webhook.",
		RunE: func(cmd *cobra.Command, args []string) error {
			if command != caoBinaryName {
				genDeprecatedWarning("https://docs.couchbase.com/operator/current/tools/cao.html#cao-delete-admission-flags")
			}

			if err := o.validate(UpdateCmd); err != nil {
				return err
			}

			return refreshWebhook(flags, o)
		},
	}

	cmd.Flags().Var(&o.scope, "scope", "Whether to scope the Operator to a 'namespace' or to the 'cluster'.")

	return cmd
}

// validate performs any validation that cobra doesn't on options.
func (o *generateAdmissionOptions) validate(command string) error {
	if o.scope.value.isNamespaceScope() && o.namespaceSelector.LabelSelector == nil {
		if command != UpdateCmd && command != DeleteCmd {
			return fmt.Errorf("dynamic admission controller with namespace scope requires the --namespace-selector flag")
		}
	}

	// When namespaced, we cannot access namespaces or storage classes
	// (or any cluster scoped resource for that matter) so force these
	// to false to cause the role to never be added, and the DAC not to
	// bother checking them.
	if o.scope.value.isNamespaceScope() {
		o.validateStorageClasses = false
	}

	return nil
}

type AdmissionCerts struct {
	key  []byte
	cert []byte
	ca   *util_x509.CertificateAuthority
}

func GenerateAdmissionCerts(namespace string, duration time.Duration) (*AdmissionCerts, error) {
	// Generate TLS configuration for the dynamic admission controller.
	validFrom := time.Now()
	validTo := time.Now().Add(duration)

	ca, err := util_x509.NewCertificateAuthority(util_x509.KeyTypeRSA, AdmissionResourceName+" CA", validFrom, validTo, util_x509.CertTypeCA)
	if err != nil {
		return nil, err
	}

	req := util_x509.KeyPairRequest{
		KeyType:   util_x509.KeyTypeRSA,
		CertType:  util_x509.CertTypeServer,
		ValidFrom: validFrom,
		ValidTo:   validTo,
		Req: &x509.CertificateRequest{
			Subject: pkix.Name{
				CommonName: AdmissionResourceName,
			},
			DNSNames: []string{
				AdmissionResourceName + "." + namespace + ".svc",
			},
		},
	}

	key, cert, err := req.Generate(ca)
	if err != nil {
		return nil, err
	}

	return &AdmissionCerts{key: key, cert: cert, ca: ca}, nil
}

// generate dumps all admission controller resources to standard out.
func (o *generateAdmissionOptions) generate(flags *genericclioptions.ConfigFlags) ([]runtime.Object, error) {
	namespace, _, err := flags.ToRawKubeConfigLoader().Namespace()
	if err != nil {
		return nil, err
	}

	bundle, err := GenerateAdmissionCerts(namespace, defaultExpirationTime)
	if err != nil {
		return nil, err
	}

	resources := []runtime.Object{
		o.getAdmissionServiceAccount(),
		o.getAdmissionRole(),
		o.getAdmissionRoleBinding(namespace),
		o.getAdmissionSecret(bundle.key, bundle.cert),
		o.getAdmissionDeployment(),
		o.getAdmissionService(),
		o.getAdmissionValidatingWebhook(namespace, bundle.ca.Certificate),
	}

	return resources, nil
}

// getAdmissionRole return the (cluster) role to run with.
func (o *generateAdmissionOptions) getAdmissionRole() runtime.Object {
	metadata := metav1.ObjectMeta{
		Name: AdmissionResourceName,
	}

	rules := []rbacv1.PolicyRule{
		{
			APIGroups: []string{
				couchbasev2.GroupName,
			},
			Resources: []string{
				couchbasev2.ClusterCRDResourcePlural,
				couchbasev2.BucketCRDResourcePlural,
				couchbasev2.EphemeralBucketCRDResourcePlural,
				couchbasev2.MemcachedBucketCRDResourcePlural,
				couchbasev2.ReplicationCRDResourcePlural,
				couchbasev2.UserCRDResourcePlural,
				couchbasev2.GroupCRDResourcePlural,
				couchbasev2.RoleBindingCRDResourcePlural,
				couchbasev2.BackupCRDResourcePlural,
				couchbasev2.BackupRestoreCRDResourcePlural,
				couchbasev2.AutoscalerCRDResourcePlural,
				couchbasev2.CollectionCRDResourcePlural,
				couchbasev2.CollectionGroupCRDResourcePlural,
				couchbasev2.ScopeCRDResourcePlural,
				couchbasev2.ScopeGroupCRDResourcePlural,
				couchbasev2.MigrationReplicationCRDResourcePlural,
				couchbasev2.EncryptionKeyCRDResourcePlural,
			},
			Verbs: []string{
				"get",
				"list",
			},
		},
	}

	if o.validateSecrets {
		rules = append(rules, rbacv1.PolicyRule{
			APIGroups: []string{
				"",
			},
			Resources: []string{
				"secrets",
			},
			Verbs: []string{
				"get",
			},
		})
	}

	if o.scope.value.isClusterScope() {
		if o.validateStorageClasses {
			rules = append(rules, rbacv1.PolicyRule{
				APIGroups: []string{
					"storage.k8s.io",
				},
				Resources: []string{
					"storageclasses",
				},
				Verbs: []string{
					"get",
					"list", // used to check that a default storageClass exists in the cluster
				},
			})
		}

		return &rbacv1.ClusterRole{
			ObjectMeta: metadata,
			Rules:      rules,
		}
	}

	return &rbacv1.Role{
		ObjectMeta: metadata,
		Rules:      rules,
	}
}

// getAdmissionServiceAccount get the service account to run as.
func (o *generateAdmissionOptions) getAdmissionServiceAccount() *corev1.ServiceAccount {
	return &corev1.ServiceAccount{
		ObjectMeta: metav1.ObjectMeta{
			Name: AdmissionResourceName,
		},
	}
}

// getAdmissionRoleBinding generates the (cluster) role binding linking the role to the service account.
func (o *generateAdmissionOptions) getAdmissionRoleBinding(namespace string) runtime.Object {
	metadata := metav1.ObjectMeta{
		Name: AdmissionResourceName,
	}

	subjects := []rbacv1.Subject{
		{
			Kind:      "ServiceAccount",
			Name:      AdmissionResourceName,
			Namespace: namespace,
		},
	}

	if o.scope.value.isClusterScope() {
		return &rbacv1.ClusterRoleBinding{
			ObjectMeta: metadata,
			Subjects:   subjects,
			RoleRef: rbacv1.RoleRef{
				APIGroup: "rbac.authorization.k8s.io",
				Kind:     "ClusterRole",
				Name:     AdmissionResourceName,
			},
		}
	}

	return &rbacv1.RoleBinding{
		ObjectMeta: metadata,
		Subjects:   subjects,
		RoleRef: rbacv1.RoleRef{
			APIGroup: "rbac.authorization.k8s.io",
			Kind:     "Role",
			Name:     AdmissionResourceName,
		},
	}
}

// getAdmissionSecret generates the TLS secret providing server certificates.
func (o *generateAdmissionOptions) getAdmissionSecret(key, cert []byte) *corev1.Secret {
	return &corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{
			Name: AdmissionResourceName,
		},
		Data: map[string][]byte{
			"tls.crt": cert,
			"tls.key": key,
		},
	}
}

// getAdmissionDeployment returns the canonical deployment for the admission controller.
func (o *generateAdmissionOptions) getAdmissionDeployment() *appsv1.Deployment {
	replicas := int32(o.replicas)

	nonRoot := true

	deployment := &appsv1.Deployment{
		ObjectMeta: metav1.ObjectMeta{
			Name: AdmissionResourceName,
		},
		Spec: appsv1.DeploymentSpec{
			Replicas: &replicas,
			Selector: &metav1.LabelSelector{
				MatchLabels: map[string]string{
					"app.kubernetes.io/name":     AdmissionResourceName,
					"app.kubernetes.io/instance": "couchbase-admission",
				},
			},
			Template: corev1.PodTemplateSpec{
				ObjectMeta: metav1.ObjectMeta{
					Labels: map[string]string{
						"app.kubernetes.io/name":      AdmissionResourceName,
						"app.kubernetes.io/instance":  "couchbase-admission",
						"app.kubernetes.io/component": "admission-webhook",
						"app.kubernetes.io/part-of":   "couchbase",
					},
				},
				Spec: corev1.PodSpec{
					ServiceAccountName: AdmissionResourceName,
					SecurityContext: &corev1.PodSecurityContext{
						RunAsNonRoot: &nonRoot,
						SeccompProfile: &corev1.SeccompProfile{
							Type: corev1.SeccompProfileTypeRuntimeDefault,
						},
					},
					Containers: []corev1.Container{
						{
							Name:            AdmissionResourceName,
							Image:           o.image,
							ImagePullPolicy: corev1.PullPolicy(o.imagePullPolicy),
							SecurityContext: &corev1.SecurityContext{
								AllowPrivilegeEscalation: func() *bool { b := false; return &b }(),
								ReadOnlyRootFilesystem:   func() *bool { b := true; return &b }(),
								Capabilities: &corev1.Capabilities{
									Drop: []corev1.Capability{"ALL"},
								},
							},
							Command: []string{
								"couchbase-admission-controller",
							},
							Args: []string{
								"-zap-log-level=" + o.logLevel.value,
								"-tls-cert-file=" + "/var/run/secrets/couchbase.com/couchbase-operator-admission/tls.crt",
								"-tls-private-key-file=" + "/var/run/secrets/couchbase.com/couchbase-operator-admission/tls.key",
								"-validate-secrets=" + strconv.FormatBool(o.validateSecrets),
								"-validate-storage-classes=" + strconv.FormatBool(o.validateStorageClasses),
							},
							Ports: []corev1.ContainerPort{
								{
									Name:          "https",
									ContainerPort: 8443,
								},
							},
							ReadinessProbe: &corev1.Probe{
								ProbeHandler: corev1.ProbeHandler{
									HTTPGet: &corev1.HTTPGetAction{
										Path:   "/readyz",
										Port:   intstr.FromString("https"),
										Scheme: corev1.URISchemeHTTPS,
									},
								},
							},
							LivenessProbe: &corev1.Probe{
								ProbeHandler: corev1.ProbeHandler{
									HTTPGet: &corev1.HTTPGetAction{
										Path:   "/readyz",
										Port:   intstr.FromString("https"),
										Scheme: corev1.URISchemeHTTPS,
									},
								},
								InitialDelaySeconds: 30,
								TimeoutSeconds:      5,
								PeriodSeconds:       30,
								FailureThreshold:    3,
							},
							VolumeMounts: []corev1.VolumeMount{
								{
									Name:      AdmissionResourceName,
									MountPath: "/var/run/secrets/couchbase.com/couchbase-operator-admission",
									ReadOnly:  true,
								},
							},
						},
					},
					Volumes: []corev1.Volume{
						{
							Name: AdmissionResourceName,
							VolumeSource: corev1.VolumeSource{
								Secret: &corev1.SecretVolumeSource{
									SecretName: AdmissionResourceName,
								},
							},
						},
					},
				},
			},
		},
	}

	if o.withResources {
		deployment.Spec.Template.Spec.Containers[0].Resources = corev1.ResourceRequirements{
			Requests: corev1.ResourceList{
				corev1.ResourceCPU:    o.cpuRequest.value,
				corev1.ResourceMemory: o.memoryRequest.value,
			},
			Limits: corev1.ResourceList{
				corev1.ResourceCPU:    o.cpuLimit.value,
				corev1.ResourceMemory: o.memoryLimit.value,
			},
		}
	}

	for _, secret := range o.imagePullSecret.imagePullSecrets {
		reference := corev1.LocalObjectReference{
			Name: secret,
		}

		deployment.Spec.Template.Spec.ImagePullSecrets = append(deployment.Spec.Template.Spec.ImagePullSecrets, reference)
	}

	return deployment
}

// getAdmissionService returns a cluster service definition for the admission controller.
func (o *generateAdmissionOptions) getAdmissionService() *corev1.Service {
	return &corev1.Service{
		ObjectMeta: metav1.ObjectMeta{
			Name: AdmissionResourceName,
			Labels: map[string]string{
				"app.kubernetes.io/name":      AdmissionResourceName,
				"app.kubernetes.io/instance":  "couchbase-admission",
				"app.kubernetes.io/component": "admission-webhook",
				"app.kubernetes.io/part-of":   "couchbase",
			},
		},
		Spec: corev1.ServiceSpec{
			Selector: map[string]string{
				"app.kubernetes.io/name":     AdmissionResourceName,
				"app.kubernetes.io/instance": "couchbase-admission",
			},
			Ports: []corev1.ServicePort{
				{
					Protocol:   corev1.ProtocolTCP,
					Port:       443,
					TargetPort: intstr.FromInt(8443),
				},
			},
		},
	}
}

// getAdmissionValidatingWebhook creates a validating webhook for the admission controller.
func (o *generateAdmissionOptions) getAdmissionValidatingWebhook(namespace string, ca []byte) *admissionregistrationv1.ValidatingWebhookConfiguration {
	// You need a webhook per controller when running in namespaced mode.
	// IF we reused the same one each time, we'd need to aggregate the webhooks
	// and act as a client doing read/modify/write.  This is complex so instead
	// just name them deterministically (for deletion) and make many resources.
	name := AdmissionResourceName

	if !o.scope.value.isClusterScope() {
		name = AdmissionResourceName + "-" + namespace
	}

	admissionControllerValidatePath := "/couchbaseclusters/validate"

	failurePolicy := admissionregistrationv1.Fail
	sideEffectClass := admissionregistrationv1.SideEffectClassNone

	webhook := &admissionregistrationv1.ValidatingWebhookConfiguration{
		ObjectMeta: metav1.ObjectMeta{
			Name: name,
		},
		Webhooks: []admissionregistrationv1.ValidatingWebhook{
			{
				Name: AdmissionResourceName + "." + namespace + ".svc",
				Rules: []admissionregistrationv1.RuleWithOperations{
					{
						Rule: admissionregistrationv1.Rule{
							APIGroups: []string{
								couchbasev2.GroupName,
							},
							Resources: []string{
								couchbasev2.ClusterCRDResourcePlural,
								couchbasev2.BucketCRDResourcePlural,
								couchbasev2.EphemeralBucketCRDResourcePlural,
								couchbasev2.MemcachedBucketCRDResourcePlural,
								couchbasev2.ReplicationCRDResourcePlural,
								couchbasev2.UserCRDResourcePlural,
								couchbasev2.GroupCRDResourcePlural,
								couchbasev2.RoleBindingCRDResourcePlural,
								couchbasev2.BackupCRDResourcePlural,
								couchbasev2.BackupRestoreCRDResourcePlural,
								couchbasev2.AutoscalerCRDResourcePlural,
								couchbasev2.CollectionCRDResourcePlural,
								couchbasev2.CollectionGroupCRDResourcePlural,
								couchbasev2.ScopeCRDResourcePlural,
								couchbasev2.ScopeGroupCRDResourcePlural,
								couchbasev2.MigrationReplicationCRDResourcePlural,
								couchbasev2.EncryptionKeyCRDResourcePlural,
							},
							APIVersions: []string{
								"v1",
								"v2",
							},
						},
						Operations: []admissionregistrationv1.OperationType{
							admissionregistrationv1.Create,
							admissionregistrationv1.Update,
							admissionregistrationv1.Delete,
						},
					},
				},
				ClientConfig: admissionregistrationv1.WebhookClientConfig{
					Service: &admissionregistrationv1.ServiceReference{
						Namespace: namespace,
						Name:      AdmissionResourceName,
						Path:      &admissionControllerValidatePath,
					},
					CABundle: ca,
				},
				FailurePolicy: &failurePolicy,
				SideEffects:   &sideEffectClass,
				AdmissionReviewVersions: []string{
					"v1",
				},
			},
		},
	}

	// When in namespace scoped mode, the selector will be populated and must be
	// added to the webhook.
	if !o.scope.value.isClusterScope() {
		webhook.Webhooks[0].NamespaceSelector = o.namespaceSelector.LabelSelector
	}

	return webhook
}

func refreshWebhook(flags *genericclioptions.ConfigFlags, o *generateAdmissionOptions) error {
	namespace, _, err := flags.ToRawKubeConfigLoader().Namespace()
	if err != nil {
		return err
	}

	bundle, err := GenerateAdmissionCerts(namespace, defaultExpirationTime)
	if err != nil {
		return err
	}

	config, err := flags.ToRESTConfig()
	if err != nil {
		return err
	}

	clientset, err := kubernetes.NewForConfig(config)
	if err != nil {
		return err
	}

	ctx := context.Background()

	name := AdmissionResourceName

	if !o.scope.value.isClusterScope() {
		name = AdmissionResourceName + "-" + namespace
	}

	hook, err := clientset.AdmissionregistrationV1().ValidatingWebhookConfigurations().Get(ctx, name, metav1.GetOptions{})

	if err != nil {
		return err
	}

	oldHook := hook.DeepCopy()

	for i := 0; i < len(hook.Webhooks); i++ {
		hook.Webhooks[i].ClientConfig.CABundle = bundle.ca.Certificate
	}

	secret, err := clientset.CoreV1().Secrets(namespace).Get(ctx, AdmissionResourceName, metav1.GetOptions{})

	if err != nil {
		return err
	}

	secret.Data["tls.crt"] = bundle.cert
	secret.Data["tls.key"] = bundle.key

	fmt.Println("updating validation hook with new CA")

	if _, err := clientset.AdmissionregistrationV1().ValidatingWebhookConfigurations().Update(ctx, hook, metav1.UpdateOptions{}); err != nil {
		fmt.Println("failed to update validation hook")
		return err
	}

	cleanup := func() {
		if _, err := clientset.AdmissionregistrationV1().ValidatingWebhookConfigurations().Update(ctx, oldHook, metav1.UpdateOptions{}); err != nil {
			fmt.Println("failed to roll back validation hook: %w", err)
		}
	}

	fmt.Println("updating TLS secret with new certificate/key pair")

	if _, err := clientset.CoreV1().Secrets(namespace).Update(ctx, secret, metav1.UpdateOptions{}); err != nil {
		fmt.Println("failed to update TLS secret with new certificate/key pair")
		cleanup()

		return err
	}

	return nil
}
