package config

import (
	"crypto/x509"
	"crypto/x509/pkix"
	"time"

	couchbasev2 "github.com/couchbase/couchbase-operator/pkg/apis/couchbase/v2"
	util_x509 "github.com/couchbase/couchbase-operator/pkg/util/x509"

	admissionregistrationv1beta1 "k8s.io/api/admissionregistration/v1beta1"
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	rbacv1 "k8s.io/api/rbac/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/intstr"
)

const (
	// AdmissionResourceName is the name used for all resources generated by the individual functions.
	AdmissionResourceName = "couchbase-operator-admission"
)

// DumpAdmissionYAML dumps all admission controller resources to standard out.
func DumpAdmissionYAML(conf *Config) error {
	// Generate TLS configuration for the dynamic admission controller.
	validFrom := time.Now()
	validTo := time.Now().Add(24 * 365 * 10 * time.Hour)
	ca, _ := util_x509.NewCertificateAuthority(util_x509.KeyTypeRSA, AdmissionResourceName+" CA", validFrom, validTo, util_x509.CertTypeCA)
	req := util_x509.KeyPairRequest{
		KeyType:   util_x509.KeyTypeRSA,
		CertType:  util_x509.CertTypeServer,
		ValidFrom: validFrom,
		ValidTo:   validTo,
		Req: &x509.CertificateRequest{
			Subject: pkix.Name{
				CommonName: AdmissionResourceName,
			},
			DNSNames: []string{
				AdmissionResourceName + "." + conf.Namespace + ".svc",
			},
		},
	}
	key, cert, _ := req.Generate(ca)

	var imagePullSecrets []string

	if conf.ImagePullSecret != "" {
		imagePullSecrets = []string{
			conf.ImagePullSecret,
		}
	}

	// Create resources.
	if err := DumpYAML(conf, "admission-service-account", GetAdmissionServiceAccount(conf.Namespace)); err != nil {
		return err
	}

	if err := DumpYAML(conf, "admission-cluster-role", GetAdmissionRole(conf.Namespace, conf.Cluster)); err != nil {
		return err
	}

	if err := DumpYAML(conf, "admission-cluster-role-binding", GetAdmissionRoleBinding(conf.Namespace, conf.Cluster)); err != nil {
		return err
	}

	if err := DumpYAML(conf, "admission-secret", GetAdmissionSecret(conf.Namespace, key, cert)); err != nil {
		return err
	}

	if err := DumpYAML(conf, "admission-deployment", GetAdmissionDeployment(conf.Namespace, conf.AdmissionImage, imagePullSecrets)); err != nil {
		return err
	}

	if err := DumpYAML(conf, "admission-service", GetAdmissionService(conf.Namespace)); err != nil {
		return err
	}

	if err := DumpYAML(conf, "admission-mutating-webhook", GetAdmissionMutatingWebhook(conf.Namespace, ca.Certificate, conf.Cluster, conf.NamespaceSelector.LabelSelector)); err != nil {
		return err
	}

	if err := DumpYAML(conf, "admission-validating-webhook", GetAdmissionValidatingWebhook(conf.Namespace, ca.Certificate, conf.Cluster, conf.NamespaceSelector.LabelSelector)); err != nil {
		return err
	}

	return nil
}

// GetAdmissionRole return the (cluster) role to run with.
func GetAdmissionRole(namespace string, cluster bool) metav1.Object {
	metadata := metav1.ObjectMeta{
		Name:      AdmissionResourceName,
		Namespace: namespace,
	}

	rules := []rbacv1.PolicyRule{
		{
			APIGroups: []string{
				couchbasev2.GroupName,
			},
			Resources: []string{
				couchbasev2.ClusterCRDResourcePlural,
				couchbasev2.BucketCRDResourcePlural,
				couchbasev2.EphemeralBucketCRDResourcePlural,
				couchbasev2.MemcachedBucketCRDResourcePlural,
				couchbasev2.ReplicationCRDResourcePlural,
				couchbasev2.UserCRDResourcePlural,
				couchbasev2.GroupCRDResourcePlural,
				couchbasev2.RoleBindingCRDResourcePlural,
				couchbasev2.BackupCRDResourcePlural,
				couchbasev2.BackupRestoreCRDResourcePlural,
			},
			Verbs: []string{
				"list",
			},
		},
		{
			APIGroups: []string{
				"",
			},
			Resources: []string{
				"secrets",
			},
			Verbs: []string{
				"get",
			},
		},
	}

	if cluster {
		clusterRules := []rbacv1.PolicyRule{
			{
				APIGroups: []string{
					"",
				},
				Resources: []string{
					"namespaces",
				},
				Verbs: []string{
					"get",
				},
			},
			{
				APIGroups: []string{
					"storage.k8s.io",
				},
				Resources: []string{
					"storageclasses",
				},
				Verbs: []string{
					"get",
				},
			},
		}

		rules = append(rules, clusterRules...)

		return &rbacv1.ClusterRole{
			TypeMeta: metav1.TypeMeta{
				APIVersion: "rbac.authorization.k8s.io/v1",
				Kind:       "ClusterRole",
			},
			ObjectMeta: metadata,
			Rules:      rules,
		}
	}

	return &rbacv1.Role{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "rbac.authorization.k8s.io/v1",
			Kind:       "Role",
		},
		ObjectMeta: metadata,
		Rules:      rules,
	}
}

// GetAdmissionServiceAccount get the service account to run as.
func GetAdmissionServiceAccount(namespace string) *corev1.ServiceAccount {
	return &corev1.ServiceAccount{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "v1",
			Kind:       "ServiceAccount",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      AdmissionResourceName,
			Namespace: namespace,
		},
	}
}

// GetAdmissionRoleBinding generates the (cluster) role binding linking the role to the service account.
func GetAdmissionRoleBinding(namespace string, cluster bool) metav1.Object {
	metadata := metav1.ObjectMeta{
		Name:      AdmissionResourceName,
		Namespace: namespace,
	}

	subjects := []rbacv1.Subject{
		{
			Kind:      "ServiceAccount",
			Name:      AdmissionResourceName,
			Namespace: namespace,
		},
	}

	if cluster {
		return &rbacv1.ClusterRoleBinding{
			TypeMeta: metav1.TypeMeta{
				APIVersion: "rbac.authorization.k8s.io/v1",
				Kind:       "ClusterRoleBinding",
			},
			ObjectMeta: metadata,
			Subjects:   subjects,
			RoleRef: rbacv1.RoleRef{
				APIGroup: "rbac.authorization.k8s.io",
				Kind:     "ClusterRole",
				Name:     AdmissionResourceName,
			},
		}
	}

	return &rbacv1.RoleBinding{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "rbac.authorization.k8s.io/v1",
			Kind:       "RoleBinding",
		},
		ObjectMeta: metadata,
		Subjects:   subjects,
		RoleRef: rbacv1.RoleRef{
			APIGroup: "rbac.authorization.k8s.io",
			Kind:     "Role",
			Name:     AdmissionResourceName,
		},
	}
}

// GetAdmissionSecret generates the TLS secret providing server certificates.
func GetAdmissionSecret(namespace string, key, cert []byte) *corev1.Secret {
	return &corev1.Secret{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "v1",
			Kind:       "Secret",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      AdmissionResourceName,
			Namespace: namespace,
		},
		Data: map[string][]byte{
			"tls-cert-file":        cert,
			"tls-private-key-file": key,
		},
	}
}

// GetAdmissionDeployment returns the canonical deployment for the admission controller.
func GetAdmissionDeployment(namespace, image string, imagePullSecrets []string, extraArgs ...string) *appsv1.Deployment {
	replicas := int32(1)
	deployment := &appsv1.Deployment{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "apps/v1",
			Kind:       "Deployment",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      AdmissionResourceName,
			Namespace: namespace,
		},
		Spec: appsv1.DeploymentSpec{
			Replicas: &replicas,
			Selector: &metav1.LabelSelector{
				MatchLabels: map[string]string{
					"app": AdmissionResourceName,
				},
			},
			Template: corev1.PodTemplateSpec{
				ObjectMeta: metav1.ObjectMeta{
					Labels: map[string]string{
						"app": AdmissionResourceName,
					},
				},
				Spec: corev1.PodSpec{
					ServiceAccountName: AdmissionResourceName,
					Containers: []corev1.Container{
						{
							Name:  AdmissionResourceName,
							Image: image,
							Command: []string{
								"couchbase-operator-admission",
							},
							Args: append([]string{
								"--logtostderr",
								"--stderrthreshold", "0",
								"--tls-cert-file", "/var/run/secrets/couchbase.com/couchbase-operator-admission/tls-cert-file",
								"--tls-private-key-file", "/var/run/secrets/couchbase.com/couchbase-operator-admission/tls-private-key-file",
							}, extraArgs...),
							Ports: []corev1.ContainerPort{
								{
									Name:          "https",
									ContainerPort: 8443,
								},
							},
							ReadinessProbe: &corev1.Probe{
								Handler: corev1.Handler{
									HTTPGet: &corev1.HTTPGetAction{
										Path:   "/readyz",
										Port:   intstr.FromString("https"),
										Scheme: corev1.URISchemeHTTPS,
									},
								},
							},
							VolumeMounts: []corev1.VolumeMount{
								{
									Name:      AdmissionResourceName,
									MountPath: "/var/run/secrets/couchbase.com/couchbase-operator-admission",
									ReadOnly:  true,
								},
							},
						},
					},
					Volumes: []corev1.Volume{
						{
							Name: AdmissionResourceName,
							VolumeSource: corev1.VolumeSource{
								Secret: &corev1.SecretVolumeSource{
									SecretName: AdmissionResourceName,
								},
							},
						},
					},
				},
			},
		},
	}

	for _, secret := range imagePullSecrets {
		reference := corev1.LocalObjectReference{
			Name: secret,
		}

		deployment.Spec.Template.Spec.ImagePullSecrets = append(deployment.Spec.Template.Spec.ImagePullSecrets, reference)
	}

	return deployment
}

// GetAdmissionService returns a cluster service definition for the admission controller.
func GetAdmissionService(namespace string) *corev1.Service {
	return &corev1.Service{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "v1",
			Kind:       "Service",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      AdmissionResourceName,
			Namespace: namespace,
		},
		Spec: corev1.ServiceSpec{
			Selector: map[string]string{
				"app": AdmissionResourceName,
			},
			Ports: []corev1.ServicePort{
				{
					Protocol:   corev1.ProtocolTCP,
					Port:       443,
					TargetPort: intstr.FromInt(8443),
				},
			},
		},
	}
}

// GetAdmissionMutatingWebhook creates a mutating webhook for the admission controller.
func GetAdmissionMutatingWebhook(namespace string, ca []byte, cluster bool, namespaceSelector *metav1.LabelSelector) *admissionregistrationv1beta1.MutatingWebhookConfiguration {
	// You need a webhook per controller when running in namespaced mode.
	// IF we resued the same one each time, we'd need to aggregate the webhooks
	// and act as a client doing read/modify/write.  This is complex so instead
	// just name them deterministically (for deletion) and make many resources.
	name := AdmissionResourceName

	if !cluster {
		name = AdmissionResourceName + "-" + namespace
	}

	admissionControllerMutatePath := "/couchbaseclusters/mutate"

	webhook := &admissionregistrationv1beta1.MutatingWebhookConfiguration{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "admissionregistration.k8s.io/v1beta1",
			Kind:       "MutatingWebhookConfiguration",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name: name,
		},
		Webhooks: []admissionregistrationv1beta1.MutatingWebhook{
			{
				Name: AdmissionResourceName + "." + namespace + ".svc",
				Rules: []admissionregistrationv1beta1.RuleWithOperations{
					{
						Rule: admissionregistrationv1beta1.Rule{
							APIGroups: []string{
								couchbasev2.GroupName,
							},
							Resources: []string{
								couchbasev2.ClusterCRDResourcePlural,
								couchbasev2.BucketCRDResourcePlural,
								couchbasev2.EphemeralBucketCRDResourcePlural,
								couchbasev2.MemcachedBucketCRDResourcePlural,
								couchbasev2.ReplicationCRDResourcePlural,
								couchbasev2.UserCRDResourcePlural,
								couchbasev2.GroupCRDResourcePlural,
								couchbasev2.RoleBindingCRDResourcePlural,
								couchbasev2.BackupCRDResourcePlural,
								couchbasev2.BackupRestoreCRDResourcePlural,
							},
							APIVersions: []string{
								"v1",
								"v2",
							},
						},
						Operations: []admissionregistrationv1beta1.OperationType{
							admissionregistrationv1beta1.Create,
							admissionregistrationv1beta1.Update,
						},
					},
				},
				ClientConfig: admissionregistrationv1beta1.WebhookClientConfig{
					Service: &admissionregistrationv1beta1.ServiceReference{
						Namespace: namespace,
						Name:      AdmissionResourceName,
						Path:      &admissionControllerMutatePath,
					},
					CABundle: ca,
				},
			},
		},
	}

	// When in namespace scoped mode, the selector will be populated and must be
	// added to the webhook.
	if !cluster {
		webhook.Webhooks[0].NamespaceSelector = namespaceSelector
	}

	return webhook
}

// GetAdmissionValidatingWebhook creates a validating webhook for the admission controller.
func GetAdmissionValidatingWebhook(namespace string, ca []byte, cluster bool, namespaceSelector *metav1.LabelSelector) *admissionregistrationv1beta1.ValidatingWebhookConfiguration {
	// You need a webhook per controller when running in namespaced mode.
	// IF we resued the same one each time, we'd need to aggregate the webhooks
	// and act as a client doing read/modify/write.  This is complex so instead
	// just name them deterministically (for deletion) and make many resources.
	name := AdmissionResourceName

	if !cluster {
		name = AdmissionResourceName + "-" + namespace
	}

	admissionControllerValidatePath := "/couchbaseclusters/validate"

	webhook := &admissionregistrationv1beta1.ValidatingWebhookConfiguration{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "admissionregistration.k8s.io/v1beta1",
			Kind:       "ValidatingWebhookConfiguration",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name: name,
		},
		Webhooks: []admissionregistrationv1beta1.ValidatingWebhook{
			{
				Name: AdmissionResourceName + "." + namespace + ".svc",
				Rules: []admissionregistrationv1beta1.RuleWithOperations{
					{
						Rule: admissionregistrationv1beta1.Rule{
							APIGroups: []string{
								couchbasev2.GroupName,
							},
							Resources: []string{
								couchbasev2.ClusterCRDResourcePlural,
								couchbasev2.BucketCRDResourcePlural,
								couchbasev2.EphemeralBucketCRDResourcePlural,
								couchbasev2.MemcachedBucketCRDResourcePlural,
								couchbasev2.ReplicationCRDResourcePlural,
								couchbasev2.UserCRDResourcePlural,
								couchbasev2.GroupCRDResourcePlural,
								couchbasev2.RoleBindingCRDResourcePlural,
								couchbasev2.BackupCRDResourcePlural,
								couchbasev2.BackupRestoreCRDResourcePlural,
							},
							APIVersions: []string{
								"v1",
								"v2",
							},
						},
						Operations: []admissionregistrationv1beta1.OperationType{
							admissionregistrationv1beta1.Create,
							admissionregistrationv1beta1.Update,
						},
					},
				},
				ClientConfig: admissionregistrationv1beta1.WebhookClientConfig{
					Service: &admissionregistrationv1beta1.ServiceReference{
						Namespace: namespace,
						Name:      AdmissionResourceName,
						Path:      &admissionControllerValidatePath,
					},
					CABundle: ca,
				},
			},
		},
	}

	// When in namespace scoped mode, the selector will be populated and must be
	// added to the webhook.
	if !cluster {
		webhook.Webhooks[0].NamespaceSelector = namespaceSelector
	}

	return webhook
}
