package config

import (
	"fmt"
	"strconv"
	"time"

	couchbasev2 "github.com/couchbase/couchbase-operator/pkg/apis/couchbase/v2"
	"github.com/couchbase/couchbase-operator/pkg/util/constants"

	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	rbacv1 "k8s.io/api/rbac/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
	"k8s.io/cli-runtime/pkg/genericclioptions"

	"github.com/spf13/cobra"
)

const (
	// OperatorResourceName is the name used for all resources generated by the individual functions.
	OperatorResourceName = "couchbase-operator"

	// operatorDefaultLogLevel is what we expect people to use by default.
	operatorDefaultLogLevel = "info"

	// operatorDefaultPodCreationTimout is the default wait before declaring creation a failure.
	operatorDefaultPodCreationTimout = 10 * time.Minute

	// operatorDefaultDeleteDelay is the default wait time for deleting a pod.
	operatorDefaultDeleteDelay = time.Duration(0)

	// operatorDefaultPodReadinessDelay is the default delay time for starting readiness probes.
	operatorDefaultPodReadinessDelay = 10 * time.Second

	// operatorDefaultPodReadinessPeriod is the default period between readiness probes.
	operatorDefaultPodReadinessPeriod = 20 * time.Second

	// operatorDefaultCPURequest is the number of CPUs to schedule for.
	// On my laptop it's using ~2% cpu at idle, and the operator either polls or
	// is event driven, there is no CPU heavy spining.
	operatorDefaultCPURequest = "500m"

	// operatorDefaultCPULimit is the burst number of CPUs to kill the pod if exceeded.
	operatorDefaultCPULimit = "1"

	// operatorDefaultMemoryRequest is the amount of memory to schedule for.
	// On my laptop it's using ~45000 RSS with one cluster, there is hardly any effect
	// when adding a second cluster.
	operatorDefaultMemoryRequest = "200Mi"

	// operatorDefaultMemoryLimit is the burst amount of memory to kill the pod if exceeded.
	operatorDefaultMemoryLimit = "400Mi"

	// operatorDefaultPullPolicy is the pull policy to use when downloading the image.
	// By default images are only pulled if not already present.
	operatorDefaultPullPolicy = string(corev1.PullIfNotPresent)

	// Debug flag.
	debug = "debug"
	// dlv requires a specific port be specified otherwise a random one is used.
	debugPort = "30123"
)

// generateOperatorOptions defines the options for creating the operator.
type generateOperatorOptions struct {
	// image is the operator image name.
	image string

	// scope is the scope with which to generate the operator.
	scope scopeVar

	// imagePullSecret is the name of an image pull secret for authenticating image pulls.
	imagePullSecret imagePullSecretVar

	// imagePullPolicy is the pull policy to use when downloading the image.
	imagePullPolicy string

	// logLevel is the level to emit docs at.
	logLevel zapLogLevelVar

	// podCreationTimeout is the time to wait before declaring pod creation failed.
	podCreationTimeout durationVar

	// podDeleteDelay is the time to wait before actually removing a pod.
	podDeleteDelay durationVar

	// podReadinessDelay is the time to wait before startubg the readiness probes.
	podReadinessDelay durationVar

	// podReadinessPeriod is the time between readiness probes.
	podReadinessPeriod durationVar

	// withResources allows you to add resource requests and limits.
	withResources bool

	// cpuRequest is the number of CPUs to schedule for.
	cpuRequest quantityVar

	// cpuLimit is the burst number of CPUs to kill the pod if exceeded.
	cpuLimit quantityVar

	// memoryRequest is the amount of memory to schedule for.
	memoryRequest quantityVar

	// memoryLimit is the burst amount of memory to kill the pod if exceeded.
	memoryLimit quantityVar

	// debug sets the image to run debug config
	debug bool

	// optionalMetricLabels includes uuid or uuid and name in the prometheus metric labels.
	optionalMetricLabels MetricLabel

	// separateMetricClusternameAndNamespace allows you to separate cluster name and namespace from certain metrics.
	separateMetricClusternameAndNamespace bool
}

// newGenerateOperatorOptions returns a set of options with defaults applied.
func newGenerateOperatorOptions() *generateOperatorOptions {
	return &generateOperatorOptions{
		scope:              newScopeVar(scopeNamespace),
		logLevel:           newZapLogLevelVar(operatorDefaultLogLevel),
		podCreationTimeout: newDurationVar(operatorDefaultPodCreationTimout),
		podDeleteDelay:     newDurationVar(operatorDefaultDeleteDelay),
		podReadinessDelay:  newDurationVar(operatorDefaultPodReadinessDelay),
		podReadinessPeriod: newDurationVar(operatorDefaultPodReadinessPeriod),
		cpuRequest:         newQuantityVar(operatorDefaultCPURequest),
		cpuLimit:           newQuantityVar(operatorDefaultCPULimit),
		memoryRequest:      newQuantityVar(operatorDefaultMemoryRequest),
		memoryLimit:        newQuantityVar(operatorDefaultMemoryLimit),
	}
}

// registerOperatorGenerateFlags adds generic generation flags to the provided command.
func (o *generateOperatorOptions) registerOperatorGenerateFlags(cmd *cobra.Command) {
	cmd.Flags().Var(&o.scope, "scope", "Whether to scope the Operator to a 'namespace' or to the 'cluster'.")
	cmd.Flags().StringVar(&o.image, "image", operatorImageDefault, "Operator image to use.")
	cmd.Flags().Var(&o.imagePullSecret, "image-pull-secret", "Image pull secret to allow access to the operator image.")
	cmd.Flags().StringVar(&o.imagePullPolicy, "image-pull-policy", operatorDefaultPullPolicy, "Image pull policy to affect when the image is downloaded.")
	cmd.Flags().Var(&o.logLevel, "log-level", "Log level to generate logs at.  \"info\" prints basic operations. \"debug\", or \"1\" prints extended information and API calls. \"2\" prints very detailed logs, including full API payloads that may contain passwords and keys.")
	cmd.Flags().Var(&o.podCreationTimeout, "pod-creation-timeout", "How long to wait before declaring an error when provisioning a pod.")
	cmd.Flags().Var(&o.podDeleteDelay, "pod-delete-delay", "How long to wait before performing a delete on a failed pod.")
	cmd.Flags().Var(&o.podReadinessDelay, "pod-readiness-delay", "How long to wait before starting readiness probes on server pods.")
	cmd.Flags().Var(&o.podReadinessPeriod, "pod-readiness-period", "How long to wait between readiness probes on server pods.")
	cmd.Flags().BoolVar(&o.withResources, "with-resources", false, "Populates pod resource requests and limits")
	cmd.Flags().Var(&o.cpuRequest, "cpu-request", "CPU requested for scheduling")
	cmd.Flags().Var(&o.cpuLimit, "cpu-limit", "CPU limit for constraining")
	cmd.Flags().Var(&o.memoryRequest, "memory-request", "Memory requested for scheduling")
	cmd.Flags().Var(&o.memoryLimit, "memory-limit", "Memory limit for constraining")
	cmd.Flags().BoolVar(&o.debug, debug, false, "Runs debug configuration. Not intended for external use")
	cmd.Flags().Var(&o.optionalMetricLabels, "optional-metric-labels", "Whether to add cluster uuid or cluster uuid and cluster name to prometheus metrics as labels. Allowed 'uuid-only' or 'uuid-and-name'.")
	cmd.Flags().BoolVar(&o.separateMetricClusternameAndNamespace, "separate-cluster-namespace-and-name", true, "Separates cluster name and namespace from certain metrics.")
	_ = cmd.Flags().MarkHidden(debug)
}

// getGenerateOperatorCommand creates YAML capable of creating the Operator.
func getGenerateOperatorCommand(command string, flags *genericclioptions.ConfigFlags) *cobra.Command {
	o := newGenerateOperatorOptions()

	cmd := &cobra.Command{
		Use:   "operator",
		Short: "Generates YAML for the Couchbase Autonomous Operator.",
		Long: normalize(`
			Generates YAML for the Couchbase Autonomous Operator.

			The Operator is designed to be run at the namespace scope (default).
			It watches for creation of CouchbaseCluster resources in that namespace
			and provides automated provisioning, management and disaster recovery
			of Couchbase Server.
		`),
		Example: normalize(fmt.Sprintf(`
                        # Create operator (recommended).
                        %[1]s generate operator

			# Create operator scoped to the cluster.
			%[1]s generate operator --scope cluster

			# Create operator with a custom image and secure image registry.
			%[1]s generate operator --image acme.corp/operator:1.0.0 --image-pull-secret secret-name

			# Create operator with debug logging.
			%[1]s generate operator --log-level debug

			# Create operator with extended timeouts (for slow platforms).
			%[1]s generate operator --pod-creation-timeout 1h
		`, command)),
		RunE: func(cmd *cobra.Command, args []string) error {
			resources, err := o.generate(flags)
			if err != nil {
				return err
			}

			return dumpResources(resources)
		},
	}

	o.registerOperatorGenerateFlags(cmd)

	return cmd
}

// getCreateOperatorCommand creates the Operator.
func getCreateOperatorCommand(command string, flags *genericclioptions.ConfigFlags) *cobra.Command {
	o := newGenerateOperatorOptions()

	cmd := &cobra.Command{
		Use:   "operator",
		Short: "Creates the Couchbase Autonomous Operator.",
		Long: normalize(`
			Creates the Couchbase Autonomous Operator.

                        The Operator is designed to be run at the namespace scope (default).
                        It watches for creation of CouchbaseCluster resources in that namespace
                        and provides automated provisioning, management and disaster recovery
                        of Couchbase Server.
		`),
		Example: normalize(fmt.Sprintf(`
                        # Create operator (recommended).
                        %[1]s create operator

                        # Create operator scoped to the cluster.
                        %[1]s create operator --scope cluster

                        # Create operator with a custom image and secure image registry.
                        %[1]s create operator --image acme.corp/operator:1.0.0 --image-pull-secret secret-name

                        # Create operator with debug logging.
                        %[1]s create operator --log-level debug

                        # Create operator with extended timeouts (for slow platforms).
                        %[1]s create operator --pod-creation-timeout 1h
                `, command)),
		RunE: func(cmd *cobra.Command, args []string) error {
			if command != caoBinaryName {
				genDeprecatedWarning("https://docs.couchbase.com/operator/current/tools/cao.html#cao-create-operator-flags")
			}

			resources, err := o.generate(flags)
			if err != nil {
				return err
			}

			return createResources(flags, resources)
		},
	}

	o.registerOperatorGenerateFlags(cmd)

	return cmd
}

// getDeleteOperatorCommand deletes the Operator.
func getDeleteOperatorCommand(command string, flags *genericclioptions.ConfigFlags) *cobra.Command {
	o := newGenerateOperatorOptions()

	cmd := &cobra.Command{
		Use:   "operator",
		Short: "Deletes the Couchbase Autonomous Operator.",
		Long:  "Deletes the Couchbase Autonomous Operator.",
		Example: normalize(fmt.Sprintf(`
			# Delete operator (recommended).
			%[1]s delete operator

			# Delete operator scoped to the cluster.
			%[1]s delete operator --scope cluster
		`, command)),
		RunE: func(cmd *cobra.Command, args []string) error {
			if command != caoBinaryName {
				genDeprecatedWarning("https://docs.couchbase.com/operator/current/tools/cao.html#cao-delete-operator-flags")
			}

			resources, err := o.generate(flags)
			if err != nil {
				return err
			}

			return deleteResources(flags, resources)
		},
	}

	cmd.Flags().Var(&o.scope, "scope", "Whether to scope the Operator to a 'namespace' or to the 'cluster'.")

	return cmd
}

// generate dumps all operator resources to standard out.
func (o *generateOperatorOptions) generate(flags *genericclioptions.ConfigFlags) ([]runtime.Object, error) {
	namespace, _, err := flags.ToRawKubeConfigLoader().Namespace()
	if err != nil {
		return nil, err
	}

	resources := []runtime.Object{
		o.getOperatorServiceAccount(),
		o.getOperatorRole(),
		o.getOperatorRoleBinding(namespace),
		o.getOperatorDeployment(),
		o.getOperatorService(),
	}

	return resources, nil
}

// getOperatorRole generates the cluster role to run with.
func (o *generateOperatorOptions) getOperatorRole() runtime.Object {
	metadata := metav1.ObjectMeta{
		Name: OperatorResourceName,
	}

	rules := []rbacv1.PolicyRule{
		{
			APIGroups: []string{
				"batch",
			},
			Resources: []string{
				"jobs",
				"cronjobs",
			},
			Verbs: []string{
				"list",
				"watch",
				"create",
				"update",
				"delete",
			},
		},
		{
			APIGroups: []string{
				couchbasev2.GroupName,
			},
			Resources: []string{
				couchbasev2.ClusterCRDResourcePlural,
				// OCP related hack to support deletion of all subordinate
				// resources before the cluster itself.
				couchbasev2.ClusterCRDResourcePlural + "/finalizers",
				// Not supported by GKE 1.13 for some odd reason
				// couchbasev2.ClusterCRDResourcePlural + "/status",
			},
			Verbs: []string{
				"get",    // used by the operator to update status.
				"list",   // used by the operator-sdk to discover couchbase clusters.
				"watch",  // used by the operator-sdk to monitor changes.
				"update", // used by the operator to update status.
			},
		},
		{
			APIGroups: []string{
				couchbasev2.GroupName,
			},
			Resources: []string{
				couchbasev2.ReplicationCRDResourcePlural,
				couchbasev2.MigrationReplicationCRDResourcePlural,
				couchbasev2.UserCRDResourcePlural,
				couchbasev2.GroupCRDResourcePlural,
				couchbasev2.RoleBindingCRDResourcePlural,
				couchbasev2.BackupCRDResourcePlural,
			},
			Verbs: []string{
				"get",   // used by the operator for Validation
				"list",  // used by the operator for caching
				"watch", // used by the operator for caching
			},
		},
		{
			APIGroups: []string{
				couchbasev2.GroupName,
			},
			Resources: []string{
				couchbasev2.BucketCRDResourcePlural,
				couchbasev2.EphemeralBucketCRDResourcePlural,
				couchbasev2.MemcachedBucketCRDResourcePlural,
				couchbasev2.ScopeCRDResourcePlural,
				couchbasev2.ScopeGroupCRDResourcePlural,
				couchbasev2.CollectionCRDResourcePlural,
				couchbasev2.CollectionGroupCRDResourcePlural,
			},
			Verbs: []string{
				"get",    // used by the operator for Validation
				"list",   // used by the operator for caching
				"watch",  // used by the operator for caching
				"create", // used by my "favourite" synchronization feature
			},
		},
		{
			APIGroups: []string{
				couchbasev2.GroupName,
			},
			Resources: []string{
				couchbasev2.BackupRestoreCRDResourcePlural,
			},
			Verbs: []string{
				"get",    // used by the operator for Validation
				"list",   // used by the operator for caching
				"watch",  // used by the operator for caching
				"delete", // used by the operator to cleanup restores
			},
		},
		{
			APIGroups: []string{
				couchbasev2.GroupName,
			},
			Resources: []string{
				couchbasev2.AutoscalerCRDResourcePlural,
			},
			Verbs: []string{
				"get",    // used to get specific resource
				"list",   // used by the operator for caching
				"watch",  // used by the operator for caching
				"create", // used by the operator to create resources
				"update", // used by the operator to update scale size
				"delete", // used to cleanup unused resources
			},
		},
		{
			APIGroups: []string{
				couchbasev2.GroupName,
			},
			Resources: []string{
				couchbasev2.AutoscalerCRDResourcePlural + "/status",
			},
			Verbs: []string{
				"update", // used by the operator to update status subresource
			},
		},
		{
			APIGroups: []string{
				"",
			},
			Resources: []string{
				"configmaps",
			},
			Verbs: []string{
				"get",    // used by the controller-runtime for leadership.
				"list",   // used by operator for caching
				"watch",  // used by operator for caching
				"create", // used by the controller-runtime for leadership.
				"update", // used by the controller-runtime for leadership.
				"delete", // used to migrate persistent state to 2.1
			},
		},
		{
			APIGroups: []string{
				"",
			},
			Resources: []string{
				"pods",
				"pods/status",
				"services",
				"persistentvolumeclaims",
			},
			Verbs: []string{
				"get",    // used by the operator to get specific resources.
				"list",   // used by the operator for caching
				"watch",  // used by the operator for caching
				"create", // used by the operator to create resources.
				"update", // used by the operator to modify resources.
				"delete", // used by the operator to delete resources.
				"patch",  // used by the operator to modify resources.
			},
		},
		{
			APIGroups: []string{
				"",
			},
			Resources: []string{
				"events",
			},
			Verbs: []string{
				"list",   // used by the operator for supportability.
				"create", // used by the operator to create events.
				"update", // used by the operator to update events.
			},
		},
		{
			APIGroups: []string{
				"",
			},
			Resources: []string{
				"secrets",
			},
			Verbs: []string{
				"get",    // used by the operator to get cluster and TLS secrets.
				"create", // used by the operator for persistent state
				"update", // used by the operator for persistent state
				"list",   // used by the operator for caching
				"watch",  // used by the operator for caching
			},
		},
		// Require read/write of pod disruption budgets.
		{
			APIGroups: []string{
				"policy",
			},
			Resources: []string{
				"poddisruptionbudgets",
			},
			Verbs: []string{
				"get",    // used by the operator to get pod disruption budgets.
				"create", // used by the operator to create pod disruption budgets.
				"delete", // used by the operator to delete pod disruption budgets.
				"list",   // used by the operator for caching
				"watch",  // used by the operator for caching
			},
		},
		// Leader election...
		{
			APIGroups: []string{
				"coordination.k8s.io",
			},
			Resources: []string{
				"leases",
			},
			Verbs: []string{
				"get",
				"create",
				"update",
			},
		},
	}

	if o.scope.value.isClusterScope() {
		return &rbacv1.ClusterRole{
			ObjectMeta: metadata,
			Rules:      rules,
		}
	}

	return &rbacv1.Role{
		ObjectMeta: metadata,
		Rules:      rules,
	}
}

// getOperatorServiceAccount generates the service account to run as.
func (o *generateOperatorOptions) getOperatorServiceAccount() *corev1.ServiceAccount {
	return &corev1.ServiceAccount{
		ObjectMeta: metav1.ObjectMeta{
			Name: OperatorResourceName,
		},
	}
}

// getOperatorRoleBinding generates the cluster role binding linking the role to the service account.
func (o *generateOperatorOptions) getOperatorRoleBinding(namespace string) runtime.Object {
	metadata := metav1.ObjectMeta{
		Name: OperatorResourceName,
	}

	subjects := []rbacv1.Subject{
		{
			Kind:      "ServiceAccount",
			Name:      OperatorResourceName,
			Namespace: namespace,
		},
	}

	if o.scope.value.isClusterScope() {
		return &rbacv1.ClusterRoleBinding{
			ObjectMeta: metadata,
			Subjects:   subjects,
			RoleRef: rbacv1.RoleRef{
				APIGroup: "rbac.authorization.k8s.io",
				Kind:     "ClusterRole",
				Name:     OperatorResourceName,
			},
		}
	}

	return &rbacv1.RoleBinding{
		ObjectMeta: metadata,
		Subjects:   subjects,
		RoleRef: rbacv1.RoleRef{
			APIGroup: "rbac.authorization.k8s.io",
			Kind:     "Role",
			Name:     OperatorResourceName,
		},
	}
}

// getOperatorDeployment returns the canonical way to run the operator.
func (o *generateOperatorOptions) getOperatorDeployment() *appsv1.Deployment {
	replicas := int32(1)

	nonRoot := true

	// IF we are running namespace scoped, then use the namespace metadata
	// to set the environment variable and imit the Operator.  If not then
	// set it to "" and let it have free reign over the whole cluster.
	namespaceEnv := corev1.EnvVar{
		Name: "WATCH_NAMESPACE",
	}

	if !o.scope.value.isClusterScope() {
		namespaceEnv.ValueFrom = &corev1.EnvVarSource{
			FieldRef: &corev1.ObjectFieldSelector{
				FieldPath: "metadata.namespace",
			},
		}
	}

	operatorCommand := OperatorResourceName
	operatorCommandArgs := []string{
		"--pod-create-timeout=" + o.podCreationTimeout.value.String(),
		"--pod-delete-delay=" + o.podDeleteDelay.value.String(),
		"--pod-readiness-delay=" + o.podReadinessDelay.String(),
		"--pod-readiness-period=" + o.podReadinessPeriod.String(),
		"--zap-log-level=" + o.logLevel.value,
	}

	if o.debug {
		operatorCommand = "dlv"
		operatorCommandArgs = []string{"debug", "./cmd/couchbase-operator", "--listen=:" + debugPort, "--accept-multiclient", "--continue", "--headless=true", "--api-version=2"}
	}

	deployment := &appsv1.Deployment{
		ObjectMeta: metav1.ObjectMeta{
			Name: OperatorResourceName,
		},
		Spec: appsv1.DeploymentSpec{
			Replicas: &replicas,
			Selector: &metav1.LabelSelector{
				MatchLabels: map[string]string{
					"app": OperatorResourceName,
				},
			},
			Template: corev1.PodTemplateSpec{
				ObjectMeta: metav1.ObjectMeta{
					Annotations: map[string]string{
						constants.AnnotationPrometheusScrape: "true",
						constants.AnnotationPrometheusPath:   "/metrics",
						constants.AnnotationPrometheusPort:   "8383",
						constants.AnnotationPrometheusScheme: "http",
					},
					Labels: map[string]string{
						"app": OperatorResourceName,
					},
				},
				Spec: corev1.PodSpec{
					ServiceAccountName: OperatorResourceName,
					SecurityContext: &corev1.PodSecurityContext{
						RunAsNonRoot: &nonRoot,
					},
					Containers: []corev1.Container{
						{
							Name:            OperatorResourceName,
							Image:           o.image,
							ImagePullPolicy: corev1.PullPolicy(o.imagePullPolicy),
							Command: []string{
								operatorCommand,
							},
							Args: operatorCommandArgs,
							Env: []corev1.EnvVar{
								namespaceEnv,
								{
									Name: "POD_NAME",
									ValueFrom: &corev1.EnvVarSource{
										FieldRef: &corev1.ObjectFieldSelector{
											FieldPath: "metadata.name",
										},
									},
								},
								{
									Name:  "additional-prometheus-labels",
									Value: o.optionalMetricLabels.String(),
								},
								{
									Name:  "separate-cluster-name-and-namespace",
									Value: strconv.FormatBool(o.separateMetricClusternameAndNamespace),
								},
							},
							Ports: []corev1.ContainerPort{
								{
									Name:          "http",
									ContainerPort: 8080,
								},
								{
									Name:          "prometheus",
									ContainerPort: 8383,
								},
							},
							ReadinessProbe: &corev1.Probe{
								ProbeHandler: corev1.ProbeHandler{
									HTTPGet: &corev1.HTTPGetAction{
										Path:   "/readyz",
										Port:   intstr.FromString("http"),
										Scheme: corev1.URISchemeHTTP,
									},
								},
							},
						},
					},
				},
			},
		},
	}

	if o.withResources {
		deployment.Spec.Template.Spec.Containers[0].Resources = corev1.ResourceRequirements{
			Requests: corev1.ResourceList{
				corev1.ResourceCPU:    o.cpuRequest.value,
				corev1.ResourceMemory: o.memoryRequest.value,
			},
			Limits: corev1.ResourceList{
				corev1.ResourceCPU:    o.cpuLimit.value,
				corev1.ResourceMemory: o.memoryLimit.value,
			},
		}
	}

	for _, secret := range o.imagePullSecret.imagePullSecrets {
		reference := corev1.LocalObjectReference{
			Name: secret,
		}

		deployment.Spec.Template.Spec.ImagePullSecrets = append(deployment.Spec.Template.Spec.ImagePullSecrets, reference)
	}

	return deployment
}

// Required by istio.
func (o *generateOperatorOptions) getOperatorService() *corev1.Service {
	return &corev1.Service{
		ObjectMeta: metav1.ObjectMeta{
			Name: OperatorResourceName,
		},
		Spec: corev1.ServiceSpec{
			Selector: map[string]string{
				"app": OperatorResourceName,
			},
			Ports: []corev1.ServicePort{
				{
					Name:       "http-pprof",
					Protocol:   corev1.ProtocolTCP,
					Port:       8080,
					TargetPort: intstr.FromInt(8080),
				},
				{
					Name:       "http-prometheus",
					Protocol:   corev1.ProtocolTCP,
					Port:       8383,
					TargetPort: intstr.FromInt(8383),
				},
			},
		},
	}
}

// GetOperatorDeployment is a hook for use by QE.
func GetOperatorDeployment(image string, imagePullSecrets []string, podCreationTimeout time.Duration, logLevel string, podDeleteDelay time.Duration, podReadinessDelay time.Duration, podReadinessPeriod time.Duration) *appsv1.Deployment {
	o := newGenerateOperatorOptions()
	o.image = image
	o.imagePullSecret.imagePullSecrets = imagePullSecrets
	o.podCreationTimeout.value = podCreationTimeout
	o.podDeleteDelay.value = podDeleteDelay
	o.podReadinessDelay.value = podReadinessDelay
	o.podReadinessPeriod.value = podReadinessPeriod
	o.logLevel.value = logLevel

	return o.getOperatorDeployment()
}
