package config

import (
	"fmt"
	"time"

	couchbasev1 "github.com/couchbase/couchbase-operator/pkg/apis/couchbase/v1"

	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	rbacv1 "k8s.io/api/rbac/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/intstr"
)

const (
	// OperatorResourceName is the name used for all resources generated by the individual functions.
	OperatorResourceName = "couchbase-operator"
)

// DumpAdmissionYAML dumps all operator resources to standard out.
func DumpOperatorYAML(conf *Config) error {
	if conf.NoOperator {
		return nil
	}

	if err := DumpYAML(conf, "operator-service-account", GetOperatorServiceAccount()); err != nil {
		return err
	}
	if err := DumpYAML(conf, "operator-role", GetOperatorRole()); err != nil {
		return err
	}
	if err := DumpYAML(conf, "operator-role-binding", GetOperatorRoleBinding(conf.Namespace)); err != nil {
		return err
	}
	if err := DumpYAML(conf, "operator-deployment", GetOperatorDeployment(conf.OperatorImage, conf.ImagePullSecret, 10*time.Minute)); err != nil {
		return err
	}
	return nil
}

// GetOperatorRole generates the cluster role to run with.
func GetOperatorRole() *rbacv1.Role {
	return &rbacv1.Role{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "rbac.authorization.k8s.io/v1",
			Kind:       "Role",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name: OperatorResourceName,
		},
		Rules: []rbacv1.PolicyRule{
			{
				APIGroups: []string{
					couchbasev1.GroupName,
				},
				Resources: []string{
					couchbasev1.CRDResourcePlural,
				},
				Verbs: []string{
					"get",    // used by the operator to update status.
					"list",   // used by the operator-sdk to discover couchbase clusters.
					"watch",  // used by the operator-sdk to monitor changes.
					"update", // used by the operator to update status.
				},
			},
			{
				APIGroups: []string{
					"",
				},
				Resources: []string{
					"pods",
					"services",
					"endpoints",
					"persistentvolumeclaims",
				},
				Verbs: []string{
					"get",    // used by the operator to get specific resources.
					"list",   // used by the operator to list all resources.
					"watch",  // used by the operator to monitor changes to resources (pods, pvcs only).
					"create", // used by the operator to create resources.
					"update", // used by the operator to modify resources.
					"delete", // used by the operator to delete resources.
				},
			},
			{
				APIGroups: []string{
					"",
				},
				Resources: []string{
					"pods/exec",
				},
				Verbs: []string{
					"create", // used by the operator to signify readiness.
				},
			},
			{
				APIGroups: []string{
					"",
				},
				Resources: []string{
					"events",
				},
				Verbs: []string{
					"create", // used by the operator to create events.
					"patch",  // used by client-go to create and update events.
				},
			},
			{
				APIGroups: []string{
					"",
				},
				Resources: []string{
					"secrets",
				},
				Verbs: []string{
					"get", // used by the operator to get cluster and TLS secrets.
				},
			},
			// Require read/write of pod disruption budgets.
			{
				APIGroups: []string{
					"policy",
				},
				Resources: []string{
					"poddisruptionbudgets",
				},
				Verbs: []string{
					"get",    // used by the operator to get pod disruption budgets.
					"create", // used by the operator to create pod disruption budgets.
					"delete", // used by the operator to delete pod disruption budgets.
				},
			},
		},
	}
}

// GetOperatorServiceAccount generates the service account to run as.
func GetOperatorServiceAccount() *corev1.ServiceAccount {
	return &corev1.ServiceAccount{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "v1",
			Kind:       "ServiceAccount",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name: OperatorResourceName,
		},
	}
}

// GetOperatorRoleBinding generates the cluster role binding linking the role to the service account.
func GetOperatorRoleBinding(namespace string) *rbacv1.RoleBinding {
	return &rbacv1.RoleBinding{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "rbac.authorization.k8s.io/v1",
			Kind:       "RoleBinding",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name: OperatorResourceName,
		},
		Subjects: []rbacv1.Subject{
			{
				Kind:      "ServiceAccount",
				Name:      OperatorResourceName,
				Namespace: namespace,
			},
		},
		RoleRef: rbacv1.RoleRef{
			APIGroup: "rbac.authorization.k8s.io",
			Kind:     "Role",
			Name:     OperatorResourceName,
		},
	}
}

// GetOperatorDeployment returns the canonical way to run the operator.
func GetOperatorDeployment(image string, imagePullSecret string, podCreateTimeout fmt.Stringer) *appsv1.Deployment {
	replicas := int32(1)
	deployment := &appsv1.Deployment{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "apps/v1",
			Kind:       "Deployment",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name: OperatorResourceName,
		},
		Spec: appsv1.DeploymentSpec{
			Replicas: &replicas,
			Selector: &metav1.LabelSelector{
				MatchLabels: map[string]string{
					"app": OperatorResourceName,
				},
			},
			Template: corev1.PodTemplateSpec{
				ObjectMeta: metav1.ObjectMeta{
					Labels: map[string]string{
						"app": OperatorResourceName,
					},
				},
				Spec: corev1.PodSpec{
					ServiceAccountName: OperatorResourceName,
					Containers: []corev1.Container{
						{
							Name:  OperatorResourceName,
							Image: image,
							Command: []string{
								OperatorResourceName,
							},
							Args: []string{
								"--pod-create-timeout=" + podCreateTimeout.String(),
								"--create-crd=false",
							},
							Env: []corev1.EnvVar{
								{
									Name: "MY_POD_NAMESPACE",
									ValueFrom: &corev1.EnvVarSource{
										FieldRef: &corev1.ObjectFieldSelector{
											FieldPath: "metadata.namespace",
										},
									},
								},
								{
									Name: "MY_POD_NAME",
									ValueFrom: &corev1.EnvVarSource{
										FieldRef: &corev1.ObjectFieldSelector{
											FieldPath: "metadata.name",
										},
									},
								},
							},
							Ports: []corev1.ContainerPort{
								{
									Name:          "http",
									ContainerPort: 8080,
								},
							},
							ReadinessProbe: &corev1.Probe{
								Handler: corev1.Handler{
									HTTPGet: &corev1.HTTPGetAction{
										Path: "/readyz",
										Port: intstr.FromString("http"),
									},
								},
								InitialDelaySeconds: 3,
								PeriodSeconds:       3,
								FailureThreshold:    20,
							},
						},
					},
				},
			},
		},
	}
	if imagePullSecret != "" {
		deployment.Spec.Template.Spec.ImagePullSecrets = []corev1.LocalObjectReference{
			{
				Name: imagePullSecret,
			},
		}
	}
	return deployment
}
