#!/usr/bin/env bash

# Copyright 2018-Present Couchbase, Inc.
#
# Use of this software is governed by the Business Source License included in
# the file licenses/BSL-Couchbase.txt.  As of the Change Date specified in that
# file, in accordance with the Business Source License, use of this software
# will be governed by the Apache License, Version 2.0, included in the file
# licenses/APL2.txt.

BUILD_DIR=${WORKSPACE_DIR}/build
CBOPCFG=${WORKSPACE_DIR}/build/bin/cbopcfg
OPERATOR_VERSION=$(grep -o '[0-9]\.[0-9]\.[0-9]' ${WORKSPACE_DIR}/pkg/version/version.go)

while [[ $# -gt 0 ]]
do
arg="$1"

case $arg in
    -p|--platform)
    PLATFORM="$2"
    shift
    shift
    ;;
    -o|--os)
    OS="$2"
    shift
    shift
    ;;
    -v|--version)
    VERSION="$2"
    shift
    shift
    ;;
    -b|--bld_num)
    BLD_NUM="$2"
    shift
    shift
    ;;
    -a|--arch)
    ARCH="$2"
    shift
    shift
    ;;
    *)    # unknown option
    shift
    ;;
esac
done

case $OS in
    linux)
    DIRNAME=couchbase-autonomous-operator-${PLATFORM}_${VERSION}-linux-${ARCH}
    NAME=couchbase-autonomous-operator-${PLATFORM}_${VERSION}-${BLD_NUM}-linux-${ARCH}
    ;;
    darwin)
    DIRNAME=couchbase-autonomous-operator-${PLATFORM}_${VERSION}-macos-${ARCH}
    NAME=couchbase-autonomous-operator-${PLATFORM}_${VERSION}-${BLD_NUM}-macos-${ARCH}
    ;;
    windows)
    DIRNAME=couchbase-autonomous-operator-${PLATFORM}_${VERSION}-windows-${ARCH}
    NAME=couchbase-autonomous-operator-${PLATFORM}_${VERSION}-${BLD_NUM}-windows-${ARCH}
    ;;
    *)
    ;;
esac

ARTIFACTS_DIR=${BUILD_DIR}/${DIRNAME}

mkdir -p ${ARTIFACTS_DIR}

# VERSION file
echo ${VERSION}-${BLD_NUM} > ${ARTIFACTS_DIR}/VERSION.txt

# Platform specific stuff
cp ${WORKSPACE_DIR}/docs/user/modules/ROOT/examples/${PLATFORM}/* ${ARTIFACTS_DIR}

# Autogenerated stuff
cp ${WORKSPACE_DIR}/example/crd.yaml ${ARTIFACTS_DIR}

# Static stuff
cp ${WORKSPACE_DIR}/docs/License.txt ${ARTIFACTS_DIR}
cp ${WORKSPACE_DIR}/docs/README.txt ${ARTIFACTS_DIR}
cp -r ${BUILD_DIR}/${OS}/${ARCH}/* ${ARTIFACTS_DIR}
cp -r ${BUILD_DIR}/${PLATFORM}/${OS}/${ARCH}/* ${ARTIFACTS_DIR}

# Package contents
case $OS in
    linux)
    tar -C ${BUILD_DIR} -czf ${BUILD_DIR}/${NAME}.tar.gz ${DIRNAME}
    ;;
    *)
    (cd ${BUILD_DIR} && zip -r ${NAME}.zip ${DIRNAME})
    ;;
esac
rm -rf ${ARTIFACTS_DIR}

