#!/usr/bin/env bash

BUILD_DIR=${WORKSPACE_DIR}/build
CBOPCFG=${WORKSPACE_DIR}/build/bin/cbopcfg
OPERATOR_VERSION=$(grep -o '[0-9]\.[0-9]\.[0-9]' ${WORKSPACE_DIR}/pkg/version/version.go)

while [[ $# -gt 0 ]]
do
arg="$1"

case $arg in
    -p|--platform)
    PLATFORM="$2"
    shift
    shift
    ;;
    -o|--os)
    OS="$2"
    shift
    shift
    ;;
    -v|--version)
    VERSION="$2"
    shift
    shift
    ;;
    -b|--bld_num)
    BLD_NUM="$2"
    shift
    shift
    ;;
    *)    # unknown option
    shift
    ;;
esac
done

case $OS in
    linux)
    DIRNAME=couchbase-autonomous-operator-${PLATFORM}_${VERSION}-linux-x86_64
    NAME=couchbase-autonomous-operator-${PLATFORM}_${VERSION}-${BLD_NUM}-linux-x86_64
    ;;
    darwin)
    DIRNAME=couchbase-autonomous-operator-${PLATFORM}_${VERSION}-macos-x86_64
    NAME=couchbase-autonomous-operator-${PLATFORM}_${VERSION}-${BLD_NUM}-macos-x86_64
    ;;
    windows)
    DIRNAME=couchbase-autonomous-operator-${PLATFORM}_${VERSION}-windows-amd64
    NAME=couchbase-autonomous-operator-${PLATFORM}_${VERSION}-${BLD_NUM}-windows-amd64
    ;;
    *)
    ;;
esac

ARTIFACTS_DIR=${BUILD_DIR}/${DIRNAME}

mkdir -p ${ARTIFACTS_DIR}

# VERSION file
echo ${VERSION}-${BLD_NUM} > ${ARTIFACTS_DIR}/VERSION.txt

# Platform specific stuff
cp ${WORKSPACE_DIR}/docs/user/modules/ROOT/examples/${PLATFORM}/* ${ARTIFACTS_DIR}

# Autogenerated stuff
cp ${WORKSPACE_DIR}/example/crd.yaml ${ARTIFACTS_DIR}
pushd ${ARTIFACTS_DIR}
case ${PLATFORM} in
  kubernetes)
    ${CBOPCFG} --no-operator > admission.yaml
    ${CBOPCFG} --no-admission --file
    ;;
  openshift)
    OPERATOR_IMAGE=registry.connect.redhat.com/couchbase/operator:${OPERATOR_VERSION}-1
    ADMISSION_IMAGE=registry.connect.redhat.com/couchbase/admission-controller:${OPERATOR_VERSION}-1
    ${CBOPCFG} --no-operator --dynamic-admission-controller-image ${ADMISSION_IMAGE} --image-pull-secret REDHAT_CONTAINER_REGISTRY_PULL_SECRET > admission.yaml
    ${CBOPCFG} --no-admission --operator-image ${OPERATOR_IMAGE} --image-pull-secret REDHAT_CONTAINER_REGISTRY_PULL_SECRET --file
    ;;
esac
popd

# Static stuff
cp ${WORKSPACE_DIR}/docs/License.txt ${ARTIFACTS_DIR}
cp ${WORKSPACE_DIR}/docs/README.txt ${ARTIFACTS_DIR}
cp -r ${BUILD_DIR}/${OS}/* ${ARTIFACTS_DIR}

# Package contents
case $OS in
    linux)
    tar -C ${BUILD_DIR} -czf ${BUILD_DIR}/${NAME}.tar.gz ${DIRNAME}
    ;;
    *)
    (cd ${BUILD_DIR} && zip -r ${NAME}.zip ${DIRNAME})
    ;;
esac
rm -rf ${ARTIFACTS_DIR}

