#!/bin/bash

# FILTER allows us to pre-process the source and discard irrelevant parts.
FILTER="sed"
# Ignore source code blocks (contain arbitrary non-English configuration).
FILTER="${FILTER} -e /^----$/,/^----$/d"
# Ignore asciidoc ifdef blocks (contain arbitrary non-English configuration).
FILTER="${FILTER} -e /^ifdef/,/^endif/d"
# Ignore inline literals and attributes (contain arbitrary non-English configuration).
FILTER="${FILTER} -e s/\`[^\`]*\`//g"
FILTER="${FILTER} -e s/{[^}]*}//g"
# Ignore definition lists (contain arbitrary non-English configuration).
FILTER="${FILTER} -e s/^.*::$//g"
# Ignore hyperlinks (not our problem).
FILTER="${FILTER} -e s/http:[^\[]*//g"
FILTER="${FILTER} -e s/https:[^\[]*//g"
# Ignore cross-reference file names (not user-visisble, however this may affect SEO).
FILTER="${FILTER} -e s/xref:[^\[]*//g"
# Ignore image file names (not user-visisble, however this may affect SEO).
FILTER="${FILTER} -e s/image:[^\[]*//g"
# Ignore asciidoc directives.
FILTER="${FILTER} -e s/^:.*$//g"
# Ignore links anchors.
FILTER="${FILTER} -e s/<<[^,]*//g"
# Ignore includes.
FILTER="${FILTER} -e s/^include::.*$//g"
# Ignore toc commands.
FILTER="${FILTER} -e s/^toc::.*$//g"
# Ignore anchors formatting directives etc.
FILTER="${FILTER} -e s/^\[.*$//g"
# Ignore inline ui-macros.
FILTER="${FILTER} -e s/btn:\[[^\]*\]//g"
FILTER="${FILTER} -e s/kbd:\[[^\]*\]//g"
# Log level for antora
LOG_LEVEL="fatal"

while getopts l: flag
do
  case "${flag}" in
    l) LOG_LEVEL=${OPTARG};;
    *) exit 1;;
  esac
done

# CHECK_ARGS is the spell checking command to run.
CHECK_ARGS="-l en_US --home-dir=."

# Before we spell check, ensure that the docs are generated...
make docs

GIT_STATUS="$(git status --short)"
if [[ ${GIT_STATUS} != "" ]]; then
  echo "Documentation has not been generated and committed:"
  echo ${GIT_STATUS}
  git diff
  echo
  echo "Run 'make docs' and commit the result."
  exit 1
fi

# For each asciidoc we find in the documentation, filter out the
# stuff that isn't real text and spell check the remainder.  For now
# only look in the top-level directory, anything outside of it is
# considered auto-generated and exempt.
FAIL=""
for DOCUMENT in $(find docs/user -name resource -prune -false -o -name tools -prune -false -o -path *autogen* -quit -o -type f -name *.adoc); do
  MISTAKES=$(cat ${DOCUMENT} | ${FILTER} | aspell list ${CHECK_ARGS} | sort | uniq)
  if [[ ${MISTAKES} != "" ]]; then
    echo "Spell check for file ${DOCUMENT} failed:"
    echo "${MISTAKES}" | sed 's/^/    /g'
    FAIL="yes"
  fi
done

# Any failures need to be fixed up, and we need to report and error for CI.
if [[ ${FAIL} != "" ]]; then
  echo "Documentation contains errors"
  echo "    run 'aspell check ${CHECK_ARGS}' to fix typos or add to .aspell.en.pws"
  exit 1
fi

# Now that your general spelling has been corrected, let's look at syntax...
# This step will also check for any xrefs you got wrong...
npm install
WARNINGS=$(node_modules/@antora/cli/bin/antora generate --log-level="$LOG_LEVEL" scripts/playbook.yaml 2>&1 | sed -e /^.*tabs.*$/d)
if [[ "${WARNINGS}" != "" ]]; then
  echo "Asciidoc markup contains errors"
  echo "${WARNINGS}" | sed 's/^/    /g'
  exit 1
fi
