site:
  title: Couchbase Operator CI
  url: https://acme.com
  start_page: operator::overview.adoc
content:
  sources:
  - url: ./..
    branches: HEAD
    start_path: docs/user
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
