#!/bin/bash

# Copyright 2020-Present Couchbase, Inc.
#
# Use of this software is governed by the Business Source License included in
# the file licenses/BSL-Couchbase.txt.  As of the Change Date specified in that
# file, in accordance with the Business Source License, use of this software
# will be governed by the Apache License, Version 2.0, included in the file
# licenses/APL2.txt.

set -e 

for f in $(git ls-tree -r --name-only HEAD | grep -v testrunner | xargs -exec file -i | grep text/x-python | cut -d: -f1); do
  echo "Linting: $f"
  pylint $f
done
