= Couchbase Cluster Migration Documentation

[abstract]
The Couchbase Operator can manage the migration of an unmanaged Couchbase cluster to an Operator managed cluster running on Kubernetes.

To perform a migration of an unmanaged Couchbase cluster to a managed Couchbase cluster the main requirement is that their needs to be network access between the nodes of the source cluster to the nodes in the managed cluster. If a cluster is being migrated from EC2 to EKS then this can be achieved using External DNS and AWS Load Balancers. 

To migrate an existing cluster a Couchbase Cluster spec describing the state of the existing cluster needs to be created. This spec should contain the configuration of the existing cluster, most importantly the nodes that make up the existing cluster and the services that they run. The Couchbase Operator will then recreate each of these nodes in Kubernetes and swap-rebalance them into the cluster whilst simultaneously removing their counterparts in the source cluster.

== Migration Example

### Create a source cluster
To perform the migration we need a cluster to migrate. For this example the cluster will be created by the Operator, this cluster can then be paused once created to stop any management actions on it.

Source Cluster Spec:

```
apiVersion: v1
kind: Secret
metadata:
  name: cb-example-auth
type: Opaque
data:
  username: QWRtaW5pc3RyYXRvcg==
  password: cGFzc3dvcmQ=
---
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-example
spec:
  image: couchbase/server:7.6.0
  security:
    adminSecret: cb-example-auth
    rbac:
      managed: true
  buckets:
    managed: true
  upgradeProcess: InPlaceUpgrade
  servers:
    - size: 3
      name: data
      services:
        - data
```

Once the operator has finished creating the cluster it can be paused with the spec.paused field. I.e.
```
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-example
spec:
  paused: true
  ...
```

### Migrating the cluster
To migrate the cluster a new CouchbaseCluster resource needs to be created. This spec needs three things to migrate the cluster:

* The server classes in the original cluster to be migrated over
* The spec.migration.unmanagedClusterHost field which points the operator at the source cluster
* The credentials to get admin access to the cluster supplied through a secret referenced in the spec.security.adminSecret field

To migrate the source cluster described above the following CouchbaseCluster spec can be used:

```
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-migrating
spec:
  image: couchbase/server:7.6.0
  security:
    adminSecret: cb-example-auth
    rbac:
      managed: true
  migration:
    unmanagedClusterHost: cb-example.default.svc.cluster.local
  servers:
    - size: 3
      name: data
      services:
        - data
```


Once this resource is creaed the operator will begin the migration of the cluster.


== Migration Control 
=== Migration Parameters
The migration field supports additional parameters to control the migration of the cluster.

```
  migration:
    unmanagedClusterHost: cb-example.default.svc.cluster.local
    stabilizationPeriod:  30s
    numUnmanagedNodes: 2
    maxConcurrentMigrations: 2
```

stabilizationPeriod is the time the operator will wait after a migration before starting the next migration.
If not specified the operator will start the next migration immediately.

numUnmanagedNodes is the number of nodes the operator will leave in the cluster unmigrated.
This is useful for constrolling how much of the cluster to mgirate over at a time.
If not specified
the operator will migrate all nodes.
e.g.
if the unmanaged cluster has 10 nodes and NumUnmanagedNodes is set to 2, then the operator will
migrate 8 nodes to Kubernetes and leave 2 nodes.

maxConcurrentMigrations is the maximum number of nodes migrations the operator will run concurrently.


=== Pre-migration nodes
To add nodes to the source cluster before performing any migration pre-migration nodes can be defined. These nodes will be added before any migration happens. Pre-migration nodes are simply defined by adding a Server Class for nodes that don't exist on the source cluster. Using the examples above two single pre-migration nodes can be added by modifying the spec like:

```
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-migrating
spec:
  image: couchbase/server:7.6.0
  security:
    adminSecret: cb-example-auth
    rbac:
      managed: true
  migration:
    unmanagedClusterHost: cb-example.default.svc.cluster.local
  servers:
    - size: 3
      name: data
      services:
        - data
    - size: 2
      name: pre_migration
      services:
        - data
```


To migrate an existing cluster a Couchbase Cluster spec describing the state of the existing cluster needs to be created. This spec should contain the configuration of the existing cluster, most importantly the nodes that make up the existing cluster and the services that they run. The Couchbase Operator will then recreate each of these nodes in Kubernetes and swap-rebalance them into the cluster whilst simultaneously removing their counterparts in the source cluster.

== Limiations
=== Backup Service
Currently the Operator doesn't support running nodes with the backup service. This means that if the source cluster has nodes with the backup service then these nodes will need to be removed or replaced with nodes that aren't running the backup service. Backup is still supported by the Operator