= Couchbase Operator Logging

[abstract]
How to extract and use Operator logs for problem determination.

The Operator provides flexible logging support to enable failure detection and alerting.
It is also a key resource when submitting a support request with the xref:tools/cbopinfo.adoc[`cbopinfo`] tool.

Logs are structured as JSON with one entry per line.
This provides a simple and stable foundation for parsing and ingesting logs into 3rd party logging databases.
Most popular logging solutions feature native support for JSON input:

* https://docs.fluentd.org/parser/json[Fluentd JSON parser^]
* https://www.elastic.co/guide/en/logstash/current/plugins-codecs-json_lines.html[Logstash JSON codec^]

Detailed instructions on what can be collected can be found in the xref:reference-operator-logging.adoc[Operator logging reference].
Detailed instructions on how to configure logging can be found in the xref:reference-operator-configuration.adoc[Operator configuration reference].

[IMPORTANT]
====
Couchbase server logs cannot be collected by default from the pod's standard output as is typical in Kubernetes environments.

The xref:tools/cbopinfo.adoc[`cbopinfo`] support tool can be used to collect a log archive at any time, as can the Couchbase web console.

A logging sidecar is now optionally available to stream logs from the volume used by Couchbase server. 
This is not enabled by default but see xref:reference-server-logging.adoc[Server logging reference] for full details on specifying this.

This will stream Couchbase server audit logs by default to standard output using a Fluent Bit sidecar which can be customized with any supported configuration required to send information to other technologies. 
Refer to the Fluent Bit https://docs.fluentbit.io/manual/pipeline/outputs[documentation^] for the full configuration and supported options.
====
