= Couchbase Backup and Restore

[abstract]
The Autonomous Operator provides facilities that allow data to be backed up, restored, and archived in order to aid in cluster disaster recovery.

== Overview

The Autonomous Operator provides automated backup and restore capabilities through a native integration with the Couchbase Server tool xref:server:backup-restore:enterprise-backup-restore.adoc[`cbbackupmgr`].
Automated backup is enabled in the xref:resource/couchbasecluster.adoc[`CouchbaseCluster`] resource (it is _disabled_ by default).
When backup is enabled, the Autonomous Operator defaults to a Couchbase-supplied https://hub.docker.com/r/couchbase/operator-backup[_backup image_^] that contains the xref:server:backup-restore:enterprise-backup-restore.adoc[`cbbackupmgr`] tool.

Once automated backup is enabled, individual backup policies can be configured using xref:resource/couchbasebackup.adoc[`CouchbaseBackup`] resources, which define things like _schedule_ and _backup strategy_.
Each xref:resource/couchbasebackup.adoc[`CouchbaseBackup`] resource creates one or two Kubernetes https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/[`CronJob`^] resources that will spawn backup jobs according to the given Cron schedule(s).
These backup jobs execute a helper script which performs logging and cleanup, and utilizes xref:server:backup-restore:enterprise-backup-restore.adoc[`cbbackupmgr`] to perform backup and restore.

For information on configuring automated backup and restore, refer to xref:howto-backup.adoc[].

[TIP]
====
Because backup policies are configured with a separate resource, you can use xref:concept-rbac.adoc[custom resource RBAC] to allow individuals who may not have access to xref:resource/couchbasecluster.adoc[`CouchbaseCluster`] resources to still perform backup administration.
====

== Important Considerations

* The Autonomous Operator supports two of the backup strategies available in xref:server:backup-restore:enterprise-backup-restore.adoc[`cbbackupmgr`]: _Full Only_ and _Full/Incremental_.
Complete descriptions and explanations of these strategies can be found in the xref:server:backup-restore:cbbackupmgr-strategies.adoc[`cbbackupmgr` strategies documentation].

* The Autonomous Operator runs the backup utility in a separate Pod.
Where this Pod is scheduled can have implications on backup performance, and can affect whether backup jobs are able to complete within the desired time window.
+
You should schedule backup Pods onto Kubernetes nodes that have enough resources to successfully fulfill your backup schedule.
It is also recommended that you do not schedule backup Pods onto Kubernetes nodes that host Couchbase cluster Pods, since your Couchbase cluster would be competing for resources with the backup utility.
Refer to xref:howto-backup.adoc#pod-scheduling[Pod Scheduling] for more information.

* Backup Pods require access permissions that necessitate the creation of `ServiceAccount`, `Role`, and `RoleBinding` resources.
Refer to xref:howto-backup.adoc#grant-backup-permissions[Grant Access Permissions] for more information.

* You can enable and disable automated backup at any time in the xref:resource/couchbasecluster.adoc[`CouchbaseCluster`] resource.
Disabling automated backup does not delete xref:resource/couchbasebackup.adoc[`CouchbaseBackup`] resources.
When you re-enabled automated backup, any applicable xref:resource/couchbasebackup.adoc[`CouchbaseBackup`] resources that still exist will continue to be used.

* Only the official Couchbase-supplied https://hub.docker.com/r/couchbase/operator-backup[backup image^] is supported.
This image is designed only for use with the Autonomous Operator -- it is not meant for any other context.
A new image is created for each version of Couchbase Server that the Autonomous Operator supports (refer to <<version-compatibility>> below).
+
In addition, you should ensure that your image source is trusted.
The backup image requires access to the Couchbase cluster administrative credentials in order to login and perform collection.
Granting these credentials to arbitrary code is potentially harmful.

* When your Couchbase cluster is configured with TLS, backups and restores will also occur over TLS to provide end-to-end encryption of your data while in transit.
+
[IMPORTANT]
====
The xref:server:backup-restore:enterprise-backup-restore.adoc[`cbbackupmgr`] tool _does not_ support mutual TLS authentication.
If your Couchbase cluster is using mandatory client certificate authentication, the Autonomous Operator, in an effort to keep the backup from failing, will downgrade the connection between the backup Pod and the cluster to _plain text_.
In both server-side TLS and optional client certificate authentication modes of operation, the backup will occur over TLS, using basic HTTP authentication.
====

[[version-compatibility]]
=== Version Compatibility

* Each version of Couchbase Server is released with an equivalent version of xref:server:backup-restore:enterprise-backup-restore.adoc[`cbbackupmgr`].
Therefore, when the Autonomous Operator is certified for a new version of Couchbase Server, a new https://hub.docker.com/r/couchbase/operator-backup[backup image^] is made available containing the equivalent version of xref:server:backup-restore:enterprise-backup-restore.adoc[`cbbackupmgr`].

* It's important to keep in mind that xref:server:backup-restore:enterprise-backup-restore.adoc[`cbbackupmgr`] has its own xref:server:backup-restore:enterprise-backup-restore.adoc#version-compatibility[compatibility requirements] between versions of Couchbase Server.
Therefore it's recommended that you keep the version of the backup image up-to-date with the version of Couchbase Server.
For example, backup and restore operations on a cluster running Couchbase Server 6.6.x should use the backup image `couchbase/operator-backup:6.6.0`.
+
This also applies to certain features enabled by newer versions of xref:server:backup-restore:enterprise-backup-restore.adoc[`cbbackupmgr`].
For example, only version 6.6.x or greater of the backup image will be able to utilize AWS S3 backup and restore operations, as this feature was added to `cbbackupmgr` in 6.6.

== Additional Resources

* xref:howto-backup.adoc[]

