= Autonomous Operator Logging

[abstract]
The Autonomous Operator provides flexible logging support to enable failure detection and alerting.

The Operator provides flexible logging support to enable failure detection and alerting.
It is also a key resource when submitting a support request with the xref:tools/cbopinfo.adoc[`cbopinfo`] tool.
This page describes logging that is specific to the Autonomous Operator itself.
For information about Couchbase cluster logging, refer to xref:concept-couchbase-logging.adoc[].

== Overview

The Autonomous Operator xref:howto-manage-operator-logging.adoc[emits logs] on the pod console.
Logs are structured as JSON with one entry per line, thus providing a simple and stable foundation for machine parsing and ingestion into 3rd-party logging databases.

.Example of Autonomous Operator Logs
[source,json]
----
{"level":"info","ts":1580377225.2966235,"logger":"couchbaseutil","msg":"Cluster status","cluster":"default/cb-example","balance":"balanced","rebalancing":false}
{"level":"info","ts":1580377225.296685,"logger":"couchbaseutil","msg":"Node status","cluster":"default/cb-example","name":"cb-example-0000","version":"6.5.0","class":"all_services","managed":true,"status":"warmup"}
{"level":"info","ts":1580377225.6940928,"logger":"cluster","msg":"Pods warming up, skipping","cluster":"default/cb-example"}
{"level":"info","ts":1580377225.892829,"logger":"cluster","msg":"Reconcile completed","cluster":"default/cb-example"}
{"level":"info","ts":1580377226.7565176,"logger":"cluster","msg":"Creating XDCR remote cluster","cluster":"default/cb-example","remote":"remote"}
----

.Popular logging solutions that feature native support for JSON input
[TIP]
====
* https://docs.fluentd.org/parser/json[Fluentd JSON parser^]
* https://www.elastic.co/guide/en/logstash/current/plugins-codecs-json_lines.html[Logstash JSON codec^]
====

== Related Content

* xref:howto-manage-operator-logging.adoc[].
* xref:reference-operator-logging.adoc[].
* xref:reference-operator-configuration.adoc[].
