= Deploying a Couchbase Cluster

== Prerequisites

Before proceeding to deploy a Couchbase cluster, ensure that the xref:prerequisite-and-setup.adoc[prerequisites] are met and the Couchbase Operator is up and running.

== Deploying a Cluster

Deploying a Couchbase cluster requires creating a configuration file that describes what the cluster should look like. Like all Kubernetes configurations, Couchbase clusters are defined using either YAML or JSON (YAML is preferred by Kubernetes) and then pushed into Kubernetes. Below is a sample configuration file for a Couchbase cluster.

[source,yaml]
----
apiVersion: couchbase.database.couchbase.com/v1beta1
kind: CouchbaseCluster
metadata:
  name: cb-example
spec:
  baseImage: couchbase/server
  version: enterprise-5.0.1
  authSecret: cb-example-auth
  exposeAdminConsole: true
  cluster:
    dataServiceMemoryQuota: 256
    indexServiceMemoryQuota: 256
    searchServiceMemoryQuota: 256
    indexStorageSetting: memory_optimized
    autoFailoverTimeout: 120
    autoFailoverMaxCount: 3
    autoFailoverOnDataDiskIssues: true
    autoFailoverOnDataDiskIssuesTimePeriod: 120
    autoFailoverServerGroup: false
  buckets:
    - name: default
      type: couchbase
      memoryQuota: 128
      replicas: 1
      ioPriority: high
      evictionPolicy: fullEviction
      conflictResolution: seqno
      enableFlush: true
      enableIndexReplica: false
  servers:
    - size: 3
      name: all_services
      services:
        - data
        - index
        - query
        - search
----

By taking a quick look at this configuration file you can see that it defines a cluster by specifying the following:

* Cluster name: cb-example (metadata.name)
* Couchbase version: 5.0.1 (spec.version)
* Buckets: 1 bucket named default (spec.buckets)
* Size: 3 node cluster with all services on each node (spec.servers)
* Auth secret: cb-example-auth

One thing that's important to note is the `authSecret` field. The Couchbase Operator uses Kubernetes Secrets to create and manage the Couchbase super-user credentials. As a result, the `authSecret` field must refer to secret that contains both a user name and a password field. For convenience, we provide a sample secret that can be pushed into your Kubernetes cluster. The secret sets the user name to `Administrator` and the password to `password`. To load this secret into your Kubernetes cluster, run the following command:

On Kubernetes:

 $ kubectl create -f https://packages.couchbase.com/kubernetes/0.8.1-beta2/secret.yaml
 secret "cb-example-auth" created

On OpenShift:

 $ oc create -f https://packages.couchbase.com/kubernetes/0.8.1-beta2/secret.yaml
 secret "cb-example-auth" created

The Couchbase Operator configuration is now ready to be pushed to Kubernetes. To push the Couchbase Operator configuration, run the following command:

On Kubernetes:

 $ cbopctl create -f https://packages.couchbase.com/kubernetes/0.8.1-beta2/couchbase-cluster.yaml
 couchbasecluster "cb-example" created

On OpenShift:

 $ cbopctl create -f https://packages.couchbase.com/kubernetes/0.8.1-beta2/couchbase-cluster.yaml
 couchbasecluster "cb-example" created

NOTE: `cbopctl` is a command line tool similar to kubectl or oc. It allows users to validate that the CouchbaseCluster configuration being sent to Kubernetes is a valid configuration. See xref:cbopctl.adoc[Ensuring Valid CouchbaseCluster Configurations With cbopctl] for download instructions.

The Couchbase Operator automatically begins creating the cluster. Depending on the configuration, creating a cluster can take some time. You can track the progress of cluster creation using the `kubectl describe` command. For details on how to use this command and an explanation of the output, see xref:cluster-status-guide.adoc[Displaying Information about a Couchbase Cluster].

Once the cluster has been provisioned, you'll see that various pods, a service, and a Couchbase cluster have been created. Since the configuration above was for a 3-nodes cluster, you should see three pods created. The Couchbase Operator also creates an internal headless service that can be used by applications deployed inside the same Kubernetes namespace to connect to the Couchbase cluster.
Run the following command to see the newly created pods:

On Kubernetes:

 $ kubectl get pods
 NAME                                  READY     STATUS    RESTARTS   AGE
 cb-example-0000                       1/1       Running   0          1m
 cb-example-0001                       1/1       Running   0          1m
 cb-example-0002                       1/1       Running   0          1m
 couchbase-operator-1917615544-pd4q6   1/1       Running   0          8m

On OpenShift, run the following command:

 $ oc get pods

A CouchbaseCluster object is also created for the cluster and can be used to get health and status information about the cluster. For details on how to inspect these objects, see xref:list-and-describe.adoc[Listing and Describing Pods, Services, and CouchbaseClusters]

For further details on what each field in the CouchbaseCluster configuration does, as well as a list of all available fields see xref:couchbase-cluster-config.adoc[CouchbaseCluster Configuration].
