= Couchbase Helm Chart Specification
include::partial$constants.adoc[]

[abstract]
The official Couchbase Helm Chart for the Autonomous Operator comes with a default configuration that can be customized to fit your deployment needs.

This page describes the parameters of the official Couchbase Helm Chart.
In particular, this page describes the contents of the chart's https://github.com/couchbase-partners/helm-charts/blob/master/couchbase-operator/values.yaml[values.yaml^], which contains the chart's default values.
Each of the deployed resources is listed and described, along with any user definable parameters.

For instructions on how to install and use the chart, including how to override and customize the chart's values, refer to xref:helm-setup-guide.adoc[Helm Deployment].

[IMPORTANT]
====
The official Couchbase Helm Chart may only be used with Enterprise Edition products, such as Couchbase Server Enterprise Edition and Sync Gateway Enterprise Edition.
====

.Helm Chart Values
[#table-helm-chart-values,cols="2,1,2,3",options="header"]
|===
include::partial$autogen-helm-chart-values.adoc[]
|===

== About Resource Names

All resources/objects created by the Couchbase Chart adhere to the following naming scheme: `<release-name>-<component-name>`

* `<release-name>`
 ** This is name of the installed instance.
* `<component-name>`
 ** This is the name of the Operator, Admission, and Couchbase component..
 ** If the resource is created for the _Operator_, then `<component-name>` will be whatever is specified in <<couchbaseOperator-name,`couchbaseOperator.name`>>.
 ** If the resource is created for the _admission controller_, then `<component-name>` will be whatever is specified in `<<admissionController-name,admissionController.name>>`.
 ** If the resource is created for the Couchbase cluster, then `<component-name>` will be whatever is specified in `<<cluster-name,cluster.name>>`.

=== Specifying Your Own Resources

The chart allows you to override certain resources such as `<<cluster-tls,TLS>>` certificates with ones that you've already created.
In this case, the names of the resources are determined by you and not the chart, and therefore do not adhere to the naming scheme described in the previous section.
Check the specs below for the value you are attempting to override for additional information on what type of resource is expected and how it should be formatted.

== Install Values

Installation values for selective deployment of components within the chart.

[source,yaml]
----
  # Select what to install
  install:
    # install the couchbase operator
    couchbaseOperator: true
    # install the admission controller
    admissionController: true
    # install couchbase cluster
    couchbaseCluster: true
    # install sync gateway
    syncGateway: false
----

The Couchbase Chart is capable of installing the Operator, Admission Controller, Couchbase Cluster, and Sync Gateway.

[#install]
=== `couchbaseOperator`

This field specifies whether or not the Couchbase Autonomous Operator will be installed.

[cols="1",options="header"]
|===
a| _Field Rules:_
a| The `couchbaseOperator` field defaults to `true`.
|===

=== `admissionController`

This field specifies whether or not the Couchbase Admission Controller will be installed.

[cols="1",options="header"]
|===
a| _Field Rules:_
a| The `admissionController` field defaults to `true`.
|===

=== `couchbaseCluster`

This field specifies whether or not a Couchbase Cluster will be installed.

[cols="1",options="header"]
|===
a| _Field Rules:_
a| The `couchbaseCluster` field defaults to `true`.
|===

=== `syncGateway`

This field specifies whether or not an instance of the Sync Gateway will be installed.

[cols="1",options="header"]
|===
a| _Field Rules:_
a| The `syncGateway` field defaults to `false`.
|===


== Couchbase Cluster

The `cluster` configuration represents the `CouchbaseCluster` resources to be installed.
If `install.couchbaseCluster` is set to `false` then the cluster will not be installed.

=== `cluster`

[source,yaml]
----
  cluster:
    name:
    security:
      username: Administrator
      password:
      adminSecret:
----


=== `name`

The name of the cluster to create.

_Value rules:_ The `couchbaseCluster.name` value defaults to the name of the chart if not specified.
Must be unique from any other clusters in the namespace.

=== `username`

The username to use as the cluster admin.

WARNING: This should only be used for experimental and test clusters.
Consider using `adminSecret` to provide a secret containing your own username and password.

_Value rules:_ The `couchbaseCluster.username` value is a string set to `Administrator` by default.

=== `password`

The password to use as the cluster admin.

WARNING: This should only be used for experimental and test clusters.
Consider using `adminSecret` to provide a secret containing your own username and password.

_Value rules:_ The `couchbaseCluster.password` value is a string that is auto-generated by default.


=== `adminSecret`

The secret to use for overriding the auto-generated secret.
When specified the username and password from the secret are used for Administrator login.

_Value rules:_ The `couchbaseCluster.adminSecret` value is the name of a Kubernetes secret and is not set by default.

=== Persistent Volumes

The best way to create a cluster with persistent volumes is to make a custom value file.
The following example shows how volume mounts can be added to created a persisted cluster.

Create a file named `values-persistent.yaml` with the following values:
[source,yaml]
----
cluster:
  servers:
    default:
      pod:
        volumeMounts:
          default: couchbase
          data:  couchbase
  securityContext:
      fsGroup: 1000
  volumeClaimTemplates:
    - metadata:
        name: couchbase
      spec:
        storageClassName: "default"
        resources:
          requests:
            storage: 1Gi
----

Install the cluster chart using the custom value file:
[source,console]
----
helm install my-release -f values-persistent.yaml couchbase/couchbase-cluster
----

=== additional values

All of the remaining values which can be overridden in this spec are described in the `CouchbaseCluster` documentation.


== TLS
Certificates can be auto-generated or overridden by user supplied certs.
Also since Couchbase certs are represented as plain Kubernetes secrets, the secret itself can be overridden.

[source,yaml]
----
tls:
  generate: false
  expiration: 365
  nodeToNodeEncryption: All
----

=== `generate`

This value determines whether the chart should create the cluster with TLS.

_Value rules:_ The `tls.generate` is a boolean which defaults to `false`.
When set to `true` all of the certs and keys required for TLS will be auto-generated unless manually specified.
When value is `false` certs are not generated, but manual Secrets can be provided by overriding `cluster.networking.tls`.

=== `expiration`

Expiration of CA in days

_Value rules:_ The `couchbaseTLS.expiration` defaults to 365 days.


=== `nodeToNodeEncryption`

This field defines whether node-to-node encryption is enabled.

When set to `All`, all data between Couchbase server nodes is encrypted.
When set to `ControlPlaneOnly`, only internal Couchbase server messages are encrypted, user data is not.
If not specified, data between Couchbase Server nodes is not encrypted.

As with all encryption protocols, this setting may negatively affect performance with the increased data protection.

____
_Field rules:_ This field is optional and must be either `All` or `ControlPlaneOnly`.
____


=== Custom TLS

Create cluster with auto-generated TLS certs
[source,console]
----
helm install my-release --set tls.generate=true couchbase/couchbase-cluster
----

Use manually created secrets
. Create a file named `tls_values.yaml` with the following custom override values for the Couchbase Chart:
+
[source,yaml]
----
cluster:
   networking:
     tls:
       static:
         operatorSecret: tls-operator-secret
         serverSecret: tls-server-secret

----

[source,console]
----
helm install  my-release -f tls_values.yaml couchbase/couchbase-cluster
----

== Buckets

The `buckets` configuration represent `CouchbaseBucket` resources to be installed by the cluster.

[source,yaml]
----
buckets:
  default:
    name: default
    kind: CouchbaseBucket
----

NOTE: Buckets are automatically provisioned with xref:concept-label-selection.adoc[label selectors] matching the corresponding Couchbase cluster.

At least one bucket will be created whenever `install.CouchbaseCluster` is set to `true` (if you don't actively configure at least one bucket, then a default bucket is created automatically).
If zero buckets are desired, then you must disable bucket creation completely by setting the contents to `null`.

[source,yaml]
----
buckets: null
----

NOTE: The `buckets` field must be explicitly set to `null` in order to avoid bucket creation.
Even if the section is completely empty, unless `buckets: null` is specified, the default bucket will be created.

=== `name`
This value determines the name of the bucket to create within Couchbase Server.

_Value rules:_ The `bucket.name` value is a string.
This value is optional and when not set, the object key name is used instead.
The object key name is used for the Kubernetes CRD, whereas this value is used for the bucket name that is recognized within the Couchbase Server application.

=== `kind`
This is the type of the bucket to create and can be one of the supported types provided by Couchbase Server.

_Value rules:_ The `bucket.kind` value takes one of the supported values: `CouchbaseBucket`, `CouchbaseEphemeralBucket`, or `CouchbaseMemcachedBucket`.
This value is optional and defaults to `CouchbaseBucket` when not set.

=== additional values

All of the remaining values which can be overridden in this spec are described in the `CouchbaseCluster` documentation.


== Users

The `users` configuration represent `CouchbaseUser`, `CouchbaseGroup`, and `CouchbaseRoleBinding` resources to be installed by the cluster.
Users are installed whenever `install.CouchbaseCluster` is set to `true`.

[source,yaml]
----
  users:
    developer:   # username <.>
      password: password
      authSecret:
      authDomain: local
      roles:
        - name: bucket_admin
          bucket: default
----

<.> The username is set from the key of each user configuration.
NOTE: Users are automatically provisioned with xref:concept-label-selection.adoc[label selectors] matching the corresponding Couchbase cluster.

=== `password`

The user password.

WARNING: This should only be used for experimental and test clusters.
Consider using `authSecret` or setting `authDomain: external` to improve security .

_Value rules:_ The `user.<name>.password` value is a string.
This value is required when `authDomain` is `local`.


=== `authSecret`

The Kubernetes Secret containing the user password.

_Value rules:_ The `user.<name>.authSecret` value is a string.
This value is optional and must refer to a Kubernetes Secret resource when specified.
The Secret must contain the path `data.password` with the base64 encoded value of the secret

=== `authDomain`

The Couchbase RBAC Domain to use when authenticating the user.

_Value rules:_ The `user.<name>.authDomain` value is a string.
This value is required and must be either `local` or `external`.


=== `roles`

The Couchbase Roles to assign to the user

_Value rules:_ The `user.<name>.roles` value is a list.
This value is required and must provide the `name` of a valid Couchbase Server role.
If the Couchbase Server role is a bucket role, then the name of a `bucket` value may also be provided.
If the name of a bucket is not provided for a bucket role then the value defaults to `*` which means the role applies to all buckets.

Refer to `CouchbaseGroups` documentation for list of Administrator and Bucket roles.

== Backups
This object defines parameters and variables for automated backup.
When set, the chart will create a backup job.

[source,yaml]
----
backups:
  default-backup:
    name: my-backup
    strategy: full_incremental
    full:
      schedule: "0 3 * * 0"
    incremental:
      schedule: "0 3 * * 1-6"
----

All of the provided values for this spec are described here in the xref:reference-couchbasecluster.adoc[Couchbase Cluster Configuration] documentation.

== Backup Restores
This object defines parameters and variables for automated backup restores.
When set, the chart will create a backup restore job.

[source,yaml]
----
backuprestores:
  default-restore:
    name: my-restore
    backup: my-backup
    repo: cb-example-2020-11-12T19_00_03
    start:
      int: 1
      str: oldest
    end:
      int: 1
      str: latest
    backOffLimit: 2
    logRetention: 24h
----

All of the provided values for this spec are described here in the xref:reference-couchbasecluster.adoc[Couchbase Cluster Configuration] documentation.



== Sync Gateway

The Sync Gateway configuration provides defaults for deploying Sync Gateway along with associated services.
The Sync Gateway server is installed when `install.syncGateway` is set to `true`.
When installed, Sync Gateway is automatically connected to Couchbase cluster.

[source,yaml,subs="attributes"]
----
syncGateway:
  name:
  config:
    logging:
      console:
        enabled: true
        log_level: "debug"
        log_keys:
        - "*"
    databases:
      db:
        bucket: default
        users:
          GUEST:
            disabled: false
            admin_channels: ["*"]
        server:
        username:
        password:
        allow_conflicts: false
        revs_limit: 20
        enable_shared_bucket_access: true
        cacert:
  exposeServiceType: ClusterIP
  image:
    repository: couchbase/sync-gateway
    tag: {sgw-version}
  imagePullPolicy: IfNotPresent
  configSecret:
----

IMPORTANT: If you install a bucket with a name other than `default` then you will need to update `databases.db.bucket` accordingly.

=== `exposeServiceType`

The type of service to use for exposing the Sync Gateway server.

_Value rules:_ The `exposeServiceType` value is a string.
This value is optional and defaults to `ClusterIP`.
When specified the value must be either `ClusterIP`, `NOodePort`, or `LoadBalancer`.
When the value is not specified then the exposing service is not created.

=== `configSecret`

A Kubernetes Secret containing values that override `config.databases`
This allows for sync-gateway configurations to be shared across clusters, since the Secret will contain the same configuration information about connecting to a particular Couchbase Cluster.

_Value rules:_ The `configSecret` value is a string
This value is optional.
When specified the content of the Secret will be used to override the values of `config.databases`.

== `coredns`

DNS settings to apply to the Couchbase and Sync Gateway Deployments 

[source,yaml]
----
coredns:
  service:
  searches:
  - default.svc.cluster.local
  - svc.cluster.local
  - cluster.local
----

=== `coredns.service`

The name of a Kubernetes Service resource which exposes Kubernetes DNS.
By default the `kube-dns` service is used, but user may decide to install CoreDNS for xref:concept-couchbase-networking.adoc[Inter-Cluster] Deployments.

_Value rules:_ The `coredns.service` value is a string.
This value is optional.
When specified the value must refer to a Kubernetes Service resource that is capable of providing DNS to the Sync Gateway server.

=== `coredns.searches`

The search domains to use when looking up hostnames

_Value rules:_ The `coredns.searches` value is an optional list of strings.


== Autonomous Operator

The Helm chart deploys the Operator as a Kubernetes https://kubernetes.io/docs/concepts/workloads/controllers/deployment/[Deployment].

[source,yaml,subs="attributes"]
----
couchbaseOperator:
  name: "couchbase-operator"
  image:
    repository: couchbase/operator
    tag: {operator-version}
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  commandArgs:
    pod-create-timeout: 10m
  resources: {}
  nodeSelector: {}
  tolerations: []
----

=== `commandArgs`

This spec allows you to specify command line arguments to pass on to the Operator.

_value rules:_ The `commandArgs` value is a key-value map of arguments that can be used to modify the behavior of the Operator image.
The `-pod-create-timeout:` argument is set to `10m` by default, which means that the Operator will wait 10 minutes for a Couchbase Server Pod to start.
The `-debug:` argument can also be used here, and set to `debug` for more verbose logging.

=== Additional Values
The `couchbaseOperator` parameters are described in the xref:reference-operator-configuration.adoc[Operator Deployment Settings] documentation.


== Admission Controller

[source,yaml,subs="attributes"]
----
admissionController:
  name: "couchbase-admission-controller"
  image:
    repository: couchbase/admission-controller
    tag: {admission-controller-version}
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  verboseLogging: true
----

The Helm chart deploys the admission controller as a Kubernetes https://kubernetes.io/docs/concepts/workloads/controllers/deployment/[Deployment].

[#admissionController-name]
=== `name`

This field specifies the name of the admission controller deployment.

[cols="1",options="header"]
|===
a| _Field Rules:_
a| The `name` field defaults to `couchbase-admission-controller`.
|===

=== `image`

[source,yaml,subs="attributes"]
----
  image:
    repository: couchbase/admission-controller
    tag: {admission-controller-version}
----

The repository and tag to use for pulling the admission controller image.

[cols="1",options="header"]
|===
a| _Field Rules:_
a| The `image.repository` value can refer to any repository.
The `image.tag` field can refer to any version of the admission controller image in the repository.
|===

=== `imagePullPolicy`

The policy for pulling images from the repository onto hosts.

[cols="1",options="header"]
|===
a| _Field Rules:_
a| The `imagePullPolicy` value defaults to `IfNotPresent`, which means that images are only pulled if they're not present on the Kubernetes node.
Values allowed are `Always`, `IfNotPresent`, and `Never`.
|===

=== `imagePullSecrets`

An optional list referencing secrets to use for pulling the image.

[cols="1",options="header"]
|===
a| _Field Rules:_
a| The `imagePullSecrets` value is a list which is not set by default.
Refer to the Operator documentation about xref:install-openshift.adoc#create-an-imagepullsecret[creating pull secrets].
When using the Helm CLI to override pull secrets, the list should be denoted as a comma delimited list within curly braces:

[source,console]
----
helm install --set admissionController.imagePullSecrets={pullsecret1,pullsecret2} couchbase/couchbase-operator
----
|===

=== `verboseLogging`

Determines whether the admission controller should log all of its validation notices within the console.

[cols="1",options="header"]
|===
a| _Field Rules:_
a| The `verboseLogging` field is a boolean value that is set to `false` by default, which means only validation errors are logged within the pod's console.
|===

== Admission Service

[source,yaml]
----
  admissionService:
    name:
    port: 443
    targetPort: 8443
----

The admission service is used by the webhooks to access the admission operator.
Certificates are auto-generated for this service whenever this object is enabled.
The admission service is always created when `install.admissionController` is set to `true`.


[#admissionService-name]
=== `name`

Name of the admission service.

[#admissionService-port]
=== `port`

Port exposed by the admission service to the validation webhooks.

[#admissionService-targetPort]
=== `targetPort`

Port of the admission controller targeted by the admission Service.


[cols="1",options="header"]
|===
a| _Field Rules:_
a| The `name` value defaults to whatever is specified in `<<admissionController-name,admissionController.name>>`.
|===

[#admissionCA]
== Admission Controller Certificate Authority

[source,yaml]
----
admissionCA:
  cert:
  key:
  expiration: 365
----

The `admissionCA` spec specifies the CA certificates that are applied to validating webhooks.

By default, the CA certificate and key is auto-generated.
The following example shows how to use a self-signed certificate:

. *Create Certificates*
+
Use OpenSSL to create `myCA.key` and `myCA.pem` in your current directory:
+
[source,console]
----
openssl genrsa -out myCA.key 2048
openssl req -x509 -new -nodes -key myCA.key -sha256 -days 1825 -outform PEM -out myCA.pem
----

. *Install the chart with certificates*
+
Use `--set-file` to import the files from your current directory:
+
[source,console]
----
helm install  --set-file admissionCA.cert=myCA.pem \
              --set-file admissionCA.key=myCA.key \
              couchbase/couchbase-operator
----

Refer to the xref:tls.adoc[TLS documentation] for manually creating certificates and keys that can be used to override the auto-generated secret.


=== `cert`

The PEM format CA certificate.

[cols="1",options="header"]
|===
a| _Field Rules:_
a| The `cert` value defaults to an auto-generated CA certificate.
|===

=== `key`

The PEM format CA key.

[cols="1",options="header"]
|===
a| _Field Rules:_
a| The `key` value defaults to an auto-generated CA key.
|===

=== `expiration`

Expiration of CA certificate in days.

[cols="1",options="header"]
|===
a| _Field Rules:_
a| The `expiration` value defaults to 365 days.
|===

== Admission Controller Secret

[source,yaml]
----
admissionSecret:
  name:
  cert:
  key:
----

The `admissionSecret` spec specifies the secret for the admission controller to use for validating cluster specs securely over the admission service.

To use a custom secret, you will also need to provide the CA that was used to generate the certificates and keys within the secret.
The following example shows how to use a self-signed CA and client:

. *Create CA and client certificates*
+
Use EasyRSA CA and signed client cert with DNS `cb-example.default.svc`
+
[source,console]
----
./easyrsa build-ca nopasss
./easyrsa --subject-alt-name=DNS:cb-example.default.svc build-server-full admission-controller nopas
----

. *Install chart with client certificates*
+
Install chart with custom certs and be sure to set `admissionService.name` to DNS name.
+
This example also sets `--namespace default` option since this is also included in the DNS of cert we created:
+
[source,console]
----
helm install  --namespace ci-testcluster \
              --set admissionService.name=ci-testcluster \
              --set-file admissionCA.cert=/home/ubuntu/easy-rsa/easyrsa3/pki/ca.crt \
              --set-file admissionCA.key=/home/ubuntu/easy-rsa/easyrsa3/pki/private/ca.key \
              --set-file admissionSecret.cert=/home/ubuntu/easy-rsa/easyrsa3/pki/issued/admission-controller.crt \
              --set-file admissionSecret.key=/home/ubuntu/easy-rsa/easyrsa3/pki/private/admission-controller.key \
              couchbase/couchbase-operator
----


[#admissionSecret-name]
=== `name`

This value is the name of the secret that contains the certificates for the admission operator.
This value must refer to a native Kubernetes secret which contains values for TLS `cert` and `key`.

[cols="1",options="header"]
|===
a| _Field Rules:_
a| The `admissionSecret.name` value defaults to the name of the admission controller deployment.
|===

=== `cert`

PEM format certificate to use as the admission controller's public key during validation.

[cols="1",options="header"]
|===
a| _Field Rules:_
a| The `admissionSecret.cert` value is auto-generated by default from `<<admissionCA,admissionCA>>`.
|===

=== `key`

PEM format key to use as the admission controllers private key during validation.

[cols="1",options="header"]
|===
a| _Field Rules:_
a| The `admissionSecret.key` value is auto-generated by default from `<<admissionCA,admissionCA>>`.
|===
