= Couchbase Operator Helm Chart Configuration

[abstract]
The official Helm chart for the Couchbase Autonomous Operator comes with a default configuration that can be customized to fit your deployment needs.

This page outlines the design and usage of the official Helm chart for deploying the Couchbase Autonomous Operator and its admission controller.
In particular, this page describes the contents of https://github.com/couchbase-partners/helm-charts/blob/master/couchbase-operator/values.yaml[values.yaml], which contains the Couchbase Operator Chart's default values.
Each of the deployed resources is listed and described, along with any available parameterization.

For instructions on how to install the chart, including how to customize the chart's values, see xref:helm-setup-guide.adoc[Helm Guide for the Couchbase Operator].

.All available configuration parameters for the Operator Chart
[source,yaml]
----
  # Default values for couchbase-operator chart.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  # Override default naming of chart resources
  nameOverride: ""

  # Install Default RBAC roles and bindings
  rbac:
    create: true
    apiVersion: v1beta1
    # clusterRoleAccess determines if roles are created with cluster-wide access
    clusterRoleAccess: true

  # Select what to deploy
  deployments:
    # couchbaseOperator is the couchbase-operator deployment
    couchbaseOperator: true
    # admissionController enforces validation
    admissionController: true

  # Service account names and whether to create them
  serviceAccount:
    couchbaseOperator:
      create: true
      name:
    admissionController:
      create: true
      name:

  # couchbaseOperator is the controller for couchbase cluster
  couchbaseOperator:
    # name of the couchbase operator
    name: "couchbase-operator"
    # image config
    image:
      repository: couchbase/operator
      tag: 1.1.0
    imagePullPolicy: IfNotPresent
    # imagePullSecrets is an optional list of references to secrets  to use for pulling images
    imagePullSecrets: []
    # name of the serviceAccount to use when running operator
    # defaults to serviceAccount.couchbaseOperator.name
    serviceAccountName:
    # additional command arguments will be translated to `--key=value`
    commandArgs:
      # Set to false if you are installing the CRD manually
      create-crd: true
    # readinessProbe marks pod as ready when readiness port (8080) responds
    readinessProbe:
      # initialDelaySeconds is a delay before readiness probe is initiated
      initialDelaySeconds: 3
      # periodSeconds decides how often to perform the probe
      periodSeconds: 3
      # failureThreshold sets Pod status to failure when threshold is reached
      failureThreshold: 19
      # port exposed to check readiness
      port: 8080
    # resources of couchbase-operator
    resources:
      cpu: 100m
      memory: 128Mi
    # nodeSelector for couchbase-operator pod assignment
    # Ref: https://kubernetes.io/docs/user-guide/node-selection/
    nodeSelector: {}
    # tolerations of pod match nodes with corresponding taints
    tolerations: []


  # admissionController is the controller for couchbase admission controller
  # name is derived from chart
  admissionController:
    name: "couchbase-admission-controller"
    image:
      repository: couchbase/couchbase-operator-admission
      tag: v1
    imagePullPolicy: IfNotPresent
    # imagePullSecrets is an optional list of references to secrets  to use for pulling images
    imagePullSecrets: []
    verboseLogging: true
    # name of the serviceAccount to use when running admission controller
    # defaults to serviceAccount.admissionController.name
    serviceAccountName:

  # admissionService exposes validation to cluster. This service
  # is over https and certs are auto-generated based on serviceName.
  # Use nameOverride when manually creating service, or disable altogether.
  admissionService:
    # create determines if service is created
    create: true
    # name of the service (auto-generated)
    name: ""
    # port service exposes
    port: 443

  # admissionTLS can be used to override the Certs that will be used
  # to sign the keys used by the admsission operator.
  admissionTLS:
    # disable if manually creating certs, but be sure to specify name of secret.
    create: true
    # Expiry time of CA in days for generated certs
    expiration: 365
    # PEM format ca certificate for use by validation webhook (auto-generated)
    # override via --set-file
    webhookCa: ""
    # secret is a kubrnetes Secret with certs mounted within the admission controller.
    secret:
      # name of the secret (auto-generated)
      name: ""
      # PEM format certificate (auto-generated)
      # override via --set-file
      tlsCert: ""
      # PEM format certificate (auto-generated)
      # override via --set-file
      tlsKey: ""

----

== About Resource Names

All resources/objects created by the Couchbase Operator Chart adhere to the following naming scheme: `<release-name>-<chart-setting>`.

* `<release-name>`
 ** This is autogenerated by Helm unless you specify your own name during chart installation.
* `<chart-setting>`
 ** This is the name that is specified by the chart for that particular resource.
 ** If the resource is created for the _Operator_, then `<chart-setting>` will be whatever is specified in <<couchbaseOperator-name,couchbaseOperator.name>>.
 ** If the resource is created for the _admission controller_, then `<chart-setting>` will be whatever is specified in <<admissionController-name,admissionController.name>>.

The following table includes some examples of resources that the chart creates, along with their names:

.Examples of Helm Resource Names
[#table-operator-helm-names,cols="1,2,2",options="header"]
|===
| Resource/Object | Name | Example

| Helm release
a| `<release-name>-couchbaseOperator.name`
| intent-tortoise-couchbase-operator

| Operator deployment
a| `<release-name>-couchbaseOperator.name`
| intent-tortoise-couchbase-operator

| Admission controller service account
a| `<release-name>-admissionController.name`
| intent-tortoise-couchbase-admission-controller
|===

[NOTE]
====
When you install a chart, Helm autogenerates a name for the release (usually a unique set of dictionary words).
Helm prepends this name to all of the objects and resources that the chart creates (see `<release-name>` above).

If you plan to use Helm to install multiple instances of the Operator, you should consider giving each release a unique name to help you more easily identify the resources that are associated with each release.
You can specify a name for the release during chart installation by using the `--name` flag:

[source,console]
----
helm install --name <unique-name> couchbase/couchbase-operator
----
====

=== Specifying Your Own Resources

The chart allows you to override certain resources (such as service accounts and TLS certificates) with ones that you've already created.
In this case, the names of the resources are determined by you and not the chart, and therefore do not adhere to the naming scheme described in the previous section.
Just make sure to appropriately specify those resources when you install the chart.

== rbac

The Couchbase Operator Chart installs RBAC roles for both the Operator and admission controller.
Helm’s Tiller service must have the appropriate permissions to create the required level of RBAC roles to support your deployment.
Refer to the xref:helm-setup-guide.adoc#install-tiller[Tiller installation instructions] to be sure that you've set up Helm to support your deployment's RBAC requirements.

The Couchbase Operator Chart exposes the following parameters for customizing RBAC:

[source,yaml]
----
rbac:
  create: true
  apiVersion: v1beta1
  clusterRoleAccess: true
----

[#rbac-create]
=== create

This field specifies whether or not RBAC rules will be created.
This parameter should generally be set to `true`, since it's recommended that you let the chart configure RBAC automatically.
However, you can set this parameter to `false` if you've already configured RBAC rules for the Operator and admission controller.

NOTE: If `create` is set to `false`, then you'll need to create https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/[service accounts] for both the Operator and the admission controller.
You would then need to specify those service account names in `couchbaseOperator.serviceAccountName` and `admission-controller.serviceAccountName`, respectively.

____
_Field rules:_ The `rbac.create` field defaults to `true` if not specified.
____

=== apiVersion

This field specifies the Kubernetes API version to use for creating RBAC resources.

____
_Field rules:_ The `rbac.apiVersion` field defaults to `v1beta1` if not specified.
Supported values follow Kubernetes https://kubernetes.io/docs/concepts/overview/kubernetes-api/#api-versioning[api versioning].
____

=== clusterRoleAccess

This field specifies whether or not the Operator should be given access to resources in the entire Kubernetes cluster, or restricted to just its namespace.

Setting `clusterRoleAccess` to `false` is recommended for production.

NOTE: When `clusterRoleAccess` is set to `false`, the Tiller will not be able to create the CustomResourceDefinition (CRD) type because the CRD is a cluster-wide resource in Kubernetes.
Therefore, you would need to xref:helm-setup-guide.adoc#deploy-production[manually install the CRD].

____
_Field rules:_  The `rbac.clusterRoleAccess` value defaults to `true` if not specified.
When set to `true`, the service account of the Operator gets bound to a https://kubernetes.io/docs/reference/access-authn-authz/rbac/#default-roles-and-role-bindings[cluster role].
When set to `false`, the service account is bound to a standalone role.
____

== serviceAccount

The Couchbase Operator Chart deploys Kubernetes https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/[service accounts] for both the Operator and the admission controller.
(Service accounts are required for the Operator and admission controller to exist.)

Everything under the `serviceAccount` spec is ignored when <<rbac-create,rbac.create>> is set to `false`.

[source,yaml]
----
serviceAccount:
  couchbaseOperator:
    create: true
    name:
  admissionController:
    create: true
    name:
----

=== couchbaseOperator.create

This field determines whether the chart will create a service account for the Operator.

____
_Field rules:_ The `serviceAccount.couchbaseOperator.create` field defaults to `true` if not specified.
When set to `false`, you'll need to manually create a service account and provide the name of that service account in <<couchbaseOperator-serviceAccount,couchbaseOperator.serviceAccount>>.
____

=== couchbaseOperator.name

This field specifies a custom name for the service account that gets created for the Operator.

____
_Field rules:_  The `serviceAccount.couchbaseOperator.name` field defaults to value in <<couchbaseOperator-name,couchbaseOperator.name>>.
____

=== admissionController.create

This field determines whether the chart will create a service account for the admission controller.

____
_Field rules:_ The `serviceAccount.admissionController.create` field defaults to `true` if not specified.
When set to `false`, you will need to manually create a service account and provide the name of that service account in `serviceAccount.admissionController.name`.
____

=== admissionController.name

This field specifies the name of the service account for the admission controller.

____
_Field rules:_ The `serviceAccount.admissionController.name` field defaults to the name given to the Helm chart if nothing is specified.
You must provide the name of a preexisting service account if <<admissionController-create,admissionController.create>> is set to `false`.
____

== Couchbase Operator

The Helm chart deploys the Operator as a Kubernetes https://kubernetes.io/docs/concepts/workloads/controllers/deployment/[Deployment].

[source,yaml]
----
couchbaseOperator:
  name: "couchbase-operator"
  serviceAccountName: ""
  image:
    repository: couchbase/operator
    tag: 1.1.0
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  commandArgs:
    create-crd: true
  readinessProbe:
    initialDelaySeconds: 3
    periodSeconds: 3
    failureThreshold: 19
    port: 8080
  resources:
    cpu: 100m
    memory: 128Mi
  nodeSelector: {}
  tolerations: []
----

[#couchbaseOperator-name]
=== name

This field specifies name of the Operator deployment.

____
_Field rules:_ The `name` field defaults to the name of the Helm chart.
____

[#couchbaseOperator-serviceAccount]
=== serviceAccount

This field specifies the name of the Kubernetes service account to use for the Operator deployment.
When using custom RBAC roles, this field should be set to a preexisting ServiceAccount.

____
_Field rules:_  The `couchbaseOperator.serviceAccountName` value defaults to the value of `serviceAccount.couchbaseOperator.name`.


=== image

The repository and tag to use for pulling the operater image.
[source, yaml]
----
  image:
    repository: couchbase/operator
    tag: 1.1.0
----

_Value rules:_ The `couchbaseOperator.image` values can refer to any repository and tag of a released version of the couchbase operator.

=== imagePullPolicy

The Policy for pulling images from repo onto hosts

_Value rules:_ The `couchbaseOperator.imagePullPolicy` value defaults to `IfNotPresent` which means that images are only pulled if they are not present on the kubernetes node.
Values allowed are `Always`, `IfNotPresent`, and `Never.`

=== imagePullSecrets

An optional list referencing secrets to use for pulling image

_Value rules:_ The `couchbaseOperator.imagePullSecrets` value is a list which is not set by default.
Refer to the couchbase operator documentation about https://docs.couchbase.com/operator/1.1/install-openshift.html#create-an-imagepullsecret[creating pull secrets].
When using the helm cli to override pull secrets, the list should be denoted as a comma delimited list within curly braces:
[source,console]
----
helm install --set couchbaseOperator.imagePullSecrets={pullsecret1,pullsecret2} couchbase/couchbase-operator
----


=== commandArgs

The map of command line arguments to pass in to the operator.

_Value rules:_ The `couchbaseOperator.commandArgs` value is a key-value map of arguments that can be used to modify the behavior of the oprator image.
By default the value is set to `-create-crd: true` which means that the operator will attempt to create the CRD if it does not already exist.

WARNING: If you have not given the operator cluster wide privileges then `-create-crd: true` will fail if you have not manually deployed the CRD.
Refer to the quick start section about <<production-deployment, production deployments>> about manually creating the CRD.


=== readinessProbe

Configuration of the readiness probe used by kubernetes to determine with the operator Pod is Ready.

[source, yaml]
----
couchbaseOperator:
  ...
  readinessProbe:
    initialDelaySeconds: 3
    periodSeconds: 3
    failureThreshold: 19
----


_Value rules:_  Refer to https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes[configuring probes] of the kubernetes documentation for more information configuring the `couchbaseOperator.readinessProbe` values.


=== resources

Resources for cpu and memory of the Pod

[source, yaml]
----
  resources:
    cpu: 100m
    memory: 128Mi
----


_Value rules:_ Refer to https://kubernetes.io/docs/tasks/configure-pod-container/assign-memory-resource/#specify-a-memory-request-and-a-memory-limit[specify request limits] of the kubernetes documentation for more information configuring the `couchbaseOperator.resources`



== Admission Controller Deployment

The helm chart deploys the admission controller as a Deployment type.
The following chart values can be customized for the admission deployment:

[source,yaml]
----
admissionController:
  name: "couchbase-admission-controller"
  serviceAccountName: ""
  image:
    repository: couchbase/couchbase-operator-admission
    tag: v1
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  verboseLogging: true
----

[#admissionController-name]
=== name

The name of the admission controller deployment.

_Value rules:_ The `admissionController.name` value is a string and defaults to the name of the helm chart.

=== serviceAccount

The name of the service account to use for the admission controller deployment.
When using custom RBAC roles, this value should be overridden and set to a pre-existing ServiceAccount.

_Value rules:_ The `admissionController.serviceAccountName` value defaults to the value of `serviceAccount.admissionController.name`.


=== image

The repository and tag to use for pulling the admission controller image.
[source, yaml]
----
  image:
    repository: couchbase/couchbase-operator-admission
    tag: v1
----

_Value rules:_ The `admissionController.image` values can refer to any repository and tag of a released version of the couchbase operator.

=== imagePullPolicy

The Policy for pulling images from repo onto hosts

_Value rules:_ The `admissionController.imagePullPolicy` value defaults to `IfNotPresent` which means that images are only pulled if they are not present on the kubernetes node.
Values allowed are `Always`, `IfNotPresent`, and `Never.`

=== imagePullSecrets

An optional list referencing secrets to use for pulling image

_Value rules:_ The `admissionController.imagePullSecrets` value is a list which is not set by default.
Refer to the couchbase operator documentation about https://docs.couchbase.com/operator/1.1/install-openshift.html#create-an-imagepullsecret[creating pull secrets].


=== verboseLogging

Value to determine whether the admission controller should logs all of its validation notices within the console.

_Value rules:_ The `admissionController.verboseLogging` is a boolean which is set to `true` by default.
When set to `false` only validation errors are logged within the Pod's console.


== Admission Service

The admission service is used by the webhooks to access the admission operator.
Certs are auto-generated for this service whenever this object is enabled.

[source,yaml]
----
admissionService:
  create: true
  name: ""
----

=== create

Value to determine if the admission service should be crated.
To create a service with your own certs then set `admissionSrevice.create` to `false` and also provide the name of your service in `admissionService.name`.


_Value rules:_ The `admissionService.create` is a boolean which is set to `true`.

=== name

Name of the operator deployment.

_Value rules:_ The `admissionService.name` is a string is set to name of the admission controller deployment.

== Admission TLS

Admission TLS specifies the certs which are are applied to both the admission service and validating webhooks.

[source,yaml]
----
admissionTLS:
  create: true
  expiration: 365
  webhookCa: ""
  secret:
    name: ""
    tlsCert: ""
    tlsKey: ""
----


By default all of the certificates are auto-generated.
To use custom secrets you will also need to provide the CA used to generate the certs and keys within the secret.
The following example shows how to use custom secrets:
[console,yaml]
----
helm install  --set admissionTLS.create=false \
              --set admissionTLS.secret.name= ”my-secret” \
              --set-file admissionTLS.webhooksCA=/home/ubuntu/easy-rsa/easyrsa3/pki/ca.crt \
        helm/couchbase-operator
----

Refer to https://docs.couchbase.com/operator/1.1/tls.html[Configuring TLS documentation] for manually creating certificates and keys which can be used to override the auto-generated secret.

=== create

This value determines whether the chart should create the Secret used by the admission controller.
When set to `false`, you will need to provide values for `webhookCa`, `tlsCert`, and `tlsKey` to use as overrides.


_Value rules:_ The `admissionTLS.create` is a boolean which defaults to `true`.


=== expiration

Expiration of CA in days

_Value rules:_ The `admissionTLS.expiration` defaults to 365 days.

=== webhookCa

The PEM format CA cert

_Value rules:_ The `admissionTLS.webhookCa` value defaults to an auto-generated CA cert.


=== secret.name

Name of secret with certs for admission operator.
This value must refer to a native kubernetes Secret which contains values for `tlsCert` and `tlsKey`.

_Value rules:_ The `admissionTLS.secret.name` value defaults to the name of the admission controller deployment.


=== secret.tlsCert

PEM format cert to use as the admission controllers public key during validation.

_Value rules:_ The `admissionTLS.secret.tlsCert` value is auto-generated by default from `admissionTLS.webhookCa`.

=== secret.tlsKey

PEM format key to use as the admission controllers private key during validation.

_Value rules:_ The `admissionTLS.secret.tlsKey` value is auto-generated by default from `admissionTLS.webhookCa`.
