= Managing a Sync Gateway Cluster

== Troubleshooting and Log Collection

This section provides information about how to diagnose and troubleshoot problems with the Sync Gateway deployment.
When troubleshooting, it is important to rule out Kubernetes itself as the root cause of the problem you are experiencing.
See the https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/[Kubernetes Troubleshooting guide] for information about debugging applications within a Kubernetes cluster.
For troubleshooting a Couchbase Server deployment using the Couchbase operator, please refer to our xref:operator::logs-troubleshooting.adoc[guide].

=== Prerequisites

* The location of the Sync Gateway logs within a pod is specified with the "logging" key in the Sync Gateway config file (see xref:logging.adoc#log-rotation-configuration[logging guide])
* To view or fetch the logs from a Sync Gateway pod, you must first identify the Sync Gateway pods in your deployment using the following command.
+
[source,console]
----
kubectl get pods
----
Your response will include a list of sync gateway pods in your deployment

===  Viewing Logs in Console

You can use kubectl to view logs for a specific pod using following command.
This command will output logs to the console.
[source,console]
----
kubectl logs -f <pod_id>
----

== Using SGCollect Info
The link:https://docs.couchbase.com/sync-gateway/2.7/sgcollect-info.html[SGCollect Info] is a command line utility with detailed statistics for a specific Sync Gateway node. This tool must be run on each node individually. The sgcollect-info tool is bundled as part of the Sync Gateway docker image. YOu have two options on how to retrieve the logs from the Sync Gateway pods.

=== Option 1
You can trigger the execution of the sgcollect-info tool on each individual pod using the link[https://docs.couchbase.com/sync-gateway/2.7/admin-rest-api.html#/server/post__sgcollect_info[_sgcollect_info]] REST endpoint.

In order to do this, you would need access to the admin port. As recommended, the admin port is expected to only be accessible over localhost. 

==== Identify list of Sync Gateway Pods
Run the following command to get list of sync gateway pods. Repeat the steps in the <<Triggering sgcollect_info>> section for every pod listed in the output. 
[source,bash]
----
kubectl get pods -o=name | grep sync-gateway
----

==== Set up Port Forwarding
Run following command to set up port forwarding from your local machine to admin port on the Sync Gateway pod. This command assumes the default admin port of 4985. If you have configured your sync gateway to use an alternative admin port, replace that in the command below

[source,bash]
----
kubectl port-forward <pod_id> 4985:4985
----


==== Triggering sgcollect_info
Trigger the execution of the `sgcollect-info` tool on the Sync Gateway pod using the link:https://docs.couchbase.com/sync-gateway/2.7/admin-rest-api.html#/server/post__sgcollect_info[POST _sgcollect_info] REST endpoint. This is an example of the command. 

NOTE: The example below outputs the logs to local directory. Instead, Enterprise customers can use this endpoint to automatically upload it to support servers.

[source,bash]
----
curl -X POST \
  http://localhost:4985/_sgcollect_info \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "output_dir": "/home/sync_gateway/logs",
  "upload": false
}’
----



==== Monitor the status of the log collection 
Use the link:https://docs.couchbase.com/sync-gateway/2.7/admin-rest-api.html#/server/get__sgcollect_info[GET _sgcollect_info] REST endpoint to monior the status of the log collection. This is an example of the command. Wait until the status reported back is not `running`

[source,bash]
----
curl -X GET \
  http://localhost:4985/_sgcollect_info \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json'
----

==== Copy Log Files
This is an optional step and is only required if you had opted not to directly to the servers. Once `sgcollect-info` has completed, you can copy the output .zip file from each of the pods to your local machine. Note that doing a `kubectl cp` is not as secure as directly uploading the logs to the servers from the pods as discussed in step <<Triggering sgcollect_info>>

[source,bash]
----
  kubectl cp <pod-id>:/home/sync_gateway/logs/* .
----


=== Option 2
This option is less secure than the option discussed in the previous section as it uses `kubectl exec` to trigger the execution of
xref:sgcollect-info.adoc[SGCollect Info] for a specific Sync Gateway node.
This tool must be run on each Sync Gateway node individually.
The sgcollect-info tool is bundled as part of the Sync Gateway docker image.

==== Collecting logs on a pod

To collect logs on a specific pod, run sgcollect_info using the kubectl https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#exec[exec command].
The following command runs sgcollect_info on the specified pod and outputs the results to an *out.zip* file.
[source,console]
----
kubectl exec <pod_id> -- /opt/couchbase-sync-gateway/tools/sgcollect_info /tmp/out.zip
----

==== Coping log output from pod

To copy the sgcollect_info generated output from the pod, use the kubectl https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#cp[cp command].
[source,console]
----
kubectl cp <pod_id>:/tmp/out.zip .
----

==== Convenience Scripts

===== Collecting  sgcollect_info logs from all pods

The following script runs sgcollect_info on all the pods and to copy the zipped files over to the current folder.
//This script is available as `collect_logs_sgw_pods.sh `
[source,console]
----
#! /bin/sh
OUTFOLDER=${1:-/tmp}
for pod in `kubectl get pods -o=name | grep sync-gateway | sed "s/^.\{4\}//"`
do
    LOGFILE=$OUTFOLDER/$pod'_sgcollect_info_out.zip'
    echo "Running sgcollect_info to generate $LOGFILE"
    kubectl exec $pod -- /opt/couchbase-sync-gateway/tools/sgcollect_info $LOGFILE
    echo "copying $pod:$LOGFILE to current folder"
    kubectl cp $pod:$LOGFILE .
done
----

== Rolling Upgrades of Sync Gateway Nodes

Since we use a deployment controller, we can do a rolling upgrade of the Sync Gateway nodes in the cluster and the load balancer will automatically take care of redirecting the traffic to the remaining nodes.

Note that if you have configured your deployment to have a single Sync Gateway import node, then you will experience some latency in processing write requests until the import node comes back up again.

. For example, if you want to upgrade the version of the Sync Gateway, you can update the corresponding deployment config file and re-apply that to the cluster
+
[source,console]
----
kubectl apply -f sgw-deployment-upgrade.yaml
----
. You can verify the status of the rollout as follows
+
[source,console]
----
kubectl rollout status deployment sync-gateway
----
The deployment controller will ensure that at least one replica is available to serve the incoming requests while the other replicas are being upgraded.
The load balancer will automatically redirect all requests to the remaining nodes.
+
If the upgrade fails for any reason, you can rollback or undo the rollout with the following command.
+
[source,console]
----
kubectl rollout undo  deployment sync-gateway
----

== Upgrading the Kubernetes Cluster

You can refer to the following xref:operator::upgrading-kubernetes.adoc[Couchbase Operator guide] for a discussion about upgrading the Kubernetes cluster on which your Couchbase deployment resides.
