= Configure Couchbase Cluster Auto-scaling
include::partial$constants.adoc[]
:HorizontalPodAutoscaler: pass:q[https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#horizontalpodautoscaler-v2beta2-autoscaling[`HorizontalPodAutoscaler`^]]

[abstract]
Configure Couchbase clusters to automatically scale based on observed usage metrics.

== Overview

The Autonomous Operator supports xref:concept-mds.adoc[Multi-Dimensional Scaling] through independently-configurable server classes, which are xref:howto-couchbase-scale.adoc[manually scalable] by default.
However, the Autonomous Operator optionally supports the automatic scaling of Couchbase clusters through an integration with the https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/[Horizontal Pod Autoscaler (HPA)^].

The sections on this page describe how to enable and configure auto-scaling for Couchbase clusters managed by the Autonomous Operator.
For a conceptual description of this feature, please refer to xref:concept-couchbase-autoscaling.adoc[].

== Preparing for Auto-scaling

Metrics play the most important role in Couchbase cluster auto-scaling.
Metrics provide the means for the Horizontal Pod Autoscaler to measure cluster performance and respond accordingly when target thresholds are crossed.

Auto-scaling can be configured to use _resource metrics_ or _Couchbase metrics_.
Resource metrics include pod CPU and memory, whereas Couchbase metrics can be stats like bucket memory utilization and query latency.
Refer to xref:concept-couchbase-autoscaling-best-practices.adoc[] for additional guidance on how various metrics can be used as a measure of cluster performance.

The Horizontal Pod Autoscaler can only monitor metrics through the Kubernetes API, therefore metrics affecting the Couchbase cluster must be exposed within the Kubernetes cluster before auto-scaling can be configured.
Refer to xref:concept-couchbase-autoscaling.adoc#about-exposed-metrics[About Exposed Metrics] in the concept documentation for more information about how metrics can be exposed for the purposes of auto-scaling.
//The tutorial xref:tutorial-autoscale-data.adoc[] also has a good example of using Helm for exposing Couchbase metrics.

[[enabling-auto-scaling]]
== Enabling Auto-scaling

Enabling auto-scaling for a particular Couchbase cluster starts with modifying the relevant xref:resource/couchbasecluster.adoc[`CouchbaseCluster`] resource.

The required configuration parameters for enabling log forwarding are described in the example below.
(The Autonomous Operator will set the default values for any fields that are not specified by the user.)

.Basic xref:resource/couchbasecluster.adoc[`CouchbaseCluster`] Auto-Scaling Parameters
[source,yaml,subs="attributes,verbatim"]
----
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-example
spec:
  servers:
  - name: data
    size: 3
    services:
    - data
  - name: index
    autoscaleEnabled: true # <.>
    size: 2
    services:
    - index
  - name: query
    autoscaleEnabled: true # <.>
    size: 2
    services:
    - query
  autoscaleStabilizationPeriod: 600s # <.>
----

<.> xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-servers-autoscaleenabled[`couchbaseclusters.spec.servers.autoscaleEnabled`]: Setting this field to `true` triggers the Autonomous Operator to create a xref:resource/couchbaseautoscaler.adoc[`CouchbaseAutoscaler`] custom resource for the relevant server class.
In this example, a xref:resource/couchbaseautoscaler.adoc[`CouchbaseAutoscaler`] resource will be created for the `index` server class.
Refer to xref:concept-couchbase-autoscaling.adoc#about-the-couchbase-autoscaler[About the Couchbase Autoscaler] for a conceptual overview of the role the xref:resource/couchbaseautoscaler.adoc[`CouchbaseAutoscaler`] custom resource plays in auto-scaling.

<.> In this example, a xref:resource/couchbaseautoscaler.adoc[`CouchbaseAutoscaler`] resource will also be created for the `query` server class.

<.> xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-autoscalestabilizationperiod[`couchbaseclusters.spec.autoscaleStabilizationPeriod`]: This field defines the xref:concept-couchbase-autoscaling.adoc#couchbase-stabilization-period[_Couchbase Stabilization Period_], which is an internal safety mechanism provided by the Autonomous Operator that is meant to help prevent over-scaling caused by metrics instability during rebalance.
The value specified in this field determines how long {HorizontalPodAutoscaler} resources will remain in https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#implicit-maintenance-mode-deactivation[_maintenance mode_^] after the cluster finishes rebalancing.
+
In this example, the stabilization period has been set to `600s`, which means that the Horizontal Pod Autoscaler will not restart monitoring until 10 minutes after the previous rebalance has completed.
Refer to xref:concept-couchbase-autoscaling-best-practices.adoc[] for additional guidance on setting this value in production environments.

After deploying the xref:resource/couchbasecluster.adoc[`CouchbaseCluster`] resource specification, the Autonomous Operator will create a xref:resource/couchbaseautoscaler.adoc[`CouchbaseAutoscaler`] resource for each server class configuration that has xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-servers-autoscaleenabled[`couchbaseclusters.spec.servers.autoscaleEnabled`] set to `true`.

IMPORTANT: Enabling auto-scaling for a particular server class configuration *does not* immediately subject the cluster to being auto-scaled.
The xref:resource/couchbaseautoscaler.adoc[`CouchbaseAutoscaler`] resource simply acts as an endpoint for the {HorizontalPodAutoscaler} resource to access the pods that are selected for auto-scaling.
The xref:resource/couchbaseautoscaler.adoc[`CouchbaseAutoscaler`] resource is only activated when <<creating-a-horizontalpodautoscaler-resource,referenced>> by a {HorizontalPodAutoscaler} resource.

=== Verifying Creation of `CouchbaseAutoscaler` Resources

The following command can be used to verify that the xref:resource/couchbaseautoscaler.adoc[`CouchbaseAutoscaler`] custom resources exist and match the size of their associated server class configurations:

[source,console]
----
$ kubectl get couchbaseautoscalers
----
----
NAME                               SIZE   SERVERS
index.cb-example                   2      index <.> <.>
query.cb-example                   2      query
----

<.> `NAME`: Each xref:resource/couchbaseautoscaler.adoc[`CouchbaseAutoscaler`] resource is named using the format `_<server-class>_._<couchbase-cluster>_`.
The name is important as it must be referenced when <<creating-a-horizontalpodautoscaler-resource,creating the `HorizontalPodAutoscaler` resource>> in order link the two resources together.

<.> `SIZE`: This is the current number of Couchbase nodes that the Autonomous Operator is maintaining for the `index` server class.
The Autonomous Operator keeps the size of a xref:resource/couchbaseautoscaler.adoc[`CouchbaseAutoscaler`] resource in sync with the size of its associated server class configuration.

[IMPORTANT]
====
xref:resource/couchbaseautoscaler.adoc[`CouchbaseAutoscaler`] custom resources are fully managed by the Autonomous Operator and should not be manually created, modified, or deleted by the user.
If one is manually deleted, the Autonomous Operator will re-create it.
However, it is possible to edit the xref:resource/couchbaseautoscaler.adoc[`CouchbaseAutoscaler`] (refer to <<scale-subresource>> below).

A xref:resource/couchbaseautoscaler.adoc[`CouchbaseAutoscaler`] resource only gets deleted by the Autonomous Operator when <<disabling-auto-scaling,auto-scaling is disabled>> for the associated server class, or if the associated xref:resource/couchbasecluster.adoc[`CouchbaseCluster`] resource is deleted altogether.
====

[[creating-a-horizontalpodautoscaler-resource]]
== Creating a `HorizontalPodAutoscaler` Resource

The Autonomous Operator relies on the Kubernetes https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/[Horizontal Pod Autoscaler (HPA)^] to provide auto-scaling capabilities.
The Horizontal Pod Autoscaler is configured via a {HorizontalPodAutoscaler} resource, which is the primary interface by which auto-scaling is configured.
Unlike the xref:resource/couchbaseautoscaler.adoc[`CouchbaseAutoscaler`] custom resource created by the Autonomous Operator, the {HorizontalPodAutoscaler} resource is created and managed by the user.

The following configuration represents an example to scale the server class from <<enabling-auto-scaling>>.

[source,yaml,subs="attributes,verbatim"]
----
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: query-hpa
spec:
  scaleTargetRef: # <.>
    apiVersion: couchbase.com/v2
    kind: CouchbaseAutoscaler
    name: query.cb-example
  behavior: # <.>
    scaleUp:
      policies: # <.>
      - type: Pods
        value: 1
        periodSeconds: 15
      stabilizationWindowSeconds: 30 # <.>
    scaleDown:
      stabilizationWindowSeconds: 300
  minReplicas: 2 # <.>
  maxReplicas: 6
  metrics: # <.>
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
----

<.> The `spec.scaleTargetRef` section must be configured to reference the relevant xref:resource/couchbaseautoscaler.adoc[`CouchbaseAutoscaler`] resource.
+
--
* `apiVersion`: This field must be set to be set to `couchbase.com/v2`.

* `kind`: This field must be set to `CouchbaseAutoscaler`.

* `name`: This field must reference the unique `name` of the xref:resource/couchbaseautoscaler.adoc[`CouchbaseAutoscaler`] custom resource.
As discussed in the previous section, xref:resource/couchbaseautoscaler.adoc[`CouchbaseAutoscaler`] resources are automatically created by the Autonomous Operator using the name format `_<server-class>_._<couchbase-cluster>_`.
--
+
Refer to xref:concept-couchbase-autoscaling.adoc#referencing-the-couchbase-autoscaler[Referencing the Couchbase Autoscaler] in the concept documentation for more detailed information about these fields.

<.> Fine-grained xref:concept-couchbase-autoscaling.adoc#scaling-behavior[_scaling behavior_] is configured via _policies_ specified in the `spec.behavior` section.
Different policies can be specified for scaling up (`behavior.scaleUp`) and scaling down (`behavior.scaleDown`).
If no user-supplied values are specified in `behavior` fields, then the https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#default-behavior[default values^] are used.

<.> `spec.behavior.[].policies`: Scaling policies are made up of the following fields: `type`, `value`, and `periodSeconds`.
The recommended settings are `type: Pods` and `value: 1`, while leaving `periodSeconds` with the default value.
+
Refer to xref:concept-couchbase-autoscaling.adoc#scaling-policies[Scaling Policies] and xref:concept-couchbase-autoscaling.adoc#scaling-increments[Scaling Increments] in the concept documentation for more detailed information about these fields.

<.> `behavior.[].stabilizationWindowSeconds`: A xref:concept-couchbase-autoscaling.adoc#horizontal-pod-stabilization[_stabilization window_] can be configured as a means to control undesirable scaling caused by fluctuating metrics.
A minimum `scaleUp` stabilization window of 30 seconds is generally recommended, unless indicated otherwise in xref:concept-couchbase-autoscaling-best-practices.adoc[].

<.> The `spec.minReplicas` and `spec.maxReplicas` fields set the minimum and maximum number of Couchbase nodes for the associated server class.
+
--
* `minReplicas` sets the boundary for the number of Couchbase nodes that the associated server class can ever be down-scaled to, and defaults to `1`.
This field is important for maintaining service availability.

* `maxReplicas` sets the upper boundary for the number of Couchbase nodes that the associated server class can ever be up-scaled to, and cannot be set to a value lower than what is defined for `minReplicas`.
This field is _required_, as it provides important protection against runaway scaling events.
--
+
Refer to xref:concept-couchbase-autoscaling.adoc#sizing-constraints[Sizing Constraints] in the concept documentation for more detailed information about these fields.

<.> The `spec.metrics` section must target a specific _metric_, along with an associated _threshold_ for that metric.
In this example, a Kubernetes resource metric (`cpu`) is being targeted with a threshold set to `70` percent utilization.
+
Refer to xref:concept-couchbase-autoscaling.adoc#target-metrics-and-thresholds[Target Metrics and Thresholds] in the concept documentation for more detailed information about targeting metrics in the {HorizontalPodAutoscaler} resource.

The {HorizontalPodAutoscaler} resource can be created like any other resource by submitting the specifications in a file using `kubectl`:

[source,console]
----
$ kubectl apply -f query-hpa.yaml
----

As soon as the {HorizontalPodAutoscaler} resource has been successfully created, the Horizontal Pod Autoscaler will begin to monitor the target metric and the cluster will be subject to auto-scaling if the targeted metric is above or below the configured threshold.

[[verifying-horizontalpodautoscaler-status]]
=== Verifying `HorizontalPodAutoscaler` Status

When the Horizontal Pod Autoscaler begins to monitor the target metric, it will begin reporting the value of metric along with the current vs desired size of the server class.

Run the following command to print these details to the console output:

[source,console]
----
$ kubectl describe hpa query-hpa
----
----
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  1% (50m) / 70% <.>
Min replicas:                         2
Max replicas:                         6
CouchbaseAutoscaler pods:             2 current / 2 desired  <.>
----

<.> The `current` observed value of the metric is displayed vs the `target` threshold.

<.> The `current` size of the server class is displayed vs the `desired` size currently being recommended by the Horizontal Pod Autoscaler.

== Disabling Scale Down

In production environments, it may be desirable to only allow a cluster to automatically scale up while requiring manual intervention to scale down.
This can be accomplished by modifying the {HorizontalPodAutoscaler} resource as follows:

[source,yaml,subs="attributes,verbatim"]
----
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: example-hpa
spec:
  behavior:
    scaleDown:
      selectPolicy: Disabled # <.>
----

<.> `spec.behavior.[].selectPolicy`: This field controls which policy is chosen by the Horizontal Pod Autoscaler if more than one policy is defined.
When set to `Disabled` no policy is chosen, and therefore auto-scaling is disabled in that direction.

By setting `spec.behavior.scaleDown.selectPolicy` to `Disabled`, the Horizontal Pod Autoscaler will never recommend scaling down the associated server class.
Specifying this setting for all {HorizontalPodAutoscaler} resources associated with a particular Couchbase cluster ensures that the cluster will never automatically scale down.

Clusters that have automatic down-scaling disabled can be manually scaled down by editing the xref:resource/couchbaseautoscaler.adoc[`CouchbaseAutoscaler`] resource directly:

[source,console]
----
$ kubectl scale --replicas=2 query.cb-example
----

The above command edits the xref:concept-couchbase-autoscaling.adoc#scale-subresource[_scale subresource_] and results in the Autonomous Operator scaling the server class named `query` to a size of `2`.

[[disabling-auto-scaling]]
== Disabling Auto-scaling

Auto-scaling, having been <<enabling-auto-scaling,enabled>> and configured for a Couchbase cluster, can subsequently be _disabled_.

The recommended method for disabling auto-scaling is to set xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-servers-autoscaleenabled[`couchbaseclusters.spec.servers.autoscaleEnabled`] back to `false` for each of the desired server classes.

[source,yaml,subs="attributes,verbatim"]
----
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-example
spec:
  servers:
  - name: index
    autoscaleEnabled: false # <.>
    size: 2
    services:
    - index
  - name: query
    autoscaleEnabled: false
    size: 2
    services:
    - query
----

<.> xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-servers-autoscaleenabled[`couchbaseclusters.spec.servers.autoscaleEnabled`]: Setting this field to `false` triggers the Autonomous Operator to delete the xref:resource/couchbaseautoscaler.adoc[`CouchbaseAutoscaler`] custom resource that had previously been created for the relevant server class.
In this example, the xref:resource/couchbaseautoscaler.adoc[`CouchbaseAutoscaler`] resource associated with the `index` server class will be deleted by the Autonomous Operator upon submitting the configuration.

Upon deleting the xref:resource/couchbaseautoscaler.adoc[`CouchbaseAutoscaler`] resource, the Autonomous Operator will no longer reconcile the current size of the server class with the recommendations of the Horizontal Pod Autoscaler, and instead the value specified in xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-servers-size[`couchbaseclusters.spec.servers.size`] will become the new source of truth.
For example, if the above configuration were to be submitted, it would result in the `index` and `query` server classes each being scaled to `size: 2` from whatever size they had previously been auto-scaled to.

It's important to note, however, that the {HorizontalPodAutoscaler} resource is not managed by the Autonomous Operator, and therefore does not get deleted along with the xref:resource/couchbaseautoscaler.adoc[`CouchbaseAutoscaler`] resource.
It will continue to exist in the current namespace until it is manually deleted by the user.
Since the {HorizontalPodAutoscaler} resource can continue to be used if auto-scaling is subsequently re-enabled, it is important to <<verifying-horizontalpodautoscaler-status,verify the status>> of the {HorizontalPodAutoscaler} resource to ensure that it is persisted as expected.

If the desire is to only temporarily disable auto-scaling, the {HorizontalPodAutoscaler} resource can be left to persist until auto-scaling is eventually re-enabled.
This only works if the names of both the server class and the Couchbase cluster remain the same, because when xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-servers-autoscaleenabled[`couchbaseclusters.spec.servers.autoscaleEnabled`] is set back to `true`, the Autonomous Operator will create a xref:resource/couchbaseautoscaler.adoc[`CouchbaseAutoscaler`] resource that is already xref:concept-couchbase-autoscaling.adoc#referencing-the-couchbase-autoscaler[referenced] by the existing {HorizontalPodAutoscaler} resource.
In this case, the cluster will immediately become subject to the recommendations of the Horizontal Pod Autoscaler.

[NOTE]
====
Deleting just the {HorizontalPodAutoscaler} resource will also have the effect of "disabling" auto-scaling.
In this scenario, the Autonomous Operator continues to maintain the xref:resource/couchbaseautoscaler.adoc[`CouchbaseAutoscaler`] resource, but it will remain at the same size that was last recommended by the Horizontal Pod Autoscaler before it was deleted.
====

== Related Links

* *Learn*: xref:concept-couchbase-autoscaling.adoc[]
* *Learn*: xref:concept-couchbase-autoscaling-best-practices.adoc[]
* *Tutorial*: xref:tutorial-autoscale-query.adoc[]
* *Tutorial*: xref:tutorial-autoscale-data.adoc[]
* *Tutorial*: xref:tutorial-autoscale-index.adoc[]
* *Reference*: xref:resource/couchbaseautoscaler.adoc[]
* *Reference*: xref:reference-couchbasecluster-events.adoc#autoscaling-lifecycle[Auto-scaling Lifecycle Events]