= Configure Log Streaming
include::partial$constants.adoc[]

[abstract]
Configure Couchbase Server logs to be streamed to standard output (`stdout`).

== Overview

Couchbase Server produces a xref:server:manage:manage-logging/manage-logging.adoc#log-file-listing[variety] of log files.
By default, these logs cannot be collected from the pod's standard output (`stdout`).
This limits the ability to integrate Couchbase logging with 3rd-party monitoring or collection technologies deployed within a Kubernetes cluster.

However, the Autonomous Operator can implement a sidecar container that can read the log files on the volume of a Couchbase Server pod, and stream those logs to `stdout`.
For this purpose, Couchbase supplies a default container image -- `operator-logging` -- that is based on https://fluentbit.io/[Fluent Bit^].

NOTE: Log streaming requires that logs be written to a persistent volume (i.e. the Couchbase deployment's `default` or `logs` volumes are backed by xref:best-practices.adoc#storage[persistent storage]).
Fully-ephemeral clusters are not supported by this feature.

[[enabling-log-streaming]]
== Enabling Log Streaming

Log streaming is enabled via the xref:resource/couchbasecluster.adoc[`CouchbaseCluster`] resource specification.

All settings in the example configuration below represent the defaults for their respective fields unless otherwise noted in a callout.
The Autonomous Operator will set default values for any fields not specified by the user.

[source,yaml,subs="attributes,verbatim"]
----
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
spec:
  logging:
    server:
      enabled: true # <.>
      manageConfiguration: true
      configurationName: 〜fluent-bit-config〝
      sidecar:
        image: couchbase/operator-logging:{logging-version}〝
        configurationMountPath: 〜/fluent-bit/config/〝
    audit:
      enabled: false # <.>
      disabledEvents: []
      disabledUsers: []
      rotation:
        interval: 〜15m〝
        size: 〜20Mi〝
      garbageCollection:
        sidecar:
          enabled: false
          image: "{logging-helper}"
          age: 〜1h〝
          interval: 〜20m〝
          resources:
            requests:
              cpu:
              memory:
----

<.> xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-logging-server-enabled[`couchbaseclusters.spec.logging.server.enabled`]: Setting this field to `true` enables the logging sidecar container.
This field defaults to `false`.
+
This is technically the only field that is required to enable log streaming.

<.> xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-logging-audit-enabled[`couchbaseclusters.spec.logging.audit.enabled`]: This field is used to enable audit logging, and defaults to `false`.
+
Unlike other Couchbase logs, audit logging is not turned on by default.
If you intend to stream audit logs, you must xref:howto-manage-couchbase-logging.adoc#configuring-audit-logging[configure audit logging] first.


After deploying the changes to the xref:resource/couchbasecluster.adoc[`CouchbaseCluster`] resource specification, the logs will be available on the standard output of the `logging` container in the pod:

[source,console]
----
kubectl logs cb-example-0000 logging
----

////
== Parsing Streamed Logs

We haven't detailed parsing anywhere yet.

== Redacting Streamed Logs

Need to move over the tutorial content.
////

== Customizing Log Streaming

The <<enabling-log-streaming>> section describes how to enable log streaming using only default settings.
The default settings utilize the official https://github.com/couchbase/couchbase-operator-logging[Couchbase-supplied image^], which is based on the official https://fluentbit.io/[Fluent Bit^].
This means that anything supported by Fluent Bit is also available to https://docs.fluentbit.io/manual/administration/configuring-fluent-bit[configure^] for custom log streaming.

=== Enable Custom Log Streaming

[source,yaml,subs="attributes,verbatim"]
----
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
spec:
  logging:
    server:
      enabled: true 
      manageConfiguration: false # <.>
      configurationName: 〜fluent-bit-config〝 # <.>
      sidecar:
        image: couchbase/operator-logging:{logging-version}〝 # <.>
        configurationMountPath: 〜/fluent-bit/config/〝 # <.>
----

<.> xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-logging-server-manageconfiguration[`couchbaseclusters.spec.logging.server.manageConfiguration`]: Set this field to `false`.
This prevents the Autonomous Operator from removing any custom configuration.

<.> xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-logging-server-configurationname[`couchbaseclusters.spec.logging.server.configurationName`]: The name of the `Secret` that <<create-custom-secret,contains the custom configuration>> that will be used to configure the logging sidecar.
Note that this `Secret` must be present in the same namespace as the Couchbase deployment for the `Pod` to start.

<.> xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-logging-server-sidecar-image[`couchbaseclusters.spec.logging.server.sidecar.image`]: If desired, use this field to specify a custom logging sidecar image.
A few reasons for specifying a custom image include adding certificates for self-signed endpoints internally, or to switch to another implementation or the Fluent Bit image.

<.> xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-logging-server-sidecar-configurationmountpath[`couchbaseclusters.spec.logging.server.sidecar.configurationMountPath`]: This is the location to mount the `Secret` into the image.
This defaults to the usual Fluent Bit mount path.
This only need to be modified if a non-default logging sidecar image is used that requires a different mount.

[[create-custom-secret]]
=== Store the Custom Configuration in a Secret

Since a log streaming configuration can contain sensitive information, it is stored in a Kubernetes `Secret`.
The `Secret` is used to https://kubernetes.io/docs/concepts/configuration/secret/#restrictions[populate the volume mounted into the sidecar^] so that the configuration files get picked up by Fluent Bit.
You can add any configuration that is supported by Fluent Bit as a custom version of the `Secret` and the Autonomous Operator will use it in preference.

Under default settings, the Autonomous Operator creates a `Secret` named `fluent-bit-config` that contains the standard log streaming configuration. 
However you can create a custom version of the `Secret` that reduces the number of streamed logs to just the audit log:

.Custom Log Streaming Configuration
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: fluent-bit-config
stringData:
  fluent-bit.conf: |
    [SERVICE]
        flush        1
        daemon       Off
        log_level    Warning
        parsers_file /fluent-bit/etc/parsers-couchbase.conf

    # We split up the input configuration to simplify reuse in testing and custom configurations (so you don't have to repeat it).
    # @include /fluent-bit/etc/couchbase/in-*.conf
    # Each of the logs should have a tag: couchbase.log.<logname>.
    # Only include audit log
    @include /fluent-bit/etc/couchbase/in-audit-log.conf

    # Output all parsed Couchbase logs by default
    [OUTPUT]
        name  stdout
        match couchbase.log.*
----

Changing the `Secret` will update the volume in the sidecar, and when the configuration change is detected in the xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-logging-server-sidecar-configurationmountpath[`couchbaseclusters.spec.logging.server.sidecar.configurationMountPath`] directory, the watcher process restarts Fluent Bit internally to pick it up without having to restart the entire Couchbase Server pod.

CAUTION: Anything logged whilst Fluent Bit is restarting may be lost as log buffering is not yet supported.

NOTE: The ability to restart Fluent Bit internally is a special characteristic of the Couchbase-supplied default container image (`couchbase-logging`). 
If you're using a custom sidecar container image, be aware that Fluent Bit, on its own, does not currently support https://github.com/fluent/fluent-bit/issues/365[dynamic reload^] of its configuration.

////
Holding off on enabling this until we have content for the redaction and parsing sections.
Likely that we will move this to the image repository itself.
== Supported Logs

Couchbase Server produces a xref:server:manage:manage-logging/manage-logging.adoc#log-file-listing[variety] of logs.
The Couchbase-supplied log streaming container image has varying levels of support for each of these logs.

.Log Streaming Support
[#table-log-support-for-streaming,cols="2,1,1,3",options="header"]
|===
| Log File | Supports Redaction? | Default Parsing? | Parser

| `audit`
|
| 㜅 Yes
| `couchbase_json_log`

| `babysitter`
|
| 㜅 Yes
| `couchbase_erlang_multiline`

| `couchdb`
|
| 㜅 Yes
| `couchbase_erlang_multiline`

| `crash-log.bin`
| 
| 
|

| `debug`
|
| 㜅 Yes
| `couchbase_erlang_multiline`

| `error`
|
| 㜅 Yes
| `couchbase_erlang_multiline`

| `eventing`
|
| 㜅 Yes
| `couchbase_simple_log_mixed`

| `fts`
|
| 㜅 Yes
| `couchbase_simple_log_mixed`

| `goxdcr`
|
| 㜅 Yes
| `couchbase_simple_log_utc`

| `http_access`
|
| 㜅 Yes
| `couchbase_http`

| `http_access_internal`
|
| 㜅 Yes
| `couchbase_http`

| `indexer`
|
| 㜅 Yes
| `couchbase_simple_log`

| `info`
|
| 㜅 Yes
| `couchbase_erlang_multiline`

| `json_rpc`
|
| 㜅 Yes
| `couchbase_erlang_multiline`

| `mapreduce_errors`
| 
| 
|

| `memcached`
|
| 㜅 Yes
| `couchbase_simple_log`

| `metakv`
|
| 㜅 Yes
| `couchbase_erlang_multiline`

| `ns_couchdb`
|
| 㜅 Yes
| `couchbase_erlang_multiline`

| `projector`
|
| 㜅 Yes
| `couchbase_simple_log`

| `rebalance`
|
| 㜅 Yes
| `couchbase_json_log`

| `reports`
|
| 㜅 Yes
| `couchbase_erlang_multiline`

| `ssl_proxy`
| 
| 
|

| `stats`
| 
| 
|

| `views`
| 
|
| 

| `xdcr`
| 
| 
|

| `xdcr_errors`
| 
| 
|

| `xcdr_trace`
| 
| 
|

| `analytics_access.log`
| 
| 
|

| `analytics_cbas_debug.log`
| 
| 
|

| `analytics_dcpdebug.log`
| 
| 
|

| `analytics_dcp_failed_ingestion.log`
| 
| 
| 

| `analytics_debug.log`
|
| 㜅 Yes
| `couchbase_java_multiline`

| `analytics_error.log`
|
| 㜅 Yes
| `couchbase_java_multiline`

| `analytics_info.log`
|
| 㜅 Yes
| `couchbase_java_multiline`

| `analytics_shutdown.log`
| 
| 
|

| `analytics_warn.log`
|
| 㜅 Yes
| `couchbase_java_multiline` 
|===

[NOTE]
====
In the table above, some logs are subsets of others so can be parsed with the same parser.
`analytics_debug.log` will include everything in `analytics_info.log` which in turn includes everything in `analytics_warn.log` and `analytics_error.log`.
Similarly, `debug.log` will include everything in `info.log` which in turn includes everything in `error.log`.
However, this would lead to duplicate entries and additional loading so by default we use the log with the most information in it: the level of each log line is still recorded if required.
====
////

== Example Configuration

An example configuration showing the CRD with events and users provided to the optional audit fields:

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: cb-example-auth
type: Opaque
data:
  username: QWRtaW5pc3RyYXRvcg== # Administrator
  password: cGFzc3dvcmQ=         # password
---
apiVersion: couchbase.com/v2
kind: CouchbaseEphemeralBucket
metadata:
  name: default
---
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-example
spec:
  logging:
    server:
      enabled: true
    audit:
      enabled: true
      disabledEvents: 
        - 8243
      disabledUsers: 
        - "@eventing/local"
        - "@cbq-engine/local"
      garbageCollection:
        sidecar:
          enabled: true
  image: couchbase/server:6.6.0
  security:
    adminSecret: cb-example-auth
  buckets:
    managed: true
  servers:
  - size: 3
    name: all_services
    services:
    - data
    - index
    - query
    - search
    - eventing
    - analytics
    volumeMounts:
      default: couchbase 
  volumeClaimTemplates: 
  - metadata:
      name: couchbase 
    spec:
      storageClassName: standard 
      resources: 
        requests:
          storage: 1Gi
----
