= Configure Prometheus Metrics Collection
include::partial$constants.adoc[]

[abstract]
You can set up the Autonomous Operator to use the Couchbase Prometheus Exporter for metrics collection.

== Overview

Prometheus is the de facto metrics collection platform for use in Kubernetes environments.
The Autonomous Operator provides Prometheus integration for collecting and exposing Couchbase Server metrics via the https://github.com/couchbase/couchbase-exporter[Couchbase Prometheus Exporter^].

Prometheus metrics collection is enabled in the `CouchbaseCluster` resource.
The configuration allows you to specify a Couchbase-provided container image that contains the Prometheus Exporter.
The Autonomous Operator injects the image as a https://kubernetes.io/docs/concepts/workloads/pods/pod-overview/#how-pods-manage-multiple-containers["sidecar" container^] in each Couchbase Server pod.

NOTE: The Couchbase-supplied Prometheus Exporter container image is only supported on Kubernetes platforms in conjunction with the Couchbase Autonomous Operator.

== Configuration

Prometheus metrics collection is enabled in the `CouchbaseCluster` resource.

[source,yaml,subs="attributes,verbatim"]
----
apiVersion: couchbase/v2
kind: CouchbaseCluster
spec:
  monitoring:
    prometheus:
      enabled: true # <.>
      image: couchbase/exporter:{prometheus-version} # <.>
      authorizationSecret: cb-metrics-token # <.>
----

<.> Setting xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-monitoring-prometheus-enabled[`couchbaseclusters.spec.monitoring.prometheus.enabled`] to `true` enables injection of the sidecar into Couchbase Server pods.

<.> If the xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-monitoring-prometheus-image[`couchbaseclusters.spec.monitoring.prometheus.image`] field is left unspecified, then the dynamic admission controller will automatically populate it with the most recent container image that was available when the installed version of the Autonomous Operator was released.
The default image for open source Kubernetes comes from https://hub.docker.com/r/couchbase/exporter[Docker Hub^], and the default image for OpenShift comes from https://access.redhat.com/containers/#/vendor/couchbase[Red Hat Container Catalog^].
+
If pulling directly from the the Red Hat Container Catalog, then the path will be something similar to `registry.connect.redhat.com/couchbase/exporter:{prometheus-version}` (you can refer to the catalog for the most recent images).
If image pull secrets are required to access the image, they are inherited from the Couchbase Server pod and can be set explicitly with the xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-servers-pod[`couchbaseclusters.spec.servers.pod.spec.imagePullSecrets`] field or implicitly with a service account specified with the xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-servers-pod[`couchbaseclusters.spec.servers.pod.spec.serviceAccountName`] field.

<.> You can optionally specify a Kubernetes Secret that contains a bearer token value that clients will need to use to gain access to the Prometheus metrics.

[NOTE]
====
If you wish to create a Kubernetes secret with a bearer token, simply edit and create the following definition:

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: cb-metrics-token
type: Opaque
stringData:
  token: your-plain-text-bearer-token-here
----

The `stringData` field allows you to put a non-base64 encoded string directly into the Secret, and Kubernetes will then encode the string for you when the Secret is created or updated.
====

.Important Considerations
* You can enable/disable Prometheus metric collection at any time during the cluster's lifecycle.
However, since `Pod` resources are immutable, enabling or disabling metric collection will require a rolling upgrade of the cluster.
* Only official Prometheus images provided by Couchbase are supported (with the exception of user-supplied images that specifically enable <<customizing-metrics,customized metrics>>).
+
In addition, you should ensure that your image source is trusted.
The sidecar container requires access to the Couchbase cluster administrative credentials in order to login and perform collection.
Granting these credentials to arbitrary code is potentially harmful.

[[customizing-metrics]]
== Customizing Metrics

By default, the exporter collects all metrics from Couchbase Server, with each metric having a default name and default metadata associated with it.
The exporter supports certain user-configurable customizations to these defaults.

The Couchbase Prometheus Exporter currently supports the following customizations:

* Change the namespace, subsystem, name, and help text for each metric.
* Enable and disable whether a metric is exported to Prometheus.

These customizations are enabled by building your own custom version of the Couchbase Prometheus Exporter container image.
For instructions on how to create a custom metrics configuration and build it into a container image, refer to the https://github.com/couchbase/couchbase-exporter#customizing-metrics[`couchbase-exporter` README^].

== Using Exported Metrics

Once configured, active metrics can be collected from each Couchbase Server pod on port 9091.

The Autonomous Operator does not create or manage resources for third-party software.
Prometheus scrape targets must be manually created by the user.

=== Couchbase Cluster Auto-scaling

The Autonomous Operator supports xref:concept-couchbase-autoscaling.adoc[auto-scaling Couchbase clusters].
In order to properly take advantage of this feature, users must xref:concept-couchbase-autoscaling.adoc#couchbase-metrics[expose Couchbase metrics through the Kubernetes custom metrics API].

Discovery of available metrics can be performed through Prometheus https://github.com/couchbase/couchbase-exporter#queries[queries^].
However, the Couchbase Exporter repository contains a convenient https://github.com/couchbase/couchbase-exporter/blob/master/example/config.json[list of the Couchbase metrics being exported^].

Some metric names are further explained in the Couchbase Server documentation:

* Data Service
** xref:server:rest-api:rest-bucket-stats.adoc[Getting Bucket Statistics]
** xref:server:rest-api:rest-buckets-summary.adoc[Getting Bucket Information]
** xref:server:cli:cbstats/cbstats-all.adoc[`cbstats` all]

* Index Service
** xref:server:rest-api:rest-index-stats.adoc[Index Statistics API]

* Query Service
** xref:server:n1ql:n1ql-rest-api/admin.adoc#_statistics[Admin Rest API - Statistics]

* Search Service
** xref:server:rest-api:rest-fts-statistics.adoc[Getting Search Statistics]

* Eventing Service
** xref:server:eventing:eventing-api.adoc[Eventing Statistics API]

* XDCR
** xref:server:rest-api:rest-xdcr-statistics.adoc[Getting XDCR Stats]

* Clusters and Nodes
** xref:server:rest-api:rest-cluster-get.adoc[Retrieving Cluster Information]
** xref:server:rest-api:rest-get-cluster-tasks.adoc[Getting Cluster Tasks]
** xref:server:rest-api:rest-servergroup-get.adoc[Getting Group Information]
** xref:server:rest-api:rest-node-get-info.adoc[Getting Server Node Information]

== Related Links

You might find the following resources helpful when setting up your Prometheus environment:

* Couchbase Blog -- https://blog.couchbase.com/step-by-step-guide-for-running-couchbase-autonomous-operator-2-0-with-prometheus-part-1/[Part 1^] & https://blog.couchbase.com/step-by-step-guide-for-running-couchbase-autonomous-operator-2-0-with-prometheus-part-2/[Part 2^]
* https://github.com/couchbase/couchbase-exporter[Couchbase Prometheus Exporter GitHub^]
* https://prometheus-operator.dev[Prometheus Operator^]
* https://github.com/prometheus-operator/kube-prometheus[`kube-prometheus`^]
