= Manage Couchbase Server Logging
include::partial$constants.adoc[]

[abstract]
Couchbase Server generates logs that can be used for auditing and troubleshooting purposes.

== Overview

The Couchbase Server application records important events, and saves the details to a xref:server:manage:manage-logging/manage-logging.adoc#log-file-listing[variety] of log files.
These logs are distinct from the logs that are generated by the xref:concept-operator-logging.adoc[Autonomous Operator itself].

Logging is performed continuously within each Couchbase Server container in a Couchbase deployment.
When using xref:concept-persistent-volumes.adoc[persistent volumes] -- as is xref:best-practices.adoc#storage[recommended] for all production deployments -- log files are written to either the `default` or `logs` volume.

Couchbase Server manages logging automatically and uses default settings for things like logging level, file size, and rotation/expiration.
The one exception is `audit.log`.
This is a special log file, used to manage cluster-security, and is handled separately from the other log files.
For information on `audit.log`, refer to <<configuring-audit-logging>>.

== Manually Collect Couchbase Server Logs

In most situations, the xref:tools/cbopinfo.adoc[`cbopinfo`] tool will successfully allow logs to be collected and downloaded.
However, there are some cases where collection will fail.
For example, let's say a stateful service (e.g. Data, Index, Analytics) crashes and the Autonomous Operator recovers the pod continuously.
In this hypothetical situation, the pod does not remain alive for long enough for xref:tools/cbopinfo.adoc[`cbopinfo`] to automatically collect the logs, and therefore manual log collection is required.

The general process for manual log collection is as follows:

. Pause the Operator for the cluster by setting `spec.paused` to `true`
. Create a temporary pod resource with the persistent volumes mounted
. Run the `cbcollect_info` command
. Download the logs from the pod
. Delete the temporary pod
. Resume the Operator by removing `spec.paused` or setting it to `false`

=== Create a Temporary Pod

The basic template will look like the following:

[source,yaml,subs="attributes"]
----
---
apiVersion: v1
kind: Pod
metadata:
  name: cb-example-0005
  namespace: default
spec:
  restartPolicy: never
  containers:
  - name: couchbase-server
    image: couchbase/server:{couchbase-version}
    command: '/bin/sleep'
    args:
    - '86400'
    volumeMounts:
    - mountPath: /opt/couchbase/var/lib/couchbase
      name: pvc-couchbase-cb-example-0005-00-default
      subPath: default
    - mountPath: /opt/couchbase/etc
      name: pvc-couchbase-cb-example-0005-00-default
      subPath: etc
    - mountPath: /mnt/data
      name: pvc-couchbase-cb-example-0005-00-data
  volumes:
    - name: pvc-couchbase-cb-example-0005-00-default
      persistentVolumeClaim:
        claimName: pvc-couchbase-cb-example-0005-00-default
    - name: pvc-couchbase-cb-example-0005-00-data
        persistentVolumeClaim:
          claimName: pvc-couchbase-cb-example-0005-00-data
----

The pod contains a single container running a Couchbase Server image as this contains all the necessary command line tools.  We modify the container entry point to run `/bin/sleep` for `86400` seconds (a day) while logs are collected and downloaded.

The associated `volumes` that need to be defined for the pod can be determined by running the following command, assuming the pod you wish to collect from is `cb-example-0005`:

[source,console]
----
$ kubectl get pvc -lcouchbase_node=cb-example-0005
----

Any returned volumes will need to be defined in `volumes` and be correctly mounted in the pod via the `volumeMounts`.  `volumeMounts` names refer to their corresponding entries in `volumes`.  The following documents the `volumeMounts` required for each entry in `volumes` given the returned persistent volume claims:

pvc-couchbase-cb-example-0005-00-default::
The `default` persistent volume claim requires two `volumeMounts`.  The _default_ `subPath` must be mounted at `/opt/couchbase/var/lib/couchbase`.  The _etc_ `subPath` must be mounted at `/opt/couchbase/etc`.

pvc-couchbase-cb-example-0005-00-data::
If specified the `data` persistent volume claim requires a single mount in `volumeMounts`, and must be mounted as `/mnt/data`.

pvc-couchbase-cb-example-0005-00-index::
If specified the `index` persistent volume claim requires a single mount in `volumeMounts`, and must be mounted as `/mnt/index`.

pvc-couchbase-cb-example-0005-00-analytics-00::
If specified `analytics` persistent volume claims require a single mount in `volumeMounts` per volume, they must be mounted as `/mnt/analytics-00`.  If multiple analytics mounts are specified they will have different numeric suffixes e.g. `pvc-couchbase-cb-example-0005-00-analytics-01` would be mounted as `/mnt/analytics-01`.

=== Collecting & Downloading Logs

Please see the documentation for `cbcollect_info`, however a typical command to run would be:

[source,console]
----
$ kubectl exec -ti pod/cb-example-0005 /opt/couchbase/bin/cbcollect_info /tmp/cbinfo-default-cb-example-0005-$(date +%y%m%dT%H%M%S%z)
----

The `pod` name refers to the name given to the pod in the template.  The convention for logs is `cbinfo`, _namespace_, _pod name_, _timestamp_.

Once complete the logs can be downloaded to the local host.

[source,console]
----
$ kubectl cp default/cb-example-0005:/tmp/cbcollectinfo-default-cb-example-0005-181005T154746+0100.zip .
----

[[configuring-audit-logging]]
== Configuring Audit Logging

Couchbase Server xref:server:learn:security/auditing.adoc[audit logging] is a special type of logging that is not enabled by default. 
When audit logging is enabled, Couchbase Server begins recording information on _who_ has performed _what_ action, _when_, and _how_ successfully.

Audit records are written as JSON documents to a default file, named `audit.log`, which is stored alongside all other Couchbase Server log files in the `default` or `logs` volume that is attached to the pod.
After a specified period time, or once the file reaches a specified size (whichever happens first), the file is closed, and is saved under a modified name that features a timestamp corresponding to the time of saving.
A new, empty `audit.log` file is created and saved when a new audit event is generated.

[CAUTION]
====
Couchbase Server rotates audit logs, but never expires or deletes them.
This is by design, as Couchbase Server intentionally has no facility to modify or delete an audit log file once it has been rotated.
As a result, it is the explicit responsibility of the administrator to implement a policy for expiring and/or moving audit logs to a different storage location.
_Without active intervention, rotated audit logs will eventually consume all available storage, leading to node and cluster failures._
====

There are two approaches you can choose when it comes to implementing audit logging: _managed_ and _automated_.
The <<managed-audit-logging,managed>> approach involves the administrator directly enabling audit logging in Couchbase Server, and requires that the administrator actively manage the resultant audit log files.
With the <<automated-audit-logging,automated>> approach, the Autonomous Operator handles the audit log configuration, and optionally manages the resultant audit log files.

[[managed-audit-logging]]
=== Managed Audit Logging

Managed audit logging can be implemented after the Couchbase cluster has been successfully deployed by the Autonomous Operator.
Once the cluster is deployed, the administrator can enable and configure audit logging directly through the Couchbase UI, CLI, or REST API.
Refer to xref:server:manage:manage-security/manage-auditing.adoc[] in the Couchbase Server documentation for more information.

Once audit logging is enabled, it's up to the administrator to manage the resultant `audit.log` files.
It is expected that the administrator will implement an automated system for expiring and/or moving audit logs to a different storage location subject to a retention policy.

[[automated-audit-logging]]
=== Automated Audit Logging

NOTE: Automated audit logging requires that logs be written to a persistent volume (i.e. the Couchbase deployment's `default` or `logs` volumes are backed by xref:best-practices.adoc#storage[persistent storage]).
Fully-ephemeral clusters are not supported by this feature.

An audit logging configuration can be specified in the xref:resource/couchbasecluster.adoc[`CouchbaseCluster`] resource specification, allowing the Autonomous Operator to set up audit logging in Couchbase Server, and optionally manage the resultant audit log files.

All settings in the example configuration below represent the defaults for their respective fields unless otherwise noted in a callout.
The Autonomous Operator will set default values for any fields not specified by the user.

[source,yaml,subs="attributes,verbatim"]
----
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
spec:
    audit:
      enabled: true # <.>
      disabledEvents: []
      disabledUsers: []
      rotation:
        interval: “15m”
        size: “20Mi”
      garbageCollection:
        sidecar:
          enabled: true # <.>
          image: "{logging-helper}" # <.>
          age: “1h”
          interval: “20m”
          resources:
            requests:
              cpu:
              memory:
----

<.> xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-logging-audit-enabled[`couchbaseclusters.spec.logging.audit.enabled`]: Setting this field to `true` enables audit logging on the Couchbase cluster.
This field defaults to `false`.
+
This is technically the only field that is required to configure audit logging.

<.> xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-logging-audit-garbagecollection-sidecar-enabled[`couchbaseclusters.spec.logging.audit.garbageCollection.sidecar.enabled`]: Setting this field to `true` enables garbage collection of rotated audit logs.
This field defaults to `false`.
+
This is technically the only field that is required to configure garbage collection of rotated audit logs.
Note, however, that garbage collection can only be enabled if xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-logging-audit-enabled[`couchbaseclusters.spec.logging.audit.enabled`] is also set to `true`.

<.> xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-logging-audit-garbagecollection-sidecar-image[`couchbaseclusters.spec.logging.audit.garbageCollection.sidecar.image`]: This is the base image of the sidecar helper container that will be added to the server pods for handling the cleanup for rotated logs.
This sidecar is a standard Linux container, as all it needs to do is find and remove files of the appropriate name and age. 
+
Be aware that there are security concerns with using a standard Linux image, such as the potential for arbitrary shell execution and write-access to the volumes, which can potentially be exploited by a malicious image.
In order limit potential abuse, the garbage collection sidecar uses a sub-path to only mount the logs directory.
In addition, the commands run by the garbage collector are not configurable, and the filenames of removed logs are printed to the pod's standard console output.

After enabling automated audit logging, you should take care only to use the xref:resource/couchbasecluster.adoc[`CouchbaseCluster`] resource specification for making further modifications to the audit logging configuration.
Manual changes that are made to the configuration via the Couchbase UI, CLI, or REST API (such as changing the audit log directory) are not prevented by the Autonomous Operator, and can cause audit logging failures.
