= Installing on OpenShift

[abstract]
This guide walks through the recommended procedure for installing the Couchbase Autonomous Operator on a Red Hat OpenShift project.

[IMPORTANT]
====
If you are looking to upgrade an existing installation of the Operator, see xref:howto-operator-upgrade.adoc[Upgrading the Autonomous Operator].
====

== Prerequisites

Download the Operator https://www.couchbase.com/downloads[package^] and unpack it on the same computer where you normally run `oc`.
The Operator package contains YAML configuration files and command-line tools that you will use to install the Operator.

[IMPORTANT]
====
After you unpack the download, the resulting directory will be titled something like `couchbase-autonomous-operator-openshift.x.x-linux_x86_64`.
Make sure to `cd` into this directory before you run the commands in this guide.
====

All commands in this guide are run as a system administrator account; they require the creation of cluster scoped resources or the granting of roles to service accounts (privilege escalation).

== Install the CRD

The first step in installing the Operator is to install the custom resource definitions (CRD) that describe the Couchbase resource types.
This can be achieved with the following command:

[source,console]
----
$ oc create -f crd.yaml
----

== Install the Operator

The operator is composed of two components; a per-cluster dynamic admission controller (DAC) and a per-namespace Operator.
Refer to the xref:concept-operator.adoc[operator architecture document] for additional information on what is required and security considerations.

The DAC and Operator will be installed into the current project/namespace selected by the `oc` command.
Ensure you have created and selected the correct namespace to install into.

The Redhat container catalog requires that deployments have login credentials that allow access to container images; these are provided by a secret:

[source,console]
----
$ oc create secret docker-registry rh-catalog --docker-server=registry.connect.redhat.com \
  --docker-username=<rhel-username> --docker-password=<rhel-password> --docker-email=<docker-email>
----

[IMPORTANT]
====
This command uses 3rd party resources and is subject to change.
Consult the documentation provided by Redhat for up to date instructions.
====

The following command will install both the DAC and the Operator:

[source,console]
----
$ ./cbopcfg --image-pull-secret rh-catalog \
  --dynamic-admission-controller-image registry.connect.redhat.com/couchbase/admission-controller:2.0.0-1 \
  --operator-image registry.connect.redhat.com/couchbase/operator:2.0.0-1 | kubectl create -f -
----

=== Custom Installation

Alternatively, you may wish to install just the DAC in the `camelot` namespace:

[source,console]
----
$ oc project camelot
$ ./cbopcfg --no-operator --image-pull-secret rh-catalog \
  --dynamic-admission-controller-image registry.connect.redhat.com/couchbase/admission-controller:2.0.0-1 | oc create -f -
----

And then install just the Operator into the `asgard` namespace:

[source,console]
----
$ oc project asgard
$ ./cbopcfg --no-admission --image-pull-secret rh-catalog \
  --operator-image registry.connect.redhat.com/couchbase/operator:2.0.0-1 | oc create -f -
----

For further installation options please see the xref:reference-cbopcfg.adoc[cbopcfg] reference manual.

== Check the Status of the Operator

You can use the following command to check on the status of the deployments:

[source,console]
----
$ oc get deployments
NAME                           READY   UP-TO-DATE   AVAILABLE   AGE
couchbase-operator             1/1     1            1           8s
couchbase-operator-admission   1/1     1            1           8s
----

The Operator is ready to deploy `CouchbaseCluster` resources when both the DAC and Operator deployments are fully ready and available.

== Installing User Permissions

By default on an OpenShift platform, users will not have permissions to create and modify Couchbase custom resources.
We provide a cluster role that can be installed once and referenced by any number of user accounts.
To install the role:

[source,console]
----
$ oc create -f cluster-role-user.yaml
----

To associate the role with a user `merlin` in the namespace `camelot` use the following command:

[source,console]
----
$ oc create rolebinding merlin-couchbasecluster --namespace camelot --user merlin --clusterrole couchbasecluster
----

You can now login as the user `merlin` and manage Couchbase resources in the `camelot` namespace.

== Uninstalling the Operator

Uninstalling the DAC and Operator is the reverse of the installation process:

[source,console]
----
$ ./cbopcfg | kubectl delete -f -
$ oc delete -f crd.yaml
----

== Next Steps

* xref:howto-couchbase-create.adoc[How-to Deploy a Couchbase Cluster]
