= Install the Operator on Kubernetes
:page-aliases: install-admission-controller, list-and-describe

[abstract]
This guide walks through the recommended procedure for installing the Couchbase Autonomous Operator on an open source Kubernetes cluster that has _RBAC enabled_.

[IMPORTANT]
====
If you are looking to upgrade an existing installation of the Operator, see xref:howto-operator-upgrade.adoc[Upgrading the Autonomous Operator].
====

== Prerequisites

Download the Operator https://www.couchbase.com/downloads[package^] and unpack it on the same computer where you normally run `kubectl`.
The Operator package contains YAML configuration files and command-line tools that you will use to install the Operator.

[IMPORTANT]
====
After you unpack the download, the resulting directory will be titled something like `couchbase-autonomous-operator-kubernetes_x.x.x-linux_x86_64`.
Make sure to `cd` into this directory before you run the commands in this guide.
====

All commands in this guide are run as a system administrator account; they require the creation of cluster scoped resources or the granting of roles to service accounts (privilege escalation).

== Install the CRD

The first step in installing the Operator is to install the custom resource definitions (CRD) that describe the Couchbase resource types.
This can be achieved with the following command:

[source,console]
----
$ kubectl create -f crd.yaml
----

== Install the Operator

The operator is composed of two components; a per-cluster dynamic admission controller (DAC) and a per-namespace Operator.
Refer to the xref:concept-operator.adoc[operator architecture document] for additional information on what is required and security considerations.

The following command will install both the DAC and the Operator into the `default` namespace.

[source,console]
----
$ bin/cbopcfg admission -cluster | kubectl create -f -
$ bin/cbopcfg operator | kubectl create -f -
----

=== Custom Installation

Alternatively, you may wish to install just the DAC in the `camelot` namespace:

[source,console]
----
$ bin/cbopcfg admission --namespace camelot --cluster | kubectl create -f -
----

And then install just the Operator into the `asgard` namespace:

[source,console]
----
$ bin/cbopcfg operator --namespace asgard | kubectl create -f -
----

For further installation options please see the xref:reference-cbopcfg.adoc[cbopcfg] reference manual.

== Check the Status of the Operator
You can use the following command to check on the status of the deployments:

[source,console]
----
$ kubectl get deployments
NAME                           READY   UP-TO-DATE   AVAILABLE   AGE
couchbase-operator             1/1     1            1           8s
couchbase-operator-admission   1/1     1            1           8s
----

The Operator is ready to deploy `CouchbaseCluster` resources when both the DAC and Operator deployments are fully ready and available.

== Uninstalling the Operator

Uninstalling the DAC and Operator is the reverse of the installation process:

[source,console]
----
$ bin/cbopcfg | kubectl delete -f -
$ kubectl delete -f crd.yaml
----

== Next Steps

* xref:howto-couchbase-create.adoc[How-to Deploy a Couchbase Cluster]
