= Installing on Kubernetes (Without RBAC)

This guide walks through the recommended procedure for installing the Couchbase Autonomous Operator on a Kubernetes cluster that does not have RBAC enabled. This guide is mainly recommended for development clusters or https://kubernetes.io/docs/tasks/tools/install-minikube/[Minikube]. Running a Kubernetes cluster without RBAC is not recommended in production.

NOTE: If you are using a Minikube cluster with Kubernetes 1.10 or later, RBAC is enabled by default. You can either disable RBAC, or follow the instructions to xref:install-kubernetes.adoc[install the Operator on Kubernetes with RBAC enabled].

== Starting the Operator

Run the following command to install the Operator:

[source,console]
----
kubectl create -f https://packages.couchbase.com/kubernetes/1.0.0/k8s/operator.yaml
----

Running this command downloads the Operator Docker image (specified in the `operator.yaml` file) and creates a https://kubernetes.io/docs/concepts/workloads/controllers/deployment/[deployment], which manages a single instance of the Operator. The Operator uses a deployment so that it can restart if the pod it's running in dies.

After you run the `kubectl create` command, it generally takes less than a minute for Kubernetes to deploy the Operator and for the Operator to be ready to run.

=== Check the Status of the Deployment

You can use the following command to check on the status of the deployment:

[source,console]
----
kubectl get deployments -l app=couchbase-operator
----

If you run the previous command immediately after the Operator is deployed, the output will look something like the following:

[source,console]
----
NAME                 DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
couchbase-operator   1         1         1            0           10s
----

In this case, the deployment is called `couchbase-operator`. The `DESIRED` field in the output shows that this deployment will create one pod running the Operator. The `CURRENT` field shows that one Operator pod has been created. However, the `AVAILABLE` field indicates that the pod is not ready yet since its value is 0 and not 1. That means that the Operator is still establishing a connection to the Kubernetes master node to allow it to get updates on CouchbaseCluster objects. Once the Operator has completed this task, it will be able to start managing Couchbase Server clusters and the status will be shown as `AVAILABLE`.

You should continue to poll the status of the Operator until the output looks similar to the following:

[source,console]
----
NAME                 DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
couchbase-operator   1         1         1            1           47s
----

=== Check the Status of the Operator

You can use the following command to verify that the Operator has started successfully:

[source,console]
----
kubectl get pods -l app=couchbase-operator
----

If the Operator is up and running, the command returns an output where the `READY` field shows `1/1`, such as:

[source,console]
----
NAME                                  READY   STATUS   RESTARTS   AGE
couchbase-operator-1917615544-t5mhp   1/1     Running  0          57s
----

You can also check the logs to confirm that the Operator is up and running. Look for the message: `CRD initialized, listening for events... module=controller`.

[source,console]
----
$ kubectl logs couchbase-operator-1917615544-t5mhp
time="2018-04-25T03:01:56Z" level=info msg="Obtaining resource lock" module=main
time="2018-04-25T03:01:56Z" level=info msg="Starting event recorder" module=main
time="2018-04-25T03:01:56Z" level=info msg="Attempting to be elected the couchbase-operator leader" module=main
time="2018-04-25T03:02:13Z" level=info msg="I'm the leader, attempt to start the operator" module=main
time="2018-04-25T03:02:13Z" level=info msg="Creating the couchbase-operator controller" module=main
time="2018-04-25T03:02:13Z" level=info msg="Event(v1.ObjectReference{Kind:\"Endpoints\", Namespace:\"default\", Name:\"couchbase-operator\", UID:\"9b86c750-47e7-11e8-866e-080027b2a68d\", APIVersion:\"v1\", ResourceVersion:\"23482\", FieldPath:\"\"}): type: 'Normal' reason: 'LeaderElection' couchbase-operator-75ddfdbdb5-bz7ng became leader" module=event_recorder
time="2018-04-25T03:02:13Z" level=info msg="CRD initialized, listening for events..." module=controller
time="2018-04-25T03:02:13Z" level=info msg="starting couchbaseclusters controller"
----

== Next Steps

Install the xref:cbopctl.adoc[cbopctl] command line tool and use it to xref:deploying-couchbase.adoc[deploy a Couchbase Server cluster].

== Uninstalling the Operator

.Uninstalling the Operator is a two-step process:

. Delete the Operator.
+
[source,console]
----
kubectl delete deployment couchbase-operator
----

. Delete the CRD.
+
Make sure all instances of the Operator have been deleted from the Kubernetes cluster before you delete the CRD. Once all instances of the Operator have been deleted, run the following command to delete the CRD:
+
[source,console]
----
$ kubectl delete crd couchbaseclusters.couchbase.com
----
