= Installing on OpenShift

This guide walks through the recommended procedure for installing the Couchbase Autonomous Operator on a Red Hat OpenShift project.

.This guide assumes the following:

* You have a working knowledge of OpenShift and Kubernetes
* You are installing on a new OpenShift cluster
* You have access to an OpenShift user that has cluster-admin privileges (`system:admin` in this guide)
* You have access to a standard OpenShift user without cluster-admin privileges (`developer` in this guide)

If you have an OpenShift environment that already has a custom setup (non-default), you should be able to modify a few of the parameters in the various commands and configuration files mentioned in this guide in order to fit your requirements.

IMPORTANT: This guide makes certain assumptions about the role-based access control (RBAC) settings in your OpenShift environment. Refer to the  xref:kubernetes-rbac.adoc[RBAC doumentation] before you install the Operator, as your OpenShift environment may differ from the environment upon which this guide is based.

== Create an OpenShift Project

The first thing that you need to do is use a standard OpenShift user to create a https://docs.openshift.com/container-platform/3.9/architecture/core_concepts/projects_and_users.html#projects[project] where the Operator will reside:

[source,console]
----
$ oc login -u developer

$ oc new-project operator-example

$ oc logout
----

In this example, the standard user is `developer`, and the project is `operator-example`. Later in this guide you will give `developer` the ability to manage the Operator and the Couchbase Server clusters in `operator-example`.

== Install the Custom Resource Definition

The next step in setting up the Operator is to install the CouchbaseCluster custom resource definition (CRD). The Operator can do this for you automatically (xref:install-kubernetes.adoc[as it does when installing on open source Kubernetes]), but in OpenShift it's better to do it manually because installing a CRD is a cluster-level operation and requires cluster-level permissions that should not be given to typical users.

To install the CRD, log in as an OpenShift user that has cluster-admin privileges (in this case `system:admin`) and run the following command:

[source,console]
----
$ oc login -u system:admin

$ oc create -f https://packages.couchbase.com/kubernetes/0.9.0-beta3/openshift/crd.yaml
----

NOTE: You only need to install the CRD once. After that, you can create the Operator in any OpenShift project.

== Create a Role and Service Account for the Operator

You need to create a https://docs.openshift.com/container-platform/3.9/architecture/additional_concepts/authorization.html#roles[role] in OpenShift that allows the Operator to access the resources that it needs to run. Since the Operator might run in many different projects, it's best to create a _cluster role_ because you can assign that role to a https://docs.openshift.com/container-platform/3.9/dev_guide/service_accounts.html[service account] in any OpenShift project.

To create the cluster role for the Operator, run the following command as the `system:admin` user:

[source,console]
----
oc create -f https://packages.couchbase.com/kubernetes/0.9.0-beta3/openshift/cluster-role-sa.yaml
----

NOTE: You only need to create the cluster role once.

After the cluster role is created, you need to create a service account in the project where you are installing the Operator, and then assign the cluster role to that service account using a https://docs.openshift.com/container-platform/3.9/admin_guide/manage_rbac.html[role binding]:

[source,console]
----
$ oc create serviceaccount couchbase-operator --namespace operator-example

$ oc create rolebinding couchbase-operator --clusterrole couchbase-operator --serviceaccount operator-example:couchbase-operator
----

A service account is used as opposed to a traditional user for the Operator because service accounts are meant to be used for processes running in OpenShift.

TIP: To set up a service account for the Operator in another OpenShift project, repeat these steps again in that project.

== Create a Role for a User

Since the `developer` user needs to be able to create and delete the Couchbase cluster, you need to create another cluster role with permissions to handle the management of the CouchbaseCluster resource.

Run the following command to create the cluster role for `developer`:

[source,console]
----
oc create -f https://packages.couchbase.com/kubernetes/0.9.0-beta3/openshift/cluster-role-user.yaml
----

Next, you need to allow `developer` to be able to manage the CouchbaseCluster resource in the `operator-example` project:

[source,console]
----
oc create rolebinding couchbasecluster-developer --clusterrole couchbasecluster --user developer --namespace operator-example
----

Alternatively, if you want `developer` to be able to manage CouchbaseCluster objects in all projects, then you can run the following command instead:

[source,console]
----
oc create clusterrolebinding couchbasecluster-developer --clusterrole couchbasecluster --user developer
----

NOTE: If you want to create role bindings for multiple users either at the cluster or namespace level, they will need to have unique names. In the previous examples, if you were to create a role binding for user `alice`, you'd use the name `couchbasecluster-alice` in place of `couchbasecluster-developer`.

== Create the Operator

At this point you can now use the `developer` user to create the Operator in the `operator-example` project. To create and start the Operator, run the following command:

[source,console]
----
oc create -f https://packages.couchbase.com/kubernetes/0.9.0-beta3/openshift/operator.yaml
----

Running this command downloads the Operator Docker image (specified in the `operator.yaml` file) and creates a https://kubernetes.io/docs/concepts/workloads/controllers/deployment/[deployment], which manages a single instance of the Operator. The Operator uses a deployment so that it can restart if the pod it's running in dies.

After you run the `oc create` command, it generally takes less than a minute for OpenShift to deploy the Operator and for the Operator to be ready to run.

=== Check the Status of the Deployment

You can use the following command to check on the status of the deployment:

[source,console]
----
oc get deployments -l app=couchbase-operator
----

If you run the previous command immediately after the Operator is deployed, the output will look something like the following:

[source,console]
----
NAME                 DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
couchbase-operator   1         1         1            0           10s
----

In this case, the deployment is called `couchbase-operator`. The `DESIRED` field in the output shows that this deployment will create one pod running the Operator. The `CURRENT` field shows that one Operator pod has been created. However, the `AVAILABLE` field indicates that the pod is not ready yet since its value is 0 and not 1. That means that the Operator is still establishing a connection to the Kubernetes master node to allow it to get updates on CouchbaseCluster objects. Once the Operator has completed this task, it will be able to start managing Couchbase Server clusters and the status will be shown as `AVAILABLE`.

You should continue to poll the status of the Operator until the output looks similar to the following:

[source,console]
----
NAME                 DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
couchbase-operator   1         1         1            1           47s
----

=== Check the Status of the Operator

You can use the following command to verify that the Operator has started successfully:

[source,console]
----
oc get pods -l app=couchbase-operator
----

If the Operator is up and running, the command returns an output where the `READY` field shows `1/1`, such as:

[source,console]
----
NAME                                  READY   STATUS   RESTARTS   AGE
couchbase-operator-1917615544-t5mhp   1/1     Running  0          57s
----

You can also check the logs to confirm that the Operator is up and running. Look for the message: `starting couchbaseclusters controller`

[source,console]
----
$ oc logs couchbase-operator-1917615544-t5mhp
time="2018-04-25T03:01:56Z" level=info msg="Obtaining resource lock" module=main
time="2018-04-25T03:01:56Z" level=info msg="Starting event recorder" module=main
time="2018-04-25T03:01:56Z" level=info msg="Attempting to be elected the couchbase-operator leader" module=main
time="2018-04-25T03:02:13Z" level=info msg="I'm the leader, attempt to start the operator" module=main
time="2018-04-25T03:02:13Z" level=info msg="Creating the couchbase-operator controller" module=main
time="2018-04-25T03:02:13Z" level=info msg="Event(v1.ObjectReference{Kind:\"Endpoints\", Namespace:\"default\", Name:\"couchbase-operator\", UID:\"9b86c750-47e7-11e8-866e-080027b2a68d\", APIVersion:\"v1\", ResourceVersion:\"23482\", FieldPath:\"\"}): type: 'Normal' reason: 'LeaderElection' couchbase-operator-75ddfdbdb5-bz7ng became leader" module=event_recorder
time="2018-04-25T03:02:13Z" level=info msg="starting couchbaseclusters controller"
----

== Next Steps

Install the xref:cbopctl.adoc[cbopctl] command line tool and use it to xref:deploying-couchbase.adoc[deploy a Couchbase Server cluster].

== Uninstalling the Operator

.Uninstalling the Operator is a two-step process:

. Delete the Operator.
+
You can delete the Operator as the `developer` or `system:admin` user.
+
[source,console]
----
kubectl delete deployment couchbase-operator
----
+
NOTE: Deleting the Operator from a namespace will not remove or affect any Couchbase pods in your Kubernetes cluster.

. Delete the CRD.
+
NOTE: You can only delete the CRD as the `system:admin` user.
+

Make sure the Operator has been deleted from all other OpenShift projects in the cluster before you delete the CRD. Once the Operator has been deleted, run the following command to delete the CRD:
+
[source,console]
----
kubectl delete crd couchbaseclusters.couchbase.database.couchbase.com
----
