= Introduction

The Couchbase Autonomous Operator provides native integration of Couchbase Server with open source Kubernetes and Red Hat OpenShift.
It enables you to automate the management of common Couchbase tasks such as the configuration, creation, scaling, and recovery of Couchbase clusters.
By reducing the complexity of running a Couchbase cluster, it lets you focus on the desired configuration and not worry about the details of manual deployment and life-cycle management.

== What Does it Support?

The Operator can deploy and manage:

* Couchbase Server Enterprise Edition

The Operator is certified on the following platforms:

* xref:install-kubernetes.adoc[Kubernetes]
* xref:install-openshift.adoc[Red Hat OpenShift]
* xref:tutorial-eks.adoc[Amazon EKS]
* xref:tutorial-gke.adoc[Google GKE]
* xref:tutorial-aks.adoc[Microsoft AKS]

[NOTE]
====
For more information on supported platforms and versions see the xref:prerequisite-and-setup.adoc[system requirements documentation].
====

== How Does it Work?

The Operator extends Kubernetes by defining types that represent Couchbase clusters and resources.
These types are declarative; they define what the cluster should look like.
The Operator monitors Kubernetes for Couchbase resources, creating or updating Couchbase clusters to match the declarative specification.

[NOTE]
====
For more information on what the Operator does, its behavior and its architecture see the xref:concept-operator.adoc[Operator architecture concepts documentation].
====

== What Features Does it Provide?

The goal of the Operator is to fully manage one or more Couchbase deployments so that you don't need to worry about the operational complexities of running Couchbase.
The following is a list of the management tasks that are currently supported:

* Cluster life-cycle
 ** xref:howto-couchbase-create.adoc[Cluster provisioning]
 ** xref:howto-couchbase-scale.adoc[Cluster scaling]
 ** xref:howto-couchbase-upgrade.adoc[Cluster upgrade]
 ** Cluster auto-recovery
* Cluster configuration
 ** xref:howto-persistent-volumes.adoc[Persistent volumes]
 ** xref:howto-server-groups.adoc[Server groups]
 ** xref:howto-xdcr.adoc[Cross data center replication (XDCR)]
 ** xref:howto-tls.adoc[TLS and certificate rotation]
 ** User and group management
 ** xref:howto-backup.adoc[Backup and restore]
 ** xref:howto-prometheus.adoc[Prometheus monitoring]

== Essential Reading

Kubernetes and the Operator are complex systems -- you shouldn't go in unprepared.
The following is a selection of documentation that should be read and understood fully before continuing:

* xref:best-practices.adoc[Best practices] - understand the best way to deploy Couchbase clusters
* xref:prerequisite-and-setup.adoc[System requirements] - understand supported platforms, software and resource requirements
* xref:prerequisite-cloud.adoc[Public cloud prerequisites] - understand how to prepare public clouds to run the Operator
* xref:concept-label-selection.adoc[Custom resource label selection] - understand how Couchbase cluster specifications are built
* xref:concept-couchbase-networking.adoc[Network architectures] - understand how to correctly configure networking for the best experience

== Getting Started

Once you have read the essential guides, you are ready to install the Operator and create your first Couchbase cluster.

* xref:install-kubernetes.adoc[Installing the Operator on Kubernetes]
* xref:install-openshift.adoc[Installing the Operator on Red Hat OpenShift]
* xref:howto-couchbase-create.adoc[Deploying a Couchbase cluster]
* xref:howto-ui.adoc[Connecting to the Couchbase web console]

== Finding Your Way Around

The documentation is organized into easy to navigate sections that are targeted to specific users.
The sections are defined as follows:

Getting Started::
Important platform information and best practice guidelines must be read before proceeding.
This section is also the home of quick-start installation guides.

Learn::
High level architectural documentation and feature descriptions.
This section should be read if you wish to correctly plan and size your Couchbase clusters before deployment.

Manage::
Simple how-to guides.
This section documents how to configure your Couchbase cluster resources with simple copy and paste style tutorials.

Reference::
Detailed resource and component guides.
This section details low-level functionality of all the resources and fields exposed to the user, their formats and constraints.
Individual Operator containers and tools are fully documented with detailed command line argument manuals.

Tutorials::
How to integrate with and configure 3rd party components.
The Operator itself can provision and manage simple clusters for most use cases.
In more complex situations that involve complex networking or interaction with other, external services, we need to provide guidance on how to integrate.
These tutorial are provided as-is and may become inaccurate as 3rd party dependencies evolve.

== Further Reading

* xref:whats-new.adoc[What's New?]
* xref:release-notes.adoc[Release Notes]
