= Prerequisites and System Requirements

To install the Couchbase Autonomous Operator, all you need is a running Kubernetes or OpenShift cluster.

If you don't have access to a Kubernetes cluster, but still want to use the Operator for development, https://kubernetes.io/docs/tasks/tools/install-minikube/[Minikube^] (single-node Kubernetes cluster) and https://developers.redhat.com/products/codeready-containers/overview[Red Hat CodeReady Containers^] (single-node OpenShift cluster) make great free alternatives.
Both of these products are much easier to install and deploy when compared to setting up and running an actual Kubernetes or OpenShift cluster.

== Platform Compatibility

=== Support Definitions

Certified:: Couchbase has performed an extensive testing and review process to make sure that the Operator runs well out of the box on the specified platform.

Supported:: Couchbase believes that the Operator will run well out of the box on the specified platform, but extensive testing has not been performed.
Couchbase will make a best effort to investigate issues on a Supported platform version, but it is recommended that you run the Operator on a Certified platform version.

Developer Preview:: Couchbase is still developing functionality for the specified platform, but you are encouraged to start your own testing and provide early feedback.

=== Couchbase Server Compatibility

[#table-operator-compatibility-couchbase,cols="1,1",options="header"]
|===
| Software | Version

| Couchbase Server Enterprise Edition
| Certified 6.5.1, 6.6

_Unless otherwise stated, maintenance/patch releases (x.x**.X**) inherit the same support level._
|===

=== Kubernetes Platform Compatibility

[#table-operator-compatibility,cols="1,1",options="header"]
|===
| Platform | Version

| Open Source Kubernetes
| Certified 1.19

Supported 1.17, 1.18, 1.20

| Red Hat OpenShift Container Platform
| Certified 4.6

Supported 4.4, 4.5, 4.7
|===

=== Public Kubernetes Service Compatibility

[#table-operator-compatibility-public,cols="1,1",options="header"]
|===
| Service | Support Level

| Amazon EKS
| Certified

| Google GKE
| Certified

| Microsoft AKS
| Certified
|===

[#compatibility-pv]
=== Persistent Volume Compatibility

Persistent volumes are mandatory for production deployments.
Review the xref:best-practices.adoc#persistent-volumes-best-practices[Operator best practices] for more information about cluster supportability requirements.

.Persistent Volume Compatibility List
[#table-operator-compatibility-pv,cols="1,1",options="header"]
|===
| Volume | Support Level

| https://kubernetes.io/docs/concepts/storage/storage-classes/#aws-ebs[AWS EBS^]
| Certified

| https://kubernetes.io/docs/concepts/storage/storage-classes/#azure-disk[Azure Disk^]
| Certified

| https://kubernetes.io/docs/concepts/storage/storage-classes/#ceph-rbd[Ceph RBD^]
| Certified

| https://kubernetes.io/docs/concepts/storage/storage-classes/#gce-pd[GCE PD^]
| Certified

| https://kubernetes.io/docs/concepts/storage/storage-classes/#glusterfs[GlusterFS^]
| Certified

| https://kubernetes.io/docs/concepts/storage/storage-classes/#portworx-volume[Portworx Volume^]
| Certified
|===

== CPU and Memory Requirements

It is highly recommended that your Couchbase clusters are deployed with some form of memory resource request in order to ensure fair scheduling of workloads and to ensure resources are available to meet basic service levels.

You can set all resource allocations yourself explicitly, however for new users to the platform we recommend using xref:resource/couchbasecluster.adoc#spec-autoresourceallocation[auto resource allocation].
Using this feature will require:

* 2 CPUs per Couchbase pod by default.
* 512MiB of memory per pod for each of the Data, Index, Search, and Eventing Services that are enabled.
  1GiB of memory per pod if the the Analytics Service is enabled.
  An additional 25% memory overhead on top of the memory requirements for each service.
  For a typical development cluster where all services are enabled, this would equal 3.75GiB.

You can read more about pod scheduling in the xref:best-practices.adoc#pod-scheduling[best practices] documentation.

== RBAC and Networking Requirements

Preparing the Kubernetes cluster to run the Operator may require setting up proper RBAC and network settings in your Kubernetes cluster.
Before moving forward, review the following documentation:

* xref:reference-operator-rbac.adoc[RBAC]
* xref:concept-kubernetes-networking.adoc[Kubernetes Networking]
* xref:concept-couchbase-networking.adoc[Couchbase Cluster Networking]

== Next Steps

As you're setting up your Kubernetes environment, make sure that you're following the recommended xref:best-practices.adoc[best practices].

Once your Kubernetes environment is set up, you can move on to installing the admission controller and the Operator.

* xref:install-kubernetes.adoc[Installing the Operator on Open Source Kubernetes]
* xref:install-openshift.adoc[Installing the Operator on OpenShift]
