= Public Cloud Prerequisites
:page-aliases: cloud-intro

[abstract]
Vendor specific tasks to perform before installing the Operator.

Kubernetes is supposed to be portable so a workload can be moved seamlessly from one cloud to another.
There is however, scope in Kubernetes that allows for implementations to differ in ways that are not generic.
This page details any tasks that need to be performed before deploying the Operator on public cloud infrastructure.

== Amazon EKS

=== Authentication

Amazon EKS uses proprietary authentication based on IAM.
The use of Couchbase provided tools (xref:reference-cbopinfo.adoc[`cbopinfo`] and `cbopconv`) will require your Kubernetes configuration file to be setup to use IAM authentication.
Instructions for installing the authenticator can be found in the https://docs.aws.amazon.com/eks/latest/userguide/install-aws-iam-authenticator.html[official documentation^].

[#eks-best-practices]
=== Best Practices

Storage classes::
The EBS volume type `io1` is recommended over `gp2` for any Storage Classes due to its performance characteristics.
The https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html[official AWS user guide^] itself recommends `io1` for “Large database workloads”.

== Google GKE

=== Authentication

Google GKE uses proprietary authentication in order to set up your Kubernetes configuration file.
The https://cloud.google.com/sdk/[Google Cloud SDK^] can allow you to authenticate and configure with the `gcloud auth login` command.

=== Authorization

By default, Google GKE does not provide the necessary privileges required to deploy the Autonomous Operator.
The required privileges can be granted to a specific user with the following command:

[source,console]
----
$ kubectl create clusterrolebinding \
  john-doe-admin-binding \ # <.>
  --clusterrole cluster-admin \ # <.>
  --user john.doe@acme.com # <.>
----

<.> The `ClusterRoleBinding` name can be anything you wish.
<.> The `--clusterorle` name refers to a pre-installed role provided by GKE.
<.> The `--user` parameter is the same as your Google Cloud account name used to login to the system.

=== Firewalling

By default, the GKE control plane is firewalled off from Kubernetes nodes.
This behavior stops the Operator dynamic admission controller (DAC) from functioning.
You must configure firewall rules to allow the GKE control plane to connect to port 8443 on the DAC pod.

For further details see the https://github.com/kubernetes/kubernetes/issues/79739[reated issue^] and https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters#add_firewall_rules[how to add a firewall rule^].

== Microsoft Azure

=== Authentication

Microsoft AKS uses proprietary authentication in order to set up your Kubernetes configuration file.
The https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest[Azure CLI^] can allow you to authenticate and configure with the `az login` command.

[#ask-best-practices]
=== Best Practices

Disk limits::
AKS nodes have a maximum disk limit.
This will restrict the number of persistent volumes that can be created within a cluster.
The limits apply on a per-node basis.
For example, if the VM type in your AKS cluster supports a maximum of eight data disks, and you have four nodes in your cluster, then your cluster can support 32 volumes.
+
See the https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes[Azure documentation^] for more information about max data disks.

Single disk per pod::
Given the slow mount time, it’s best to limit each pod to one disk (excluding the default disk).
For example, separate server classes should be created for Data, Index, and Analytics pods.

Consider the limitations of Azure Disks::
Azure Disks are attached to VMs when pods are created.
There are several <<aks-known-issues,known issues>> related to this behavior, most notably that manual intervention is required on node failure, as well as the occurrence of failures related to slow detach/attach times when pods are moved.
+
Third-party storage providers like Portworx decouple volume-to-node attachment by instead creating a replicating pool of storage.
Storage nodes may also be run separately from compute nodes.
Most issues with persistent volumes on AKS are the result of nodes being attached and moved between nodes.


[#aks-known-issues]
=== Known Issues

AKS doesn't support Azure Availability Zones::
At the time of this writing, AKS doesn't support Azure Availability Zones.
Rather, AKS supports Azure Availability Sets to achieve high availability.
+
Availability Sets are labeled numerically (e.g. `0` and `1`).
This means that xref:concept-server-groups.adoc[server groups] also have to be named “0” and “1".

Failed nodes require manual volume failover::
When an Azure node is down and has volumes attached, a forced detach is required.
This has to be done using the Azure CLI.
If a recovery or upgrade is happening at the time of node failover, then it will fail. *On delta recovery create new PVC

Slow volume mounts::
AKS volume mounts may cause pod creation to time out while waiting for the availability of its underlying disks.
The main reason for this is due to the time it takes to attach a disk to the VM versus the time the attach controller expects the disk to be attached.
When the latter exceeds the former, failed mount events are generated and the attach controller enters into a state of high back off wait time:
+
** https://github.com/Azure/AKS/issues/719
** https://github.com/kubernetes/cloud-provider-azure/blob/master/docs/azuredisk-issues.md
** https://portworx.com/understand-resolve-warning-failed-attach-volume-warning-failed-mount-errors-kubernetes-azure/
