= Prerequisites and Setup

To install the Couchbase Autonomous Operator, all you need is a running Kubernetes or OpenShift cluster.

== Platform Compatibility
See the following table for platform compatibility information:

.Couchbase Autonomous Operator Compatibility List

|===

|                | *Open Source Kubernetes* | *Red Hat OpenShift* | *Couchbase Server*

| *Operator 0.9* | 1.9+                     | 3.9+                | 5.5

|===

If you don't have access to a Kubernetes cluster, but still want to use the Operator for development, https://kubernetes.io/docs/tasks/tools/install-minikube/[Minikube] (single-node Kubernetes cluster) and https://docs.openshift.org/latest/minishift/getting-started/installing.html[Minishift] (single-node OpenShift cluster) make great alternatives. Both of these products are much easier to install and deploy when compared to setting up and running an actual Kubernetes or OpenShift cluster.

== RBAC and Networking Requirements

Preparing the Kubernetes cluster to run the Operator may require setting up proper RBAC and network settings in your Kubernetes cluster. Before moving forward, review the following documentation:

* xref:kubernetes-rbac.adoc[RBAC]
* xref:networking.adoc[Networking]

== Next Steps

Once your Kubernetes environment is set up, you can move on to installing the Operator.

* xref:install-kubernetes.adoc[Installing on Kubernetes]
* xref:install-kubernetes-no-rbac.adoc[Installing on Kubernetes (without RBAC)]
* xref:install-openshift.adoc[Installing on OpenShift]
** xref:bootstrap-openshift.adoc[Bootstrapping OpenShift]
+
_Bootstrap automation should only be used in development clusters since it involves granting privileges to the Operator that aren't ideal in a production OpenShift cluster._

For information about how the Operator deployment is defined, as well as documentation about the fields that you might want to customize, see xref:operator-config.adoc[Couchbase Operator Configuration].
