= Prerequisites and System Requirements

To install the Couchbase Autonomous Operator, all you need is a running Kubernetes or OpenShift cluster.

If you don't have access to a Kubernetes cluster, but still want to use the Operator for development, https://kubernetes.io/docs/tasks/tools/install-minikube/[Minikube^] (single-node Kubernetes cluster) and https://developers.redhat.com/products/codeready-containers/overview[Red Hat CodeReady Containers^] (single-node OpenShift cluster) make great free alternatives.
Both of these products are much easier to install and deploy when compared to setting up and running an actual Kubernetes or OpenShift cluster.

== Platform Compatibility

=== Support Definitions

Certified:: Couchbase has performed an extensive testing and review process to make sure that the Operator runs well out of the box on the specified platform.

Supported:: Couchbase believes that the Operator will run well out of the box on the specified platform, but extensive testing has not been performed.
Couchbase will make a best effort to investigate issues on a Supported platform version, but it is recommended that you run the Operator on a Certified platform version.

Developer Preview:: Couchbase is still developing functionality for the specified platform, but you are encouraged to start your own testing and provide early feedback.

=== Couchbase Server Compatibility

[#table-operator-compatibility-couchbase,cols="1,1",options="header"]
|===
| Software | Version

| Couchbase Server Enterprise Edition
| Certified 6.0.4, 6.5, 6.6footnote:202-requirement[Requires Couchbase Autonomous Operator 2.0.2 or later]

_Unless otherwise stated, maintenance/patch releases (x.x**.X**) inherit the same support level._
|===

=== Kubernetes Platform Compatibility

[#table-operator-compatibility,cols="1,1",options="header"]
|===
| Platform | Version

| Open Source Kubernetes
| Certified 1.14, 1.15, 1.16footnote:202-requirement[], 1.17footnote:202-requirement[], 1.18footnote:202-requirement[]

| Red Hat OpenShift Container Platform
| Certified 4.3

Supported 4.1, 4.2
|===

=== Public Kubernetes Service Compatibility

[#table-operator-compatibility-public,cols="1,1",options="header"]
|===
| Service | Support Level

| Amazon EKS
| Certified

| Google GKE
| Certified

| Microsoft AKS
| Certified
|===

[#compatibility-pv]
=== Persistent Volume Compatibility

Persistent volumes are mandatory for production deployments.
Review the xref:best-practices.adoc#persistent-volumes-best-practices[Operator best practices] for more information about cluster supportability requirements.

.Persistent Volume Compatibility List
[#table-operator-compatibility-pv,cols="1,1",options="header"]
|===
| Volume | Support Level

| https://kubernetes.io/docs/concepts/storage/storage-classes/#aws-ebs[AWS EBS^]
| Certified

| https://kubernetes.io/docs/concepts/storage/storage-classes/#azure-disk[Azure Disk^]
| Certified

| https://kubernetes.io/docs/concepts/storage/storage-classes/#ceph-rbd[Ceph RBD^]
| Certified

| https://kubernetes.io/docs/concepts/storage/storage-classes/#gce-pd[GCE PD^]
| Certified

| https://kubernetes.io/docs/concepts/storage/storage-classes/#glusterfs[GlusterFS^]
| Certified

| https://kubernetes.io/docs/concepts/storage/storage-classes/#portworx-volume[Portworx Volume^]
| Certified
|===

== RBAC and Networking Requirements

Preparing the Kubernetes cluster to run the Operator may require setting up proper RBAC and network settings in your Kubernetes cluster.
Before moving forward, review the following documentation:

* xref:reference-operator-rbac.adoc[RBAC]
* xref:concept-kubernetes-networking.adoc[Kubernetes Networking]
* xref:concept-couchbase-networking.adoc[Couchbase Cluster Networking]

== Next Steps

As you're setting up your Kubernetes environment, make sure that you're following the recommended xref:best-practices.adoc[best practices].

Once your Kubernetes environment is set up, you can move on to installing the admission controller and the Operator.

* xref:install-kubernetes.adoc[Installing the Operator on Open Source Kubernetes]
* xref:install-openshift.adoc[Installing the Operator on OpenShift]
