= cbopcfg
include::partial$constants.adoc[]
:tabs:

`cbopcfg` is a command-line tool that is provided in the Couchbase Autonomous Operator https://www.couchbase.com/downloads[package^].
It is used to generate resource configuration to quickly configure and run the Operator.

The `cbopcfg` is not intended to allow configuration of every aspect of the Operator.
We provide xref:helm-setup-guide.adoc[Helm] charts to allow more complex deployment scenarios.

== Installation

Make sure that you have downloaded the Operator https://www.couchbase.com/downloads[package^] and unpacked it.

After you unpack the download, the resulting directory will be titled something like `couchbase-autonomous-operator-kubernetes_x.x.x-linux_x86_64`.

[{tabs}]
====
macOS::
+
--
. Open a Terminal window and go to the directory where the `cbopcfg` binary is located:
+
[source,console]
----
$ cd couchbase-autonomous-operator-kubernetes_x.x.x-macos_x86_64/bin/
----

. Make the `cbopcfg` binary executable:
+
[source,console]
----
$ chmod +x ./cbopcfg
----

. Move the binary into your PATH:
+
[source,console]
----
$ sudo mv ./cbopcfg /usr/local/bin/cbopcfg
----
--

Linux::
+
--
. Open a command prompt and go to the directory where the `cbopcfg` binary is located:
+
[source,console]
----
$ cd couchbase-autonomous-operator-kubernetes_x.x.x-linux_x86_64/bin/
----

. Make the `cbopcfg` binary executable:
+
[source,console]
----
$ chmod +x ./cbopcfg
----

. Move the binary into your PATH:
+
[source,console]
----
$ sudo mv ./cbopcfg /usr/local/bin/cbopcfg
----
--

Windows::
+
--
. Open a command prompt and go to the directory where the `cbopcfg` binary is located:
+
[source,console]
----
$ cd couchbase-autonomous-operator-kubernetes_x.x.x-windows_x86_64\bin\
----

. Add the `cbopcfg` binary into your PATH.
--
====

== Commands

=== cbopcfg generate admission

This command generates YAML to the console that is necessary to create the dynamic admission controller.
By default this is installed at the cluster scope.

The following options are provided:

-n, --namespace <string>::
If specified, this will override the default namespace `default`, or the current active namespace as shown in `kubectl config get-contexts`.

--image <string>::
If specified, this will override the default admission controller image `couchbase/admission-controller:{operator-version}`.

--image-pull-secret <string>::
If specified, this will add the image pull secret name to all deployments.
This is required when pulling images from private container repositories such as the Red Hat container registry.

--scope <string>::
If specified, this will override the default scope `cluster`.
When using the `namespace` scope, then the dynamic admission controller will be deployed with a Kubernetes `Role`.
This limits the ability of the admission controller for security reasons, while maintaining full functionality.
When deployed with the `namespace` scope, you must also specify the `--namepsace-selector` option.

--namespace-selector <string>::
If specified, this configures admission webhooks to select a DAC instance in a specific namespace.
This flag is required when `--cluster` is not set and `--no-admission` is not set e.g. you are creating a namespaced DAC.
+
The format of the flag is a set of key/value pairs e.g. `key=value` or `key1=value1,key2=value2`, where both keys and values are strings.
These key/value pairs define a label selector that defines what namespace the DAC is being installed into.
Kubernetes does _not_ allow the selection of named namespaces, only labeled namespaces.
+
For example, if you wanted to install the DAC into namespace `foo` first you would label it:
+
[source,console]
----
$ kubectl label namespace foo namespace-name=foo
----
+
Then finally reference it in your DAC configuration:
+
[source,console]
----
$ cbopcfg generate admission --scope namespace --namespace-selector namespace-name=foo
----

--validate-secrets | --validate-secrets=<bool>::
If specified, this controls whether secrets referenced by Couchbase resources are checked for existence, and correct formatting.
For TLS secrets, the key and certificate are also validated for correctness for use with Couchbase server.
+
This flag defaults to `true`.
When set to `false` this also removes secret access from the DAC role/cluster role.

--validate-storage-classes | --validate-storage-classes=<bool>::
If specified, this controls whether storage classes referenced by Couchbase resources are checked for existence.
+
This flag defaults to `true`.
When set to `false` this also removes storage class access from the DAC role/cluster role.

=== cbopcfg create admission

This command shares all the same options as `cbopcfg generate admission`, but creates them against the Kubernetes API after generation.

=== cbopcfg delete admission

This command deletes any resources that would have been generated by `cbopcfg generate admission`.
Only the `--scope` option is valid as that controls the resource types under consideration.

=== cbopcfg generate operator

This command generates YAML that is necessary to deploy the Operator.
By default this is installed at the namespace scope.

The following options are provided:

-n, --namespace <string>::
If specified, this will override the default namespace `default`.

--image <string>::
If specified, this will override the default operator image `couchbase/operator:{operator-version}`.

--image-pull-secret <string>::
If specified, this will add the image pull secret name to all deployments.
This is required when pulling images from private container repositories such as the Red Hat container registry.

--scope <string>::
If specified, this will override the default scope `namespace`.
By default the Operator will run in a namespace and will not be able to see resources in another namespace.
This option may be set to `cluster` that will allow a single Operator instance to control Couchbase clusters in all namespace in the Kubernetes cluster.

--log-level <string>::
If specified, this will override the default log level `info`.
Level `info`/`0` is for basic logging.
Level `debug`/`1` is for extended logging and API level call tracing.
Level `2` is for full logging with all API payloads (including passwords and keys).

--pod-creation-timeout <string>::
If specified, this will override the default pod creation timeout `10m`.
This timeout applies to creating a Couchbase server pod and any associated persistent volumes.

=== cbopcfg create operator

This command shares all the same options as `cbopcfg generate operator`, but creates them against the Kubernetes API after generation.

=== cbopcfg delete operator

This command deletes any resources that would have been generated by `cbopcfg generate operator`.
Only the `--scope` option is valid as that controls the resource types under consideration.

=== cbopcfg generate backup

This command generates YAML that is required by backup jobs for status reporting.

The following options are provided:

-n, --namespace <string>::
If specified, this will override the default namespace `default`.

=== cbopcfg create backup

This command shares all the same options as `cbopcfg generate backup`, but creates them against the Kubernetes API after generation.

=== cbopcfg delete backup

This command deletes any resources that would have been generated by `cbopcfg generate backup`.

== Examples

To create the operator in the `default` namespace.

[source,console]
----
$ cbopcfg create operator
----

To create a configuration file:

[source,console]
----
$ cbopcfg generate operator > operator.yaml
----

To create an operator on Red Hat OpenShift:

[source,console]
----
$ oc project myproject
$ cbopcfg create operator --image-pull-secret my-redhat-docker-credentials
----
