= cbopcfg
include::partial$constants.adoc[]
:tabs:

`cbopcfg` is a command-line tool that is provided in the Couchbase Autonomous Operator https://www.couchbase.com/downloads[package^].
It is used to generate resource configuration to quickly configure and run the Operator.

The `cbopcfg` is not intended to allow configuration of every aspect of the Operator.
We provide xref:helm-setup-guide.adoc[Helm] charts to allow more complex deployment scenarios.

== Installation

Make sure that you have downloaded the Operator https://www.couchbase.com/downloads[package^] and unpacked it.

After you unpack the download, the resulting directory will be titled something like `couchbase-autonomous-operator-kubernetes_x.x.x-linux_x86_64`.

[{tabs}]
====
macOS::
+
--
. Open a Terminal window and go to the directory where the `cbopcfg` binary is located:
+
[source,console]
----
$ cd couchbase-autonomous-operator-kubernetes_x.x.x-macos_x86_64/bin/
----

. Make the `cbopcfg` binary executable:
+
[source,console]
----
$ chmod +x ./cbopcfg
----

. Move the binary into your PATH:
+
[source,console]
----
$ sudo mv ./cbopcfg /usr/local/bin/cbopcfg
----
--

Linux::
+
--
. Open a command prompt and go to the directory where the `cbopcfg` binary is located:
+
[source,console]
----
$ cd couchbase-autonomous-operator-kubernetes_x.x.x-linux_x86_64/bin/
----

. Make the `cbopcfg` binary executable:
+
[source,console]
----
$ chmod +x ./cbopcfg
----

. Move the binary into your PATH:
+
[source,console]
----
$ sudo mv ./cbopcfg /usr/local/bin/cbopcfg
----
--

Windows::
+
--
. Open a command prompt and go to the directory where the `cbopcfg` binary is located:
+
[source,console]
----
$ cd couchbase-autonomous-operator-kubernetes_x.x.x-windows_x86_64\bin\
----

. Add the `cbopcfg` binary into your PATH.
--
====

=== Options

component::
This positional parameter must be specified and maust be one of `operator`, `admission` or `backup`.
This specifies the specific component to install.

--namespace <string>::
If specified, this will override the default namespace `default`.
Specifying the namespace is especially important when installing the dynamic admission controller as this flag affects TLS certificate generation.

--operator-image <string>::
If specified, this will override the default operator image `couchbase/operator:{operator-version}`.

--dynamic-admission-controller-image <string>::
If specified, this will override the default admission controller image `couchbase/admission-controller:{operator-version}`.

--image-pull-secret <string>::
If specified, this will add the image pull secret name to all deployments.
This is required when pulling images from private container repositories such as the Red Hat container registry.

--file::
If specified, individual YAML files are created rather than all output going to the console.

--cluster::
If specified, this will configure the DAC/Operator to run at the cluster scope (as opposed to namespace scope) meaning only one instance is required per Kubernetes cluster.

--namespace-selector <string>::
If specified, this configures admission webhooks to select a DAC instance in a specific namespace.
This flag is required when `--cluster` is not set and `--no-admission` is not set e.g. you are creating a namespaced DAC.
+
The format of the flag is a set of key/value pairs e.g. `key=value` or `key1=value1,key2=value2`, where both keys and values are strings.
These key/value pairs define a label selector that defines what namespace the DAC is being installed into.
Kubernetes does _not_ allow the selection of named namespaces, only labeled namespaces.
+
For example, if you wanted to install the DAC into namespace `foo` first you would label it:
+
[source,console]
----
$ kubectl label namespace foo namespace-name=foo
----
+
Then finally reference it in your DAC configuration:
+
[source,console]
----
$ cbopcfg admission -namespace-selector namespace-name=foo
----

== Examples

To create configuration to run the operator in the `default` namespace.

[source,console]
----
$ cbopcfg operator | kubectl create -f -
----

To create a configuration file:

[source,console]
----
$ cbopcfg operator > operator.yaml
----

To create configuration to run on Red Hat Openshift:

[source,console]
----
$ cbopcfg operator --namespace myproject --image-pull-secret my-redhat-docker-credentials > operator.yaml
----
