= CouchbaseBackup and CouchbaseBackupRestore Status
include::partial$constants.adoc[]

[abstract]
Status fields attached to CouchbaseBackup and CouchbaseBackupRestore resources by the Operator.

Each `CouchbaseBackup` and `CouchbaseBackupRestore` resource has a status object.
These resources share very similar status objects which is why they have been collated into this single document.
This object is used to communicate current resources and updates associated with the backup environment.
The provided status information should be helpful in pairing an associate `CouchbaseBackupRestore` resource to a existing `CouchbaseBackup` resource, for example, without requiring to explore the contents of a Persistent Volume Claim.

[IMPORTANT]
====
Status fields should be considered read only.
Any modifications will not affect either resource and will be reverted by the Operator.
====

An example status object may look like the following, with individual attributes explained below:

[source,yaml,subs="attributes"]
----
apiVersion: couchbase.com/v2
kind: CouchbaseBackup
status:
  archive: /data/backups
  capacityUsed: 1.76Gi
  cronjob: cbbackup-full-full
  duration: 13s
  job: cbbackup-full-full-1584385800
  lastRun: "2020-03-16T19:10:10Z"
  lastSuccess: "2020-03-16T19:10:23Z"
  output: '{"location": "2020-03-16T19_10_10.637314674Z", "duration_seconds": "11.992174441",
    "avg_data_transfer_rate_bytes_sec": 7172259, "total_items": 100000, "total_items_size_bytes":
    85951774, "buckets": {"default": {"mutations_backedup": "100000", "mutations_failed":
    "0", "deletions_backedup": "0", "deletions_failed": "0"}}}'
  pod: cbbackup-full-full-1584385800-n6xm8
  repo: cb-example-2020-03-16T19_10_10
  repoList: cb-example-2020-03-16T19_09_09, cb-example-2020-03-16T19_10_10
  running: false
----

The `CouchbaseBackup` custom resource definition defines custom formatting that is used by the following command:

[source,console,subs="attributes",options="nowrap"]
----
$ kubectl get couchbasebackups
NAME            STRATEGY    VOLUME SIZE   CAPACITY USED   LAST RUN               LAST SUCCESS           RUNNING   AGE
my-cbbackup     full_only   5Gi           1.76Gi          2020-03-16T18:48:07Z   2020-03-16T18:48:18Z   false     71s
----

These fields are provided for convenience when looking up and configuring clusters and map to status variables as follows:

STRATEGY::
xref:reference-couchbasebackup.adoc#spec-strategy[`spec.strategy`]

SIZE::
xref:reference-couchbasebackup.adoc#spec-size[`spec.size`]

CAPACITYUSED::
<<status-capacityused,`status.capacityUsed`>>

LASTRUN::
<<status-lastrun,`status.lastRun`>>

LASTSUCCESS::
<<status-lastsuccess, `status.lastSuccess`>>

RUNNING::
<<status-running, `status.running`>>

The `CouchbaseBackupRestore` custom resource definition provides a very similar status object and custom formatting:

[source,yaml,subs="attributes"]
----
apiVersion: couchbase.com/v2
kind: CouchbaseBackupRestore
status:
  archive: /data/backups
  capacityUsed: 2.03Gi
  duration: 11s
  job: cbrestore
  lastRun: "2020-03-16T19:12:51Z"
  lastSuccess: "2020-03-16T19:13:02Z"
  output: '{"buckets": {"default": {"mutations": {"succeeded": "100000", "failed": "0",
    "skipped": "0"}, "deletions": {"succeeded": "0", "failed": "0", "skipped":
    "0"}}}, "backups_restored": "1", "duration_seconds": "10.123074814", "avg_data_transfer_rate_bytes_sec":
    1992294, "total_items": "100000", "total_items_size_bytes": 20143144}'
  pod: cbrestore-ts4br
  repo: cb-example-2020-03-16T19_10_10
  repoList: cb-example-2020-03-16T19_08_10, cb-example-2020-03-16T19_09_09, cb-example-2020-03-16T19_10_10,
    cb-example-2020-03-16T19_11_09, cb-example-2020-03-16T19_12_10
  running: false
----

The `CouchbaseBackupRestore` custom resource definition defines custom formatting that is used by the following command:

[source,console,subs="attributes",options="nowrap"]
----
NAME        CAPACITY USED   LAST RUN               LAST SUCCESS           DURATION   RUNNING   AGE
cbrestore   2.03Gi          2020-03-16T19:12:51Z   2020-03-16T19:13:02Z   11s        false     8s
----

These fields are provided for convenience when looking up and configuring clusters and map to status variables as follows:

CAPACITYUSED::
<<status-capacityused,`status.capacityUsed`>>

LASTRUN::
<<status-lastrun,`status.lastRun`>>

LASTSUCCESS::
<<status-lastsuccess, `status.lastSuccess`>>

DURATION::
<<status-duration, `status.duration`>>

RUNNING::
<<status-running, `status.running`>>

== status

This section defines and describes individual status fields for both `CouchbaseBackup` and `CouchbaseBackupRestore` status objects, unless otherwise stated.

=== status.archive

This is the absolute path of where all backups and logs are stored. Persistent Volume Claims are mounted onto pods at the path `/data`.
This absolute path cannot be changed currently so this field really exists for validation.

____
_Field rules:_ This field will be a string and should always be `{backup-archive}` after the first backup is run.
____

=== status.capacityUsed

The used capacity of the mounted Persistent Volume Claim.

____
_Field rules:_ This field will be a string.
____

=== status.cronjob

This field is only applicable to `CouchbaseBackup` objects and tells us the name of the most recent or currently running Cronjob.

____
_Field rules:_ This field will be a string.
____

=== status.duration

This field tells us how long in seconds the last job took to complete.

____
_Field rules:_ This field will be a duration.
____

=== status.job

The name of the most recent or currently running job.

____
_Field rules:_ This field will be a string.
____

=== status.lastRun

A timestamp telling us when the last job was executed.

____
_Field rules:_ This field will be a string and conform to https://tools.ietf.org/html/rfc3339[RFC-3339^]
____

=== status.lastSuccess

A timestamp telling us when the last job was successful.

____
_Field rules:_ This field will be a string and conform to https://tools.ietf.org/html/rfc3339[RFC-3339^]
____

=== status.output

Output passes through the output of the most recent `cbbackupmgr` execution.

____
_Field rules:_ This field will be a string.
____

=== status.pod

The name of the most recent or currently running pod that runs `cbbackupmgr`.

____
_Field rules:_ This field will be a string.
____

=== status.repo

The name of the folder that we are currently working in or most recently performed operations in.

____
_Field rules:_ This field will be a string.
____

=== status.repoList

repoList provides a list of all the repos that exist in the backup archive `{backup-archive}`, which should aid in selecting one to create a `CouchbaseBackupRestore`.
____
_Field rules:_ This field will be a string.
____

=== status.running

Whether the condition is `True` or `False`.

____
_Field rules:_ This field will be a string, and either `True` or `False`.
____
