= `CouchbaseBackup` Resource

:toc: macro

Once you have allowed the Autonomous Operator to manage and perform Automated Backup, you will need to create a `CouchbaseBackup` object to specify the timings and details of the backups.

A `CouchbaseBackup` object will spawn either 1 or 2 cron jobs that belong to that resource, and those cron jobs in turn will create the Kubernetes jobs which perform the backup jobs themselves.

The following YAML shows all possible fields that may be configured for a `CouchbaseBackup`.
In this case the following YAML is completely valid.

.All available `CouchbaseBackup` configuration parameters
[source,yaml]
----
apiVersion: couchbase.com/v2
kind: CouchbaseBackup
metadata:
  name: my-backup
  labels:
    cluster: my-cluster
spec:
  strategy: full_incremental
  full:
    schedule: "0 3 * * 0"
  incremental:
    schedule: "0 3 * * 1-6"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  backOffLimit: 2
  backupRetention: 24h
  logRetention: 24h
  size: 5Gi
  s3bucket: my-backup-bucket
  storageClassName: standard
----

toc::[]

== Top-Level Definitions

The following are the top-level parameters that can be defined:

[source,yaml]
----
apiVersion: couchbase.com/v2
kind: CouchbaseBackup
metadata:
  name: my-backup
  labels:
    cluster: my-cluster
----

=== `apiVersion`

The API version defines which version of the resource this configuration refers to.

____
_Field rules:_ This field is required and must be set to `couchbase.com/v2`
____

=== `kind`

The kind defines the type of resource this configuration refers to.

____
_Field rules:_ This field is required and must be set to `CouchbaseBackup`
____

=== `metadata.name`

The metadata name defines the name of the resource.
The name must be unique for the kind defined.

____
_Field rules:_ This field is required and must be unique as described above.
____

=== `metadata.labels`

The metadata labels allow the resource to be tagged so that it is only selected by specific `CouchbaseCluster` resources.
Further details about resource selection can be found on the xref:concept-label-selection.adoc[Couchbase Resources and RBAC page].

____
_Field rules:_ This field is optional and must be a map of string key/value pairs.
____

== `spec`

The following are parameters that may be set on the `CouchbaseBackup`:

[source,yaml]
----
spec:
  strategy: full_incremental
  full:
    schedule: "0 3 * * 0"
  incremental:
    schedule: "0 3 * * 1-6"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  backOffLimit: 2
  backupRetention: 24h
  logRetention: 24h
  size: 5Gi
  s3bucket: my-backup-bucket
  storageClassName: standard
----

=== `spec.strategy`

This field defines which backup strategy to use for Automated Backup.
The following backup strategies are supported: _Full Backup Only_ and _Full/Incremental_.
For more information about these backup strategies, please refer to the xref:server:backup-restore:cbbackupmgr-strategies.adoc[`cbbackupmgr` documentation].

____
_Field rules:_ This field is required and must be either `full_only` or `full_incremental`.
____

=== `spec.full.schedule`

This field defines the schedule a user wants the Operator to perform a full backup of the cluster.

____
_Field rules:_ This field is required for both strategies and must be a valid Cron schedule.
____

=== `spec.incremental.schedule`

This field defines the schedule a user wants the Operator to perform an incremental backup of the cluster.

____
_Field rules:_ This field is only required for a `full_incremental` strategy and must be a valid Cron schedule.
____

=== `spec.successfulJobsHistoryLimit`

This field defines the amount of successful jobs to keep before Kubernetes starts deleting older ones.

____
_Field rules:_ This field is optional and must be any non-negative integer. The default value is 3.
____

=== `spec.failedJobsHistoryLimit`

This field defines the amount of failed jobs to keep before Kubernetes starts deleting older ones.

____
_Field rules:_ This field is optional and must be any non-negative integer. The default value is 5.
____

=== `spec.backOffLimit`

This field defines the amount of times one backup job will try to perform a backup.
Once it has reached the back off limit the job will no longer run and the next attempted backup will occur at the next run of the cron job.

____
_Field rules:_ This field is optional and must be any non-negative integer. The default value is 2.
____

=== `spec.backupRetention`

This field defines the time period in which to retain existing backups.
On each run of a backup job older backups outside this time frame are deleted.

____
_Field rules:_ This field is optional and defaults to `720h` (30 days). If specified it must contain a decimal number and a unit suffix such as `s`, `m` or `h`.  The decimal number cannot be negative.
____

=== `spec.logRetention`

This field defines the time period in which to retain backup logs. Older logs outside this time frame are deleted.
On each run of a backup job logging takes place which is stored on the Persistent Volume of the same name as the `CouchbaseBackup` object.

____
_Field rules:_ This field is optional and defaults to `168h` (7 days). If specified it must contain a decimal number and a unit suffix such as `s`, `m` or `h`.  The decimal number cannot be negative.
____

=== `spec.size`

This field defines the size of the Persistent Volume to store backups and logs on.

____
_Field rules:_ This field is optional and defaults to `20Gi`. If specified the field must be a Kubernetes https://godoc.org/k8s.io/apimachinery/pkg/api/resource#Quantity[resource quantity^].
____

=== `spec.s3bucket`

This field defines the name of the AWS S3 bucket to perform backup and restore operations on.
For further information see xref:howto-backup.adoc#backup-and-restore-to-s3[Backup and Restore to S3].

____
_Field rules:_ This field is optional and must be a valid S3 bucket.
____

=== `spec.storageClassName`

This field defines the Storage Class of the Persistent Volume to store backups and logs on.

____
_Field rules:_ This field is optional and must be a valid Storage Class.
____
