= `CouchbaseRoleBinding` Resource

:toc: macro

The Couchbase Autonomous Operator operates on `CouchbaseCluster` objects.

`CouchbaseRoleBinding` resources are analogous to Kubernetes `RoleBinding` resources.

The following YAML shows all possible fields that may be configured for a `CouchbaseRoleBinding`.
This configuration may not be valid and is only for illustrative purposes.

.All available `CouchbaseRoleBinding` configuration parameters
[source,yaml]
----
apiVersion: couchbase.com/v2
kind: CouchbaseRoleBinding
metadata:
  name: my-role-binding
spec:
  subjects:
  - kind: CouchbaseUser
    name: my-user
  roleRef:
    kind: CouchbaseGroup
    name: my-group
----

toc::[]

== Top-Level Definitions

The following are relevant generic parameters that can be defined:

[source,yaml]
----
apiVersion: couchbase.com/v2
kind: CouchbaseRoleBinding
metadata:
  name: my-cluster
----

=== `apiVersion`

The API version defines which version of the resource this configuration refers to.

____
_Field rules:_ This field is required and must be set to `couchbase.com/v2`
____

=== `kind`

The kind defines the type of resource this configuration refers to.

____
_Field rules:_ This field is required and must be set to `CouchbaseRoleBinding`
____

=== `metadata.name`

The metadata name defines the name of the resource.
The name must be unique for the kind defined.

____
_Field rules:_ This field is required and must be unique as described above.
____

== `spec`

The following are parameters that may be set on the role binding:

[source,yaml]
----
spec:
  subjects:
  - kind: CouchbaseUser
    name: my-user
  roleRef:
    kind: CouchbaseGroup
    name: my-group
----

=== `spec.subjects[]`

This field is a list of subjects to a apply role to.

=== `spec.subjects[].kind`

This defines the the type of resource to apply the role to.

____
_Field rules:_ This field is required and must be either `CouchbaseUser` or `CouchbaseGroup`.
____

=== `spec.subjects[].name`

This defines the the name of the resource to apply the role to.

____
_Field rules:_ This field is required and must be the name of an existing `CouchbaseUser` or `CouchbaseGroup`.
____

=== `spec.roleRef.kind`

This field defines the type of resource to extract the roles from.

____
_Field rules:_ This field is required and must be `CouchbaseGroup`.
____

=== `spec.roleRef.name`

This defines the the name of the resource to extract the roles from.

____
_Field rules:_ This field is required and must be the name of an existing `CouchbaseGroup`.
____
