= Release Notes

Couchbase Autonomous Operator 1.0 provides the first native integration of Couchbase Server with Kubernetes platforms.

The goal of the Operator is to fully manage one or more Couchbase Server deployments so that you don’t need to worry about the operational complexities of running Couchbase. The following is a summary of the Couchbase features and management tasks that are currently supported:

* Cluster configuration

* Cluster provisioning

* Ad-hoc scalability

* Auto-recovery

* Configuration validation

* XDCR

* Server groups

* TLS

* Persistent volume support

Couchbase Autonomous Operator 1.0 was released in August 2018.

== Platform Support

For the latest platform support information, see xref:prerequisite-and-setup.adoc[Prerequisites].

== Known Issues and Limitations

.Known Limitations
* Upgrading Couchbase Server using the Operator is not currently supported.

* The Operator manages the state of the Couchbase Server cluster. Therefore, at this time, all cluster configuration changes must be made by modifying the CouchbaseCluster configuration file and pushing it to Kubernetes. Any manual changes to the configuration that are made using the Couchbase Server Web Console, CLI, REST API, or SDK will be reverted by the Operator. This includes things like adding a node or creating a server group.
+
The one exception is when `disableBucketManagement` is set to `true` in the CouchbaseCluster configuration (the default is `false`). If this is the case, the creation and deletion of Couchbase buckets must be done manually. Refer to the CouchbaseCluster xref:couchbase-cluster-config.adoc[documentation] for more information.

.Known Issues
[#table_knownissues_v1,cols="25,66"]
|===
| Issue | Description

| https://issues.couchbase.com/browse/K8S-504[K8S-504]
| *Summary*: Pod volumes are deleted when pods are deleted.
As a result, important debugging information may not be available after a failure.

| https://issues.couchbase.com/browse/K8S-538[K8S-538]
| *Summary*: `cbopinfo` does not redact potentially sensitive information from all logs.

| https://issues.couchbase.com/browse/K8S-493[K8S-493]
| *Summary*: It's not possible to attach a persistent volume to the Couchbase logs directory for deployments when Couchbase data is not written to a persistent volume.
This means that important debugging information may be unavailable during failure situations.

*Workaround*: You should always deploy Couchbase clusters in production with persistent volumes.

| https://issues.couchbase.com/browse/K8S-556[K8S-556]
| *Summary*: Only dynamic volume provisioning via storage classes is supported.

| https://issues.couchbase.com/browse/K8S-389[K8S-389]
| *Summary*: Kubernetes doesn't allow the setting of ulimit parameters on individual containers.

*Workaround*: You can set ulimits on the physical machine that Kubernetes is running on; the ulimit parameters will be inherited by the containers.

| https://issues.couchbase.com/browse/K8S-531[K8S-531]
| *Summary*: When the same event occurs on different Couchbase nodes, the event order is not reported consistently.
This may affect applications that rely on the event order to be consistent when checking the status of a Couchbase cluster.

| https://issues.couchbase.com/browse/K8S-421[K8S-421]
| *Summary*: If a cluster is scaling up when not enough nodes are present, the Operator will not rebalance the cluster even if some nodes can be added.

*Workaround*: You should ensure that sufficient resources are present in the Kubernetes cluster before scaling a Couchbase cluster.

| https://issues.couchbase.com/browse/K8S-89[K8S-89]
| *Summary*: If you manually increase the number of replicas of a bucket, then the Operator may rebalance the cluster before reverting the bucket's changes.

*Workaround*: You should always change the CouchbaseCluster configuration through the Operator.
If you change the CouchbaseCluster configuration directly on the cluster (such as through the Couchbase Server Web Console), then the Operator will revert those changes.

| https://issues.couchbase.com/browse/K8S-537[K8S-537]
| *Summary*: In rare cases, Kubernetes can drop events that are logged by the Operator.

|===

== Feedback

You can have a big impact on future versions of the Operator (and its documentation) by providing Couchbase with your direct feedback and observations. Please feel free to post your questions and comments to the https://forums.couchbase.com/c/couchbase-server/Kubernetes[Couchbase Forums].

== Licenses for Third-Party Components

The complete list of licenses for Couchbase products is available on the https://www.couchbase.com/legal/agreements[Legal Agreements] page. Couchbase is thankful to all of the individuals that have created these third-party components.

== More Information

* xref:server:release-notes:relnotes.adoc[Couchbase Server Release Notes]
