= Release Notes for Couchbase Autonomous Operator {operator-version-minor}
include::partial$constants.adoc[]

Autonomous Operator {operator-version-minor} introduces a preview of our new Cluster Migration functionality well as a number of other improvements and minor fixes.

Take a look at the xref:whats-new.adoc[What's New] page for a list of new features and improvements that are available in this release.

== Installation

For installation instructions, refer to:

* xref:install-kubernetes.adoc[]
* xref:install-openshift.adoc[]

== Upgrading to Autonomous Operator {operator-version-minor}

The necessary steps needed to upgrade to this release depend on which version of the Autonomous Operator you are upgrading from.

=== Upgrading from 1.x, 2.0, or 2.1

There is no direct upgrade path from versions prior to 2.2.0.
To upgrade from a 1.x, 2.0.x, or 2.1.x release, you must first upgrade to 2.4.x, paying particular attention to supported Kubernetes platforms and Couchbase Server versions.
Refer to the xref:2.4@operator::howto-operator-upgrade.adoc[Operator 2.4 upgrade steps] if upgrading from a pre-2.2 release.

=== Upgrading from 2.2, 2.3, 2.4, 2.5, 2.6, or 2.7

There are no additional upgrade steps when upgrading from these versions, and you may follow the xref:howto-operator-upgrade.adoc[standard upgrade process].

For further information read the xref:concept-upgrade.adoc[Couchbase Upgrade] concepts page.

[#release-v280]
== Release 2.8.0

Couchbase Autonomous Operator 2.8.0 was released in March 2025.

[#changes-in-behavior-v280]
=== Changes in Behaviour

==== Admission Controller Changes

The Dynamic Admission Controller (DAC) will now warn if any cluster settings don't match our xref:best-practices.adoc#production-deployments[Best Practices for Production Deployments].

The DAC will now prevent changes to the `CouchbaseCluster` spec while a hibernation is taking place.
If hibernation is enabled while a cluster is migrating, upgrading, scaling, or rebalancing, that process will conclude before the cluster enters hibernation. The DAC will warn when this is the case, and it will be visible in the operator logs.

To prevent any invalid resources failing to reconcile (i.e. if the DAC is not deployed in the current environment), the DAC Validation is now run at the beginning of the reconciliation loop.
Any invalid resources will be skipped for reconciliation, marked as `NotValid`, and logged.

==== Bucket and Index Service Settings

In a previous version of the Operator, `enablePageBloomFilter` was unfortunately missed from the Index Service settings.
This has been addressed in CAO 2.8.0, and it is now available as xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-cluster-indexer-enablepagebloomfilter[`couchbaseclusters.spec.cluster.indexer.enablePageBloomFilter`].

Until CAO 2.8.0, Bucket Compaction settings were only available to be set in the xref:resource/couchbasecluster.adoc[`CouchbaseCluster`] resource, at xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-cluster-autocompaction[`couchbaseclusters.spec.cluster.autoCompaction`].
These settings have now been added to the xref:resource/couchbasebucket.adoc[`CouchbaseBucket`] resource at xref:resource/couchbasebucket.adoc#couchbasebuckets-spec-autocompaction[`couchbasebuckets.spec.autoCompaction`].

[IMPORTANT]
====
Prior to Operator 2.8.0, the above settings could still be set directly on the cluster.

To avoid these being reset to default values during the CAO upgrade, any of the above settings that have been changed must be added to the appropriate resource during the upgrade.

Specifically, this needs to be done _after_ updating the CRDs, and _before_ installing the new Operator

For further information see xref:howto-operator-upgrade.adoc#update-existing-resources[Update Existing Resources].
====

==== Metrics Changes

A number of new metrics have been added, see xref:reference-prometheus-metrics.adoc[Prometheus Metrics Reference] for details.

It is now possible to include the Couchbase Cluster UUID, or Cluster UUID and Cluster Name, as labels with any Operator metric that is related to a specific Couchbase Cluster.
This can be enabled by setting `optional-metric-labels` to either `uuid-only` or `uuid-and-name`, when using xref:tools/cao.adoc#cao-create-operator-flags[cao create operator] or xref:tools/cao.adoc#cao-generate-operator-flags[cao generate operator].

While adding the Couchbase Cluster UUID and Cluster Name labels, it was discovered that there were inconsistencies regarding the Kubernetes Namespace and Cluster Resource Name labels in some of the existing metrics.
Some had separate labels for `namespace` and `name`, and some had a combined `namespace/name` label.
In order to provide consistency, all metrics by default now have separate `name` and `namespace` labels.
The previous behavior, where a small number of metrics had the combined form of the label, can be achieved by setting `separate-cluster-namespace-and-name` to `false`, when using xref:tools/cao.adoc#cao-create-operator-flags[cao create operator] or xref:tools/cao.adoc#cao-generate-operator-flags[cao generate operator].

==== Annotation Changes

===== Storage Backend Migration

As an enhancement to the Couchstore/Magma migration functionality added in Operator 2.7, CAO 2.8.0 adds two new annotations:

* Bucket Migrations are now disabled by default, to prevent unexpected node rebalances.  These can be enabled with xref:reference-annotations.adoc#cao-couchbase-combuckets-enablebucketmigrationroutines[`cao.couchbase.com/buckets.enableBucketMigrationRoutines`].
* Similar to a maintenance upgrade, it is now possible to specify how many Pods can be migrated at a time with xref:reference-annotations.adoc#cao-couchbase-combuckets-maxconcurrentpodswaps[`cao.couchbase.com/buckets.maxConcurrentPodSwaps`].

===== History Retention

The annotations related to History Retention, that were added in Operator 2.4.1, have now been added to the xref:resource/couchbasebucket.adoc[`CouchbaseBucket`], and xref:resource/couchbasecollection.adoc[`CouchbaseCollection`] resources, at xref:resource/couchbasebucket.adoc#couchbasebuckets-spec-historyretention[`couchbasebuckets.spec.historyRetention`], and xref:resource/couchbasecollection.adoc#couchbasecollections-spec-history[`couchbasecollections.spec.history`], respectively.

The History Retention annotations should be considered deprecated, and it should be noted that if used, they will take precedence over the equivalent values in the resources.
Care should be taken to make sure that the annotations are removed as soon as the resources have been updated with the new attributes.

[#fixed-issues-v280]
=== Fixed Issues

[#table-fixed-issues-v280,cols="25,66"]
|===
| Issue | Description

a| https://jira.issues.couchbase.com/browse/K8S-3558[K8S-3558^]
a| *Summary:* Operator commences an In-place Upgrade when the cluster is under-resourced.

a| https://jira.issues.couchbase.com/browse/K8S-3579[K8S-3579^]
a| *Summary:* Operator tries to change invalid bucket configurations in a loop.

a| https://jira.issues.couchbase.com/browse/K8S-3591[K8S-3591^]
a| *Summary:* Operator crashes if Incremental Backup is missing schedule.

a| https://jira.issues.couchbase.com/browse/K8S-3596[K8S-3596^]
a| *Summary:* Crash in Operator due to invalid memory access.

a| https://jira.issues.couchbase.com/browse/K8S-3605[K8S-3605^]
a| *Summary:* Upgrade Swap Rebalance is retried with different parameters on Operator Pod deletion.

a| https://jira.issues.couchbase.com/browse/K8S-3609[K8S-3609^]
a| *Summary:*  Hibernation fails to bring back any Pod with error extracting image version.

a| https://jira.issues.couchbase.com/browse/K8S-3621[K8S-3621^]
a| *Summary:* Shadowed Secret did not get updated.

a| https://jira.issues.couchbase.com/browse/K8S-3632[K8S-3632^]
a| *Summary:* Unable to set -1 for Collection-level `maxTTL`.

a| https://jira.issues.couchbase.com/browse/K8S-3639[K8S-3639^]
a| *Summary:* Operator loses track of pending Pods when an Eviction of the Operator Pod occurs.

a| https://jira.issues.couchbase.com/browse/K8S-3641[K8S-3641^]
a| *Summary:*  Crash in `handleVolumeExpansion` if `enableOnlineVolumeExpansion` is True but no Volume Mounts configured.

a| https://jira.issues.couchbase.com/browse/K8S-3655[K8S-3655^]
a| *Summary:*  Clear Upgrade condition if the Operator isn't performing an upgrade.

a| https://jira.issues.couchbase.com/browse/K8S-3659[K8S-3659^]
a| *Summary:*  When scaling down, Cluster does not maintain balance across Server Groups.

a| https://jira.issues.couchbase.com/browse/K8S-3696[K8S-3696^]
a| *Summary:*  DAC prevents configuration of multiple XDCR Replications of same Buckets to different remote Clusters.

a| https://jira.issues.couchbase.com/browse/K8S-3772[K8S-3772^]
a| *Summary:* Self-Certification: Artifacts PVC should use `--storage-class` parameter when creating the Certification Pod.

a| https://jira.issues.couchbase.com/browse/K8S-3788[K8S-3788^]
a| *Summary:* Operator container crashes when there is a managed Scope/Collection Group added for the Ephemeral Bucket.

|===

[#known-issues-v280]
=== Known Issues

[#table-known-issues-v280,cols="25,66"]
|===
| Issue | Description

a| https://jira.issues.couchbase.com/browse/K8S-3617[K8S-3617^]
a| *Summary:* It is not currently possible to set xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-cluster-indexer-redistributeindexes[`couchbaseclusters.spec.cluster.indexer.redistributeIndexes`] from True to False during a reconciliation.

a| https://jira.issues.couchbase.com/browse/K8S-3908[K8S-3908^]
a| *Summary:* Metric `couchbase_operator_memory_under_management_bytes` is incorrectly showing 0.

a| https://jira.issues.couchbase.com/browse/K8S-3909[K8S-3909^]
a| *Summary:* Metric `couchbase_operator_cpu_under_management` is incorrectly showing 0.

a| https://jira.issues.couchbase.com/browse/K8S-3910[K8S-3910^]
a| *Summary:* Operator tries to migrate storage backend of buckets even before couchbase cluster is in 7.6.0+.

|===

== Feedback

You can have a big impact on future versions of the Operator (and its documentation) by providing Couchbase with your direct feedback and observations.
Please feel free to post your questions and comments to the https://forums.couchbase.com/c/couchbase-server/Kubernetes[Couchbase Forums].

== Licenses for Third-Party Components

The complete list of licenses for Couchbase products is available on the https://www.couchbase.com/legal/agreements[Legal Agreements] page.
Couchbase is thankful to all of the individuals that have created these third-party components.

== More Information

* xref:server:release-notes:relnotes.adoc[Couchbase Server Release Notes]