= Release Notes for Couchbase Autonomous Operator {operator-version-minor}
include::partial$constants.adoc[]

Couchbase Autonomous Operator {operator-version-minor} is an incremental release that improves general behavior and security.
It also extends functionality to allow automatic scaling of your Couchbase cluster resources, and provides additional configuration options.

Take a look at the xref:whats-new.adoc[What's New] page for a list of new features and improvements that are available in this release.

[#release-v210]
== Release 2.1.0

Couchbase Autonomous Operator 2.1.0 was released in December 2020.

[#supported-platforms-v210]
=== Platform Support

For the latest platform support information, refer to xref:prerequisite-and-setup.adoc[].

==== New Platform Support

This release adds support for the following platforms:

* Open Source Kubernetes 1.19
* Red Hat OpenShift Container Platform 4.4, 4.5, 4.6

==== Removed Platform Support

This release drops support for the following platforms:

* Couchbase Server 6.0
* Open Source Kubernetes 1.14
* Red Hat OpenShift Container Platform 4.1, 4.2

[#changes-in-behavior-v210]
=== Major Behavior Changes and Enhancements

==== Improved Pod Readiness Checks

Prior to this release, pod readiness was preformed with an exec based probe that looked for the presence of an operator created file.
This required the "pods/exec" privilege, and is a security concern in some environments.

The new method uses pod readiness gates, updating Kubernetes resources directly, and using existing required permissions.
When upgrading to this release from an earlier one, existing Couchbase Clusters must undergo an upgrade to begin using this new readiness method.

Additionally, Kubernetes clusters must be of version 1.14 or higher before upgrading the Operator.

==== Improved Support for Ephemeral Clusters

Ephemeral, in-memory caching has been a highly requested feature.
With this release, we make ephemeral clusters more automated and highly-available.

Ephemeral clusters will now recover from a total outage -- where all pods are deleted or enter into an error state.
They can also enable forced failover -- where Couchbase Server inhibits auto-failover due to potential data loss, however being ephemeral, the data is lost regardless.

These improvements will ease platform adoption as the Operator will constantly retry to create clusters, rather than entering into a failed state.

[#fixed-issues-v210]
=== Fixed Issues

[#table-fixed-issues-v210,cols="25,66"]
|===
| Issue | Description

a| https://issues.couchbase.com/browse/K8S-1676[K8S-1676^]
a| *Summary:* The `Snappy` compression type was removed from the XDCR API from Couchbase Server 6.5.1 onward.
As the Operator now supports 6.5.0+, this compression type has also been removed from the `CouchbaseReplication` Kubernetes configuration API.
This is a backwards incompatible change.
Modify all replications to use either `None` or `Auto` before upgrading existing clusters to Operator 2.1.0.

a| https://issues.couchbase.com/browse/K8S-1675[K8S-1675^]
a| *Summary:* A bucket -- by default -- is named after the Kubernetes resource, but may also be named explicitly in the bucket specification.
The dynamic admission controller performed validation on replications, ensuring a corresponding named source bucket existed.
This validation only looked at the Kubernetes resource name, and not the explicit name.
The DAC now respect the explicit name overriding the resource name when validating.

a| https://issues.couchbase.com/browse/K8S-1532[K8S-1532^]
a| *Summary:* The cluster upgrade mechanism used to rely on the `CouchbaseCluster` status for stateful operations.
The status shouldn't be relied upon for state, as it is not always preserved.
This may in certain cases result in the Couchbase Server version as reported by the status being incorrect.

a| https://issues.couchbase.com/browse/K8S-1471[K8S-1471^]
a| *Summary:* IP address ranges on Couchbase Server pod services could not be updated.

a| https://issues.couchbase.com/browse/K8S-1415[K8S-1415^]
a| *Summary:* The `Available` condition on `CouchbaseCluster` status was set to `true` once the initial pod was created for a cluster.
This behavior has been modified to only set the condition once the cluster is fully scaled to the initial size.
`Available` now correctly reflects that the cluster is available and ready for use.
|===

[#release-v203]
== Release 2.0.3

Couchbase Autonomous Operator 2.0.3 was released in November 2020.

[#fixed-issues-v203]
=== Fixed Issues

[#table-fixed-issues-v203,cols="25,66"]
|===
| Issue | Description

a| https://issues.couchbase.com/browse/K8S-1736[K8S-1736^]
a| *Summary:* When running a Couchbase cluster with persistent volume storage and TLS, the Operator is unable to recover the cluster in the event of a total loss of all Couchbase Server pods.
|===

[#release-v202]
== Release 2.0.2

Couchbase Autonomous Operator 2.0.2 was released in August 2020.

[#supported-platforms-v202]
=== Platform Support

For the latest platform support information, refer to xref:prerequisite-and-setup.adoc[].

==== New Platform Support

This release adds support for the following platforms/versions:

* Couchbase Server Enterprise Edition 6.6 (Certified)
* Open Source Kubernetes 1.16 (Certified), 1.17 (Certified), 1.18 (Certified)
* Red Hat OpenShift Container Platform 4.3 (Certified)

==== Removed Platform Support

This release drops support for the following platforms/versions:

* Open Source Kubernetes 1.13

[#fixed-issues-v202]
=== Fixed Issues

[#table-fixed-issues-v202,cols="25,66"]
|===
| Issue | Description

a| https://issues.couchbase.com/browse/K8S-1600[K8S-1600^]
a| *Summary:* An issue can occur where the Autonomous Operator incorrectly populates the Prometheus sidecar's container specification.
This only applies to configurations using TLS, and causes the Prometheus exporter to be unable to start.

a| https://issues.couchbase.com/browse/K8S-1492[K8S-1492^]
a| *Summary:* A memory leak in a 3rd party library dependency causes the Autonomous Operator to continually allocate memory until the host system detects memory exhaustion and terminates the Autonomous Operator process.
In some circumstances, this can lead to the Autonomous Operator being unable to restart due to lock contention.
|===

[#known-issues-v202]
=== Known Issues

[#table-known-issues-v202,cols="25,66"]
|===
| Issue | Description

a| https://issues.couchbase.com/browse/K8S-1585[K8S-1585^]
a| *Summary:* When running applications (such as Sync Gateway) that are using DNS SRV over TLS to connect to a Couchbase Cluster in the same Kubernetes cluster, lookup may fail hostname validation checks.

*Workaround:* Add wildcard matches to the Subject Alternate Names (SANs) in the certificate for the Kubernetes-based host names. Specifically, add `DNS:*.$\{cluster}.$\{namespace}.svc` and `DNS:$\{cluster}-srv.$\{namespace}.svc` as discussed in the xref:tutorial-tls.adoc#creating-a-couchbase-cluster-server-certificate[Creating TLS Certificates] tutorial.

a| https://issues.couchbase.com/browse/K8S-1532[K8S-1532^]
a| *Summary:* When using the Autonomous Operator to upgrade Couchbase Server from version 6.5.0 to 6.5.1, the resulting deployment may still show 6.5.0 as the version, even though the individual nodes in the pods are in fact running version 6.5.1.
////
Include the following statement in the description of this issue when it is moved to the fixed issues table in the 2.1 RN.
It was possible that when using the Autonomous Operator to upgrade Couchbase Server from version 6.5.0 to 6.5.1, the resulting deployment would still show 6.5.0 as the version, even though the individual nodes in the pods are in fact running version 6.5.1.
Now, when an upgrade of Couchbase Server completes, the correct upgraded version is shown.
////
a| https://issues.couchbase.com/browse/K8S-1483[K8S-1483^]
a| *Summary:* Logging is provided by a 3rd party library.
This library adds in a sampler that can cause an array out of bounds panic due to non-standard log levels, and is generally not compatible with Couchbase support processes.

This library will be removed or replaced in a future release of the Autonomous Operator.
////
Include the following statement in the description of this issue when it is moved to the fixed issues table in the 2.1 RN.
Prior to Autonomous Operator 2.1, logging was provided by a 3rd party library that is no longer used.
It provided additional logging functionality that was neither advertised in the reference guide, supported, nor compatible with Couchbase support processes.
As a result, this functionality has been removed.
////
a| https://issues.couchbase.com/browse/K8S-1168[K8S-1168^]
a| *Summary:* Pod readiness is performed with an exec-based probe that looks for the presence of an operator-created file.
This requires the "pods/exec" privilege, and is a security concern in some environments.

A new readiness method will be implemented in a future release of the Autonomous Operator.
////
Include the following statement in the description of this issue when it is moved to the fixed issues table in the 2.1 RN.
Autonomous Operator 2.1 implements a new method that uses pod readiness gates, updating Kubernetes resources directly, and using existing required permissions.
When upgrading to this release from an earlier one, existing Couchbase clusters must undergo an upgrade to begin using this new readiness method.
Additionally, Kubernetes clusters must be of version 1.14 or higher before upgrading the Autonomous Operator to version 2.1.
////
a| https://issues.couchbase.com/browse/K8S-968[K8S-968^]
a| *Summary:* CRDs are now generated directly from source using upstream tooling.
As a result, some attributes in the CRD may not be compatible with older versions of Kubernetes.
An error containing the following message can be ignored, and you can feel free to follow the instructions in the message.

[source,console]
----
unknown field "x-kubernetes-list-type" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps]; if you choose to ignore these errors, turn validation off with --validate=false` is 
----
|===

[#release-v201]
== Release 2.0.1

Couchbase Autonomous Operator 2.0.1 was released in May 2020.

[#changes-in-behavior-v201]
=== Major Behavior Changes and Enhancements

* *Support for node-to-node encryption*
+
--
Starting with this release, the Autonomous Operator now supports Couchbase Server xref:server:learn:clusters-and-availability/node-to-node-encryption.adoc[node-to-node encryption].

Node-to-node encryption can be enabled with the new xref:reference-couchbasecluster.adoc#spec-networking-tls-nodetonodeencryption[`spec.networking.tls.nodeToNodeEncryption`] field in the xref:reference-couchbasecluster.adoc[`CouchbaseCluster`] resource.
--

* *Bucket name handling*
+
--
In Autonomous Operator version 2.0.0, it wasn't possible to have two clusters in a single namespace that utilized xref:reference-couchbasebucket.adoc[`CouchbaseBucket`] resources that had the same xref:reference-couchbasebucket.adoc#metadata-name[`metadata.name`] but with otherwise different configurations.

In version 2.0.1, this issue is resolved by the new xref:reference-couchbasebucket.adoc#spec-name[`spec.name`] field, which, if set, overrides the xref:reference-couchbasebucket.adoc#metadata-name[`metadata.name`] field.
The `spec.name` field can be used with all supported bucket types: xref:reference-couchbasebucket.adoc#spec-name[Couchbase], xref:reference-couchbaseephemeralbucket.adoc#spec-name[Ephemeral], and xref:reference-couchbasememcachedbucket.adoc#spec-name[Memcached].

This enhancement also resolves a related issue caused by Kubernetes metadata names having a fixed regex that does not match the regex for Couchbase buckets.
One situation in which this issue would manifest was when bucket names contained an underscore.
As a result, when upgrading from version 1.2.x to 2.0, it wasn't possible to use old buckets which had underscores in their names.
The `cbopconv` tool now takes this into account when xref:howto-operator-upgrade.adoc[upgrading] from 1.2.x to version 2.0.1.
--

[#fixed-issues-v201]
=== Fixed Issues

[#table-fixed-issues-v201,cols="25,66"]
|===
| Issue | Description

a| https://issues.couchbase.com/browse/K8S-1452[K8S-1452^]
a| *Summary:*  Prometheus metrics collection will fail to run on open source Kubernetes if you use the default Prometheus exporter image.
This is the result of an issue with the `couchbase/exporter:1.0.0` image, and does _not_ occur with the OpenShift version of the image that is found on the Red Hat Container Catalog.

It's important to note that in Autonomous Operator 2.0.0, the admission controller fills in a default value of `couchbase/exporter:1.0.0` for xref:reference-couchbasecluster.adoc#spec-monitoring-prometheus-image[`spec.monitoring.prometheus.image`] if it is left unspecified, and therefore this issue would always occur unless you explicitly specified a value of `couchbase/exporter:1.0.1`.

In Autonomous Operator 2.0.1, the admission controller fills in a default value of `couchbase/exporter:1.0.2`.
This updated tag is already reflected in the xref:howto-prometheus.adoc[relevant documentation].

NOTE: The `couchbase/exporter:1.0.2` image is not compatible with Autonomous Operator 2.0.0.
As a result, `couchbase/exporter:1.0.1` is the only (and final) Prometheus exporter image that is compatible with Autonomous Operator 2.0.0.
Please note that these image compatibility issues only affect the https://hub.docker.com/r/couchbase/exporter[Docker Hub-hosted^] images that are used with Autonomous Operator deployments on open source Kubernetes.
This does not affect the https://catalog.redhat.com/software/containers/detail/5e21d6b269aea31642847b61[Red Hat-hosted^] images that are used with Autonomous Operator deployments on OpenShift.  

a| https://issues.couchbase.com/browse/K8S-1451[K8S-1451^]
a| *Summary:* A behavioral change to XDCR in Couchbase Server 6.5.1 means that the documented method for generating connection strings will not work.
This applies to incoming XDCR connections that are external to the Kubernetes cluster i.e. xref:concept-couchbase-networking.adoc#public-networking-with-external-dns[public networking with External DNS] and xref:concept-couchbase-networking.adoc#generic-networking[generic networking].

a| https://issues.couchbase.com/browse/K8S-1449[K8S-1449^]
a| *Summary:* Running `cbopcfg` with the intention of generating backup resources will not result in the expected behavior.

The previous workaround for creating backup resources is no longer required, and the documentation for xref:howto-backup.adoc[configuring backups] has been updated with the relevant `cbopcfg` command.

a| https://issues.couchbase.com/browse/K8S-1437[K8S-1437^]
a| *Summary:* The current operator-backup image in the Red Hat Container Catalog has a security grade of C due to being built on an older RHEL base image.
A new image will be built to resolve this security grade and the default value for this image will be reflected in the next maintenance release.
The reported vulnerability, CVE-2019-13734, is low risk in this use, as the Autonomous Operator does not use the RHEL-supplied Chrome or SQLite as described in the vulnerability.
|===

[#release-v200]
== Release 2.0.0

Couchbase Autonomous Operator 2.0.0 was released in April 2020.

[#install-upgrade-v200]
=== Installation and Upgrade

For installation instructions, refer to xref:install-kubernetes.adoc[] and xref:install-openshift.adoc[].

For upgrade instructions, refer to xref:howto-operator-upgrade.adoc[].

////
CAUTION: The Autonomous Operator 2.0.0 Beta is not production-ready software, and therefore upgrading from the Beta to the final GA version will not be supported.
You should only install the Beta software in development environments for testing purposes.
////

[#supported-platforms-v200]
=== Platform Support

For the latest platform support information, refer to xref:prerequisite-and-setup.adoc[].

==== New Platform Support

This release adds support for the following platforms:

* Open Source Kubernetes 1.15
* Red Hat OpenShift 4.2

==== Removed Platform Support

This release drops support for the following platforms:

* Couchbase Server 5.5
* Red Hat OpenShift Container Platform 3.x

[#changes-in-behavior-v200]
=== Major Behavior Changes

==== New Couchbase Custom Resource Model

As discussed on the xref:whats-new.adoc[What's New] page, this release introduces a new model for deploying and managing Couchbase custom resources.
Previously, you would deploy a cluster using a single, monolithic `CouchbaseCluster` resource configuration that defined everything about a cluster (e.g. nodes, buckets, XDCR, etc).
Starting with Autonomous Operator 2.0, parts of the `CouchbaseCluster` resource have been separated into their own custom resource types, which the Autonomous Operator aggregates together using xref:concept-label-selection.adoc[label selection].

The available set of Couchbase custom resource types include:

* xref:reference-couchbasecluster.adoc[CouchbaseCluster Resource]
* xref:reference-couchbasebucket.adoc[CouchbaseBucket Resource]
* xref:reference-couchbaseephemeralbucket.adoc[CouchbaseEphemeralBucket Resource]
* xref:reference-couchbasememcachedbucket.adoc[CouchbaseMemcachedBucket Resource]
* xref:reference-couchbasereplication.adoc[CouchbaseReplication Resource]
* xref:reference-couchbaseuser.adoc[CouchbaseUser Resource]
* xref:reference-couchbasegroup.adoc[CouchbaseGroup Resource]
* xref:reference-couchbaserolebinding.adoc[CouchbaseRoleBinding]

Autonomous Operator {operator-version-minor} requires that all Couchbase custom resources use the new format.
Couchbase custom resources -- such as `CouchbaseCluster` -- are not backwards compatible between Autonomous Operator versions 1 and 2.
If you're upgrading from Autonomous Operator 1.x, a tool (`cbopconv`) has been provided in the standard Autonomous Operator download package to convert your existing `CouchbaseCluster` resources to version 2.

Read more about how to use the `cbopconv` tool in the xref:howto-operator-upgrade.adoc[upgrade documentation].

==== Installation Procedure

The documented installation procedures now take advantage of the `cbopcfg` tool for installing both the Dynamic Admission Controller and the Autonomous Operator.
This tool greatly simplifies the installation process and accommodates most environments.

Read more about the xref:reference-cbopcfg.adoc[`cbopcfg` tool], as well as xref:install-kubernetes.adoc[Installing on Kubernetes] and xref:install-openshift.adoc[Installing on OpenShift].

[NOTE]
====
If the `cbopcfg` tool doesn't suit your environment, you can still manually install the Dynamic Admission Controller and Autonomous Operator using YAML configuration:

* xref:reference-admission-rbac.adoc[Dynamic Admission Controller spec]
* xref:reference-operator-configuration.adoc[Autonomous Operator spec]
====

==== Couchbase Pod Upgrades

The Autonomous Operator can now better handle certain configuration changes that require pods to be replaced.
Some of these configuration changes include:

* Modification of environment variables
* xref:concept-scheduling.adoc[Modification of scheduling constraints]
* xref:concept-memory-allocation.adoc[Modification of memory constraints]
* xref:concept-tls.adoc[Enabling and disabling of TLS]
* xref:concept-persistent-volumes.adoc[Enabling and disabling of persistent storage]

Read more about xref:concept-upgrade[Couchbase Pod Upgrades].

==== Logging

The Autonomous Operator and Dynamic Admission Controller now use JSON logging. 
This change includes some helpful enhancements, such as pod status outputs no longer spanning multiple lines, and rebalance status now being labeled with proper cluster context.

[#fixed-issues-v200]
=== Fixed Issues

[#table-fixed-issues-v200,cols="25,66"]
|===
| Issue | Description

a| https://issues.couchbase.com/browse/K8S-1329[K8S-1329^]
a| *Summary:* In releases prior to 2.0.0, removing a server class with a `NodePort` would fail (hang indefinitely).
As a workaround, it was recommended to not use `NodePorts`.
Starting in 2.0.0, the Autonomous Operator will remove server classes correctly when using `NodePorts`.

a| https://issues.couchbase.com/browse/K8S-1189[K8S-1189^]
a| *Summary:* Helm no longer merges Exposed Feature Sets when editing.
In releases prior to 2.0.0, editing the Exposed Features, such as `client` and `admin`, would be merged to `clientadmin` incorrectly.
This is no longer the case with Helm Charts for 2.0 and later.

a| https://issues.couchbase.com/browse/K8S-1169[K8S-1169^]
a| *Summary:* When deploying on Red Hat OpenShift using the Operator Lifecycle Manager (OLM), you may see the error messages `The field status.members is invalid` or `The field status.conditions is invalid`.
This has been corrected in the 2.0 release.

a| https://issues.couchbase.com/browse/K8S-1111[K8S-1111^]
a| *Summary:* In releases prior to 2.0, running `kubectl wait` on a Couchbase Cluster resource-based deployment may have resulted in errors such as `error: .status.conditions accessor error`.
Starting in 2.0, it is possible to run `kubectl wait` on Couchbase Cluster defined resources to wait until Pods are ready, etc.
|===

[#known-issues-v200]
=== Known Issues

[#table-known-issues-v200,cols="25,66"]
|===
| Issue | Description

a| https://issues.couchbase.com/browse/K8S-1452[K8S-1452^]
a| *Summary:*  Prometheus metrics collection will fail to run on open source Kubernetes if you use the default Prometheus exporter image.
This is the result of an issue with the `couchbase/exporter:1.0.0` image, and does _not_ occur with the OpenShift version of the image that is found on the Red Hat Container Catalog.

It's important to note that the admission controller will fill in a default value of `couchbase/exporter:1.0.0` for xref:reference-couchbasecluster.adoc#spec-monitoring-prometheus-image[`spec.monitoring.prometheus.image`] if it is left unspecified, and therefore this issue will always occur unless you follow the workaround below.

*Workaround:* Explicitly specify a value of `couchbase/exporter:1.0.1` for the xref:reference-couchbasecluster.adoc#spec-monitoring-prometheus-image[`spec.monitoring.prometheus.image`] field.
This updated tag is already reflected in the xref:howto-prometheus.adoc[relevant documentation].

a| https://issues.couchbase.com/browse/K8S-1449[K8S-1449^]
a| *Summary:* Running `cbopcfg` with the intention of generating backup resources will not result in the expected behavior.

*Workaround:* Until `cbopcfg` is fixed, a workaround for creating backup resources is provided in the documentation for xref:howto-backup.adoc[configuring backups].

a| https://issues.couchbase.com/browse/K8S-1437[K8S-1437^]
a| *Summary:* The current operator-backup image in the Red Hat Container Catalog has a security grade of C due to being built on an older RHEL base image.
A new image will be built to resolve this security grade and the default value for this image will be reflected in the next maintenance release.
The reported vulnerability, CVE-2019-13734, is low risk in this use, as the Autonomous Operator does not use the RHEL-supplied Chrome or SQLite as described in the vulnerability.

*Workaround:* Ensure you do not use Chrome from backup jobs to access websites.
Edit the image tag under `spec.backup.image` in the running `CouchbaseCluster` resource configuration from revision `-4` to revision `-5`.

a| https://issues.couchbase.com/browse/K8S-1395[K8S-1395^]
a| *Summary:* On macOS 10.15 (Catalina), you may see an error such as `./cbopcfg: cannot execute binary file` when trying to execute commands included in the Autonomous Operator download package.

*Workaround:* Update the macOS security settings as outlined in the https://support.apple.com/en-us/HT202491[Apple article on macOS Gatekeeper].
Go to System Preferences > Security & Privacy, and under the General tab, find the header “Allow apps downloaded from” and select *App Store and identified developers*.

a| https://issues.couchbase.com/browse/K8S-1451[K8S-1451^]
a| *Summary:* A behavioral change to XDCR in Couchbase Server 6.5.1 means that the documented method for generating connection strings will not work.
This applies to incoming XDCR connections that are external to the Kubernetes cluster i.e. xref:concept-couchbase-networking.adoc#public-networking-with-external-dns[public networking with External DNS] and xref:concept-couchbase-networking.adoc#generic-networking[generic networking].

*Workaround:* We advise the use of load-balanced XDCR endpoints as they have stable names and provide high-availability.
Couchbase Server 6.5.1, however, requires that the connection string exactly matches a Couchbase Server node hostname.
Additional instructions are xref:howto-client-sdks.adoc#cbs-651[provided] to allow successful configuration of XDCR connections.
|===

== Feedback

You can have a big impact on future versions of the Operator (and its documentation) by providing Couchbase with your direct feedback and observations. Please feel free to post your questions and comments to the https://forums.couchbase.com/c/couchbase-server/Kubernetes[Couchbase Forums].

== Licenses for Third-Party Components

The complete list of licenses for Couchbase products is available on the https://www.couchbase.com/legal/agreements[Legal Agreements] page. Couchbase is thankful to all of the individuals that have created these third-party components.

== More Information

* xref:server:release-notes:relnotes.adoc[Couchbase Server Release Notes]
