= Release Notes for Couchbase Autonomous Operator 1.2

Couchbase Autonomous Operator 1.2 introduces several new features and enhancements, including the ability to automatically upgrade Couchbase Server clusters.

Take a look at the xref:whats-new.adoc[What's New] page for a list of new features and improvements that are available in this release.

== Release 1.2.0

Couchbase Autonomous Operator 1.2.0 was released in .

[#install-upgrade-v120]
=== Installation and Upgrade

For installation instructions, see xref:install-kubernetes.adoc[Installing on Kubernetes] and xref:install-openshift.adoc[Installing on OpenShift].

For upgrade instructions, see xref:upgrading-the-operator.adoc[Upgrading the Operator].

[#supported-platforms-v120]
=== Platform Support

For the latest platform support information, see xref:prerequisite-and-setup.adoc[Prerequisites].

[#changes-in-behavior-v120]
=== Major Behavior Changes

* The Operator now requires the installation of an xref:install-admission-controller.adoc[admission controller]. The admission controller is installed separately and replaces the `cbopctl` command line client that was distributed in Operator releases prior to version 1.2.
+
The primary purpose of the admission controller is to validate Couchbase cluster configuration changes before the Operator acts on them, thus protecting your Couchbase deployment (and the Operator) from any accidental damage that might arise from an invalid configuration.

[#fixed-issues-v120]
=== Fixed Issues

.Issues Fixed in Version 1.2.0
[#table_fixednissues_v120,cols="25,66"]
|===
| Issue | Description

| TBD
| TBD
|===

[#known-issues-v120]
=== Known Issues and Limitations

.Known Issues and Limitations
[#table_knownissues_v120,cols="25,66"]
|===
| Issue | Description

| General
| Couchbase client access is only supported locally within the Kubernetes cluster or where cluster DNS can be accessed by, or replicated to, a remote network.

For more information, see xref:networking.adoc[About Kubernetes Networking and Couchbase].

| General
| The Operator manages the state of the Couchbase Server cluster.
Therefore, at this time, all cluster configuration changes must be made by modifying the CouchbaseCluster configuration file and pushing it to Kubernetes.
Any manual changes to the configuration that are made using the Couchbase Server Web Console, CLI, REST API, or SDK will be reverted by the Operator.
This includes things like adding a node or creating a server group.

The one exception is when `disableBucketManagement` is set to `true` in the CouchbaseCluster configuration (the default is `false`).
If this is the case, the creation and deletion of Couchbase buckets must be done manually.
Refer to the CouchbaseCluster xref:couchbase-cluster-config.adoc[documentation] for more

| TBD
| TBD
|===

== Feedback

You can have a big impact on future versions of the Operator (and its documentation) by providing Couchbase with your direct feedback and observations. Please feel free to post your questions and comments to the https://forums.couchbase.com/c/couchbase-server/Kubernetes[Couchbase Forums].

== Licenses for Third-Party Components

The complete list of licenses for Couchbase products is available on the https://www.couchbase.com/legal/agreements[Legal Agreements] page. Couchbase is thankful to all of the individuals that have created these third-party components.

== More Information

* xref:server:release-notes:relnotes.adoc[Couchbase Server Release Notes]
