= Release Notes for Couchbase Autonomous Operator {operator-version-minor}
include::partial$constants.adoc[]

Couchbase Autonomous Operator {operator-version-minor} is a landmark release that's built to take advantage of the latest Kubernetes improvements in the areas of security and custom resources.
The changes in this release enable several advancements in how you can manage, monitor, and deploy Couchbase clusters.

Take a look at the xref:whats-new.adoc[What's New] page for a list of new features and improvements that are available in this release.

[#release-v200]
== Release 2.0.0 Beta

Couchbase Autonomous Operator 2.0.0 Beta was released in March 2020.

[#install-upgrade-v200]
=== Installation and Upgrade

For installation instructions, see xref:install-kubernetes.adoc[Installing on Kubernetes] and xref:install-openshift.adoc[Installing on OpenShift].

For upgrade instructions, see xref:howto-operator-upgrade.adoc[Upgrading the Operator].

CAUTION: The Autonomous Operator 2.0.0 Beta is not production-ready software, and therefore upgrading from the Beta to the final GA version will not be supported.
You should only install the Beta software in development environments for testing purposes.

[#supported-platforms-v200]
=== Platform Support

For the latest platform support information, see xref:prerequisite-and-setup.adoc[Prerequisites].

==== New Platform Support

This release adds support for the following platforms:

* Open Source Kubernetes 1.15

==== Removed Platform Support:

This release drops support for the following platforms:

* Red Hat OpenShift Container Platform 3.x

[#changes-in-behavior-v200]
=== Major Behavior Changes

==== New Couchbase Custom Resource Model

As discussed on the xref:whats-new.adoc[What's New] page, this release introduces a new model for deploying and managing Couchbase custom resources.
Previously, you would deploy a cluster using a single, monolithic `CouchbaseCluster` resource configuration that defined everything about a cluster (e.g. nodes, buckets, XDCR, etc).
Starting with Autonomous Operator 2.0, parts of the `CouchbaseCluster` resource have been separated into their own custom resource types, which the Autonomous Operator aggregates together using xref:concept-label-selection.adoc[label selection].

The available set of Couchbase custom resource types include:

* xref:reference-couchbasecluster.adoc[CouchbaseCluster Resource]
* xref:reference-couchbasebucket.adoc[CouchbaseBucket Resource]
* xref:reference-couchbaseephemeralbucket.adoc[CouchbaseEphemeralBucket Resource]
* xref:reference-couchbasememcachedbucket.adoc[CouchbaseMemcachedBucket Resource]
* xref:reference-couchbasereplication.adoc[CouchbaseReplication Resource]
* xref:reference-couchbaseuser.adoc[CouchbaseUser Resource]
* xref:reference-couchbasegroup.adoc[CouchbaseGroup Resource]
* xref:reference-couchbaserolebinding.adoc[CouchbaseRoleBinding]

Autonomous Operator {operator-version-minor} requires that all Couchbase custom resources use the new format.
Couchbase custom resources -- such as `CouchbaseCluster` -- are not backwards compatible between Autonomous Operator versions 1 and 2.
If you're upgrading from Autonomous Operator 1.x, a tool (`cbopconv`) has been provided in the standard Autonomous Operator download package to convert your existing `CouchbaseCluster` resources to version 2.

Read more about how to use the `cbopconv` tool in the xref:howto-operator-upgrade.adoc[upgrade documentation].

==== Installation Procedure

The documented installation procedures now take advantage of the `cbopcfg` tool for installing both the Dynamic Admission Controller and the Autonomous Operator.
This tool greatly simplifies the installation process and accommodates most environments.

Read more about the xref:reference-cbopcfg.adoc[`cbopcfg` tool], as well as xref:install-kubernetes.adoc[Installing on Kubernetes] and xref:install-openshift.adoc[Installing on OpenShift].

[NOTE]
====
If the `cbopcfg` tool doesn't suit your environment, you can still manually install the Dynamic Admission Controller and Autonomous Operator using YAML configs:

* xref:reference-admission-rbac.adoc[Dynamic Admission Controller spec]
* xref:reference-operator-configuration.adoc[Autonomous Operator spec]
====

==== Couchbase Pod Upgrades

The Autonomous Operator can now better handle certain configuration changes that require pods to be replaced.
Some of these configuration changes include:

* Modification of environment variables
* xref:concept-scheduling.adoc[Modification of scheduling constraints]
* xref:concept-memory-allocation.adoc[Modification of memory constraints]
* xref:concept-tls.adoc[Enabling and disabling of TLS]
* xref:concept-persistent-volumes.adoc[Enabling and disabling of persistent storage]

Read more about xref:concept-upgrade[Couchbase Pod Upgrades].

==== Logging

The Autonomous Operator and Dynamic Admission Controller now use JSON logging. 
This change includes some helpful enhancements, such as pod status outputs no longer spanning multiple lines, and rebalance status now being labelled with proper cluster context.

== Feedback

You can have a big impact on future versions of the Operator (and its documentation) by providing Couchbase with your direct feedback and observations. Please feel free to post your questions and comments to the https://forums.couchbase.com/c/couchbase-server/Kubernetes[Couchbase Forums].

== Licenses for Third-Party Components

The complete list of licenses for Couchbase products is available on the https://www.couchbase.com/legal/agreements[Legal Agreements] page. Couchbase is thankful to all of the individuals that have created these third-party components.

== More Information

* xref:server:release-notes:relnotes.adoc[Couchbase Server Release Notes]
