= Release Notes for Couchbase Autonomous Operator {operator-version-minor}
include::partial$constants.adoc[]

Couchbase Autonomous Operator {operator-version-minor} is an incremental release that improves general behavior and security.
It also extends functionality to allow automatic scaling of your Couchbase cluster resources, and provides additional configuration options.

Take a look at the xref:whats-new.adoc[What's New] page for a list of new features and improvements that are available in this release.

[#release-v220]
== Release 2.2.0

Couchbase Autonomous Operator 2.2.0 was released in 2021.

[#changes-in-behavior-v220]
=== Major Behavior Changes and Enhancements

==== Improved Security Defaults

The Couchbase Server default minimum TLS version is 1.0.
This is insecure and easily compromised if a client downgrades to a version less than 1.2.
Operator 2.2 makes TLS 1.2 the minimum by default, and will automatically update the TLS minimum version unless it is explicitly specified with the xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-networking-tls-tlsminimumversion[`couchbaseclusters.spec.networking.tls.tlsMinimumVersion`] parameter.

You can prevent this change from occurring when xref:howto-operator-upgrade.adoc[upgrading the Operator] on existing clusters by setting xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-networking-tls-tlsminimumversion[`couchbaseclusters.spec.networking.tls.tlsMinimumVersion`] to `TLS1.0` after upgrading the CRDs, and before restarting the Operator.

==== TLS Certificate and Key Handling

Couchbase Server requires that the TLS resources be called `pkey.key` and `chain.pem`, however the majority of 3rd-party certificate managers generate `tls.key` and `tls.crt`.
This format is governed by the Kubernetes `kubernetes.io/tls` secret type.
To provide integration with 3rd-party providers, and to maintain backward compatibility with existing clusters, the Operator now provides secret shadowing.

A new TLS source -- xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-networking-tls-secretsource[`couchbaseclusters.spec.networking.tls.secretSource`] -- allows you to use `kubernetes.io/tls` type secrets to configure Couchbase Server.
When using this new TLS source, a shadow copy of the TLS secret is created, with the key names changed to those hard coded in Couchbase Server.
The shadow secret can then be mounted and used inside Couchbase Server pods.
As the secret is shadowed, the Operator can reformat private keys, and therefore now supports PKCS#8 formatted private keys.

3rd-party certificate managers can be used with clusters that are configured with this new TLS source.
Refer to the tutorial xref:tutorial-cert-manager.adoc[] for an example.

For existing clusters using the legacy xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-networking-tls-static[`couchbaseclusters.spec.networking.tls.static`] source, the Operator works as before -- directly mounting and consuming the TLS secret without a shadow secret.

==== Improved Server Group Support

Prior to this release, server groups had to be enabled on cluster creation, and were immutable for the lifetime of the cluster.
These restrictions have now been lifted.

It is now possible to enable Couchbase Server groups, and Operator pod scheduling, while a cluster is running.

It is also now possible to modify the list of server groups used for scheduling.
Previously if an availability zone were to suffer an outage, the Operator would continually attempt to recreate failed pods in the same availability zone to maintain even balance across the requested set.
While the availability zone continues to suffer an outage, the Couchbase cluster would be undersized, potentially impacting the ability to service client requests.
This release allows the availability zones to be modified, excluding the failed one, so that the Operator is able to scale the cluster back up to the correct size.

All server group migration operations use a shortest-path algorithm in order to minimize disruption.

==== Improved XDCR Connection Support

Prior to this release, any updates to XDCR remote clusters would be silently ignored.
In order to modify any setting, the remote cluster and all replications would have to be deleted and recreated from scratch.

This release adds the ability to modify remote cluster identification and authentication settings.
This provides the ability to rotate passwords and certificates on the remote cluster, or even replace the remote cluster entirely.

==== Automatic Resource Allocation

Kubernetes allows pods to reserve and limit compute resources.
Resource reservation provides Kubernetes with the ability to fairly schedule pods so that they don't complete for CPU and memory.

The Operator now provides the ability to automatically manage pod CPU and memory resource requests with the xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-autoresourceallocation[`couchbaseclusters.spec.autoResourceAllocation`] field.
When in use, pods will have their resource requests automatically populated depending on the services enabled on that pod, and the individual Couchbase service quotas.

Updating quotas will cause the cluster to upgrade as pod resource requests are updated.
A new dummy memory quota for the query service is introduced to allow management of memory resource requests, even though Couchbase itself does not provide the ability to constrain this service.

==== Improved Upgrade Behavior

Prior to this release, the Operator allowed two types of upgrade -- a one pod at a time rolling upgrade, and a whole cluster upgrade.

This release allows rolling upgrades to be extended to upgrade either a fixed number of pods, or a percentage of the cluster size.
Both values can be set, and both will be considered, the Operator selecting the one resulting in the fewest number of pods being upgraded at a time.

Rolling upgrades can be configured with the xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-rollingupgrade[`couchbaseclusters.spec.rollingUpgrade`] parameter.

[NOTE]
====
A whole cluster "immediate" upgrade is now synonymous with a rolling upgrade set to upgrade 100% of the cluster at a time.
Immediate upgrades may be removed at some point in the future as it duplicates functionality.
====

==== Improved Backup Handling

While not a replacement for a properly implemented monitoring solution, it may be beneficial to have your backup storage grow with your requirements.
To this end, two new features are introduced.

The first allows manual update of the volume size, by manually editing the xref:resource/couchbasebackup.adoc#couchbasebackups-spec-size[`couchbasebackups.spec.size`] field.

The second allows automatic updates to be performed by the Autonomous Operator, thus keeping backups to the minimum size necessary to operate, and reducing cost, while also supporting future expansion.
In this mode of operation, the xref:resource/couchbasebackup.adoc#couchbasebackups-spec-autoscaling[`couchbasebackups.spec.autoScaling`] field controls the behavior.
When the free storage becomes lower than xref:resource/couchbasebackup.adoc#couchbasebackups-spec-autoscaling-thresholdpercent[`couchbasebackups.spec.autoScaling.thresholdPercent`] percent, volume expansion will be triggered.
Volumes will be automatically grown by xref:resource/couchbasebackup.adoc#couchbasebackups-spec-autoscaling-incrementpercent[`couchbasebackups.spec.autoScaling.incrementPercent`] percent of the current volume size.
If specified, the xref:resource/couchbasebackup.adoc#couchbasebackups-spec-autoscaling-limit[`couchbasebackups.spec.autoScaling.limit`] field will limit the maximum volume size.
When not specified, volumes can grow indefinitely.

In order to use any resize capability, your backups must be using a storage class where volume expansion is enabled.

==== Improved Backup and Restore

By default, both of these operations would execute with only a single thread of execution.
This led to poor performance.
You can now specify the number of threads to use.
This will typically be dictated by the CPU resource allocated to the backup job.

Restores were also inflexible, all data that was backed up, was also restored.
This release introduces filters, so that you can control exactly what is restored from a backup.
You can choose to include or exclude specific buckets, restore data for a particular service, and even restore to a different bucket name when restoring documents.

This release requires you to upgrade your backup image to at least `couchbase/operator-backup:6.6.0-XXX`.

==== Other Notable Changes

* The dynamic admission controller (DAC) now allows xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-servers-volumeMounts-index[couchbaseclusters.spec.servers.volumeMounts.index] to be configured for server classes that include the Search Service and that don't include the Index Service.
Previously, the DAC would reject configurations that specified the index volume mount unless the Index Service was also included in the server class.

== Feedback

You can have a big impact on future versions of the Operator (and its documentation) by providing Couchbase with your direct feedback and observations. Please feel free to post your questions and comments to the https://forums.couchbase.com/c/couchbase-server/Kubernetes[Couchbase Forums].

== Licenses for Third-Party Components

The complete list of licenses for Couchbase products is available on the https://www.couchbase.com/legal/agreements[Legal Agreements] page. Couchbase is thankful to all of the individuals that have created these third-party components.

== More Information

* xref:server:release-notes:relnotes.adoc[Couchbase Server Release Notes]
