= Release Notes for Couchbase Autonomous Operator {operator-version-minor}
include::partial$constants.adoc[]

Autonomous Operator {operator-version-minor} release provides full support for Couchbase Server 7.6, and several improvements to Pod Scheduling and Networking, as well as a number of minor fixes.

Take a look at the xref:whats-new.adoc[What's New] page for a list of new features and improvements that are available in this release.

== Installation

For installation instructions, refer to:

* xref:install-kubernetes.adoc[]
* xref:install-openshift.adoc[]

== Upgrading to Autonomous Operator {operator-version-minor}

The necessary steps needed to upgrade to this release depend on which version of the Autonomous Operator you are upgrading from.

=== Upgrading from 1.x, 2.0, or 2.1

There is no direct upgrade path from versions prior to 2.2.0.
To upgrade from a 1.x, 2.0.x, or 2.1.x release, you must first upgrade to 2.4.x, paying particular attention to supported Kubernetes platforms and Couchbase Server versions.
Refer to the xref:2.4@operator::howto-operator-upgrade.adoc[Operator 2.4 upgrade steps] if upgrading from a pre-2.2 release.

=== Upgrading from 2.2, 2.3, 2.4, 2.5, or 2.6

There are no additional upgrade steps when upgrading from these versions, and you may follow the xref:howto-operator-upgrade.adoc[standard upgrade process].
However, due to https://issues.couchbase.com/browse/K8S-3097[K8S-3097^], all users will encounter a mandatory upgrade cycle when upgrading from a release older than 2.5.0, to versions 2.5.0, 2.5.1, or 2.6.0 through 2.6.3, to expose the missing Indexer HTTPS Port (see xref:server:install:install-ports.adoc#detailed-port-description[Detailed Port Description] for network port requirements).
This behavior has changed in versions 2.5.2, 2.6.4, and 2.7.0, and there is no mandatory upgrade cycle -- the missing port is added the next time there is a regular maintenance activity that involves Pod creation.
[IMPORTANT]
====
An upgrade cycle is a relatively heavyweight operation that requires all pods in the cluster to be replaced, and data transferred between the old and new pods.
The time taken to perform this operation is dependent on network bandwidth, disk IO and the amount of data resident in the database.
For large, production databases, ensure an adequate maintenance window is scheduled as to minimize any disruption to clients and other business critical functions.

For further information read the xref:concept-upgrade.adoc[Couchbase Upgrade] concepts page.
====

[#release-v270]
== Release 2.7.0

Couchbase Autonomous Operator 2.7.0 was released in August 2024.

[#changes-in-behavior-v270]
=== Changes in Behaviour

==== Delta Recovery / In-Place Upgrades

The `DeltaRecovery` upgrade strategy added in Operator 2.6 has been replaced by `InPlaceUpgrade`, to better reflect the actual behaviour (not every Service can be Delta Recovered), and `DeltaRecovery` is now deprecated.

==== Storage Backend Migration

In Server 7.6 it is now possible to migrate between the Couchstore and Magma storage backends, as described in xref:7.6@server:manage/manage-buckets/migrate-bucket.adoc[Migrate a Bucket’s Storage Backend].
Operator will automatically start the required Rebalances if it detects an unresolved Storage backend change.
Storage Backend can also be configured using annotations, see xref:reference-annotations.adoc#bucket-backend-configuration[Bucket Backend Configuration] for more details.

==== Query Service Settings

Over time, a significant gap had appeared between the Query Service settings available in Couchbase Server, and the ones exposed via the `CouchbaseCluster` CRD in Autonomous Operator.
This has been addressed in CAO 2.7.0, and the following cluster-wide settings are now available:

* Server 6.5+: `queryPipelineBatch`, `queryPipelineCap`, `queryScanCap`, `queryTimeout`, `queryPreparedLimit`, `queryCompletedLimit`, `queryCompletedThreshold`, `queryLogLevel`, `queryMaxParallelism`.
* Server 7.0+: `queryTxTimeout`, `queryMemoryQuota`, `queryUseCBO`, `queryCleanupClientAttempts`, `queryCleanupLostAttempts`, `queryCleanupWindow`, `queryNumAtrs`.
* Server 7.6+: `queryNodeQuota`, `queryUseReplica`, `queryNodeQuotaValPercent`, `queryNumCpus`, `queryCompletedMaxPlanSize`.

Note that `queryNodeQuota` is being exposed via the existing xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-cluster-queryservicememoryquota[`spec.cluster.queryServiceMemoryQuota`].
For Server versions prior to 7.6, this value is used to determine Pod resource requirements, and from version 7.6 onwards will also be used to set `queryNodeQuota` on the Couchbase Server cluster (see https://issues.couchbase.com/browse/K8S-3436[K8S-3436^]).

Note that `queryNumCpus` requires a restart of the Query Service to take effect.
In practice in a Kubernetes environment, this means that this will only affect Pods started after the setting has been updated.

[IMPORTANT]
====
Prior to Operator 2.7.0, the above Query Service settings could still be set directly on the cluster.

To avoid these being reset to default values during the CAO upgrade, any of the above settings that have been changed must be added to the `CouchbaseCluster` resource during the upgrade.

Specifically, this needs to be done _after_ updating the CRDs, and _before_ installing the new Operator

For further information see xref:howto-operator-upgrade.adoc#update-existing-resources[Update Existing Resources].
====

==== Audit Log Pruning

With the addition of native pruning of rotated Audit Logs in Server 7.6, the xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-logging-audit-garbagecollection[`garbageCollection`] sidecar is now deprecated.

==== Miscellaneous Changes

* `cao collect logs` now has improved handling of larger clusters (https://issues.couchbase.com/browse/K8S-3322[K8S-3322^]).
* xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-networking-exposedfeatures[`couchbaseclusters.spec.networking.exposedFeatures`] now includes `backup` as an option, allowing external access for the `cbbackupmgr` tool (https://issues.couchbase.com/browse/K8S-3508[K8S-3508^]).
* Any options specified at xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-security-securitycontext[`couchbaseclusters.spec.security.securityContext`] are now also applied to the Operator Backup container (https://issues.couchbase.com/browse/K8S-3417[K8S-3417^]).
* It is possible to set a longer Termination Grace Period on the Cloud Native Gateway container with xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-networking-cloudnativegateway-terminationgraceperiodseconds[`terminationGracePeriodSeconds`]  (https://issues.couchbase.com/browse/K8S-3257[K8S-3257^]).
* A number of new metrics have been added, see xref:reference-prometheus-metrics.adoc[Prometheus Metrics Reference] for details.

[#fixed-issues-v270]
=== Fixed Issues

[#table-fixed-issues-v270,cols="25,66"]
|===
| Issue | Description

a| https://issues.couchbase.com/browse/K8S-3377[K8S-3377^]
a| *Summary:* Previously the `TestTLSRotateCAKillPodAndKillOperator` test was failing with Server 7.6.

a| https://issues.couchbase.com/browse/K8S-3391[K8S-3391^]
a| *Summary:* Previously the Operator was not correctly deleting un-managed XDCR Remote Cluster References.

a| https://issues.couchbase.com/browse/K8S-3452[K8S-3452^]
a| *Summary:* Previously the Operator was triggering a mandatory upgrade cycle when upgrading from 2.4.x or earlier.

a| https://issues.couchbase.com/browse/K8S-3587[K8S-3587^]
a| *Summary:* Previously the `eventing_manage_functions` RBAC role was missing from the list of cluster roles.

|===

[#known-issues-v270]
=== Known Issues

[#table-known-issues-v270,cols="25,66"]
|===
| Issue | Description

a| https://issues.couchbase.com/browse/K8S-3632[K8S-3632^]
a| *Summary:* It is not currently possible to set xref:resource/couchbasecollection.adoc#couchbasecollections-spec-maxttl[`couchbasecollections.spec.maxTTL`] to `-1` to disable expiry.

a| https://jira.issues.couchbase.com/browse/K8S-3663[K8S-3663^]
a| Three tests: TestPersistentVolumeAutoRecovery, TestUpgradeSupportableKillStatefulPodOnCreate, and TestAutoscaleUpMandatoryMutualTLS may fail when running self-certification on Kubernetes 1.31.

|===

== Feedback

You can have a big impact on future versions of the Operator (and its documentation) by providing Couchbase with your direct feedback and observations.
Please feel free to post your questions and comments to the https://forums.couchbase.com/c/couchbase-server/Kubernetes[Couchbase Forums].

== Licenses for Third-Party Components

The complete list of licenses for Couchbase products is available on the https://www.couchbase.com/legal/agreements[Legal Agreements] page.
Couchbase is thankful to all of the individuals that have created these third-party components.

== More Information

* xref:server:release-notes:relnotes.adoc[Couchbase Server Release Notes]