= Release Notes for Couchbase Autonomous Operator {operator-version-minor}
include::partial$constants.adoc[]

Couchbase Autonomous Operator {operator-version-minor} is a significant release that expands support for
Couchbase Server 7, providing full support for scope and collections.

Take a look at the xref:whats-new.adoc[What's New] page for a list of new features and improvements that are available in this release.

== Installation

For installation instructions, refer to:

* xref:install-kubernetes.adoc[]
* xref:install-openshift.adoc[]

== Upgrading to Autonomous Operator {operator-version-minor}

The necessary steps needed to upgrade to this release depend on which version of the Autonomous Operator you are upgrading from.

* Version 1.x.x
** There is no direct upgrade path from versions prior to 2.0.x.
To upgrade from a 1.x.x release, you must first upgrade to 2.0.x, paying particular attention to supported Kubernetes platforms and Couchbase Server versions.
Refer to the xref:2.0@operator::howto-operator-upgrade.adoc[2.0.x upgrade steps] if upgrading from a 1.x.x release.

* Version 2.0.x
** Additional steps and considerations are required when upgrading from version 2.0.x.
Please refer to <<upgrade-v20x>>.

* Version 2.1.x
** There are no additional upgrade steps or considerations when upgrading from this version.
You may follow xref:howto-operator-upgrade.adoc[standard upgrade process].

* Version 2.2.x
** There are no additional upgrade steps or considerations when upgrading from this version.
You may follow xref:howto-operator-upgrade.adoc[standard upgrade process].

[[upgrade-v20x]]
=== Upgrading from Version 2.0.x

First, ensure that you are running xref:prerequisite-and-setup.adoc[compatible versions] of Kubernetes and Couchbase Server before upgrading.

==== TLS Requirements

If you are *not* utilizing TLS, you can skip this section.

The TLS requirements have been modified as of Autonomous Operator 2.1.
In order to ease the migration from legacy client bootstrap (CCCP) to the newest version (GCCCP), the Autonomous Operator requires Couchbase cluster subject alternative names (SANs) to be updated.
Consult the xref:tutorial-tls.adoc[TLS tutorial] for a full list of all the required SANs, and the xref:howto-tls-rotation.adoc[TLS rotation guide] in order to prepare for upgrade.
Failure to perform this step will result in errors from the dynamic admission controller (DAC) once upgraded.

==== Mandatory Couchbase Upgrade Cycle

When upgrading from version 2.0.x, Couchbase clusters will undergo a mandatory upgrade cycle.

Pod readiness checks were previously driven by an `exec` based readiness probe.
This was a security concern because it granted the Autonomous Operator `pods/exec` privileges, which may not be acceptable in highly regulated environments.
As of Autonomous Operator 2.1, readiness checks are performed using readiness gates that use the Kubernetes API exclusively.

You can use the xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-rollingupgrade[`couchbaseclusters.spec.rollingUpgrade`] configuration parameter to speed up this upgrade.
To enable this feature while upgrading the Autonomous Operator, stop the old Operator, replace the CRDs, edit the xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-rollingupgrade[`couchbaseclusters.spec.rollingUpgrade`] field to enable bulk upgrades, then start the new Operator.
Refer to xref:howto-operator-upgrade.adoc[] for further details.

[#release-v230-beta1]
== Release 2.3.0-beta1

Couchbase Autonomous Operator 2.3.0-beta1 was released in October 2021.

[#changes-in-behavior-v230-beta1]
=== New Features and Behavioral Changes

==== Scopes and Collections Management

The Operator now has the ability to fully manage scopes and collections within a bucket.
Scopes and collections provide fine grained access control and replication, and improved scalability.

For further information consult the xref:concept-scopes-and-collections.adoc[Scopes and Collections Concepts] documentation.

==== Backup and Restore Improvements

Due to interface changes introduced in Couchbase Server 7.0, a new backup image (1.2.0) is the only supported version that will run with Operator 2.3.
It continues to support operation with Couchbase Server version 6.5 and 6.6.

[IMPORTANT]
====
Ensure that any backup jobs are upgraded to use the new image when moving to Operator 2.3.
====

Backup 1.2.0 fully supports operation with Couchbase scopes and collections.
Additional improvements include support for filtering of backup source data -- thus minimizing backup size and improving performance, and the addition of new options for filtering restore data -- such as with document key and value regular expressions.

==== Removal of Admission Controller Mutation

Prior to this release, the dynamic admission controller was utilized to provide some defaults to Couchbase custom resources.
The vast majority of these defaults have already been migrated to native CRD defaulting.
Mutation has now been fully removed to provide out-of-the-box compatibility with platforms like GKE Autopilot where mutation is prohibited.

Some defaults were not able to be migrated so have been removed entirely:

* Default file system groups for persistent volumes (does not affect Red Hat OCP).
When using Couchbase with PVCs, the operator tries to reuse data where possible.
In order for an old volume to be used by a new pod, the data needs to be read and written by the same group across all pods.
Clusters that use backups are also affected, as these reuse PVCs across backup jobs.
+
Previously the DAC provided dynamic defaults depending on the platform (Kubernetes/Red Hat OCP).
While OCP should work without specifying the file system group, Kubernetes users will need to explicitly specify the group when using persistent volumes.
Follow the existing xref:concept-persistent-volumes.adoc#using-storage-classes[persistent volume concepts] documentation for guidance on configuration.
* Backup and Prometheus images.
These were dynamically populated by the DAC for ease of use, depending on platform.
These fields are now marked as required to be provided by the end user.
Up to date images can be found on Docker hub and the Red Hat container catalog.
See the xref:prerequisite-and-setup.adoc[prerequisites] documentation for compatible image versions.

==== Tooling Updates

Previous releases came bundled with `cbopcfg` and `cbopinfo` binaries to aid installation and support requests respectively.
While these binaries are still part of the distribution, the new xref:tools/cao.adoc[`cao`] binary features all the existing functionality of these tools, and extends the feature set to allow self-service platform certification.
The existing `cbopcfg` and `cbopinfo` binaries are now deprecated and will be removed in a later release.

You should update any tooling to use `cao`, or you can alias existing commands to use the new binary:

[source,console]
----
$ alias cbopcfg='cao'
$ alias cbopinfo='cao collect-logs'
----

[#fixed-issues-v230-beta1]
=== Fixed Issues

[#table-fixed-issues-v230-beta1,cols="25,66"]
|===
| Issue | Description

a| https://issues.couchbase.com/browse/K8S-2432[K8S-2432^]
a| *Summary:* When recovering a pod and using persistent volume storage, there is the possibly of a race condition when running the Couchbase Server pod's initialization container.
This occurs when the underlying storage provider returns an error, rather than a definitive answer a to whether a file exists.
The error appears as if the file doesn't exist, and so the container erroneously reinitializes its persistent storage and resets configuration, particularly storage path locations.
This fix removes the condition check, and replaces with a non-destructive copy instead.

|===

== Feedback

You can have a big impact on future versions of the Operator (and its documentation) by providing Couchbase with your direct feedback and observations. Please feel free to post your questions and comments to the https://forums.couchbase.com/c/couchbase-server/Kubernetes[Couchbase Forums].

== Licenses for Third-Party Components

The complete list of licenses for Couchbase products is available on the https://www.couchbase.com/legal/agreements[Legal Agreements] page. Couchbase is thankful to all of the individuals that have created these third-party components.

== More Information

* xref:server:release-notes:relnotes.adoc[Couchbase Server Release Notes]
