= Release Notes

Couchbase Autonomous Operator 1.0 is the first production-ready native integration of Couchbase Server with Kubernetes platforms.

The goal of the Operator is to fully manage one or more Couchbase Server deployments so that you don’t need to worry about the operational complexities of running Couchbase. The following is a list of the Couchbase features and management tasks that are currently supported:

* Cluster configuration

* Cluster provisioning

* Ad-hoc scalability

* Auto-recovery

* Configuration validation

* XDCR

* Server Groups

* TLS

* Persistent volume support

Couchbase Autonomous Operator 1.0 was released in August 2018.

== Platform Support

For the latest platform support information, see xref:prerequisite-and-setup.adoc[Prerequisites and Setup].

== Known Issues and Limitations

[#table-known-issues-1.0.0,cols="1,3",options="header"]
|===

|Issue
|Description

|xref:https://issues.couchbase.com/browse/K8S-538[K8S-538]
|

|xref:https://issues.couchbase.com/browse/K8S-327[K8S-327]
|

|xref:https://issues.couchbase.com/browse/K8S-504[K8S-504]
|

|xref:https://issues.couchbase.com/browse/K8S-421[K8S-421]
|

|xref:https://issues.couchbase.com/browse/K8S-493[K8S-493]
|

|xref:https://issues.couchbase.com/browse/K8S-389[K8S-389]
|

|xref:https://issues.couchbase.com/browse/K8S-89[K8S-89]
|

|xref:https://issues.couchbase.com/browse/K8S-531[K8S-531]
|

|xref:https://issues.couchbase.com/browse/K8S-537[K8S-537]
|

|===

== Feedback

You can have a big impact on future versions of the Operator (and its documentation) by providing Couchbase with your direct feedback and observations. Please feel free to post your questions and comments to the https://forums.couchbase.com/c/couchbase-server/Kubernetes[Couchbase Forums].

== Licenses for Third-Party Components

The complete list of licenses for Couchbase products is available on the xref:https://www.couchbase.com/legal/agreements[Legal Agreements] page. Couchbase is thankful to all of the individuals that have created these third-party components.

== More Information

* xref:server:release-notes:relnotes.adoc[Couchbase Server Release Notes]
