= Release Notes for Couchbase Autonomous Operator {operator-version-minor}
include::partial$constants.adoc[]

Autonomous Operator {operator-version-minor} release is primarily focused on platform updates, feature parity with Couchbase Server, improvements to Pod Management and Security, as well as a number of minor fixes.

Take a look at the xref:whats-new.adoc[What's New] page for a list of new features and improvements that are available in this release.

== Installation

For installation instructions, refer to:

* xref:install-kubernetes.adoc[]
* xref:install-openshift.adoc[]

== Upgrading to Autonomous Operator {operator-version-minor}

The necessary steps needed to upgrade to this release depend on which version of the Autonomous Operator you are upgrading from.

=== Upgrading from 1.x, 2.0, or 2.1

There is no direct upgrade path from versions prior to 2.2.0.
To upgrade from a 1.x, 2.0.x, or 2.1.x release, you must first upgrade to 2.4.x, paying particular attention to supported Kubernetes platforms and Couchbase Server versions.
Refer to the xref:2.4@operator::howto-operator-upgrade.adoc[Operator 2.4 upgrade steps] if upgrading from a pre-2.2 release.

=== Upgrading from 2.2, 2.3, 2.4, or 2.5

There are no additional upgrade steps when upgrading from these versions, and you may follow the xref:howto-operator-upgrade.adoc[standard upgrade process].
However, due to https://issues.couchbase.com/browse/K8S-3097[K8S-3097^], all users will encounter a mandatory upgrade cycle when upgrading from releases older than 2.5.0, to expose the missing Indexer HTTPS Port (see xref:server:install:install-ports.adoc#detailed-port-description[Detailed Port Description] for network port requirements).

[IMPORTANT]
====
An upgrade cycle is a relatively heavyweight operation that requires all pods in the cluster to be replaced, and data transferred between the old and new pods.
The time taken to perform this operation is dependent on network bandwidth, disk IO and the amount of data resident in the database.
For large, production databases, ensure an adequate maintenance window is scheduled as to minimize any disruption to clients and other business critical functions.

For further information read the xref:concept-upgrade.adoc[Couchbase Upgrade] concepts page.
====

[#release-v260]
== Release 2.6.0

Couchbase Autonomous Operator 2.6.0 was released in December 2023.

[#changes-in-behavior-v260]
=== New Features and Behavioral Changes

==== Immediate Backups

The CouchbaseBackup resource now has the backup strategies of immediate_full and immediate_incremental to run a backup immediately.

==== Pod Management

The operator now takes into consideration index placement, data placement, and server version to identify pods to remove on scaling events.
The operator now will perform in place upgrades using Delta Recovery rebalances on Couchbase Server version upgrades.

==== Pod and Container Changes

The operator now adds the prometheus.io/scheme annotation to pods.
The operator now adds platform specific zone labels for EKS, GKE and AKS to Couchbase Server persistent volume claims.

==== CRD Changes

The field `couchbasebackuprestore.spec.backup` is no longer mandatory when using ephemeral volumes.
The field `couchbasecluster.spec.onlineExpansionTimeout` has been added as an int that specifies the number of minutes between 0-30 that the operator should wait before failing over to swap rebalance for volume expansions.
The field `couchbasecluster.spec.upgradeProcess` has been added as an enum of "DeltaRecovery" or "SwapRebalance".  Default is "SwapRebalance".

==== CLI Changes

Logs can now be uploaded directly to the Couchbase support portal via the `--upload-host`, `--customer`, `--upload-proxy` and `--ticket` parameters
Pod Readiness Delay and Pod Readiness period can be set via the `cao create operator` command.  These settings will be applied to all pods created by the operator.


[#fixed-issues-v260]
=== Fixed Issues

[#table-fixed-issues-v260,cols="25,66"]
|===
| Issue | Description

a| https://issues.couchbase.com/browse/K8S-3216[K8S-3216^]
a| *Summary:* Previously the operator would loop on buckets with specific settings, continuously updating and spamming logs.

a| https://issues.couchbase.com/browse/K8S-3189[K8S-3189^]
a| *Summary:* Previously the operator identified the eventing_admin role as a bucket role and not a cluster role

a| https://issues.couchbase.com/browse/K8S-3179[K8S-3179^]
a| *Summary:* Previously the operator would log a large json structure to the logs when it failed to create a pod.  

a| https://issues.couchbase.com/browse/K8S-3095[K8S-3095^]
a| *Summary:* Previously the Operator would not allow you remove the setting for readerThreads

a| https://issues.couchbase.com/browse/K8S-3283[K8S-3283^]
a| *Summary:* Previously the Operator would not use the new `couchbasecluster.spec.security.podSecurityContext` when creating backup jobs

|===

== Feedback

You can have a big impact on future versions of the Operator (and its documentation) by providing Couchbase with your direct feedback and observations.
Please feel free to post your questions and comments to the https://forums.couchbase.com/c/couchbase-server/Kubernetes[Couchbase Forums].

== Licenses for Third-Party Components

The complete list of licenses for Couchbase products is available on the https://www.couchbase.com/legal/agreements[Legal Agreements] page.
Couchbase is thankful to all of the individuals that have created these third-party components.

== More Information

* xref:server:release-notes:relnotes.adoc[Couchbase Server Release Notes]