= Configuring TLS

[abstract]
Couchbase supports transport layer security (TLS) in order to encrypt communications on the wire and provide mutual authentication between peers.
Couchbase clients (including the Couchbase Autonomous Operator) require the usage of TLS in order to communicate with the Couchbase cluster.

The basic requirements are:

* A certificate authority (CA) certificate which will be used by all actors to validate that peer certificates have been digitally signed by a trusted CA.

* A server certificate/key pair for all nodes in the Couchbase cluster. If you are using a hierarchy of intermediate CAs, these must be appended to the client certificate, ending in the intermediate CA that is signed by the top-level CA. Server certificates must have a subject alternative name (SAN) set so that a client can assert that the host name that it's connecting to is the same as that in the certificate.
+
Couchbase currently supports using wildcard entries only. For example, `*.cluster.domain.svc` where _cluster_ is the name of the CouchbaseCluster resource, and _domain_ is the namespace that the cluster is running in (typically `default`).

Additionally Couchbase Server may be configured to use mutual-TLS and client certificate authentication.

These additional requirements are:

* A client certificate/key pair that is valid for the administrative user defined in the `CouchbaseCluster` attribute `spec.security.adminSecret`.
+
The username is encoded into the certificate as per the xref:couchbase-cluster-config.adoc#spec-networking-tls-clientcertificatepaths[username extraction rules].

== Configuration

An example configuration is as follows:

[source,yaml]
----
spec:
  ...
  tls:
    static:
      serverSecret: couchbase-server-tls
      operatorSecret: couchbase-operator-tls
  ...
----

For a static TLS configuration, `serverSecret` and `operatorSecret` need to be specified. These refer to named Kubernetes secrets which are described below.

== Creating Secrets

Secrets are specified in the CouchbaseCluster resource, therefore they may have any name you choose. The format of individual secrets is discussed below.

=== spec.tls.static.serverSecret

Server secrets need to be mounted as a volume within the Couchbase Server pod with specific names. The certificate chain must be named `chain.pem` and the private key `pkey.key`.

[source,console]
----
kubectl create secret generic couchbase-server-tls \
  --from-file example/tls/certs/chain.pem \
  --from-file example/tls/certs/pkey.key
----

=== spec.tls.static.operatorSecret

The Operator client secrets are read directly from the API. It expects only a single value to be present; `ca.crt` is the top-level CA which is used to authenticate all TLS server certificate chains.

[source,console]
----
kubectl create secret generic couchbase-operator-tls \
  --from-file example/tls/certs/ca.crt
----

If using client certificate authentication you will also need to specify the client certificate chain and key pair with the keys `couchbase-operator.crt` and `couchbase-operator.key` respectively:

[source,console]
----
kubectl create secret generic couchbase-operator-tls \
  --from-file example/tls/certs/ca.crt \
  --from-file example/tls/certs/couchbase-operator.crt \
  --from-file example/tls/certs/couchbase-operator.key
----

== Creating Certificates

Creating X.509 certificates is beyond the scope of this documentation and is given only for illustrative purposes only.
Please consult the https://docs.couchbase.com/server/6.5/learn/security/certificates.html[Couchbase Server documentation^] for additional details on certificate and TLS configuration.

=== EasyRSA

EasyRSA by OpenVPN makes operating a public key infrastructure (PKI) relatively simple, and is the recommended method to get up and running quickly.

First clone the repository:

[source,console]
----
git clone https://github.com/OpenVPN/easy-rsa
----

Initialize and create the CA certificate/key. You will be prompted for a private key password and the CA common name (CN), something like _Couchbase CA_ is sufficient. The CA certificate will be available as `pki/ca.crt`.

[source,console]
----
cd easy-rsa/easyrsa3
----

[source,console]
----
./easyrsa init-pki
----

[source,console]
----
./easyrsa build-ca
----

Create a server wildcard certificate and key to be used on Couchbase Server pods. The Operator/clients will access the pods via Kubernetes services (`cb-example-0000.cb-example.default.svc`, for example) so this needs to be in the SAN list in order for a client to verify the certificate belongs to the host that is being connected to. To this end, we add in a `--subject-alt-name`, this can be specified multiple times in case your client uses a different method of addressing. The key/certificate pair can be found in `pki/private/couchbase-server.key` and `pki/issued/couchbase-server.crt` and used as `pkey.pem` and `chain.pem`, respectively, in the `serverSecret`.

[source,console]
----
./easyrsa --subject-alt-name=DNS:*.cb-example.default.svc build-server-full couchbase-server nopass
----

Note, password-protected keys are not supported by Couchbase Server or the Operator.

==== Private Key Formatting

Due to an https://issues.couchbase.com/browse/MB-24404[issue] with Couchbase Server's private key handling, server keys need to be PKCS#1 formatted. This can be achieved with the following commands:

[source,console]
----
openssl rsa -in pkey.key -out pkey.key.der -outform DER
----

[source,console]
----
openssl rsa -in pkey.key.der -inform DER -out pkey.key -outform PEM
----

==== Creating a Client Certificate

This process is very similar to creating a server certificate.
Assuming the administrative user defined for Couchbase Server is `Administrator` you can create a client certificate for the Operator to use with the following command:

[source,console]
----
./easyrsa build-client-full Administrator nopass
----

The created files `pki/private/Administrator.key` and `pki/issued/Administrator.crt` can be used as `couchbase-operator.crt` and `couchbase-operator.key` respectively when specifying the `CouchbaseCluster` `spec.networking.tls.static.operatorSecret`.

== Certificate Rotation

Certificates can go out of date, or the private keys of the server certificate and the signing CA can become compromised.
The Operator supports Kubernetes https://kubernetes.io/docs/tasks/tls/certificate-rotation/[certificate rotation^] in order to enable the replacement of these expired certificates or compromised keys.

The following are some examples of certificate rotation:

* Replacement of the certificate chain and key pair (server secret)
+
Use when:
+
 ** Certificates expire
 ** Server or intermediate CA keys have been compromised

* Replacement of the whole PKI (both Operator and server secrets)
+
Use when:
+
 ** The root CA has been compromised

The relevant errors will be shown when a certificate is found to be invalid or compromised.

.Expired certificate
[source,console]
----
certificate cannot be verified: x509: certificate has expired or is not yet valid
----

.Compromised certificate
[source,console]
----
certificate cannot be verified: x509: certificate signed by unknown authority
----

[NOTE]
====
Certificate rotation is fully supported when using client certificate authentication.
Due to technical reasons all TLS reconciliation occurs over plain text.
This is however still secure as private keys are never exposed by the Operator over the wire.
Private keys are securely mounted on Couchbase Server pods by Kubernetes.
====

=== Replacing Server Certificates

In the event of server certificate expiry or compromise, a new certificate and key pair generated by the same CA can be used to create a new server TLS secret to be loaded onto Couchbase Server pods, replacing the existing secret.
If a certificate chain is being used, it's possible to just generate a new leaf certificate from the intermediate CA.

First, get the existing secret and direct it into a new YAML file (`resource.yaml` in this example):

[source, console]
----
kubectl get secret couchbase-server-tls -o yaml > resource.yaml
----

The contents of the new file will look similar to the following:

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: couchbase-server-tls
type: Opaque
data:
  chain.pem: Q2VydGlmaWXRhO...
  pkey.key: LS0tLS1CRUdJTi...
----

Next, replace the relevant data fields in the YAML file.
To do this, start by base64-encoding the PKI files in question.

Certificate chain:

[source,console]
----
base64 -i chain.pem
----

Private key:

[source,console]
----
base64 -i pkey.key
----

Then replace the relevant fields under `data` with the new base64 values:

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: couchbase-server-tls
type: Opaque
data:
  chain.pem: NhdGU6CiAgICBEY...
  pkey.key: LSUlFcFFJQkFBS0N...
----

Finish the certificate rotation by pushing the new secret to Kubernetes:

[source,console]
----
kubectl replace -f resource.yaml
----

You can then check that the new secret has been applied:

[source,console]
----
kubectl get secret couchbase-server-tls -o yaml
----

[source,yaml]
----
apiVersion: v1
data:
  chain.pem: NhdGU6CiAgICBEY...
  pkey.key: LSUlFcFFJQkFBS0N...
kind: Secret
metadata:
  creationTimestamp: "2019-01-09T09:42:35Z"
  name: couchbase-server-tls
  namespace: default
  resourceVersion: "116380"
  selfLink: /api/v1/namespaces/default/secrets/couchbase-server-tls
  uid: e5111d54-13f2-11e9-baeb-0ac70bf4cf44
type: Opaque
----

Each pod will have a copy of the new certificate and key in a mounted inbox on each node.

NOTE: Since the Operator secret (`couchbase-operator-tls`) contains the root CA, there should be no need to rotate the Operator secret when a server certificate has been compromised or expired.
However, if the root CA has been compromised, you will need to replace the Operator secret, as described in the next section.

=== Replacing the entire PKI

If the root CA is compromised, a full rotation and replacement of the PKI will be required.
When you replace the PKI, you'll also need to replace the server _and_ Operator TLS secrets with ones that include certificates and keys that align to the new CA.

Replacing the Operator secret (`couchbase-operator-tls`) involves the same procedure as replacing the server secret.
