= Couchbase TLS

Couchbase supports transport layer security [TLS] in order to encrypt communications on the wire and provide mutual authentication between peers.

The basic requirements are:

* A certificate authority [CA] certificate which will be used by all actors to validate that peer certificates have been digitally signed by a trusted CA
* A server certificate/key pair for all nodes in the Couchbase cluster.  If using a hierarchy of intermediate CAs these must be appended to the client certificate, ending in the intermediate CA signed by the top-level CA.  Server certificates must have a subject alternative name [SAN] set so that a client can assert that the host name it is connecting to is the same as that in the certificate.  We currently support using wildcard entries only e.g. `*.cluster.domain.svc`, where _cluster_ is the name of the _couchbasecluster_ resource, and _domain_ is the namespace the cluster is running in (typically _default_).

IMPORTANT: In version 1.0.0+ TLS certifcates are installed as part of the pod creation process, and cannot be enabled on an existing cluster.

IMPORTANT: In version 1.0.0+ TLS csertificate rotation is not supported.

== Configuration

An example configuration is as follows:

[source,yaml]
----
spec:
  ...
  tls:
    static:
      member:
        serverSecret: couchbase-server-tls
      operatorSecret: couchbase-operator-tls
  ...
----

For static TLS configuration _serverSecret_ and _operatorSecret_ need to be specified.  These refer to named Kubernetes secrets which are described below.

== Creating Secrets

Secrets are referred to in the _couchbasecluster_ resource, therefore may have any name you choose.  The format of individual secrets is discussed below.

=== spec.tls.static.member.serverSecret

Server secrets need to be mounted as a volume within the Couchbase Server pod with specific names.  The certificate chain must be named _chain.pem_ and the private key _pkey.pem_.

[source,shell]
----
$ kubectl create secret generic couchbase-server-tls \
  --from-file example/tls/certs/chain.pem \
  --from-file example/tls/certs/pkey.key
----

=== spec.tls.static.operatorSecret

The operator client secrets are read directly from the API.  We expect only a single value to be present; _ca.crt_ is the top-level CA which is used to authenticate all TLS server certificate chains.

[source,shell]
----
$ kubectl create secret generic couchbase-operator-tls \
  --from-file example/tls/certs/ca.crt
----

== Creating Certificates

Creating X.509 certificates is beyond the scope of this documentation and is given only for illustrative purposes only.

=== EasyRSA

EasyRSA by OpenVPN makes operating a public key infrastructure [PKI] relatively simple, and is the recommended method to get up and running quickly.

First clone the repository:

[source,shell]
----
$ git clone https://github.com/OpenVPN/easy-rsa
----

Initialize and create the CA certificate/key.  You will be prompted for a private key password and the CA common name [CN], something like _Couchbase CA_ is sufficient.  The CA certificate will be available as _pki/ca.crt_.

[source,shell]
----
$ cd easy-rsa/easyrsa3
$ ./easyrsa init-pki
$ ./easyrsa build-ca
----

Create a server wildcard certificate and key to be used on Couchbase Server pods.  The operator/clients will access the pods via Kubernetes services for example _cb-example-0000.cb-example.default.svc_ so this needs to be in the SAN list in order for a client to verify the certificate belongs to the host being connected to.  To this end we add in a _--subject-alt-name_, this can be specified multiple times in case your client uses a different method of addressing.  The key/certificate pair can be found in _pki/private/couchbase-server.key_ and _pki/issued/coouchbase-server.crt_ and used as _pkey.pem_ and in the _chain.pem_ files respectively in the _serverSecret_.

[source,shell]
----
$ ./easyrsa --subject-alt-name=DNS:*.cb-example.default.svc build-server-full couchbase-server nopass
----

Please note that password protected keys are supported by neither Couchbase Server nor Couchbase Operator.

==== Private Key Formatting

Due to an https://issues.couchbase.com/browse/MB-24404[issue] with Couchbase server's private key handling, server keys need to be PKCS#1 formatted.  This can be achieved with the following commands:

[source,shell]
----
$ openssl rsa -in pkey.key -out pkey.key.der -outform DER
$ openssl rsa -in pkey.key.der -inform DER -out pkey.key -outform PEM
----
