= Streaming Couchbase Logs

[abstract]
Enable and setup log streaming to other tools for the Couchbase Autonomous Operator.

include::partial$tutorial.adoc[]

This guide walks through an example of configuring log streaming to Loki and Elasticsearch for the Couchbase Server pods.
It also shows how to target Azure blob storage and Amazon S3 storage for the audit logs.
A redaction example is shown to demonstrate how we can do redaction in-flight if required.

== Log configuration

The Couchbase server images currently log to various files in a volume per pod rather than standard output as is typical in Kubernetes environments. 
However there is now xref:concept-couchbase-logging.adoc#log-streaming[support] for a log streamer sidecar using https://fluentbit.io/[Fluent Bit^]. 
This can be enabled in the CRD, if not specified it defaults to disabled to maintain existing behavior.

The Couchbase Autonomous Operator provides a default configuration via a `Secret`. 
The name of this `Secret` is specified by the CRD and defaults to `fluent-bit-config`. 
The purpose of the `Secret` is to provide the various configuration files as a volume to the logging sidecar. 
This means you can add any configuration supported by Fluent Bit as a custom version of the `Secret` and the operator will use it in preference.

The easiest way to do this is create the `Secret` prior to the cluster to guarantee it is used, again make sure it is in the right namespace.

[IMPORTANT]
====
The pod will not start if the `Secret` is missing as it is required.
The `spec.logging.manageConfiguration` field in the CRD must be set to `false` to use a custom configuration, otherwise the operator will overwrite the `Secret` with its own version.
====

Here is an example configuration that demonstrates how to use the Couchbase log streamer image but customize it slightly, in this case by reducing the logs shipped to just the audit one:

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: fluent-bit-config
stringData:
  fluent-bit.conf: |
    [SERVICE]
        flush        1
        daemon       Off
        log_level    Warning
        parsers_file /fluent-bit/etc/parsers-couchbase.conf

    # We split up the input configuration to simplify reuse in testing and custom configurations (so you don't have to repeat it).
    # @include /fluent-bit/etc/couchbase/in-*.conf
    # Each of the logs should have a tag: couchbase.log.<logname>.
    # Only include audit log
    @include /fluent-bit/etc/couchbase/in-audit-log.conf

    # Output all parsed Couchbase logs by default
    [OUTPUT]
        name  stdout
        match couchbase.log.*
----

Be careful with formatting, Fluent Bit is very particular in that files must all follow the same indentation.

== Cluster configuration

Here is an example cluster configuration with a single bucket configuration and other non-production defaults.
The main thing it demonstrates is how to ensure we can provide a custom log configuration by setting `manageConfiguration: false`.

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: cb-example-auth
type: Opaque
data:
  username: QWRtaW5pc3RyYXRvcg== # Administrator
  password: cGFzc3dvcmQ=         # password
---
apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: default
---
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-example
spec:
  logging:
    audit:
      enabled: true
      garbageCollection:
        sidecar:
          enabled: true
    server:
      enabled: true
      manageConfiguration: false # This is vital to ensure we use a custom configuration provided
  image: couchbase/server:6.6.1
  security:
    adminSecret: cb-example-auth
  buckets:
    managed: true
  servers:
  - size: 3
    name: all_services
    services:
    - data
    - index
    - query
    - search
    - eventing
    - analytics
    volumeMounts:
      default: couchbase 
  volumeClaimTemplates: 
  - metadata:
      name: couchbase 
    spec:
      storageClassName: standard 
      resources: 
        requests:
          storage: 1Gi
----

The key components here are the enabling of the logger sidecar (and also the sidecar to cleanup rotated audit logs):

[source,yaml]
----
spec:
  logging:
    audit:
      enabled: true
      garbageCollection:
        sidecar:
          enabled: true
    server:
      enabled: true
      manageConfiguration: false
----

With this deployed, the logs will be available on the standard output of the `logging` container in the pods:

[source,bash]
----
kubectl logs cb-example-0000 logging
----

== Loki example

A simple approach to deploy a full logging and monitoring solution is to use the Loki stack.
This stack can provide a Fluent Bit `daemonset` (node logs), Prometheus, Loki and Grafana deployments so provides a nice and simple integrated solution for monitoring and logging.
A Helm chart deployment can be used to push this out: https://grafana.com/docs/loki/latest/installation/helm/#deploy-loki-stack-loki-fluent-bit-grafana-prometheus
Full details are on that page to then use Grafana and configure the stack how you might want in your cluster.

As a simple example using the default namespace:
[source,bash]
----
helm repo add grafana https://grafana.github.io/helm-charts
helm upgrade --install loki grafana/loki-stack \
--set fluent-bit.enabled=false,promtail.enabled=true,grafana.enabled=true,prometheus.enabled=true,prometheus.alertmanager.persistentVolume.enabled=false,prometheus.server.persistentVolume.enabled=false
----

The configuration uses PromTail over Fluent Bit for shipping logs from the Kubernetes nodes. 
The main reason for this is to mitigate an issue with our sidecars triggering a fingerprint collision in Loki:
* https://github.com/fluent/fluent-bit/issues/1746
* https://github.com/grafana/loki/issues/898#issuecomment-552333246
It may be better/easier to ship direct from the Fluent Bit sidecar to Loki using the https://docs.fluentbit.io/manual/pipeline/outputs/loki[plugin^].
This would allow you to stream individual logs separately, the helm deployment is the typical `daemonset` deployment of all logs on the node.

Once it is deployed, you can retrieve the Grafana admin secret and do any port forwarding or similar required:
[source,bash]
----
kubectl get secret loki-grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo
kubectl port-forward service/loki-grafana 3000:80 
----

Refer to the https://grafana.com/docs/loki/latest/overview/[official Loki documentation^] for up-to-date information and any more details.

[IMPORTANT]
====
For alerting on logs through the UI, make sure to use a https://github.com/grafana/grafana/pull/31424[version of Grafana >= 7.5^].
====

== Elasticsearch example

An Elasticsearch deployment or stateful set is required and likely a Kibana instance too. 
An example instance is shown below although this is a basic example with a single replica.

[source,yaml]
----
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  clusterIP: None
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
        resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
        ports:
        - containerPort: 9200
          name: rest
          protocol: TCP
        - containerPort: 9300
          name: inter-node
          protocol: TCP
        env:
          - name: cluster.name
            value: k8s-logs
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.seed_hosts
            value: "es-cluster-0.elasticsearch"
          - name: cluster.initial_master_nodes
            value: "es-cluster-0"
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  ports:
  - port: 5601
  selector:
    app: kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.2.0
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch:9200
        ports:
        - containerPort: 5601
----

This needs to be deployed in the same namespace as the Couchbase cluster or the service URL will need to be explicit (include the namespace) in the log configuration.

Once this is in place we can configure Fluent Bit, the main area to manage is the output plugin configuration with the rest being the same as above:

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: fluent-bit-config
stringData:
  fluent-bit.conf: |
    # Just include the normal file and append to it the Elasticsearch output
    @include /fluent-bit/etc/fluent-bit.conf

    # Output to Elasticsearch
    [OUTPUT]
        name  es
        match couchbase.log.*
        Logstash_Format On 
        Include_Tag_Key On
        Tag_Key FluentBit-Key
        Host elasticsearch
        Port 9200
----

In this case we send all logs to Elasticsearch via a regex match.

If the Elasticsearch instance is in another namespace then the `Host` must be updated to include the namespace according to the usual Kubernetes syntax `<service>.<namespace>`.
Similarly if it is external then the correct URL needs to be provided and resolved correctly.

== Azure Blob Storage example

Full details are on the Fluent Bit documentation https://docs.fluentbit.io/manual/pipeline/outputs/azure_blob[page^].
This example shows you how to reconfigure the default sidecar to ship the audit logs to an Azure endpoint and builds on the previous example.

The important steps to cover are:
1. CRD configuration - make sure logging is enabled but the `manageConfiguration: false` field is set so the operator does not reconcile our log configuration.
2. Fluent Bit configuration - as the operator is not providing it, we now must provide a custom configuration to use.

For CRD configuration we will use the custom example xref:tutorial-couchbase-logging.adoc#Cluster_Configuration[above].

To configure Fluent Bit, the main area to manage is the output plugin configuration with the rest being the same as above:

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: fluent-bit-config
stringData:
  fluent-bit.conf: |
    # Just include the normal file and append to it the Elasticsearch output
    @include /fluent-bit/etc/fluent-bit.conf

    # Output only audit log by default
    [OUTPUT]
        name                  azure_blob
        match                 couchbase.log.audit
        account_name          YOUR_ACCOUNT_NAME
        shared_key            YOUR_SHARED_KEY
        path                  kubernetes
        container_name        logs
        auto_create_container on
        tls                   on
----

Be aware of setting the `YOUR_*` variables above for `account_name` and `shared_key` along with things like the `container_name` and `path`.
The Fluent Bit documentation describes all the various options.

To simplify testing, the https://github.com/Azure/Azurite[Azurite^] emulator can be used.

[source,yaml]
----
apiVersion: v1
kind: Service
metadata:
  name: azurite
  labels:
    app: azurite
spec:
  ports:
  - port: 10000
  selector:
    app: azurite
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurite-deployment
  labels:
    app: azurite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurite
  template:
    metadata:
      labels:
        app: azurite
    spec:
      containers:
      - name: azurite
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
        - containerPort: 10000
----

The log configuration then becomes:
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: fluent-bit-config
stringData:
  fluent-bit.conf: |
    # Just include the normal file and append to it the Elasticsearch output
    @include /fluent-bit/etc/fluent-bit.conf

    # Output only audit log by default
    [OUTPUT]
        name                  azure_blob
        match                 couchbase.log.audit
        account_name          devstoreaccount1
        shared_key            Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
        path                  kubernetes
        container_name        logs
        auto_create_container on
        tls                   off
        emulator_mode         on
        endpoint              azurite:10000
----

== Amazon S3 example

Again, all the details are on the Fluent Bit documentation https://docs.fluentbit.io/manual/pipeline/outputs/s3[page^].
`role_arn` is an important setting to specify if not using something like instance roles.

The log configuration then becomes:
[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: fluent-bit-config
stringData:
  fluent-bit.conf: |
    # Just include the normal file and append to it the Elasticsearch output
    @include /fluent-bit/etc/fluent-bit.conf

    # Output only audit log by default
    [OUTPUT]
        Name                         s3
        Match                        couchbase.log.audit
        bucket                       my-bucket
        region                       us-west-2
        total_file_size              250M
        s3_key_format                $TAG[2]/$TAG[0]/%Y/%m/%d/%H/%M/%S
        s3_key_format_tag_delimiters .-
----

Refer to the Fluent Bit documentation as this also links out to the https://github.com/aws/aws-for-fluent-bit[AWS packaged Fluent-Bit image^] for example which may be a better option to use for your sidecar.

== Image configuration

The CRD supports specifying a different image and/or version for log streaming support.
This may be required if a custom image is required with self-signed certificates for example, or if you want to use another image like the AWS one provided for their cloud.

To specify another image but keep the rest of the configuration the same then all that needs to be provided is the `spec.logging.server.sidecar.image` field with the correct image name to use.
Be aware that this will then lose the Couchbase log parsing and other configuration provided by default in the Couchbase log streamer image. 
The parser configuration could be provided in by customizing the log configuration which will then make it available to the new image as the volume, any other configuration will also need to be provided which may also need a tweak to the `spec.logging.server.sidecar.configurationMountPath` as well.

== Log redaction in-flight

Fluent Bit provides some very powerful facilities to mutate the log lines before they even leave the container.
This could be used for redaction for example which is what this example shows, but it could be extended to any time of user-configurable mutation.

There are two main approaches to redaction:
1. Just remove the entire line.
2. Replace/remove redacted content within the line.

Redaction details are covered https://docs.couchbase.com/server/current/manage/manage-logging/manage-logging.html#understanding_redaction[here], a quick summary is that we hash and replace the contents of the `<ud>...</ud>` tags in the string.

Option 1 can be provided by a simple https://docs.fluentbit.io/manual/pipeline/filters/grep[grep^] filter within Fluent Bit:
[source]
----
[FILTER]
    Name grep
    Match *
    Exclude message \<ud\>
----
This will filter out any entries for the `message` key that match the regex.

Option 2 is the current implementation within Couchbase Server log collection, i.e. via `cbcollect_info` or similar tooling.
The Couchbase Fluent Bit image provides built-in support for redaction although it is not enabled by default.
Redaction can be carried out by using a https://docs.fluentbit.io/manual/pipeline/filters/lua[LUA filter^] with the LUA scripting required to support it all present in the image already.

A `redaction.lua` LUA script is provided inside the image to use with the `cb_sub_message` function to call inside the filter.

The following example generates a sample message to redact using the Fluent Bit dummy plugin, usually you would match an existing log file you wanted to redact:
[source]
----
# Simple test generator for redaction
[INPUT]
    Name dummy
    Tag couchbase.redact.test
    Dummy {"message": "Cats are <ud>sma#@&*+-.!!!!!rter</ud> than dogs, and <ud>sheeps</ud>"}

# Redaction of fields
[FILTER]
    Name    lua
    # Typically this would be a couchbase.log.X tag instead you match on, this is just for the test here
    Match   couchbase.redact.*
    script  redaction.lua
    call    cb_sub_message

# Now rewrite the tags for redacted information - not required if redacting normal logs
[FILTER]
    Name rewrite_tag
    Match couchbase.redact.*
    Rule message .* couchbase.log.$TAG[2] false

[OUTPUT]
    name  stdout
    match couchbase.log.*
----
When run this will output something like the following showing the redacted strings as hashes now:
[source,bash]
----
0] couchbase.logs.test: [1616146713.035099437, {"message"=>"Cats are <ud>00b335216f27c1e7d35149b5bbfe19d4eb2d6af1</ud> than dogs, and <ud>888f807d45ff6ce47240c7ed4e884a6f9dc7b4fb</ud>"}]
[0] couchbase.logs.test: [1616146714.035226932, {"message"=>"Cats are <ud>00b335216f27c1e7d35149b5bbfe19d4eb2d6af1</ud> than dogs, and <ud>888f807d45ff6ce47240c7ed4e884a6f9dc7b4fb</ud>"}]
[0] couchbase.logs.test: [1616146715.035028818, {"message"=>"Cats are <ud>00b335216f27c1e7d35149b5bbfe19d4eb2d6af1</ud> than dogs, and <ud>888f807d45ff6ce47240c7ed4e884a6f9dc7b4fb</ud>"}]
[0] couchbase.logs.test: [1616146716.035374579, {"message"=>"Cats are <ud>00b335216f27c1e7d35149b5bbfe19d4eb2d6af1</ud> than dogs, and <ud>888f807d45ff6ce47240c7ed4e884a6f9dc7b4fb</ud>"}]
[0] couchbase.logs.test: [1616146717.035079113, {"message"=>"Cats are <ud>00b335216f27c1e7d35149b5bbfe19d4eb2d6af1</ud> than dogs, and <ud>888f807d45ff6ce47240c7ed4e884a6f9dc7b4fb</ud>"}]
----

[NOTE]
====
For redaction we recommend only matching those streams you want to redact to reduce the load.
LUA scripting has an overhead and it is recommended to use an extra Fluent Bit worker thread at least if you enable it.

A salt for redaction can be provided in the logging configuration secret by specifying it in the `redaction.salt` file/key.
The salt is defaulted to the cluster name by the operator and is provided in the default configuration even though it is not used by default.
====

Redaction is not enabled by default for these main reasons:
1. It is optional in Couchbase Server.
2. Performance - running a regex and string substitution can be expensive.
3. Debugging - it may hash away useful identifiers for internal usage.
4. Logs are not being exported externally by default anyway, they just go to standard output. A user would have to use a custom configuration to ship them elsewhere at which point the redaction can also be configured (and tuned for just the streams being exported).
5. A standard Kubernetes log pipeline architecture fed by the log streamer may already do redaction, e.g. Fluentd has a https://github.com/fluent/fluent-plugin-sanitizer[sanitizer plugin^].