= Upgrading A Couchbase Cluster

The Couchbase operator provides support to automatically upgrade a running cluster.  It performs a rolling upgrade one node at a time.  First a new node is created with the same pod configuration as the chosen node to upgrade, thus maintaining the same services e.g. data, index etc.  Data is rebalanced across the cluster so that the old node is evacuated and ejected from the cluster and the new node takes the load as data is transferred.  By manintaining N+1 nodes during the process we are able to handle all queries seemlessly without any performance degrdation.  Finally the selected upgrade node is deleted.

== Initiating an Upgrade

Simply edit the cluster specification and change the version string to a valid container.  Instructions for updating your specification can be found xref:updating-couchbase.adoc[here]

NOTE: Upgrades are limited to only next next major version.

NOTE: If for some reason the upgrade process fails you are able to roll back to the previous version.  Couchbase Server does not support downgrading once the entire cluster has upgraded.
