= Upgrading a Couchbase Cluster

[abstract]
The Couchbase Autonomous Operator provides support for automatically upgrading a running Couchbase cluster.

The Operator performs a rolling upgrade of a Couchbase cluster one node at a time.
A new node is created with the same pod configuration as the chosen node to upgrade, thus maintaining the same Couchbase services, e.g. Data, Index, etc.

Data is rebalanced across the cluster so that the old node is evacuated and ejected from the cluster, and the new node takes the load as data is transferred.
By maintaining N+1 nodes during the upgrade process, the cluster can handle all queries seamlessly without any performance degradation.

== Initiating an Upgrade

To upgrade a Couchbase cluster, simply edit the CouchbaseCluster specification and change the version string to a valid container.
Instructions for updating your specification can be found xref:updating-couchbase.adoc[here]

* Only direct upgrade paths are supported.
Direct upgrades include point releases and next major versions.
Refer to the Couchbase Server xref:server:install:upgrade.adoc[upgrade documentation] for more information about direct upgrade paths.
* If for some reason the upgrade process fails, you are able to roll back to the previous version.
Couchbase Server does not support downgrading once the entire cluster has been upgraded.
