= What's New?
include::partial$constants.adoc[]

Autonomous Operator {operator-version-minor} release is primarily focused on adding some key features introduced in Couchbase Server 7.0 to Autonomous Operator such as Scopes and Collections, and RBAC changes to Analytics.
It also includes a brand new tool to self-certify Autonomous Operator on Kubernetes platforms along with various other components.

== Manage Scopes and Collections with Autonomous Operator

Couchbase Server 7.0 has introduced Scopes and Collections that are new data organization layers between Couchbase Buckets and JSON documents which enables a Dynamic Data Containment Model.
Together, Scopes and Collections change the game by making Couchbase one of the few flexible NoSQL systems to support multi-layered structures that map to the relational database schema.
At the same time, they provide data isolation which is very useful for high-density applications.

With Autonomous Operator 2.3-beta, we are introducing Scopes and Collections for Kubernetes deployments where Data Isolation and Dynamic Data Containment are very important use-cases, especially for modern application developments based on microservices architecture.
With the 2.3-beta release, Autonomous Operator has the ability to fully manage scopes and collections within a bucket. With Scopes and Collections, Autonomous Operator provides fine-grained access control and cross-datacenter-replication, and improved scalability.
Migration from Couchbase Server 6.x to 7.x happens seamlessly with no additional steps required at your end.

xref:concept-scopes-and-collections.adoc[Learn more] about how Scopes and Collections work in Autonomous Operator.

== Self-Certify Autonomous Operator for any certified Kubernetes platform

With Autonomous Operator 2.3-beta we are introducing a self-certification tool that allows you to certify your platform and other platform specific components such as storage, networking for use with Autonomous Operator.

Today Autonomous Operator is tested and certified against a number of major platforms such as Amazon EKS, Google GKE, Microsoft AKS, and Red Hat OCP.
Official certification is often a time-consuming process, so this has to be constrained. However, we understand that end users may not want to use one of the officially certified platforms for some of the reasons listed below:

* Data locality - vendors may not operate in your country or region
* On-premise deployments - you may be using your own version of Kubernetes
* Vendor lock-in - you may be tied to existing infrastructure providers

So, there has to be another way of supporting these users and providing confidence that the Autonomous Operator will function as designed in your environment.
This is why we are introducing a self-certification tool with Autonomous Operator.
It fulfills the following test criteria:

* Kubernetes API conformance
** Couchbase custom resources are accepted when they should
** Couchbase custom resources are rejected when they should, either via API schema validation or the admission controller
* Platform behavior conformance
** Simulation of platform scheduling, upgrade error conditions, etc.
** Validation of the Operator that it can recover database instances in a safe and predictable manner
* Couchbase Server feature conformance
** Ensures that Couchbase server behaves in a safe and predictable manner

Thus the test framework can be used to identify where Kubernetes API rules change in an incompatible way, where Kubernetes platform behaviors lead to unexpected and unsupportable results, and where Couchbase Server changes lead to incompatibilities with the Operator.

xref:concept-platform-certification.adoc[Learn more] about self-certification.

== RBAC for Analytics 

In Couchbase Server 7.0 some new roles and RBAC settings have been added specifically to the Couchbase Analytics service, which is now also added to Operator in 2.3-beta.

== Couchbase Helm Chart 

Couchbase Helm Chart provides an alternate way to deploy Operator and Couchbase Clusters on Kubernetes platforms. Hence, with every release.
We plan to reconcile Couchbase Helm Chart with enhancements made to Operator to maintain a consistent user experience.
