= What's New?
include::partial$constants.adoc[]

Couchbase Autonomous Operator {operator-version-minor} release is focused on adding some key features introduced in Couchbase Server 7.0 to CAO such as Scopes and Collections, TLS 1.3 support, RBAC changes to Analytics, and a special feature - a Self-Certification tool - designed to certify CAO on any platform of your choice. 

== Manage Scopes and Collections with CAO
Couchbase Server 7.0 has introduced Scopes and Collections that are new data organization layers between Couchbase Buckets and JSON documents which enables a Dynamic Data Containment Model. Together, Scopes and Collections change the game by making Couchbase one of the few flexible NoSQL systems to support multi-layered structures that map to the RDBMS schema. At the same time, they provide data isolation which is very useful for high-density applications.

With CAO 2.3_Beta, we are introducing Scopes and Collections for Kubernetes deployments where Data Isolation and Dynamic Data Containment are very important use-cases, especially for modern application developments based on microservices architecture. With the 2.3_Beta release, CAO has the ability to fully manage scopes and collections within a bucket. With Scopes and collections, CAO provides fine-grained access control and cross-datacenter-replication, and improved scalability.  Migration from Couchbase Server 6.x to 7.x happens seamlessly with no additional steps required at your end. 
Learn more<link> about how Scopes and Collections work in CAO.

== Self-Certify CAO for any platform of your choice
With CAO 2.3_Beta we are introducing a Self-Certification tool that allows you to certify your platform for use with Couchbase Autonomous Operator.
Today CAO is tested and certified against a number of major platforms such as Amazon EKS, Google GKE, Microsoft AKS, and Red Hat OCP. Official certification is often a time-consuming process, so this has to be constrained. However, we understand that end users may not want to use one of the officially certified platforms for some of the reasons listed below:
* Data locality - vendors may not operate in your country or region
* On-premise deployments - you may be using your own version of Kubernetes
* Vendor lock-in - you may be tied to existing infrastructure providers

So, there has to be another way of supporting these users and providing confidence that the CAO will function as designed in your environment. This is why we are introducing a Self-Certification tool with CAO. It fulfills the following test criteria:

* Kubernetes API conformance
** Couchbase custom resources are accepted when they should
** Couchbase custom resources are rejected when they should, either via API schema validation or the admission controller
* Platform behavior conformance
** Simulation of platform scheduling, upgrade error conditions, etc.
** Validation the Operator recovers database instances in a safe and predictable manner
* Couchbase Server feature conformance
** Ensures that Couchbase server behaves in a safe and predictable manner

Thus the test framework can be used to identify where Kubernetes API rules change in an incompatible way, where Kubernetes platform behaviors lead to unexpected and unsupportable results, and where Couchbase Server changes lead to incompatibilities with the Operator.
Learn more about the Self-Certification tool here<Link>.

== TLS 1.3 Support
With Couchbase server 7.0.2, TLS 1.3 support is added, and thus to reconcile with that, CAO is also improved to support TLS 1.3. 
 
== RBAC to Analytics 
In Couchbase Server 7.0 some new roles and RBAC settings have been added specifically to the Couchabse Analytics service, which is now also added to CAO in 2.3-Beta.

== Couchbase Helm Chart 
Couchbase Helm Chart provides an alternate way to deploy CAO and Couchbase Clusters on Kubernetes platforms. Hence, with every release, we plan to reconcile Couchbase Helm Chart with enhancements made to CAO to maintain a consistent user experience.
