= What's New?
include::partial$constants.adoc[]

Autonomous Operator {operator-version-minor} release is primarily focused on adding some key features introduced in Couchbase Server 7.0 to Autonomous Operator such as Scopes and Collections, and RBAC changes to Analytics.
It also includes a brand new tool to self-certify Autonomous Operator on Kubernetes platforms along with various other components.

== Manage Scopes and Collections with Autonomous Operator

Couchbase Server 7.0 has introduced Scopes and Collections that are new data organization layers between Couchbase Buckets and JSON documents which enables a Dynamic Data Containment Model.
Together, Scopes and Collections change the game by making Couchbase one of the few flexible NoSQL systems to support multi-layered structures that map to the relational database schema.
At the same time, they provide data isolation which is very useful for high-density applications.

We are introducing Scopes and Collections for Kubernetes deployments where Data Isolation and Dynamic Data Containment are very important use-cases, especially for modern application developments based on microservices architecture.
Couchbase Autonomous Operator can now manage scopes and collections within buckets.
Specifically, this release adds the capability to "catalog" important operational aspects of Couchbase such as configurations, resource specifications, topology, and database settings to make it easier to deploy Couchbase in any other environment or cloud.

Developers can also create new scopes and collections programmatically to support their modern microservices architectures and be assured that these will be managed autonomously once they are created.
With Scopes and Collections, Autonomous Operator provides fine-grained access control and cross-datacenter-replication, and improved scalability.
Migration from Couchbase Server 6.x to 7.x happens seamlessly with no additional steps required at your end.

xref:concept-scopes-and-collections.adoc[Learn more] about how Scopes and Collections work in Autonomous Operator.

== Operator Self-Certification Lifecycle Tool

We are introducing an operator self-certification lifecycle tool that removes barriers to adopting certified Kubernetes platforms.
The self-certification lifecycle tool allows users to validate the compatibility of Kubernetes platforms and other platform-specific components such as storage and networking with Autonomous Operator.
To be fully eligible for Couchbase support, users need to follow the xref:concept-platform-certification.adoc#what-is-the-self-certification-lifecycle-process[approval process for the validated platform].

Today Autonomous Operator is tested and certified against a number of major platforms such as Amazon EKS, Google GKE, Microsoft AKS, and Red Hat OCP.
Official certification is often a time-consuming process, so this has to be constrained. However, we understand that end users may not want to use one of the officially certified platforms for some of the reasons listed below:

* Data locality - vendors may not operate in your country or region
* On-premise deployments - you may be using your own version of Kubernetes
* Vendor lock-in - you may be tied to existing infrastructure providers

So, there has to be another way of supporting these users and providing confidence that the Autonomous Operator will function as designed in your environment.
This is why we are introducing a self-certification tool with Autonomous Operator.
It fulfills the following test criteria:

* Kubernetes API conformance
** Couchbase custom resources are accepted when they should
** Couchbase custom resources are rejected when they should, either via API schema validation or the admission controller
* Platform behavior conformance
** Simulation of platform scheduling, upgrade error conditions, etc.
** Validation of the Autonomous Operator that it can recover database instances in a safe and predictable manner
* Couchbase Server feature conformance
** Ensures that Couchbase server behaves in a safe and predictable manner

Thus the test framework can be used to identify where Kubernetes API rules change in an incompatible way, where Kubernetes platform behaviors lead to unexpected and unsupportable results, and where Couchbase Server changes lead to incompatibilities with the Autonomous Operator.

NOTE: Currently, the Self Certification tool is not supported on the Red Hat OpenShift platform because it requires a new format for the binary or package validation in order to publish the Self Certification tool. Work is underway to fix these issues.

xref:concept-platform-certification.adoc[Learn more] about self-certification.

== RBAC for Analytics

In Couchbase Server 7.0 some new roles and RBAC settings have been added specifically to the Couchbase Analytics service, which is now also added to Autonomous Operator in 2.3-beta.

== Couchbase Helm Chart

Using the xref:helm-couchbase-config.adoc[Couchbase Helm Chart] provides an alternative way to deploy the Couchbase Autonomous Operator, providing operators with an easy way to deploy, manage, and maintain Couchbase clusters.
Keeping up with the new {operator-version-minor} enhancements in the Autonomous operator, the Couchbase Helm chart is kept up-to-date, delivering the best possible user experience.
