= What's New?
include::partial$constants.adoc[]

Couchbase Autonomous Operator {operator-version-minor} is a landmark release that's built to take advantage of the latest Kubernetes improvements in the areas of security and custom resources.
The changes in this release enable several advancements in how you can manage, monitor, and deploy Couchbase clusters.

Take a look at the xref:release-notes.adoc[release notes] for a more complete list of changes in this release, including known and fixed issues.

== New Couchbase Custom Resource Model

This release introduces a new model for deploying and managing Couchbase custom resources.
Previously, you would deploy a cluster using a single, monolithic `CouchbaseCluster` resource configuration that defined everything about a cluster (e.g. nodes, buckets, XDCR, etc).
Starting with Autonomous Operator {operator-version-minor}, parts of the `CouchbaseCluster` resource have been separated into their own custom resource types, which the Autonomous Operator aggregates together using xref:concept-label-selection.adoc[label selection].

Moving to this new model is crucial for the Autonomous Operator to be able to support continued evolutions in the Kubernetes and Couchbase platforms.
However, you'll find that these changes also provide immediate advantages in terms of manageability.
One of the most practical benefits is that you can achieve fine grained access control over different parts of a Couchbase deployment with the use of xref:concept-rbac.adoc[custom resource RBAC].

Autonomous Operator {operator-version-minor} requires that all Couchbase custom resources use the new format.
Couchbase custom resources -- such as `CouchbaseCluster` -- are not backwards compatible between Autonomous Operator versions 1 and 2.
If you're upgrading from Autonomous Operator 1.x, a tool (`cbopconv`) has been provided to convert your existing `CouchbaseCluster` resources to version 2.

Read more about how to xref:howto-operator-upgrade.adoc[Upgrade the Operator].

== Couchbase XDCR Management

The Autonomous Operator can now directly manage Cross Data Center Replication (XDCR) using the new xref:reference-couchbasereplication.adoc[CouchbaseReplication] resource.

Read more about how to xref:howto-xdcr.adoc[Configure XDCR].

== Couchbase RBAC Management

The Autonomous Operator can now directly manage the creation and authorization of Couchbase users (both local and LDAP).
When combined with xref:concept-label-selection.adoc[label selection], the new xref:reference-couchbaseuser.adoc[CouchbaseUser], xref:reference-couchbasegroup.adoc[CouchbaseGroup], and xref:reference-couchbaserolebinding.adoc[CouchbaseRoleBinding] resources allow a great deal of flexibility in how the Autonomous Operator can manage users in multi-cluster deployments.

Read more about managing xref:concept-user-rbac.adoc[Couchbase User RBAC].

NOTE: Support for LDAP and RBAC requires Couchbase Server 6.5. 

== Prometheus Metrics Collection

Autonomous Operator {operator-version-minor} provides native integration with the Couchbase Prometheus Exporter for collecting and exposing Couchbase Server metrics.
These exported metrics can be scraped by Prometheus and then visualized in tools like Grafana.

Read more about how to xref:howto-prometheus.adoc[Configure Prometheus Metrics Collection].

== Mutual TLS Support

Mutual TLS (mTLS) authentication between Couchbase Server and clients is now fully supported by the Autonomous Operator.
With this mode of operation, not only do clients verify that they are talking to a trusted entity, but the Couchbase Server instance can also establish trust in the client.

Read more about xref:concept-tls.adoc#tls-client-authentication[TLS Client Authentication].

== Global Auto-Compaction Management

Global Auto-Compaction settings can now be managed directly from the xref:reference-couchbasecluster.adoc#spec-cluster-autocompaction[CouchbaseCluster] resource.


