= What's New?
include::partial$constants.adoc[]

Couchbase Autonomous Operator {operator-version-minor} is an incremental release that adds new features to the Operator 2.0 series.
The changes in this release enable several advancements in how you can manage, monitor, and deploy Couchbase clusters.

Take a look at the xref:release-notes.adoc[release notes] for a more complete list of changes in this release, including known and fixed issues.

== Customizable Prometheus Metrics

The latest version of the Couchbase Prometheus Exporter allows for certain customizations to exported metrics.
The following customizations are currently supported:

* Change the namespace, subsystem, name, and help text for each metric.
* Enable and disable whether a metric is exported to Prometheus.

For more information, refer to xref:howto-prometheus.adoc#customizing-metrics[Customizing Metrics].

// Commenting out this section for future review.
////
== Upgrading to Operator 2.2

Upgrading a previous release to Operator {operator-version-minor} follows the xref:howto-operator-upgrade.adoc[usual process], however there are some things you should be aware of.

=== Before Upgrading

The technical lower limit of the Operator is Kubernetes 1.14.
Ensure your Kubernetes cluster is running this version or newer before upgrading.

The TLS requirements have been modified.
In order to ease the migration from legacy client bootstrap (CCCP) to the newest version (GCCCP), the Operator requires Couchbase cluster subject alternative names (SANs) to be updated.
Consult the xref:tutorial-tls.adoc[TLS documentation] for a full list of all the required SANs and the xref:howto-tls-rotation.adoc[TLS rotation how-to] in order to prepare for upgrade.
Failure to perform this step will result in errors from the dynamic admission controller (DAC) once upgraded.

=== During Upgrade

When upgrading Couchbase clusters from an earlier version of the Operator (prior to version {operator-version-minor}), the cluster will undergo a mandatory upgrade cycle.

Pod readiness were previously driven by an `exec` based readiness probe.
This was a security concern as it granted the Operator `pods/exec` privileges, and may be unacceptable in highly regulated environments.
As of Operator version {operator-version-minor} this will now be performed using readiness gates, that use the Kubernetes API exclusively.

You may use the <<bulk-upgrades>> feature to speed up this upgrade.
To enable during the Operator upgrade, stop the old Operator, replace the CRDs, edit the Couchbase cluster resource to enable bulk upgrades before restarting the new Operator.
////