= What's New?
include::partial$constants.adoc[]

Autonomous Operator {operator-version-minor} release is primarily focused on platform updates, feature parity with Couchbase Server, improvements to Pod Management and Security, as well as a number of minor fixes.

== Platform Updates

Autonomous Operator {operator-version-minor} is supported on versions 1.24 through 1.27 of Kubernetes, Rancher K3s, the equivalent managed cloud versions from Amazon Elastic Kubernetes Service (EKS), Google Kubernetes Engine (GKE), Microsoft Azure Kubernetes Service (AKS), and Red Hat OpenShift.

== Feature Parity with Couchbase Server

The Operator now allows Data Service (`memcached`) AuxIO and NonIO Threads to be configured.  See xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-cluster-data-auxiothreads[`couchbaseclusters.spec.cluster.data.auxIOThreads`] and xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-cluster-data-noniothreads[`couchbaseclusters.spec.cluster.data.nonIOThreads`].

The CouchbaseBackup resource now has a  Default Recovery Method which specifies how `cbbackupmgr` should recover from broken Backup/Restore attempts.
See xref:resource/couchbasebackup.adoc#couchbasebackups-spec-defaultrecoverymethod[`couchbasebackups.spec.defaultRecoveryMethod`].

== Pod Management

The Operator now parallelizes pod creation, for example during cluster creation and when performing upgrades, saving overall wall-clock time.

The Operator now adds specific labels to the PodDisruptionBudget for Cluster Member Pods, to make sure that only Cluster Members are included in the count used during a disruption.
Similarly, the internal pod cache behaviour has been improved to only cache Cluster Member pods.

== Pod and Container Security Contexts

From Operator {operator-version-minor}, xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-securitycontext[`couchbaseclusters.spec.securityContext`] has been deprecated in favour of xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-security-podsecuritycontext[`couchbaseclusters.spec.security.podSecurityContext`] and xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-security-securitycontext[`couchbaseclusters.spec.security.securityContext`], to define privilege and access control settings for Pods or Containers.
See https://kubernetes.io/docs/tasks/configure-pod-container/security-context/[Configure a Security Context for a Pod or Container] for details.
