= What's New?
include::partial$constants.adoc[]

Couchbase Autonomous Operator {operator-version-minor} is a significant release that adds new features to the Autonomous Operator 2.0 series.
The changes in this release enable several advancements in how you can manage, monitor, and deploy Couchbase clusters.

Take a look at the xref:release-notes.adoc[release notes] for a more complete list of changes in this release, including known and fixed issues.

== Couchbase Cluster Auto-scaling

The Autonomous Operator now supports Couchbase cluster auto-scaling for _all_ Couchbase services.
This means that Couchbase cluster server class configurations containing stateful services like Data and Index can now be configured to automatically scale in response to observed metrics.
(Previously, only stateless deployments of the Query Service were supported.)

The Autonomous Operator provides the necessary facilities for Couchbase clusters to be automatically scaled based on usage metrics.
This capability is provided through an integration with the Kubernetes https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/[Horizontal Pod Autoscaler (HPA)^].
Thresholds can be set for native Kubernetes metrics (such as pod CPU utilization) as well as Couchbase metrics (such as bucket memory utilization) that, once exceeded, trigger _horizontal scaling_ of individual server classes.
Auto-scaling doesn't incur any cluster downtime, and allows for each Couchbase Service to be scaled independently based on different metrics.

To help users get started in production, an xref:concept-couchbase-autoscaling-best-practices.adoc[auto-scaling best practices guide] has been provided.
This guide discusses relevant metrics for scaling individual Couchbase Services, and includes recommended settings based on internal benchmark testing performed by Couchbase.

For more information, refer to xref:concept-couchbase-autoscaling.adoc[].

== Online Expansion of Persistent Volumes

The Autonomous Operator now optionally allows for the expansion of persistent volumes that are already in use by Couchbase clusters, thus removing the need for a rolling upgrade of cluster pods.

For additional information and requirements, refer to xref:howto-persistent-volumes.adoc#online-volume-expansion[Online Volume Expansion].

== Customizable Prometheus Metrics

The latest version of the Couchbase Prometheus Exporter allows for certain customizations to exported metrics.
The following customizations are currently supported:

* Change the namespace, subsystem, name, and help text for each metric.
* Enable and disable whether a metric is exported to Prometheus.

For more information, refer to xref:howto-prometheus.adoc#customizing-metrics[Customizing Metrics].

// Commenting out this section for future review.
////
== Upgrading to Operator 2.2

Upgrading a previous release to Operator {operator-version-minor} follows the xref:howto-operator-upgrade.adoc[usual process], however there are some things you should be aware of.

=== Before Upgrading

The technical lower limit of the Operator is Kubernetes 1.14.
Ensure your Kubernetes cluster is running this version or newer before upgrading.

The TLS requirements have been modified.
In order to ease the migration from legacy client bootstrap (CCCP) to the newest version (GCCCP), the Operator requires Couchbase cluster subject alternative names (SANs) to be updated.
Consult the xref:tutorial-tls.adoc[TLS documentation] for a full list of all the required SANs and the xref:howto-tls-rotation.adoc[TLS rotation how-to] in order to prepare for upgrade.
Failure to perform this step will result in errors from the dynamic admission controller (DAC) once upgraded.

=== During Upgrade

When upgrading Couchbase clusters from an earlier version of the Operator (prior to version {operator-version-minor}), the cluster will undergo a mandatory upgrade cycle.

Pod readiness were previously driven by an `exec` based readiness probe.
This was a security concern as it granted the Operator `pods/exec` privileges, and may be unacceptable in highly regulated environments.
As of Operator version {operator-version-minor} this will now be performed using readiness gates, that use the Kubernetes API exclusively.

You may use the <<bulk-upgrades>> feature to speed up this upgrade.
To enable during the Operator upgrade, stop the old Operator, replace the CRDs, edit the Couchbase cluster resource to enable bulk upgrades before restarting the new Operator.
////