= What's New?
include::partial$constants.adoc[]

Autonomous Operator {operator-version-minor} release is primarily focused on platform updates, feature parity with Couchbase Server, improvements to Pod Management and Security, as well as a number of minor fixes. 
== Immediate Backups

It is now possible to run a CouchbaseBackup resource immediately via the new immediate_full and immediate_incremental backup strategies.

See xref:howto-backup.adoc#configure-backups[Configure Backups] for futher details.

== Improved Pod Management

Couchbase Operator now takes into consideration data topography and Couchbase Server version when determining which pods to scale down.  

== Log Uploads

There are new parameters that can be passed to the `cao collect-logs` command that will automatically upload the logs to Couchbase Support.

See xref:tools/cao.adoc#cao-collect-logs[Cao Collect Logs] for further details.

== Delta Recovery Upgrades

Couchbase Clusters can now be configured to perform a Delta-Recovery upgrades.  This upgrade is considerably faster than the current SwapRebalance method.

See xref:resources/couchbasecluster.adoc#couchbaseclusters-spec-upgradeProcess[Upgrade Process] for further details

== Quality of Life Improvements

Added an onlineExpansionTimeout to Couchbase Cluster to specify the number of minutes operator should wait before falling back to a rolling upgrade when volume expansion fails.
Added annotations to better help integrations with Prometheus.
Added platform specific zone labels to persistent volume claims for EKS, GKE and AKS.

== Pod Readiness Delay and Pod Readiness Period

Added pod readiness delay and pod readiness period parameters to the `cao create operator` command.  These will be applied to all Couchbase Server pods created by the operator.

See xref:/tools/cao.adoc#cao-create-operator[Cao Create Operator] for further details.
