= What's New?
include::partial$constants.adoc[]

Autonomous Operator {operator-version-minor} release provides full support for Couchbase Server 7.6, and several improvements to Pod Scheduling and Networking, as well as a number of minor fixes.

== Couchbase Server 7.6

See xref:7.6@server:introduction:whats-new.adoc[What’s New in Version 7.6] for full details, but the following new functionality is available in Operator 2.7, for clusters running Server 7.6:

* Data Service - Minimum Replica Count: Set with xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-cluster-data-minreplicascount[`couchbaseclusters.spec.cluster.data.minReplicasCount`].
* Data Service - Bucket Rank: Set with xref:resource/couchbasebucket.adoc#couchbasebuckets-spec-rank[`couchbasebuckets.spec.rank`].
* Index Service - File-based Rebalance: Enabled with xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-cluster-indexer-enableshardaffinity[`couchbaseclusters.spec.cluster.indexer.enableShardAffinity`].
* Auditing - Prune Rotated Logs: Set with xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-logging-audit-rotation-pruneage[`couchbaseclusters.spec.logging.audit.rotation.pruneAge`].
* Cluster Arbiter (Serviceless) Nodes: Created by leaving xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-servers-services[`couchbaseclusters.spec.servers.services`] empty.
* Backup - Backup and Restore Users and Groups: Set with xref:resource/couchbasebackup.adoc#couchbasebackups-spec-services-users[`couchbasebackups.spec.services.users`] and xref:resource/couchbasebackuprestore.adoc#couchbasebackuprestores-spec-services-users[`couchbasebackuprestores.spec.services.users`].
* Cross Data Center Replication (XDCR) - Connection Precheck: Called automatically when adding a Remote Cluster Reference.
* Data Service - Storage backend migration: Operator will automatically start the required Rebalances if it detects an unresolved Storage backend change.
Storage Backend can also be configured using annotations, see xref:reference-annotations.adoc#bucket-backend-configuration[Bucket Backend Configuration] for more details.
* Authentication - LDAP Middlebox Compatibility Mode: Can now be disabled if needed via xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-security-ldap-middleboxcompmode[`couchbaseclusters.spec.security.ldap.middleboxCompMode`].
* Data Service - Collections: xref:resource/couchbasecollection.adoc#couchbasecollections-spec-maxttl[`couchbasecollections.spec.maxTTL`] is now mutable.  However, due to https://issues.couchbase.com/browse/K8S-3632[K8S-3632^], it is not possible to set `maxTTL` to `-1` to disable expiry for that Collection.

== Delta Recovery / In-Place Upgrades

The `DeltaRecovery` upgrade process added in Operator 2.6 has been replaced by `InPlaceUpgrade`, to better reflect the actual behavior (not every Service can be Delta Recovered), and `DeltaRecovery` is now deprecated.

See xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-upgradeprocess[`couchbaseclusters.spec.upgradeProcess`] for more details.

== Server Group Improvements

In public cloud providers, it is common for the Server Groups in use to match the Availability Zones, and for there to be a small number of them.
In private data centers they are more likely to be used to represent a larger number of zones, based on racks, rows of racks, or even rooms, as well as PDUs and switches.

To allow a more even spread of Pods over a larger range of Server Groups, we have added the `shuffleServerGroups` annotation.

To take advantage of there being more Server Groups available during Pod rescheduling, we have added the `rescheduleDifferentServerGroup` annotation .

See xref:reference-annotations.adoc#cluster-scheduling[Cluster Scheduling] for more details.

== Pod Rescheduling

By applying the `reschedule` annotation to a Couchbase Pod, the operator will detect it and reschedule the Pod based on the currently selected upgrade process.
This allows Pods to be moved before any planned maintenance is performed on the Kubernetes Worker Nodes.

See xref:reference-annotations.adoc#pod-rescheduling[Pod Rescheduling] for more details.

== Improved Host Network Support

When the new `networking.improvedHostNetwork` annotation is enabled on a cluster, the Operator will skip SAN validation and will add the underlying Kubernetes hostname a Pod is running on to the alternate addresses list.

See xref:reference-annotations.adoc#host-network[Host Network] for more details.

== More Granular Couchbase Server Upgrades

Previously it was only possible to set a single Couchbase Server image for the entire `CouchbaseCluster` at xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-image[`couchbaseclusters.spec.image`], triggering a cluster-wide upgrade.
It is now possible to (optionally) set this at the Server Group/Server Class level, using xref:resource/couchbasecluster.adoc#couchbaseclusters-spec-servers-image[`couchbaseclusters.spec.servers.image`].
This overrides the Cluster-level setting, allowing per-Group/per-Class upgrades.
