= What's New?

Couchbase Autonomous Operator 1.2 is a substantial update that introduces several new manageability and automation features, including the ability to automatically upgrade Couchbase Server clusters.

Take a look at the xref:release-notes.adoc[release notes] for a list of known and fixed issues in this release.

== Automated Upgrade of Couchbase Clusters

The Operator is now capable of performing automated upgrades of Couchbase Server clusters.
Upgrading an entire Couchbase cluster is as easy as specifying the desired Couchbase version in the CouchbaseCluster configuration, and then pushing it to Kubernetes.
The Operator manages the entire online rolling upgrade by itself.

See xref:concept-upgrade.adoc[Upgrading a Couchbase Cluster]

== Integrated CouchbaseCluster Resource Validation

The Operator now requires resource validation via an https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/[admission controller^].

In previous releases of the Operator, a command-line tool called `cbopctl` was required whenever you submitted a new CouchbaseCluster configuration to the Operator.
This tool would perform client-side validation of Couchbase cluster configuration changes before the Operator would act on them, thus protecting your Couchbase deployment (and the Operator) from any accidental damage that might arise from an invalid configuration.

Starting with this release, validation checks are performed by the admission controller from within the Kubernetes cluster itself.
One of the many benefits of this change is that it allows you to use native commands like `kubectl create` and `oc edit` from anywhere, without having to worry about installing any extra command-line tools.

See xref:install-admission-controller.adoc[Installing and Using the Admission Controller]

== Helm Support

https://helm.sh/[Helm^] is a great platform for deploying, managing, and upgrading the Operator.
Official Couchbase charts make installation simple and repeatable, and Helm acts as a convenient single point of authority for keeping track of the resources that are associated with each deployment.

Whether you're new to Helm, or already have an existing Helm infrastructure, the official Couchbase Helm charts are a fantastic way to get started using the Operator.

See xref:helm-setup-guide.adoc[Helm Guide for the Couchbase Operator]

== Public Connectivity for Couchbase Clients

This release introduces support for connecting clients to the Couchbase cluster over the internet via public IP-based addressing and dynamic DNS.

See xref:network-requirements.adoc#public-connectivity-ddns[Public Connectivity]

NOTE: Couchbase clients must meet certain requirements to support public connectivity, and not all clients are supported at this time.
Refer to xref:network-requirements.adoc#table-public-connectivity[Supported Clients for Public Connectivity] for more information.

== Support for Public Kubernetes Services

The Operator now offers full production support on the following public Kubernetes services:

* Amazon Elastic Container Service for Kubernetes (EKS)
* Google Kubernetes Engine (GKE)
* Microsoft Azure Kubernetes Service (AKS)

== Rolling Upgrade of Kubernetes Clusters

With support for automatic rolling Kubernetes upgrades, the Operator helps take the hassle and anxiety out of upgrading your Kubernetes or OpenShift cluster.
By using disruption budgets, readiness probes, and custom Couchbase logic, the Operator ensures that your Couchbase deployment doesn't experience any downtime or data loss.

See xref:upgrading-kubernetes.adoc[Upgrading the Kubernetes Cluster]

== TLS Certificate Rotation

Kubernetes certificate rotation is supported in order to enable the replacement of expired or compromised certificates.

See xref:tls.adoc[Configuring TLS]

== Log Collection Improvements

Several enhancements have been made to `cbopinfo`, including a unified log collection experience for stateful and stateless deployments.

See xref:reference-cbopinfo.adoc[cbopinfo]

