= What's New?

Couchbase Autonomous Operator 1.1 introduces a number of supportability features and enhancements.
Take a look at the xref:release-notes.adoc[release notes] for a list of known and fixed issues in this release.

== Logs Support for Ephemeral Pods

To improve supportability in the case of Kubernetes node failure, the Operator now has the ability to persist just the Couchbase logs. By only persisting the log volumes, storage space can be used more efficiently. New options are also available to restrict the size and retention of logs.

This new functionality requires a persistent volume to be attached to Couchbase pods. To restrict the default volume mount to only persist the log subdirectory, add the `logs` tag under `volumeMounts` in the CouchbaseCluster xref:couchbase-cluster-config.adoc[configuration].

As a result of these changes, the Operator now supports certain stateless Couchbase node deployments in production, so long as persistent log volumes are attached to those pods. Review the xref:best-practices.adoc#persistent-volumes-best-practices[best practices] for more information about cluster supportability requirements.

== Log Redaction and Extended Debugging

Logs collected with xref:cbopinfo.adoc[cbopinfo] are automatically redacted of sensitive information by default.
In addition, new options have been added to `cbopinfo` to accommodate more environments and to be able to collect logs from volumes that are not attached to pods.
