# create a service account for the operator controller
# and give it cluster-admin permisions so that it
# is capable of making the default service account
# cluster-admin within template instantiated projects
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: couchbase-operator-admin
---
apiVersion: v1
kind: Secret
metadata:
  name: couchbase-operator-admin-secret
  annotations:
    kubernetes.io/service-account.name: couchbase-operator-admin
type: kubernetes.io/service-account-token
---
kind: ClusterRoleBinding
apiVersion: v1
metadata:
  name: couchbase-operator-admin-binding
subjects:
- kind: ServiceAccount
  name: couchbase-operator-admin
  apiGroup: rbac.authorization.k8s.io
  namespace: admin-cb-ctl
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
