FROM ashwin2002/testrunner-cloud:baseimage
WORKDIR /
# install python deps
RUN pip2 install --upgrade packaging appdirs
RUN pip install -U pip setuptools
RUN pip install paramiko && pip install gevent && pip install boto && pip install httplib2 && pip install pyyaml && pip install couchbase
# build libcouchbase
RUN git clone git://github.com/couchbase/libcouchbase.git && mkdir libcouchbase/build
WORKDIR libcouchbase/build
RUN ../cmake/configure --prefix=/usr && make && make install
WORKDIR /
RUN git clone --recursive https://github.com/kubernetes-client/python.git
WORKDIR /python
RUN python setup.py install
WORKDIR /
RUN git clone git://github.com/couchbase/testrunner.git --branch master
WORKDIR testrunner
RUN git clone https://github.com/couchbaselabs/py-tpcc.git
COPY ./tpcc/4node.ini 4node.ini
COPY getNodeIps.py getNodeIps.py
COPY tpcc-entrypoint.sh entrypoint.sh
RUN chmod +x ./entrypoint.sh
ENTRYPOINT ["./entrypoint.sh", "4", "5.5.0-2958", "3600"]
