FROM ashwin2002/testrunner-cloud:baseimage

ARG testrunnerBranch=${testrunnerBranch:-master}
ARG numNodes=${numNodes:-1}

WORKDIR /testrunner
RUN git checkout $testrunnerBranch

COPY ./${numNodes}node/${numNodes}node.ini ${numNodes}node.ini
COPY ./${numNodes}node/${numNodes}node-sanity.conf testcases.conf
COPY getNodeIps.py getNodeIps.py
COPY entrypoint.sh entrypoint.sh
RUN chmod +x ./entrypoint.sh
ENTRYPOINT ["./entrypoint.sh", ${numNodes}]
