FROM ashwin2002/testrunner-cloud:baseimage

ARG testrunnerBranch=${testrunnerBranch:-master}
ARG numNodes=${numNodes:-1}

WORKDIR /testrunner
RUN git checkout $testrunnerBranch

COPY ./platform-cert/${numNodes}node.ini ${numNodes}node.ini
COPY ./platform-cert/platform-cert.conf testcases.conf
COPY getNodeIps.py getNodeIps.py
COPY entrypoint.sh entrypoint.sh
RUN chmod +x ./entrypoint.sh
