FROM ashwin2002/testrunner-cloud:baseimage

ARG testrunnerBranch=${testrunnerBranch:-master}
ARG numNodes=${numNodes:-1}

WORKDIR /testrunner
RUN git checkout $testrunnerBranch

COPY ./tpcc/${numNodes}node.ini ${numNodes}node.ini
COPY getNodeIps.py getNodeIps.py
COPY tpcc-entrypoint.sh entrypoint.sh
RUN chmod +x ./entrypoint.sh
