FROM ubuntu:14.04
RUN apt-get update
RUN apt-get install -y --force-yes gcc g++ make cmake git-core libevent-dev libev-dev libssl-dev libffi-dev psmisc iptables zip unzip python-dev python-pip vim curl --fix-missing

# Clone all required repos
WORKDIR /
RUN git clone --recursive https://github.com/kubernetes-client/python.git
RUN git clone https://github.com/couchbase/libcouchbase.git && mkdir libcouchbase/build
RUN git clone https://github.com/couchbase/testrunner.git

WORKDIR /testrunner
RUN git clone https://github.com/couchbaselabs/py-tpcc.git

# install python deps
RUN pip2 install --upgrade packaging appdirs
RUN pip install -U pip setuptools
RUN pip install paramiko && pip install gevent && pip install boto && pip install httplib2 && pip install pyyaml

# Install cloned repos
WORKDIR /libcouchbase/build
RUN ../cmake/configure --prefix=/usr && make && make install

WORKDIR /python
RUN python setup.py install

RUN pip install couchbase

# Create branch reference locally
WORKDIR /testrunner
RUN for i in `git branch -a | grep remote | grep -v HEAD | grep -v master`; do git branch --track ${i#remotes/origin/} $i; done

