# Creates operator chart without any custom resources
---
testID: "00"
rbac:
  create: false
couchbase-operator:
  couchbaseOperator:
    image:
      tag: 1.2.0-933
    commandArgs:
      create-crd: false
  admissionController:
    image:
      tag: 1.2.0-933
