## Override RBAC with ClusterRole and ClusterBinding
---
rbac:
  create: true
  serviceAccountName: test-resource-sa
couchbase-operator:
  rbac:
    create: false
    couchbaseServiceAccountName: test-resource-sa 
    admissionServiceAccountName: test-resource-sa 
  couchbaseOperator:
    image:
      tag: 1.2.0-933
  admissionController:
    image:
      tag: 1.2.0-933
