## Override RBAC with Role and RoleBinding
---
rbac:
  create: true
  couchbaseServiceAccountName: test-resource-operator
  admissionServiceAccountName: test-resource-admission
  clusterRoleAccess: false
couchbase-operator:
  rbac:
    create: false
  couchbaseOperator:
    serviceAccountName: test-resource-operator
    image:
      tag: 1.2.0-877
  admissionController:
    serviceAccountName: test-resource-admission
    image:
      tag: 1.2.0-877
