## Override RBAC with Role and RoleBinding
---
testID: "02"
rbac:
  create: true
  serviceAccountName: ci-service-account
  clusterRoleAccess: false
couchbase-operator:
  rbac:
    create: false
    couchbaseServiceAccountName: ci-service-account
    admissionServiceAccountName: ci-service-account
  couchbaseOperator:
    image:
      tag: 1.2.0-933
    commandArgs:
      create-crd: false 
  admissionController:
    image:
      tag: 1.2.0-933
