# Creates operator chart with custom CA and client certs
# * Requires namespace named ci-testnamespace
# * Verifies DNS uses service named ci-testcluster
---
rbac:
  create: false
couchbase-operator:
  couchbaseOperator:
    image:
      tag: 1.2.0-933
  admissionController:
    image:
      tag: 1.2.0-933
  admissionService:
    name: ci-testservice
  admissionSecret:
    cert: |-
              Certificate:
                  Data:
                      Version: 3 (0x2)
                      Serial Number:
                          3d:fd:18:f9:63:91:c5:ad:8c:31:0e:be:80:2c:06:60
                  Signature Algorithm: sha256WithRSAEncryption
                      Issuer: CN=CI-CB CA
                      Validity
                          Not Before: Feb  5 19:16:21 2019 GMT
                          Not After : Jan 20 19:16:21 2022 GMT
                      Subject: CN=admission-controller
                      Subject Public Key Info:
                          Public Key Algorithm: rsaEncryption
                              Public-Key: (2048 bit)
                              Modulus:
                                  00:aa:96:b5:a8:ad:0d:19:9b:87:07:54:93:7f:30:
                                  2f:08:ff:6f:09:d5:0e:72:b8:0a:16:c4:86:73:95:
                                  2b:92:8c:26:d1:a2:13:9b:c9:85:b8:96:c3:00:bc:
                                  0a:1e:29:6c:2c:ec:3a:db:d0:5f:b8:ff:59:62:0a:
                                  da:72:22:58:32:42:33:4c:bd:f4:28:c6:cc:ec:a8:
                                  79:2d:f9:dc:93:29:2e:e3:40:93:df:2c:8b:6c:fa:
                                  c2:a0:fa:3b:0b:d4:9e:22:c5:f6:d2:96:8a:21:c7:
                                  6d:ba:bc:43:e7:35:07:a6:b9:c5:b7:ac:93:2d:73:
                                  e0:c6:7f:3e:6d:a0:cf:be:b2:9f:79:fa:c7:59:70:
                                  b4:60:a5:0d:54:af:dd:49:c4:3d:39:15:57:2e:80:
                                  af:c8:5b:12:89:15:eb:87:f4:89:8e:82:bd:e0:92:
                                  4e:8c:ec:74:d3:10:ef:b2:f0:d9:69:c0:7c:84:ad:
                                  7b:cf:6b:6d:fe:ed:ae:53:5c:03:bd:6f:2c:94:f7:
                                  6f:a0:32:5f:66:f5:19:87:86:1d:2b:13:27:09:d0:
                                  2d:8a:c6:c6:1b:d0:10:c0:40:d9:a3:aa:7d:7a:55:
                                  e3:1d:41:c0:2a:81:0e:66:17:b6:24:81:2f:cc:65:
                                  05:24:17:59:a2:ff:c1:6b:3b:ac:ff:44:7d:c2:8f:
                                  69:e9
                              Exponent: 65537 (0x10001)
                      X509v3 extensions:
                          X509v3 Basic Constraints:
                              CA:FALSE
                          X509v3 Subject Key Identifier:
                              AB:7C:99:C1:81:CE:C0:9D:05:EF:6D:B7:92:7B:C7:51:F5:66:F5:DF
                          X509v3 Authority Key Identifier:
                              keyid:4B:EC:07:7B:47:E1:E5:B3:5E:30:AD:2C:58:C8:A2:D5:91:1C:61:F4
                              DirName:/CN=CI-CB CA
                              serial:DC:00:64:F1:BE:77:FF:E6

                          X509v3 Extended Key Usage:
                              TLS Web Server Authentication
                          X509v3 Key Usage:
                              Digital Signature, Key Encipherment
                          X509v3 Subject Alternative Name:
                              DNS:ci-testservice.ci-testnamespace.svc
                  Signature Algorithm: sha256WithRSAEncryption
                       80:be:3d:c0:23:7f:d5:ec:4a:76:41:f5:f3:6c:3c:45:83:98:
                       24:9f:99:41:bd:3d:35:0b:40:8d:12:9c:45:d6:74:7b:6b:df:
                       31:02:44:7c:59:be:fd:9e:51:03:ff:aa:41:88:58:29:60:09:
                       ee:e7:77:28:4a:e7:f9:a0:dc:8e:a3:8c:89:87:31:16:5d:e4:
                       80:b7:45:c1:1b:f4:59:d4:01:fb:ef:d9:23:20:b0:b3:87:e2:
                       2d:00:18:eb:c8:aa:e8:19:01:52:5a:0c:15:cb:f9:fd:4c:ee:
                       ea:29:43:8a:17:1d:6e:57:a2:9d:36:0a:92:c0:68:b6:bf:df:
                       87:5b:33:aa:04:2b:2a:5b:cd:a6:d7:98:d6:b3:8f:27:97:a4:
                       1b:06:a7:16:5e:02:18:fd:d8:af:05:ee:85:b9:a2:9f:03:3a:
                       2d:c9:71:6a:26:cb:9c:cf:b9:ee:4f:ca:1d:ee:74:9b:41:c3:
                       cb:be:3c:1b:9d:d3:85:77:cb:6a:1e:36:32:a8:f6:52:32:48:
                       fb:71:3c:1a:1e:e0:bf:f9:57:52:f9:9e:0e:83:6d:78:41:1a:
                       66:0f:19:e3:94:75:08:7c:02:28:d4:e3:f4:7f:cc:2a:e0:b8:
                       42:a8:34:d5:fd:08:17:14:05:f5:05:c4:c6:78:4f:b8:64:44:
                       ec:12:55:36
              -----BEGIN CERTIFICATE-----
              MIIDgTCCAmmgAwIBAgIQPf0Y+WORxa2MMQ6+gCwGYDANBgkqhkiG9w0BAQsFADAT
              MREwDwYDVQQDEwhDSS1DQiBDQTAeFw0xOTAyMDUxOTE2MjFaFw0yMjAxMjAxOTE2
              MjFaMB8xHTAbBgNVBAMTFGFkbWlzc2lvbi1jb250cm9sbGVyMIIBIjANBgkqhkiG
              9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqpa1qK0NGZuHB1STfzAvCP9vCdUOcrgKFsSG
              c5Urkowm0aITm8mFuJbDALwKHilsLOw629BfuP9ZYgraciJYMkIzTL30KMbM7Kh5
              Lfnckyku40CT3yyLbPrCoPo7C9SeIsX20paKIcdturxD5zUHprnFt6yTLXPgxn8+
              baDPvrKfefrHWXC0YKUNVK/dScQ9ORVXLoCvyFsSiRXrh/SJjoK94JJOjOx00xDv
              svDZacB8hK17z2tt/u2uU1wDvW8slPdvoDJfZvUZh4YdKxMnCdAtisbGG9AQwEDZ
              o6p9elXjHUHAKoEOZhe2JIEvzGUFJBdZov/Bazus/0R9wo9p6QIDAQABo4HEMIHB
              MAkGA1UdEwQCMAAwHQYDVR0OBBYEFKt8mcGBzsCdBe9tt5J7x1H1ZvXfMEMGA1Ud
              IwQ8MDqAFEvsB3tH4eWzXjCtLFjIotWRHGH0oRekFTATMREwDwYDVQQDEwhDSS1D
              QiBDQYIJANwAZPG+d//mMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAsGA1UdDwQEAwIF
              oDAuBgNVHREEJzAlgiNjaS10ZXN0c2VydmljZS5jaS10ZXN0bmFtZXNwYWNlLnN2
              YzANBgkqhkiG9w0BAQsFAAOCAQEAgL49wCN/1exKdkH182w8RYOYJJ+ZQb09NQtA
              jRKcRdZ0e2vfMQJEfFm+/Z5RA/+qQYhYKWAJ7ud3KErn+aDcjqOMiYcxFl3kgLdF
              wRv0WdQB++/ZIyCws4fiLQAY68iq6BkBUloMFcv5/Uzu6ilDihcdbleinTYKksBo
              tr/fh1szqgQrKlvNpteY1rOPJ5ekGwanFl4CGP3YrwXuhbminwM6LclxaibLnM+5
              7k/KHe50m0HDy748G53ThXfLah42Mqj2UjJI+3E8Gh7gv/lXUvmeDoNteEEaZg8Z
              45R1CHwCKNTj9H/MKuC4Qqg01f0IFxQF9QXExnhPuGRE7BJVNg==
              -----END CERTIFICATE-----
    key: |-
              -----BEGIN PRIVATE KEY-----
              MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCqlrWorQ0Zm4cH
              VJN/MC8I/28J1Q5yuAoWxIZzlSuSjCbRohObyYW4lsMAvAoeKWws7Drb0F+4/1li
              CtpyIlgyQjNMvfQoxszsqHkt+dyTKS7jQJPfLIts+sKg+jsL1J4ixfbSloohx226
              vEPnNQemucW3rJMtc+DGfz5toM++sp95+sdZcLRgpQ1Ur91JxD05FVcugK/IWxKJ
              FeuH9ImOgr3gkk6M7HTTEO+y8NlpwHyErXvPa23+7a5TXAO9byyU92+gMl9m9RmH
              hh0rEycJ0C2KxsYb0BDAQNmjqn16VeMdQcAqgQ5mF7YkgS/MZQUkF1mi/8FrO6z/
              RH3Cj2npAgMBAAECggEAa+D1Lp+JaklNwhf9UvDAvfrzWI9xHKFAWBeeQ1fxfzK8
              ldPefKWbuBk3Zq6D44EklOArdLk438Az4WmlrYoEpnvw/zYdQvA9xefhAm9By5q+
              uR4spXUBE0Eddjnov1mNS8ZPieuDnUsGHJJUitGhbhGLdNVhGdxvKHhtnVyWJCy/
              fbnCODeETox3nVGKbr3frCzRN2VI/EWVtHdBEzNWpKsSFMUe78bEDJw66OVteaZs
              JA3K8GYRzUIK0SJdkl6XmIg6yMdT4DO4K6lgjZvENX6K4ffezRd4dZ/LGqMHlrtQ
              nL3tOnO8BXlbAIhSLI+Ti3uGnOxYRuxXX2H32cxhFQKBgQDW2B0sEnsBmZJqKOLV
              pBUX2/zuI7UZgZN0r0cEfl1uGlhDCyUFjAPg2hpufdF0jnqcOj45pUVocjwG5s6t
              dUZ5H++EVep6owXJXRyBee4t0AUJzQqAVdHAtflNaitr9ebbLDKIvxGQhSeMhuYO
              HYsVAggFnNOc2o67topsJqJjmwKBgQDLRFJcpm/ngL6U52Ql97kss5MWJ0+MEAyb
              Kd94vy5l50eZXe2XvZnhNKXvzBhrAhnxAJ2HhGrIAFaOpDEvry6M+xBPvpDTcTLB
              iI6OjDYEQYp0BMbsQjIwTxzkXAyEY87hpQ5W7O1txjiL1z2CvaJTvAxv1fMvTIKU
              bEEIIQkqywKBgDpaKFI4EsC0fVfoEvQDxNbeISxs9lsfHnWqxZcq2yV0clSDSmLf
              TI5drqAj/Ce0KwkTqKLviJJ9tGALgEcMez+atOs0iqMUdBXk/EEOZOp8fWHUFu4U
              YQv+YN/t3i1MdI9CydbqTlL6V2uLmCBtVcE29AbSOYd4tRu20JHfTGvRAoGAAz9R
              LYe/K+yjns9fize87pjj1avFGpC7EtOFbXFodVpPi4SzogP2bGGh8QXKshLzhSUk
              XyDfb9iJiXfYDVH4JWpxZUS/HZGmZO8gj+hviHvfkWDuKKIaGSl6Za+Ox6KskHBJ
              nVvloyZSivFiWy9aY4oSjMrXOr83KtXb6BxXACcCgYEAyG+n8t4PW8rXKp3rqwuS
              FUIwk6yP6T5ExDfyPHcc4LcxiLFqC1qGLMtT5Qo+GQk/32hzP7GPbdEklLNi6IzK
              UnRhkE/t+vd2oR8fpnIhJ/Tw1hSIOMHfX61dYEEqb8N4tiUFIE42rCD3qLkZQZ7h
              gMLwc22iaEQYnriWssdMyyg=
              -----END PRIVATE KEY-----
  admissionCA:
    key: |-
            -----BEGIN RSA PRIVATE KEY-----
            MIIEpAIBAAKCAQEA54iRozoKmMvm0wFCkl/sNebO803WRouBa/99XNr7aZabNYGk
            el3lN8FT6i0tK3bRewRnF57C3hEczm9/qEpdVDoFUscqylcXJzJsW8Ol3+t1ihO+
            wjuN5ACkChsV0XHn32s1g5Y5W9HwsNmyqrDcYPNoqTuV7jBBdLa/YNpsrlE5kh02
            cdhEGkfJBJK6zcfw42dNnRuRlSOwtSf3u+NHBPT7lu6ODSOxoEbntXWclkqfoe45
            axsghGTv0NtsihI2nIzt6HGsox21YTsv42qG62tvlt9YrgeAXZETI2+UsEy2/nhb
            QCnLZ2HzD0mpFPcCfXeWXGWQ+4roLRxfhye63wIDAQABAoIBAGUag84tKDd0woTd
            hf55GKKo+THRiYIgpRFN7aZAkYyYEYqZ5ALzQYbJSyV1OMZEClGXqJTt5NYnztZu
            ZeZNItgGxhBRnGPjB98764les+5F2XvEB4a1js5DYV5wWWSuQryTCjk9vipUULBJ
            P/W9aV6Eq+1KcbwjIlIfAw7+EntDc/4Bi1lpwKx88ByHRKeWJXSZGKz5VvzA+Drv
            A49nOWkNLpVIdAGt16AVre8Cgrfz2+gnpoxZD//Ju4tfqUyaMO54UTltfbmd8E5l
            GUvvyhh/zh2tbV6gYPFtblpxdRto2BpSmSbRD8F6yLRYRDRHT21d+LpOYNU5egMa
            4Hp9JaECgYEA/XULe13tSXgD00sRZ1jGAkUygsnV8wxb3jO5AZumeofeireOnYdN
            D0Yk7J/mVdZw8XZPwNk7rYgBrrjAILwNvDOa2gNNAdrclqXcx6aBNF8NhEL1p5vQ
            gKLGKKiKA08tTdnjAv+NCaIJK2jaUMP7ai4zFJtfdo0JPruuwNt/0VkCgYEA6ds3
            nIeSghC6GwgkFhV2m1jtjrYgrM9zItquARtvjD16/Z2ZSTlyJcdhYsFlrr6lfnkp
            cNK2dUlEXN5l2+5VOUN0APNzEoVz92w5m8WtWiGmHwTgDpqd6TBeLWkrKtJDyYKq
            PvXBUhdoQPnHmHfPbNQvG8qoOEbyc9rVQ+FU7vcCgYAiJyZv7j0uPDTPwPrMYUL1
            RVvEEex5fr3WWEPiupWZRzuul4NpKLUyjLInDHjeMjIv51Bh3SPUg1IuuAhzoMN9
            C7sfC3jR+irlRd5VLNOWOgS5QMiXWEClRMnM6sEGJyIkrmqPmd3oYWQ47D0WywHS
            0fziFvmrIOARCvtGU42KqQKBgQDJfA949LG9EE5YVfZJdKqhA8iBadfTLFVF1WWQ
            HKRKDvp1oqBcH3uCozr7zCcgnK+XvSqAQ3vip4KYBSF7kOeqk7xRyW7+qS6WIY+s
            728BNfabySaGTp75N6wcsfz4QvsWlla6MiEi6nnvaYWXjrqPSG1iI4Q2IKJqQUP3
            3R/BVwKBgQDRohK1lB3pCJXr5G7blRjNuySOKlsQ4EKlr9Iy9xnsblkhJqN+RzAv
            8b6HHfWVVoyO3vEpyvTmYDjKuAIJfw1DXNtG9YWsfP5RgaTrpk+sep6YVo8l2WZR
            aWL+aQ02tHv9s286gNEk9GBpSCJ5KwBnFsgHog/BLmZ58eVFzDwqbQ==
            -----END RSA PRIVATE KEY-----
    cert: |-
            -----BEGIN CERTIFICATE-----
            MIIDKzCCAhOgAwIBAgIJANwAZPG+d//mMA0GCSqGSIb3DQEBCwUAMBMxETAPBgNV
            BAMTCENJLUNCIENBMB4XDTE5MDIwNTE5MTU0MloXDTI5MDIwMjE5MTU0MlowEzER
            MA8GA1UEAxMIQ0ktQ0IgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
            AQDniJGjOgqYy+bTAUKSX+w15s7zTdZGi4Fr/31c2vtplps1gaR6XeU3wVPqLS0r
            dtF7BGcXnsLeERzOb3+oSl1UOgVSxyrKVxcnMmxbw6Xf63WKE77CO43kAKQKGxXR
            ceffazWDljlb0fCw2bKqsNxg82ipO5XuMEF0tr9g2myuUTmSHTZx2EQaR8kEkrrN
            x/DjZ02dG5GVI7C1J/e740cE9PuW7o4NI7GgRue1dZyWSp+h7jlrGyCEZO/Q22yK
            EjacjO3ocayjHbVhOy/jaobra2+W31iuB4BdkRMjb5SwTLb+eFtAKctnYfMPSakU
            9wJ9d5ZcZZD7iugtHF+HJ7rfAgMBAAGjgYEwfzAdBgNVHQ4EFgQUS+wHe0fh5bNe
            MK0sWMii1ZEcYfQwQwYDVR0jBDwwOoAUS+wHe0fh5bNeMK0sWMii1ZEcYfShF6QV
            MBMxETAPBgNVBAMTCENJLUNCIENBggkA3ABk8b53/+YwDAYDVR0TBAUwAwEB/zAL
            BgNVHQ8EBAMCAQYwDQYJKoZIhvcNAQELBQADggEBAK5wtHWvIF7WGLgnU3ok9AXo
            9IHvIY4IJd0PgpRtcS45PDv6+fcjGk7THnprPF/tk5LM2/uzqoKWtzAZLCUqyDAK
            wxczAgtHazmvSIm+art3Jnuh/pvguzMgIpTj4RiwZfTaZ5jCWJzRNdeKkUQkUFv/
            2xbZ/d0ixTvWyBGQAqvR5WnZ8wsvKARky7Z0VQKsKpbhWC+vjc1/bydZ2TAQGZYQ
            WX8co04a/RLaFX9v79nUkzOewY4Kcy684BFyMMIjPXmZXzh7+7wqRJbad98Lb2nW
            IzhyQx/NMZnGp9Rv/z9SuCumDmOgavLWunrIK1KktgMGFxC1IcaFaMCVdthrgNY=
            -----END CERTIFICATE-----
