# Creates operator chart with custom CA and secret
# * Requires namespace named ci-namespace
# * Verifies DNS uses service named ci-testcluster
---
rbac:
  create: false
tls:
  secretName: test-resource-secret
couchbase-operator:
  couchbaseOperator:
    image:
      tag: 1.2.0-877
  admissionController:
    image:
      tag: 1.2.0-877
  admissionService:
    name: ci-testservice
  admissionSecret:
    name: test-resource-secret
    create: false
  admissionCA:
      key: |-
              -----BEGIN RSA PRIVATE KEY-----
              MIIEpAIBAAKCAQEA54iRozoKmMvm0wFCkl/sNebO803WRouBa/99XNr7aZabNYGk
              el3lN8FT6i0tK3bRewRnF57C3hEczm9/qEpdVDoFUscqylcXJzJsW8Ol3+t1ihO+
              wjuN5ACkChsV0XHn32s1g5Y5W9HwsNmyqrDcYPNoqTuV7jBBdLa/YNpsrlE5kh02
              cdhEGkfJBJK6zcfw42dNnRuRlSOwtSf3u+NHBPT7lu6ODSOxoEbntXWclkqfoe45
              axsghGTv0NtsihI2nIzt6HGsox21YTsv42qG62tvlt9YrgeAXZETI2+UsEy2/nhb
              QCnLZ2HzD0mpFPcCfXeWXGWQ+4roLRxfhye63wIDAQABAoIBAGUag84tKDd0woTd
              hf55GKKo+THRiYIgpRFN7aZAkYyYEYqZ5ALzQYbJSyV1OMZEClGXqJTt5NYnztZu
              ZeZNItgGxhBRnGPjB98764les+5F2XvEB4a1js5DYV5wWWSuQryTCjk9vipUULBJ
              P/W9aV6Eq+1KcbwjIlIfAw7+EntDc/4Bi1lpwKx88ByHRKeWJXSZGKz5VvzA+Drv
              A49nOWkNLpVIdAGt16AVre8Cgrfz2+gnpoxZD//Ju4tfqUyaMO54UTltfbmd8E5l
              GUvvyhh/zh2tbV6gYPFtblpxdRto2BpSmSbRD8F6yLRYRDRHT21d+LpOYNU5egMa
              4Hp9JaECgYEA/XULe13tSXgD00sRZ1jGAkUygsnV8wxb3jO5AZumeofeireOnYdN
              D0Yk7J/mVdZw8XZPwNk7rYgBrrjAILwNvDOa2gNNAdrclqXcx6aBNF8NhEL1p5vQ
              gKLGKKiKA08tTdnjAv+NCaIJK2jaUMP7ai4zFJtfdo0JPruuwNt/0VkCgYEA6ds3
              nIeSghC6GwgkFhV2m1jtjrYgrM9zItquARtvjD16/Z2ZSTlyJcdhYsFlrr6lfnkp
              cNK2dUlEXN5l2+5VOUN0APNzEoVz92w5m8WtWiGmHwTgDpqd6TBeLWkrKtJDyYKq
              PvXBUhdoQPnHmHfPbNQvG8qoOEbyc9rVQ+FU7vcCgYAiJyZv7j0uPDTPwPrMYUL1
              RVvEEex5fr3WWEPiupWZRzuul4NpKLUyjLInDHjeMjIv51Bh3SPUg1IuuAhzoMN9
              C7sfC3jR+irlRd5VLNOWOgS5QMiXWEClRMnM6sEGJyIkrmqPmd3oYWQ47D0WywHS
              0fziFvmrIOARCvtGU42KqQKBgQDJfA949LG9EE5YVfZJdKqhA8iBadfTLFVF1WWQ
              HKRKDvp1oqBcH3uCozr7zCcgnK+XvSqAQ3vip4KYBSF7kOeqk7xRyW7+qS6WIY+s
              728BNfabySaGTp75N6wcsfz4QvsWlla6MiEi6nnvaYWXjrqPSG1iI4Q2IKJqQUP3
              3R/BVwKBgQDRohK1lB3pCJXr5G7blRjNuySOKlsQ4EKlr9Iy9xnsblkhJqN+RzAv
              8b6HHfWVVoyO3vEpyvTmYDjKuAIJfw1DXNtG9YWsfP5RgaTrpk+sep6YVo8l2WZR
              aWL+aQ02tHv9s286gNEk9GBpSCJ5KwBnFsgHog/BLmZ58eVFzDwqbQ==
              -----END RSA PRIVATE KEY-----
      cert: |-
              -----BEGIN CERTIFICATE-----
              MIIDKzCCAhOgAwIBAgIJANwAZPG+d//mMA0GCSqGSIb3DQEBCwUAMBMxETAPBgNV
              BAMTCENJLUNCIENBMB4XDTE5MDIwNTE5MTU0MloXDTI5MDIwMjE5MTU0MlowEzER
              MA8GA1UEAxMIQ0ktQ0IgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
              AQDniJGjOgqYy+bTAUKSX+w15s7zTdZGi4Fr/31c2vtplps1gaR6XeU3wVPqLS0r
              dtF7BGcXnsLeERzOb3+oSl1UOgVSxyrKVxcnMmxbw6Xf63WKE77CO43kAKQKGxXR
              ceffazWDljlb0fCw2bKqsNxg82ipO5XuMEF0tr9g2myuUTmSHTZx2EQaR8kEkrrN
              x/DjZ02dG5GVI7C1J/e740cE9PuW7o4NI7GgRue1dZyWSp+h7jlrGyCEZO/Q22yK
              EjacjO3ocayjHbVhOy/jaobra2+W31iuB4BdkRMjb5SwTLb+eFtAKctnYfMPSakU
              9wJ9d5ZcZZD7iugtHF+HJ7rfAgMBAAGjgYEwfzAdBgNVHQ4EFgQUS+wHe0fh5bNe
              MK0sWMii1ZEcYfQwQwYDVR0jBDwwOoAUS+wHe0fh5bNeMK0sWMii1ZEcYfShF6QV
              MBMxETAPBgNVBAMTCENJLUNCIENBggkA3ABk8b53/+YwDAYDVR0TBAUwAwEB/zAL
              BgNVHQ8EBAMCAQYwDQYJKoZIhvcNAQELBQADggEBAK5wtHWvIF7WGLgnU3ok9AXo
              9IHvIY4IJd0PgpRtcS45PDv6+fcjGk7THnprPF/tk5LM2/uzqoKWtzAZLCUqyDAK
              wxczAgtHazmvSIm+art3Jnuh/pvguzMgIpTj4RiwZfTaZ5jCWJzRNdeKkUQkUFv/
              2xbZ/d0ixTvWyBGQAqvR5WnZ8wsvKARky7Z0VQKsKpbhWC+vjc1/bydZ2TAQGZYQ
              WX8co04a/RLaFX9v79nUkzOewY4Kcy684BFyMMIjPXmZXzh7+7wqRJbad98Lb2nW
              IzhyQx/NMZnGp9Rv/z9SuCumDmOgavLWunrIK1KktgMGFxC1IcaFaMCVdthrgNY=
              -----END CERTIFICATE-----
