 # Cluster with persistent volumes  
---
rbac:
  create: false
couchbase-operator:
  couchbaseOperator:
    image:
      tag: 1.2.0-933
  admissionController:
    image:
      tag: 1.2.0-933
couchbase-cluster:
  couchbaseCluster:
    servers:
      all_services:
        size: 4
        services:
          - data
        pod:
          volumeMounts:
            default: couchbase
            data:  couchbase
    securityContext:
      fsGroup: 1000
    volumeClaimTemplates:
      - metadata:
          name: couchbase
          annotations:
            storageclass.couchbase.com/binding-mode: WaitForFirstConsumer
        spec:
          storageClassName: "default"
          resources:
            requests:
              storage: 1Gi
    couchbaseTLS:
      create: true 
