# Override (DNS) Cluster CA and Keys
# * Requires namespace named ci-namespace
# * Verifies DNS uses service named ci-testcluster
---
testID: "10"
# Cannot do service test with fake dns.
# However, if there are any issues the admission
# controller will fail cluster creation.
enableServiceTest: false
rbac:
  create: false
couchbase-operator:
  couchbaseOperator:
    image:
      tag: 1.2.0-933
  admissionController:
    image:
      tag: 1.2.0-933
couchbase-cluster:
  couchbaseCluster:
    name: ci-testcluster
    adminConsoleServiceType: LoadBalancer
    exposedFeatureServiceType: LoadBalancer
    dns:
      domain: exposed.dns.com
    servers:
      all_services:
        size: 4
        services:
          - data
        pod:
          volumeMounts:
            default: couchbase
            data:  couchbase
    securityContext:
      fsGroup: 1000
    volumeClaimTemplates:
      - metadata:
          name: couchbase
          annotations:
            storageclass.couchbase.com/binding-mode: WaitForFirstConsumer
        spec:
          storageClassName: "default"
          resources:
            requests:
              storage: 1Gi
  couchbaseTLS:
    create: true
    key: |-
          -----BEGIN RSA PRIVATE KEY-----
          MIIEpAIBAAKCAQEAuZo/q8+zMZEIWV/4rfbFpKtPM+4r+/EmE7STfBKNkQhxWuch
          2EVgy6yEFyL342EJHe+oVZKy3/NwVPmBKtDSsncp/pDQOgrtgjddddPGH+rxGNo7
          S3N7r9H7eLbufWsa+0wOAxBSd/LiCpkaM2e4QRxlNdb6UXMA7m773vjDDgys6k+3
          ZU5rzV2PUEhg0IwA0ZYRR7MVUZ7Qmau0mMpgu/vWN5IODAzgaCDHHdX85A187RI1
          X36N5Drbw6J7aBKgy8P3cEqvf0Q3UNyFOxTEk43VqvdZXKQcIWH5mUri1vF1nkaC
          3g+np7T83Ftoxbx5DKOfiyGKo+K+2IwQ8mz2hQIDAQABAoIBAQCj4juObduATNve
          bwuaMGfcOxe4dvmHgStqAuynhYpTIe1VovkTik8qCK6p70qLD8eJE3DD/sDLVp09
          qwIO2EzzIJ2IFj6GwdduP4za2Z/71uwEUc5BlTsFyJgPwxdazxQICOPmeKcZGvHV
          AdNMyKy9cWE85RIqkS2lW4IzI9y3raBRf2xkHcwycn+o5A9MSowBgD9NwXzrbMLL
          JLmzXV7jdxy1e1LDRoyHlwlFA3po9Su7OZEAQ/aaRNxW6eQXPXo1J8qC7V4qVJFD
          uGZpgAHUDLelWwORv7/rW3Q6f67u+9s7+SkHZFvSf65z1Wft9tA/YbsceBQYjr0u
          UCkkuUeBAoGBAOLLzhdrNwnFQCUSP4EK36DmQMjR+SoBpzqOIJC8RBsNYeIvA0lY
          qphGYFcM7dYqm5DtngcaqmghGMSB/BV9vg2Qc3Z/yvOi+gKCqPLhQ6nU3fCgCnOO
          1RinU01nfBnzJ7L5r8tBo8chZwGr00DCj3K/fzqSZySGLrpgOZWv44v5AoGBANGA
          hcZlUOjRGwRNM25KKy3OORc0X5uFArl0P+Uzko+A9Lro74+1hO4ooxzTkjUAsFAd
          7/WZlerqPhLQ3fdZZdJgBg921+NAfLFzbySPVbeUUBxQZ1QPleuytAVM2Ma8oipx
          9dfwKvS4XgJSr0gvfacpMaesdt7d7xhIxMLVhantAoGBAMTYQ65L3l9alswWRIwK
          FgMfFge3R13QRYcrKNS2sx4PxW99goq8rISyQJgNnriODqwBsXFVEaaDY23brCIz
          GyvGvpCRZmOEhx56rYzxO7tCCMf7AFdAF3DoegLq2OnlBAXxdUUjWbVSJodqzVae
          B8d+sjzyKReoZxJYxmJHYWZxAoGAPtwhR3X+4NxdDt1bISx/6C6IUr4UMcWnG54V
          zd+7ifNXev2JY8VDLXJj/rI8nEqonGFfLoH2yZWfKmYhM6ZPNuA48UrnW/htcZEB
          OCcJwRtvLg+x8Tb79MyZ1z1HjdnrjnDDIxecy/DFxEyq6y3UteNWUskcoaJVqyOq
          ZgtLH8ECgYAsadMRiT8eX+g6aejk4ldGaEgFxS1HajdzBWrTLAJaiUVBYBJZeZn5
          SI7v6ji+AENRyclVrVd45d6fsQqVUeoodPB8PdUz533gSJdYrwJF5AK+WL2QkYDM
          VcuOhJ2WpkDRu447QkmebEtcVIlT8V+2MrkB3b7POYyIUe1N4B/CHA==
          -----END RSA PRIVATE KEY-----

    cert: |-
           -----BEGIN CERTIFICATE-----
           MIIDNTCCAh2gAwIBAgIJAKM9qfQsYQ01MA0GCSqGSIb3DQEBCwUAMBYxFDASBgNV
           BAMTC0Vhc3ktUlNBIENBMB4XDTE5MDIxMTIyMDU1MloXDTI5MDIwODIyMDU1Mlow
           FjEUMBIGA1UEAxMLRWFzeS1SU0EgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
           ggEKAoIBAQC5mj+rz7MxkQhZX/it9sWkq08z7iv78SYTtJN8Eo2RCHFa5yHYRWDL
           rIQXIvfjYQkd76hVkrLf83BU+YEq0NKydyn+kNA6Cu2CN11108Yf6vEY2jtLc3uv
           0ft4tu59axr7TA4DEFJ38uIKmRozZ7hBHGU11vpRcwDubvve+MMODKzqT7dlTmvN
           XY9QSGDQjADRlhFHsxVRntCZq7SYymC7+9Y3kg4MDOBoIMcd1fzkDXztEjVffo3k
           OtvDontoEqDLw/dwSq9/RDdQ3IU7FMSTjdWq91lcpBwhYfmZSuLW8XWeRoLeD6en
           tPzcW2jFvHkMo5+LIYqj4r7YjBDybPaFAgMBAAGjgYUwgYIwHQYDVR0OBBYEFDM9
           toMOdaAXMGEt+jGzc5MKBxcjMEYGA1UdIwQ/MD2AFDM9toMOdaAXMGEt+jGzc5MK
           BxcjoRqkGDAWMRQwEgYDVQQDEwtFYXN5LVJTQSBDQYIJAKM9qfQsYQ01MAwGA1Ud
           EwQFMAMBAf8wCwYDVR0PBAQDAgEGMA0GCSqGSIb3DQEBCwUAA4IBAQCNMHiR34c6
           DBsouPxytqH2yJTx8BERHysPXvqV9w2IFSkV0ELYun45CMRC5rN0DGQamussBQJB
           Y8sLYq17katuY0ZYBiqyWS4A4pVcEGSTWsUL0ONrgnSJGJKG4bh/zf97u6kAFekT
           dxh9uVfn/4aFUa1++GDEUqEC1PpGXVBcGlfmuHdsLVhFNHw4lDO67NUkrK4DDQTA
           Oyk+wOheiSTEaKesIQ0ewlgCU+XKxgXP6b4TFuzK1OnoblcryDbHJtHzm61YbVDl
           V2dxKtyGOlhQPxAb2UxcllnF7CqdEoZAp3XY3N17Edt667urWbs02xt6dCmviGWU
           NnDiG0X8Dxse
           -----END CERTIFICATE-----
    operatorSecret:
      cert: |-
              Certificate:
                  Data:
                      Version: 3 (0x2)
                      Serial Number:
                          12:c0:8a:dd:83:d2:74:02:d2:7b:4f:83:51:25:1b:86
                  Signature Algorithm: sha256WithRSAEncryption
                      Issuer: CN=Easy-RSA CA
                      Validity
                          Not Before: Feb 11 23:08:38 2019 GMT
                          Not After : Jan 26 23:08:38 2022 GMT
                      Subject: CN=citestclusterdns
                      Subject Public Key Info:
                          Public Key Algorithm: rsaEncryption
                              Public-Key: (2048 bit)
                              Modulus:
                                  00:b6:70:0d:83:6d:5d:07:b9:3c:4d:bb:01:bb:d5:
                                  80:04:64:20:dd:74:d1:43:01:65:61:07:00:76:ae:
                                  41:28:10:53:23:13:b9:5e:a2:dd:ca:33:04:14:a5:
                                  98:f6:15:35:29:87:9c:6b:bb:cf:6e:d9:05:d0:51:
                                  71:62:c0:6e:c9:e3:7a:96:4e:3c:aa:29:bf:8f:fd:
                                  f5:a8:03:5f:a4:89:8a:b7:74:21:99:3d:2c:2c:d7:
                                  5f:db:a0:47:80:c9:47:34:ad:47:bd:ac:02:26:f4:
                                  d5:60:cc:8b:64:01:c1:4f:00:ab:ee:cf:6d:37:23:
                                  55:ed:2e:72:c2:9f:61:34:bb:ef:f5:68:87:58:b4:
                                  82:40:09:e3:6d:3e:98:f1:d6:23:e2:e3:98:c3:b7:
                                  5b:76:82:8d:ec:b1:2e:04:4d:8c:e7:89:31:94:77:
                                  9e:39:88:62:d4:30:7b:c1:4b:e4:5a:56:0c:dc:53:
                                  8b:0b:c8:c8:bf:95:98:b8:f4:0a:79:1f:30:2e:64:
                                  12:21:12:88:14:3d:e4:1a:3a:63:b0:7f:97:fa:90:
                                  88:ee:00:cf:f1:f9:cb:47:86:06:81:a0:44:86:2e:
                                  fd:bd:9d:49:e3:8d:ac:a9:12:21:db:a6:6a:85:3c:
                                  11:4c:cc:30:65:f1:f0:55:03:d5:16:d1:20:c5:56:
                                  27:c3
                              Exponent: 65537 (0x10001)
                      X509v3 extensions:
                          X509v3 Basic Constraints: 
                              CA:FALSE
                          X509v3 Subject Key Identifier: 
                              B8:5B:6F:CC:F4:D0:FE:0F:D3:90:74:4A:63:AF:9E:50:C1:FD:6D:34
                          X509v3 Authority Key Identifier: 
                              keyid:33:3D:B6:83:0E:75:A0:17:30:61:2D:FA:31:B3:73:93:0A:07:17:23
                              DirName:/CN=Easy-RSA CA
                              serial:A3:3D:A9:F4:2C:61:0D:35

                          X509v3 Extended Key Usage: 
                              TLS Web Server Authentication
                          X509v3 Key Usage: 
                              Digital Signature, Key Encipherment
                          X509v3 Subject Alternative Name: 
                              DNS:*.ci-testcluster.ci-testnamespace.svc, DNS:*.ci-testcluster.exposed.dns.com
                  Signature Algorithm: sha256WithRSAEncryption
                       3d:92:0d:e9:eb:a9:81:7b:9e:3d:70:6a:cd:40:63:d7:cf:d4:
                       f2:51:b4:8a:c1:1c:66:61:c6:8d:91:c3:7c:7d:f2:17:a2:c3:
                       3c:81:41:51:0a:91:f5:e1:0f:15:49:c5:90:d4:05:5b:06:a1:
                       98:91:e1:44:71:14:ac:62:3a:10:e9:23:01:ad:02:8b:83:3f:
                       e1:99:07:aa:76:69:f1:f1:a1:da:96:21:96:59:ed:0d:1f:03:
                       a6:5b:18:48:3b:63:bc:01:b3:92:71:bf:55:47:cc:53:8b:df:
                       17:da:a1:30:ea:5f:74:71:2a:80:dc:62:72:71:52:9a:8e:00:
                       ac:e2:e7:95:3d:b2:e0:87:14:08:0c:f8:61:b8:c8:ff:d0:9f:
                       af:9a:79:bf:15:21:27:76:9e:fa:83:3e:39:39:a3:67:6f:d4:
                       e5:71:1e:52:13:b5:d1:5f:73:12:2d:9c:96:49:cf:fc:36:c6:
                       31:7a:f0:28:ca:a7:c5:2d:66:b0:c0:fa:e5:72:f7:d6:87:a2:
                       8d:f3:f3:2d:0d:2f:23:12:1d:d0:b2:ef:d8:a0:19:f7:44:9c:
                       3f:16:20:e5:3f:59:76:5c:a8:b6:43:bf:f7:33:70:3a:7a:9c:
                       82:4b:36:d1:fb:19:9a:dd:4e:97:bd:a5:03:9c:80:6c:72:7c:
                       37:96:59:34
              -----BEGIN CERTIFICATE-----
              MIIDpzCCAo+gAwIBAgIQEsCK3YPSdALSe0+DUSUbhjANBgkqhkiG9w0BAQsFADAW
              MRQwEgYDVQQDEwtFYXN5LVJTQSBDQTAeFw0xOTAyMTEyMzA4MzhaFw0yMjAxMjYy
              MzA4MzhaMBsxGTAXBgNVBAMTEGNpdGVzdGNsdXN0ZXJkbnMwggEiMA0GCSqGSIb3
              DQEBAQUAA4IBDwAwggEKAoIBAQC2cA2DbV0HuTxNuwG71YAEZCDddNFDAWVhBwB2
              rkEoEFMjE7leot3KMwQUpZj2FTUph5xru89u2QXQUXFiwG7J43qWTjyqKb+P/fWo
              A1+kiYq3dCGZPSws11/boEeAyUc0rUe9rAIm9NVgzItkAcFPAKvuz203I1XtLnLC
              n2E0u+/1aIdYtIJACeNtPpjx1iPi45jDt1t2go3ssS4ETYzniTGUd545iGLUMHvB
              S+RaVgzcU4sLyMi/lZi49Ap5HzAuZBIhEogUPeQaOmOwf5f6kIjuAM/x+ctHhgaB
              oESGLv29nUnjjaypEiHbpmqFPBFMzDBl8fBVA9UW0SDFVifDAgMBAAGjgeswgegw
              CQYDVR0TBAIwADAdBgNVHQ4EFgQUuFtvzPTQ/g/TkHRKY6+eUMH9bTQwRgYDVR0j
              BD8wPYAUMz22gw51oBcwYS36MbNzkwoHFyOhGqQYMBYxFDASBgNVBAMTC0Vhc3kt
              UlNBIENBggkAoz2p9CxhDTUwEwYDVR0lBAwwCgYIKwYBBQUHAwEwCwYDVR0PBAQD
              AgWgMFIGA1UdEQRLMEmCJSouY2ktdGVzdGNsdXN0ZXIuY2ktdGVzdG5hbWVzcGFj
              ZS5zdmOCICouY2ktdGVzdGNsdXN0ZXIuZXhwb3NlZC5kbnMuY29tMA0GCSqGSIb3
              DQEBCwUAA4IBAQA9kg3p66mBe549cGrNQGPXz9TyUbSKwRxmYcaNkcN8ffIXosM8
              gUFRCpH14Q8VScWQ1AVbBqGYkeFEcRSsYjoQ6SMBrQKLgz/hmQeqdmnx8aHaliGW
              We0NHwOmWxhIO2O8AbOScb9VR8xTi98X2qEw6l90cSqA3GJycVKajgCs4ueVPbLg
              hxQIDPhhuMj/0J+vmnm/FSEndp76gz45OaNnb9TlcR5SE7XRX3MSLZyWSc/8NsYx
              evAoyqfFLWawwPrlcvfWh6KN8/MtDS8jEh3Qsu/YoBn3RJw/FiDlP1l2XKi2Q7/3
              M3A6epyCSzbR+xma3U6XvaUDnIBscnw3llk0
              -----END CERTIFICATE-----
      key: |-
              -----BEGIN RSA PRIVATE KEY-----
              MIIEpAIBAAKCAQEAtnANg21dB7k8TbsBu9WABGQg3XTRQwFlYQcAdq5BKBBTIxO5
              XqLdyjMEFKWY9hU1KYeca7vPbtkF0FFxYsBuyeN6lk48qim/j/31qANfpImKt3Qh
              mT0sLNdf26BHgMlHNK1HvawCJvTVYMyLZAHBTwCr7s9tNyNV7S5ywp9hNLvv9WiH
              WLSCQAnjbT6Y8dYj4uOYw7dbdoKN7LEuBE2M54kxlHeeOYhi1DB7wUvkWlYM3FOL
              C8jIv5WYuPQKeR8wLmQSIRKIFD3kGjpjsH+X+pCI7gDP8fnLR4YGgaBEhi79vZ1J
              442sqRIh26ZqhTwRTMwwZfHwVQPVFtEgxVYnwwIDAQABAoIBAQCJQfa4yeAzPmcj
              aC4evruJEjgzxX7ndbZrcJQltmapGNcjzeQqUkihpw5L5mcVxdDwhOnnmC6xjDA2
              kf/Ht1XjKPWC/ivgLnbEg+J93MPpi93EtmfM3dxNhGDHYWhKeaTL+g6+ohogaxXa
              tSmuPS/OG4g/rOnTkQ9F2itXSAgfXnxNa/gR9Li9PGmDbIvJVgzVnM1uMpzOWq+Z
              95pQpgxdhTrOMu159zVE/s8QtrF7BdjxqoiUMXpzjfU84n/d8qhOYkb/2/gK4+VT
              3Uo7jwU8LE6GwTpjOTXntRxK6eAISWRswzq1sBgRQ4btIWRGoxWVDRPo0VsLVusC
              p4FyolBRAoGBAOjJCJMiWe8K2epVlwFqFOM8pgNJ8K1g7Q84pC+PfY1kZ+iyEL1R
              fgisbB0f1Wk4VrVrApZfOCNrSr9dLTO0cGL8D/81LRObH/pl1ICaN1KQVknXP8Zh
              VwCSjvwmcH+GzxnW4o2oQ7HFu4i44Khw9YZZGvIIZLTbnKjznS501hZZAoGBAMih
              p5RmeAKEt5FLqttH4l2wlGNXlOTwAyuOTdxhUeqck/KM3EqNj9DDvli+2b69Iapx
              oBHQEpI/pvdFLBqul+9RZOIsZsGNvqz3FeTeYRBXe1Lz+Bzpv2NzGYaEQQ8cqQPr
              V3kRnoxG0tNC+KxvC3OySSpwcaCcKdPcXxtV3WN7AoGBALei/7SygKfms4n9AycG
              fHvWuFAX4FmmANzlHgC2/aCw+JfFAReYVgiZnKBNIJnk6+IqDNx7OVoXpdvYsXP8
              gDxWBHibhnfVBCEQe9cH0WS8oJWXzKO+3leBRnL8D/tKac5EimydtOlkx1BQKEo4
              8jeNy4frvyY9qRRPOkwPt2PhAoGAG/sPmA7CZfeEcmsPJQ3dcBuUVlZ8mYEvr/9k
              tHuOJR45M/aZMnyTthXWkiHr1EIkU9UM8e8G6AagjpPDFuWKowHDBBgVLKFMGmtL
              TmQFPXY16NfFnqKq4n/G64++UxE4MSe9R1FBv2aROI16iPHjsvsGYTjVYATngHiX
              ewR6n8kCgYAlJTNN4FxoNBVl1g3CIfMjfqAuIp2hAxdJouHyuxY2Hh0lx3TV0YYj
              MJAN2MlrejltdcIsZ3GBP4rC64yNn+11dVvTVC34ELDYzcij88zY6lovrHnyKLqq
              Nusb7BINNU+NZKe/+fLr/jWSWEPOo2qVOYbTFO4jXdS/1Ii4JxnwvA==
              -----END RSA PRIVATE KEY-----
