#!/bin/sh

# Copyright 2018-Present Couchbase, Inc.
#
# Use of this software is governed by the Business Source License included in
# the file licenses/BSL-Couchbase.txt.  As of the Change Date specified in that
# file, in accordance with the Business Source License, use of this software
# will be governed by the Apache License, Version 2.0, included in the file
# licenses/APL2.txt.

# Couchbase Server start script.

set -e

if [ "$1" = 'couchbase-server' ]
then

    if [ "$(id -u)" != "0" ]; then
        echo "This script must be run as root"
        exit 1
    fi

    # Create directories where couchbase stores its data
    cd /opt/couchbase
    mkdir -p var/lib/couchbase \
        var/lib/couchbase/config \
        var/lib/couchbase/data \
        var/lib/couchbase/stats \
        var/lib/couchbase/logs \
        var/lib/moxi
    chown -R couchbase:couchbase var

    # Start couchbase
    echo "Starting Couchbase Server -- Web UI available at http://<ip>:8091"
    exec gosu couchbase "$@"
fi

exec "$@"