#!/bin/bash

# Copyright 2018-Present Couchbase, Inc.
#
# Use of this software is governed by the Business Source License included in
# the file licenses/BSL-Couchbase.txt.  As of the Change Date specified in that
# file, in accordance with the Business Source License, use of this software
# will be governed by the Apache License, Version 2.0, included in the file
# licenses/APL2.txt.

export PATH=$PATH:/opt/couchbase/bin:/opt/couchbase/bin/tools:/opt/couchbase/bin/install:/usr/local/bin/
service() {
   if [ "$1" == "stop" ]; then
      ps aux | grep couchbase | grep -v grep | grep -v systemctl | awk '{print $2}' | xargs kill
      echo "couchbase service stopped"
   fi

   if [ "$1" == "start" ]; then
      nohup couchbase-start couchbase-server -- -noinput > /opt/_status 2>&1 </dev/null &
      echo "couchbase service started"
   fi
}

if [ "$2" == "couchbase.service" ]; then
   service $1
elif [ "$2" == "couchbase-server.service" ]; then
   service $1
else
   if [ "$0" == "/usr/sbin/reboot" ]; then
       # fake reboot
       service stop
       sleep 10
       service start
   else
       exec /bin/systemctl.bin "$@"
   fi
fi