/*
Copyright 2025-Present Couchbase, Inc.

Use of this software is governed by the Business Source License included in
the file licenses/BSL-Couchbase.txt.  As of the Change Date specified in that
file, in accordance with the Business Source License, use of this software will
be governed by the Apache License, Version 2.0, included in the file
licenses/APL2.txt.
*/

package cluster

import (
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"strings"
	"testing"

	couchbasev2 "github.com/couchbase/couchbase-operator/pkg/apis/couchbase/v2"
	"github.com/couchbase/couchbase-operator/pkg/util/couchbaseutil"
	"github.com/stretchr/testify/assert"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

func TestOrderKeysForCreation(t *testing.T) {
	keys := []*couchbasev2.CouchbaseEncryptionKey{
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "key1",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
				AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{
					EncryptWithKey: "key2",
				},
			},
		},
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "key2",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
				AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{
					EncryptWithKey: "key4",
				},
			},
		},
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "key3",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType:       couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
				AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{},
			},
		},
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "key4",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
				AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{
					EncryptWithKey: "key3",
				},
			},
		},
	}

	orderedKeys := orderKeysForCreation(keys)

	assert.Equal(t, orderedKeys[0].Name, "key3")
	assert.Equal(t, orderedKeys[1].Name, "key4")
	assert.Equal(t, orderedKeys[2].Name, "key2")
	assert.Equal(t, orderedKeys[3].Name, "key1")
}

func TestOrderKeysForCreationWithExtras(t *testing.T) {
	keys := []*couchbasev2.CouchbaseEncryptionKey{
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "key1",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
				AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{
					EncryptWithKey: "key2",
				},
			},
		},
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "aws-key1",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType: couchbasev2.CouchbaseEncryptionKeyTypeAWS,
				AWSKey:  &couchbasev2.CouchbaseEncryptionKeyAWS{},
			},
		},
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "key2",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
				AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{
					EncryptWithKey: "key4",
				},
			},
		},
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "aws-key2",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType: couchbasev2.CouchbaseEncryptionKeyTypeAWS,
				AWSKey:  &couchbasev2.CouchbaseEncryptionKeyAWS{},
			},
		},
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "key3",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType:       couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
				AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{},
			},
		},
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "key4",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
				AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{
					EncryptWithKey: "key3",
				},
			},
		},
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "kmip-key1",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType: couchbasev2.CouchbaseEncryptionKeyTypeKMIP,
				KMIPKey: &couchbasev2.CouchbaseEncryptionKeyKMIP{},
			},
		},
	}

	orderedKeys := orderKeysForCreation(keys)

	// Check that we haven't lost any keys
	for _, key := range keys {
		found := false

		for _, k := range orderedKeys {
			if key.Name == k.Name {
				found = true
				break
			}
		}

		assert.True(t, found, "key %s not found in ordered keys", key.Name)
	}

	// Check that the normal keys are in the correct order
	i := 0
	expectedOrderForNormalKeys := []string{"key3", "key4", "key2", "key1"}

	for _, key := range orderedKeys {
		if strings.HasPrefix(key.Name, "key") {
			assert.Equal(t, key.Name, expectedOrderForNormalKeys[i])
			i++
		}
	}
}

func TestOrderKeysForCreationWithMultipleDependencyGraphs(t *testing.T) {
	keys := []*couchbasev2.CouchbaseEncryptionKey{
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "key1-1",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
				AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{
					EncryptWithKey: "key1-2",
				},
			},
		},
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "key1-2",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType:       couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
				AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{},
			},
		},
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "kmip-key1",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType: couchbasev2.CouchbaseEncryptionKeyTypeKMIP,
				KMIPKey: &couchbasev2.CouchbaseEncryptionKeyKMIP{},
			},
		},
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "key2-1",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType:       couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
				AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{},
			},
		},
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "key2-2",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
				AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{
					EncryptWithKey: "key2-1",
				},
			},
		},
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "aws-key1",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType: couchbasev2.CouchbaseEncryptionKeyTypeAWS,
				AWSKey:  &couchbasev2.CouchbaseEncryptionKeyAWS{},
			},
		},
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "key2-3",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
				AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{
					EncryptWithKey: "key2-2",
				},
			},
		},
	}

	orderedKeys := orderKeysForCreation(keys)

	// Check that we haven't lost any keys
	for _, key := range keys {
		found := false

		for _, k := range orderedKeys {
			if key.Name == k.Name {
				found = true
				break
			}
		}

		assert.True(t, found, "key %s not found in ordered keys", key.Name)
	}

	graph1ExpectedOrder := []string{"key1-2", "key1-1"}
	graph2ExpectedOrder := []string{"key2-1", "key2-2", "key2-3"}

	i, j := 0, 0

	for _, key := range orderedKeys {
		if strings.HasPrefix(key.Name, "key1") {
			assert.Equal(t, key.Name, graph1ExpectedOrder[i])
			i++
		} else if strings.HasPrefix(key.Name, "key2") {
			assert.Equal(t, key.Name, graph2ExpectedOrder[j])
			j++
		}
	}
}

// failedRequestError builds a couchbaseutil.FailedRequestError of the same
// shape produced by couchbaseutil.Client.doRequest on an HTTP 4xx/5xx. Only
// the Body and StatusCode fields are inspected by the classifier under test;
// the rest only affect the Error() string.
func failedRequestError(statusCode int, body string) error {
	u, _ := url.Parse("http://example.invalid/settings/encryptionKeys")

	return couchbaseutil.NewFailedRequestError(
		&http.Request{Method: http.MethodPost, URL: u},
		&http.Response{Status: http.StatusText(statusCode), StatusCode: statusCode},
		[]byte(body),
		couchbaseutil.ErrStatusError,
	)
}

func TestIsCredentialFilePendingError(t *testing.T) {
	credentialsFileBody := `{"errors":{"data":{"credentialsFile":"The value must be a valid file"}}}`

	cases := []struct {
		name string
		err  error
		want bool
	}{
		{
			name: "nil error",
			err:  nil,
			want: false,
		},
		{
			name: "plain non-request error",
			err:  errors.New("connection refused"),
			want: false,
		},
		{
			name: "401 unauthorized credentialsFile body",
			err:  failedRequestError(http.StatusUnauthorized, credentialsFileBody),
			want: false,
		},
		{
			name: "500 server error",
			err:  failedRequestError(http.StatusInternalServerError, "internal"),
			want: false,
		},
		{
			name: "400 unrelated body",
			err:  failedRequestError(http.StatusBadRequest, `{"errors":{"data":{"keyARN":"invalid"}}}`),
			want: false,
		},
		{
			name: "400 partial body credentialsFile only",
			err:  failedRequestError(http.StatusBadRequest, `{"credentialsFile":"something else"}`),
			want: false,
		},
		{
			name: "400 partial body wrong message only",
			err:  failedRequestError(http.StatusBadRequest, `{"someOther":"must be a valid file"}`),
			want: false,
		},
		{
			name: "400 credentialsFile + must be a valid file",
			err:  failedRequestError(http.StatusBadRequest, credentialsFileBody),
			want: true,
		},
		{
			name: "wrapped 400 credentialsFile",
			err:  fmt.Errorf("post failed: %w", failedRequestError(http.StatusBadRequest, credentialsFileBody)),
			want: true,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			assert.Equal(t, tc.want, isCredentialFilePendingError(tc.err))
		})
	}
}

func TestEncryptionKeyDependency(t *testing.T) {
	cases := []struct {
		name string
		key  *couchbasev2.CouchbaseEncryptionKey
		want string
	}{
		{
			name: "AWS key has no dependency",
			key: &couchbasev2.CouchbaseEncryptionKey{
				ObjectMeta: metav1.ObjectMeta{Name: "aws-root"},
				Spec: couchbasev2.CouchbaseEncryptionKeySpec{
					KeyType: couchbasev2.CouchbaseEncryptionKeyTypeAWS,
				},
			},
			want: "",
		},
		{
			name: "KMIP key has no dependency",
			key: &couchbasev2.CouchbaseEncryptionKey{
				ObjectMeta: metav1.ObjectMeta{Name: "kmip-root"},
				Spec: couchbasev2.CouchbaseEncryptionKeySpec{
					KeyType: couchbasev2.CouchbaseEncryptionKeyTypeKMIP,
				},
			},
			want: "",
		},
		{
			name: "AutoGenerated with nil AutoGenerated block",
			key: &couchbasev2.CouchbaseEncryptionKey{
				ObjectMeta: metav1.ObjectMeta{Name: "autogen"},
				Spec: couchbasev2.CouchbaseEncryptionKeySpec{
					KeyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
				},
			},
			want: "",
		},
		{
			name: "AutoGenerated with empty EncryptWithKey (master password)",
			key: &couchbasev2.CouchbaseEncryptionKey{
				ObjectMeta: metav1.ObjectMeta{Name: "autogen"},
				Spec: couchbasev2.CouchbaseEncryptionKeySpec{
					KeyType:       couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
					AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{},
				},
			},
			want: "",
		},
		{
			name: "AutoGenerated wraps with another key",
			key: &couchbasev2.CouchbaseEncryptionKey{
				ObjectMeta: metav1.ObjectMeta{Name: "data-key"},
				Spec: couchbasev2.CouchbaseEncryptionKeySpec{
					KeyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
					AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{
						EncryptWithKey: "kek-intermediate",
					},
				},
			},
			want: "kek-intermediate",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			assert.Equal(t, tc.want, encryptionKeyDependency(tc.key))
		})
	}
}

func TestIsEncryptionKeyDeferred(t *testing.T) {
	t.Run("nil map returns false", func(t *testing.T) {
		c := &Cluster{}
		assert.False(t, c.isEncryptionKeyDeferred("anything"))
	})

	t.Run("empty map returns false", func(t *testing.T) {
		c := &Cluster{deferredEncryptionKeys: map[string]struct{}{}}
		assert.False(t, c.isEncryptionKeyDeferred("anything"))
	})

	t.Run("absent key returns false", func(t *testing.T) {
		c := &Cluster{deferredEncryptionKeys: map[string]struct{}{
			"key-A": {},
		}}
		assert.False(t, c.isEncryptionKeyDeferred("key-B"))
	})

	t.Run("present key returns true", func(t *testing.T) {
		c := &Cluster{deferredEncryptionKeys: map[string]struct{}{
			"key-A": {},
			"key-B": {},
		}}
		assert.True(t, c.isEncryptionKeyDeferred("key-A"))
		assert.True(t, c.isEncryptionKeyDeferred("key-B"))
	})
}
