package cluster

import (
	"strings"
	"testing"

	couchbasev2 "github.com/couchbase/couchbase-operator/pkg/apis/couchbase/v2"
	"github.com/stretchr/testify/assert"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

func TestOrderKeysForCreation(t *testing.T) {
	keys := []*couchbasev2.CouchbaseEncryptionKey{
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "key1",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
				AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{
					EncryptWithKey: "key2",
				},
			},
		},
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "key2",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
				AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{
					EncryptWithKey: "key4",
				},
			},
		},
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "key3",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType:       couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
				AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{},
			},
		},
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "key4",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
				AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{
					EncryptWithKey: "key3",
				},
			},
		},
	}

	orderedKeys := orderKeysForCreation(keys)

	assert.Equal(t, orderedKeys[0].Name, "key3")
	assert.Equal(t, orderedKeys[1].Name, "key4")
	assert.Equal(t, orderedKeys[2].Name, "key2")
	assert.Equal(t, orderedKeys[3].Name, "key1")
}

func TestOrderKeysForCreationWithExtras(t *testing.T) {
	keys := []*couchbasev2.CouchbaseEncryptionKey{
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "key1",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
				AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{
					EncryptWithKey: "key2",
				},
			},
		},
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "aws-key1",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType: couchbasev2.CouchbaseEncryptionKeyTypeAWS,
				AwsKey:  &couchbasev2.CouchbaseEncryptionKeyAWS{},
			},
		},
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "key2",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
				AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{
					EncryptWithKey: "key4",
				},
			},
		},
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "aws-key2",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType: couchbasev2.CouchbaseEncryptionKeyTypeAWS,
				AwsKey:  &couchbasev2.CouchbaseEncryptionKeyAWS{},
			},
		},
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "key3",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType:       couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
				AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{},
			},
		},
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "key4",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
				AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{
					EncryptWithKey: "key3",
				},
			},
		},
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "kmip-key1",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType: couchbasev2.CouchbaseEncryptionKeyTypeKMIP,
				KmipKey: &couchbasev2.CouchbaseEncryptionKeyKMIP{},
			},
		},
	}

	orderedKeys := orderKeysForCreation(keys)

	// Check that we haven't lost any keys
	for _, key := range keys {
		found := false

		for _, k := range orderedKeys {
			if key.Name == k.Name {
				found = true
				break
			}
		}

		assert.True(t, found, "key %s not found in ordered keys", key.Name)
	}

	// Check that the normal keys are in the correct order
	i := 0
	expectedOrderForNormalKeys := []string{"key3", "key4", "key2", "key1"}

	for _, key := range orderedKeys {
		if strings.HasPrefix(key.Name, "key") {
			assert.Equal(t, key.Name, expectedOrderForNormalKeys[i])
			i++
		}
	}
}

func TestOrderKeysForCreationWithMultipleDependencyGraphs(t *testing.T) {
	keys := []*couchbasev2.CouchbaseEncryptionKey{
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "key1-1",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
				AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{
					EncryptWithKey: "key1-2",
				},
			},
		},
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "key1-2",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType:       couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
				AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{},
			},
		},
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "kmip-key1",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType: couchbasev2.CouchbaseEncryptionKeyTypeKMIP,
				KmipKey: &couchbasev2.CouchbaseEncryptionKeyKMIP{},
			},
		},
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "key2-1",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType:       couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
				AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{},
			},
		},
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "key2-2",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
				AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{
					EncryptWithKey: "key2-1",
				},
			},
		},
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "aws-key1",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType: couchbasev2.CouchbaseEncryptionKeyTypeAWS,
				AwsKey:  &couchbasev2.CouchbaseEncryptionKeyAWS{},
			},
		},
		{
			ObjectMeta: metav1.ObjectMeta{
				Name: "key2-3",
			},
			Spec: couchbasev2.CouchbaseEncryptionKeySpec{
				KeyType: couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
				AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{
					EncryptWithKey: "key2-2",
				},
			},
		},
	}

	orderedKeys := orderKeysForCreation(keys)

	// Check that we haven't lost any keys
	for _, key := range keys {
		found := false

		for _, k := range orderedKeys {
			if key.Name == k.Name {
				found = true
				break
			}
		}

		assert.True(t, found, "key %s not found in ordered keys", key.Name)
	}

	graph1ExpectedOrder := []string{"key1-2", "key1-1"}
	graph2ExpectedOrder := []string{"key2-1", "key2-2", "key2-3"}

	i, j := 0, 0

	for _, key := range orderedKeys {
		if strings.HasPrefix(key.Name, "key1") {
			assert.Equal(t, key.Name, graph1ExpectedOrder[i])
			i++
		} else if strings.HasPrefix(key.Name, "key2") {
			assert.Equal(t, key.Name, graph2ExpectedOrder[j])
			j++
		}
	}
}
