package e2e

import (
	"context"
	"fmt"
	"testing"
	"time"

	couchbasev2 "github.com/couchbase/couchbase-operator/pkg/apis/couchbase/v2"
	"github.com/couchbase/couchbase-operator/pkg/util/couchbaseutil"
	"github.com/couchbase/couchbase-operator/pkg/util/jsonpatch"
	"github.com/couchbase/couchbase-operator/test/e2e/e2eutil"
	"github.com/couchbase/couchbase-operator/test/e2e/framework"
	"github.com/couchbase/couchbase-operator/test/e2e/types"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// mustCreateEncryptionKey creates an auto-generated encryption key for testing.
func mustCreateAutoGeneratedEncryptionKey(t *testing.T, k8s *types.Cluster, name string) *couchbasev2.CouchbaseEncryptionKey {
	key := &couchbasev2.CouchbaseEncryptionKey{
		ObjectMeta: metav1.ObjectMeta{
			Name: name,
		},
		Spec: couchbasev2.CouchbaseEncryptionKeySpec{
			KeyType:       couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
			AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{},
			Usage: &couchbasev2.CouchbaseEncryptionKeyUsage{
				Configuration: true,
				Key:           true,
				Log:           true,
				Audit:         true,
				AllBuckets:    true,
			},
		},
	}

	createdKey, err := k8s.CRClient.CouchbaseV2().CouchbaseEncryptionKeys(k8s.Namespace).Create(context.TODO(), key, metav1.CreateOptions{})
	if err != nil {
		e2eutil.Die(t, fmt.Errorf("failed to create encryption key %s: %w", name, err))
	}

	return createdKey
}

// TestEncryptionAtRest tests encryption at rest functionality
// 1. Creates encryption keys
// 2. Creates a cluster with encryption at rest disabled initially
// 3. Validates the cluster creation events
// 4. Tests enabling encryption for configurations
// 5. Tests disabling encryption for configurations
// 6. Tests enabling encryption for audit logs
// 7. Tests disabling encryption for audit logs.
func TestEncryptionAtRest(t *testing.T) {
	// Platform configuration.
	f := framework.Global

	kubernetes, cleanup := f.SetupTest(t)
	defer cleanup()

	framework.Requires(t, kubernetes).AtLeastVersion("8.0.0")

	// Static configuration.
	clusterSize := 1

	// Create encryption keys
	// mustCreateEncryptionKey(t, kubernetes, "config-key")
	// mustCreateEncryptionKey(t, kubernetes, "audit-key")
	// mustCreateEncryptionKey(t, kubernetes, "log-key")

	// Create the cluster with encryption at rest
	cluster := clusterOptions().WithEphemeralTopology(clusterSize).Generate(kubernetes)
	cluster.Spec.Security.EncryptionAtRest = &couchbasev2.EncryptionAtRestSpec{
		Managed: true,
		Configuration: &couchbasev2.EncryptionAtRestUsageConfiguration{
			Enabled: false,
		},
		Audit: &couchbasev2.EncryptionAtRestUsageConfiguration{
			Enabled: false,
		},
		Log: &couchbasev2.EncryptionAtRestUsageConfiguration{
			Enabled: false,
		},
	}

	cluster = e2eutil.MustNewClusterFromSpec(t, kubernetes, cluster)

	// Test enabling encryption for audit logs
	t.Run("EnableAuditEncryption", func(t *testing.T) {
		cluster = e2eutil.MustPatchCluster(t, kubernetes, cluster, jsonpatch.NewPatchSet().Replace("/spec/security/encryptionAtRest/audit", &couchbasev2.EncryptionAtRestUsageConfiguration{Enabled: true}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.ClusterSettingsEditedEvent(cluster, "audit encryption at rest"), 2*time.Minute)
		e2eutil.MustPatchEncryptionAtRestSettings(t, kubernetes, cluster, jsonpatch.NewPatchSet().Test("/Audit/EncryptionMethod", couchbaseutil.EncryptionMethodNodeSecretManager), 1*time.Minute)
	})

	// Test enabling encryption for configurations
	t.Run("EnableConfigurationEncryption", func(t *testing.T) {
		cluster = e2eutil.MustPatchCluster(t, kubernetes, cluster, jsonpatch.NewPatchSet().Replace("/spec/security/encryptionAtRest/configuration", &couchbasev2.EncryptionAtRestUsageConfiguration{Enabled: true}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.ClusterSettingsEditedEvent(cluster, "configuration encryption at rest"), 2*time.Minute)
		e2eutil.MustPatchEncryptionAtRestSettings(t, kubernetes, cluster, jsonpatch.NewPatchSet().Test("/Config/EncryptionMethod", couchbaseutil.EncryptionMethodNodeSecretManager), 1*time.Minute)
	})

	// Test enabling encryption for logs
	t.Run("EnableLogEncryption", func(t *testing.T) {
		cluster = e2eutil.MustPatchCluster(t, kubernetes, cluster, jsonpatch.NewPatchSet().Replace("/spec/security/encryptionAtRest/log", &couchbasev2.EncryptionAtRestUsageConfiguration{Enabled: true}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.ClusterSettingsEditedEvent(cluster, "log encryption at rest"), 2*time.Minute)
		e2eutil.MustPatchEncryptionAtRestSettings(t, kubernetes, cluster, jsonpatch.NewPatchSet().Test("/Log/EncryptionMethod", couchbaseutil.EncryptionMethodNodeSecretManager), 1*time.Minute)
	})

	t.Run("ConfigureRotationInterval", func(t *testing.T) {
		rotationInterval := time.Hour * 24 * 10
		cluster = e2eutil.MustPatchCluster(t, kubernetes, cluster, jsonpatch.NewPatchSet().Replace("/spec/security/encryptionAtRest/configuration/rotationInterval", &metav1.Duration{Duration: rotationInterval}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.ClusterSettingsEditedEvent(cluster, "configuration encryption at rest"), 2*time.Minute)
		e2eutil.MustPatchEncryptionAtRestSettings(t, kubernetes, cluster, jsonpatch.NewPatchSet().Test("/Config/DEKRotationInterval", int(rotationInterval.Seconds())), 1*time.Minute)
	})

	t.Run("ConfigureKeyLifetime", func(t *testing.T) {
		keyLifetime := time.Hour * 24 * 45
		cluster = e2eutil.MustPatchCluster(t, kubernetes, cluster, jsonpatch.NewPatchSet().Replace("/spec/security/encryptionAtRest/configuration/keyLifetime", &metav1.Duration{Duration: keyLifetime}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.ClusterSettingsEditedEvent(cluster, "configuration encryption at rest"), 2*time.Minute)
		e2eutil.MustPatchEncryptionAtRestSettings(t, kubernetes, cluster, jsonpatch.NewPatchSet().Test("/Config/DEKLifetime", int(keyLifetime.Seconds())), 1*time.Minute)
	})
}

func TestAutoGeneratedEncryptionKey(t *testing.T) {
	// Platform configuration.
	f := framework.Global

	kubernetes, cleanup := f.SetupTest(t)
	defer cleanup()

	framework.Requires(t, kubernetes).AtLeastVersion("8.0.0")

	// Static configuration.
	clusterSize := 1

	// Create the cluster with encryption at rest disabled initially
	cluster := clusterOptions().WithEphemeralTopology(clusterSize).Generate(kubernetes)
	cluster.Spec.Security.EncryptionAtRest = &couchbasev2.EncryptionAtRestSpec{
		Managed: true,
	}

	cluster = e2eutil.MustNewClusterFromSpec(t, kubernetes, cluster)

	// Create encryption keys
	key := mustCreateAutoGeneratedEncryptionKey(t, kubernetes, "encryption-key")

	e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyCreatedEvent(cluster, key.Name), 2*time.Minute)
	e2eutil.MustAssertEncryptionKeyExists(t, kubernetes, cluster, key.Name)

	t.Run("TestSetConfigurationUsage", func(t *testing.T) {
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/usage", &couchbasev2.CouchbaseEncryptionKeyUsage{
			Configuration: true,
			Key:           false,
			Log:           false,
			Audit:         false,
			AllBuckets:    false,
		}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/Usage", []string{"config-encryption"}), 1*time.Minute)
	})

	t.Run("TestSetKeyUsage", func(t *testing.T) {
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/usage", &couchbasev2.CouchbaseEncryptionKeyUsage{
			Configuration: false,
			Key:           true,
			Log:           false,
			Audit:         false,
			AllBuckets:    false,
		}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/Usage", []string{"KEK-encryption"}), 1*time.Minute)
	})

	t.Run("TestSetLogUsage", func(t *testing.T) {
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/usage", &couchbasev2.CouchbaseEncryptionKeyUsage{
			Configuration: false,
			Key:           false,
			Log:           true,
			Audit:         false,
			AllBuckets:    false,
		}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/Usage", []string{"log-encryption"}), 1*time.Minute)
	})

	t.Run("TestSetAuditUsage", func(t *testing.T) {
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/usage", &couchbasev2.CouchbaseEncryptionKeyUsage{
			Configuration: false,
			Key:           false,
			Log:           false,
			Audit:         true,
			AllBuckets:    false,
		}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/Usage", []string{"audit-encryption"}), 1*time.Minute)
	})

	t.Run("TestSetAllBucketsUsage", func(t *testing.T) {
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/usage", &couchbasev2.CouchbaseEncryptionKeyUsage{
			Configuration: false,
			Key:           false,
			Log:           false,
			Audit:         false,
			AllBuckets:    true,
		}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/Usage", []string{"bucket-encryption"}), 1*time.Minute)
	})

	t.Run("TestAutoGeneratedSettings", func(t *testing.T) {
		// Test 1: Enable auto rotation with 30 day interval and future start time
		futureTime := metav1.NewTime(time.Now().Add(24 * time.Hour))
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/autoGenerated", &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{
			Rotation: &couchbasev2.CouchbaseEncryptionKeyRotation{
				IntervalDays: 30,
				StartTime:    &futureTime,
			},
			CanBeCached: true,
		}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/AutoGenerated/NextRotationTime", futureTime.Format(time.RFC3339)).Test("/EncryptionKey/AutoGenerated/RotationIntervalInDays", 30).Test("/EncryptionKey/AutoGenerated/CanBeCached", true), 1*time.Minute)
	})
}
