package e2e

import (
	"context"
	"fmt"
	"testing"
	"time"

	couchbasev2 "github.com/couchbase/couchbase-operator/pkg/apis/couchbase/v2"
	"github.com/couchbase/couchbase-operator/pkg/util/couchbaseutil"
	"github.com/couchbase/couchbase-operator/pkg/util/eventschema"
	"github.com/couchbase/couchbase-operator/pkg/util/jsonpatch"
	"github.com/couchbase/couchbase-operator/pkg/util/k8sutil"
	"github.com/couchbase/couchbase-operator/pkg/util/retryutil"
	"github.com/couchbase/couchbase-operator/test/e2e/e2espec"
	"github.com/couchbase/couchbase-operator/test/e2e/e2eutil"
	"github.com/couchbase/couchbase-operator/test/e2e/framework"
	"github.com/couchbase/couchbase-operator/test/e2e/types"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// mustCreateEncryptionKey creates an auto-generated encryption key for testing.
func mustCreateAutoGeneratedEncryptionKey(t *testing.T, k8s *types.Cluster, name string) *couchbasev2.CouchbaseEncryptionKey {
	key := &couchbasev2.CouchbaseEncryptionKey{
		ObjectMeta: metav1.ObjectMeta{
			Name: name,
		},
		Spec: couchbasev2.CouchbaseEncryptionKeySpec{
			KeyType:       couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
			AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{},
			Usage: &couchbasev2.CouchbaseEncryptionKeyUsage{
				Configuration: true,
				Key:           true,
				Log:           true,
				Audit:         true,
				AllBuckets:    true,
			},
		},
	}

	createdKey, err := k8s.CRClient.CouchbaseV2().CouchbaseEncryptionKeys(k8s.Namespace).Create(context.TODO(), key, metav1.CreateOptions{})
	if err != nil {
		e2eutil.Die(t, fmt.Errorf("failed to create encryption key %s: %w", name, err))
	}

	return createdKey
}

func mustCreateAutoGeneratedAWSKey(t *testing.T, k8s *types.Cluster, name string) *couchbasev2.CouchbaseEncryptionKey {
	key := &couchbasev2.CouchbaseEncryptionKey{
		ObjectMeta: metav1.ObjectMeta{
			Name: name,
		},
		Spec: couchbasev2.CouchbaseEncryptionKeySpec{
			KeyType: couchbasev2.CouchbaseEncryptionKeyTypeAWS,
			AWSKey: &couchbasev2.CouchbaseEncryptionKeyAWS{
				KeyARN:    "arn:aws:kms:us-west-2:123456789012:key/1234abcd-12ab-34cd-56ef-1234567890ab",
				KeyRegion: "us-west-2",
			},
		},
	}

	createdKey, err := k8s.CRClient.CouchbaseV2().CouchbaseEncryptionKeys(k8s.Namespace).Create(context.TODO(), key, metav1.CreateOptions{})
	if err != nil {
		e2eutil.Die(t, fmt.Errorf("failed to create encryption key %s: %w", name, err))
	}

	return createdKey
}

func mustGenerateKeyCertPair(t *testing.T, keyPassphrase string) ([]byte, []byte, error) {
	kpr := e2eutil.CreateKeyPairReqData(e2eutil.KeyTypeRSA, e2eutil.KeyEncodingPKCS8, e2eutil.CertTypeClient, e2eutil.CreateCertReq("Couchbase Cluster"))

	validFrom := time.Now().In(time.UTC)
	validTo := validFrom.AddDate(10, 0, 0)

	ca, err := e2eutil.NewCertificateAuthority(e2eutil.KeyTypeRSA, "Couchbase CA", validFrom, validTo, e2eutil.CertTypeCA)
	if err != nil {
		e2eutil.Die(t, fmt.Errorf("failed to create certificate authority: %w", err))
	}

	_, clusterKey, clusterCert, err := kpr.Generate(ca, validFrom, validTo)
	if err != nil {
		e2eutil.Die(t, fmt.Errorf("failed to generate key cert pair: %w", err))
	}

	if clusterKey, err = e2eutil.AddPKCS8Passphrase(clusterKey, []byte(keyPassphrase)); err != nil {
		e2eutil.Die(t, fmt.Errorf("failed to add passphrase to key: %w", err))
	}

	return clusterKey, clusterCert, nil
}

func mustCreateAutoGeneratedKMIPKey(t *testing.T, k8s *types.Cluster, name string) (*couchbasev2.CouchbaseEncryptionKey, *corev1.Secret) {
	testKeyPassphrase := "test-passphrase"

	clusterKey, clusterCert, err := mustGenerateKeyCertPair(t, testKeyPassphrase)
	if err != nil {
		e2eutil.Die(t, fmt.Errorf("failed to create key cert pair: %w", err))
	}

	secretName := name + "-secret"
	secret := &corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{
			Name: secretName,
		},
		Data: map[string][]byte{
			"passphrase": []byte(testKeyPassphrase),
			"tls.key":    clusterKey,
			"tls.crt":    clusterCert,
		},
	}

	secret = e2eutil.MustCreateSecret(t, k8s, secret)

	key := &couchbasev2.CouchbaseEncryptionKey{
		ObjectMeta: metav1.ObjectMeta{
			Name: name,
		},
		Spec: couchbasev2.CouchbaseEncryptionKeySpec{
			KeyType: couchbasev2.CouchbaseEncryptionKeyTypeKMIP,
			KMIPKey: &couchbasev2.CouchbaseEncryptionKeyKMIP{
				ClientSecret:          secretName,
				Host:                  "localhost",
				Port:                  1636,
				TimeoutInMs:           1000,
				VerifyWithSystemCA:    true,
				VerifyWithCouchbaseCA: true,
				EncryptionApproach:    couchbasev2.CouchbaseEncryptionApproachNativeEncryptDecrypt,
			},
		},
	}

	key, err = k8s.CRClient.CouchbaseV2().CouchbaseEncryptionKeys(k8s.Namespace).Create(context.TODO(), key, metav1.CreateOptions{})
	if err != nil {
		e2eutil.Die(t, fmt.Errorf("failed to create encryption key %s: %w", name, err))
	}

	return key, secret
}

// TestEncryptionAtRest tests encryption at rest functionality
// 1. Creates encryption keys
// 2. Creates a cluster with encryption at rest disabled initially
// 3. Validates the cluster creation events
// 4. Tests enabling encryption for configurations
// 5. Tests disabling encryption for configurations
// 6. Tests enabling encryption for audit logs
// 7. Tests disabling encryption for audit logs.
func TestEncryptionAtRest(t *testing.T) {
	// Platform configuration.
	f := framework.Global

	kubernetes, cleanup := f.SetupTest(t)
	defer cleanup()

	framework.Requires(t, kubernetes).AtLeastVersion("8.0.0")

	// Static configuration.
	clusterSize := 1

	// Create encryption keys

	// Create the cluster with encryption at rest
	cluster := clusterOptions().WithEphemeralTopology(clusterSize).Generate(kubernetes)
	cluster.Spec.Security.EncryptionAtRest = &couchbasev2.EncryptionAtRestSpec{
		Managed: true,
		Configuration: &couchbasev2.EncryptionAtRestUsageConfiguration{
			Enabled: false,
		},
		Audit: &couchbasev2.EncryptionAtRestUsageConfiguration{
			Enabled: false,
		},
		Log: &couchbasev2.EncryptionAtRestUsageConfiguration{
			Enabled: false,
		},
	}

	cluster = e2eutil.MustNewClusterFromSpec(t, kubernetes, cluster)

	// Test enabling encryption for audit logs
	t.Run("EnableAuditEncryption", func(t *testing.T) {
		cluster = e2eutil.MustPatchCluster(t, kubernetes, cluster, jsonpatch.NewPatchSet().Replace("/spec/security/encryptionAtRest/audit", &couchbasev2.EncryptionAtRestUsageConfiguration{Enabled: true}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.ClusterSettingsEditedEvent(cluster, "audit encryption at rest"), 2*time.Minute)
		e2eutil.MustPatchEncryptionAtRestSettings(t, kubernetes, cluster, jsonpatch.NewPatchSet().Test("/Audit/EncryptionMethod", couchbaseutil.EncryptionMethodNodeSecretManager), 1*time.Minute)
	})

	// Test enabling encryption for configurations
	t.Run("EnableConfigurationEncryption", func(t *testing.T) {
		cluster = e2eutil.MustPatchCluster(t, kubernetes, cluster, jsonpatch.NewPatchSet().Replace("/spec/security/encryptionAtRest/configuration", &couchbasev2.EncryptionAtRestUsageConfiguration{Enabled: true}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.ClusterSettingsEditedEvent(cluster, "configuration encryption at rest"), 2*time.Minute)
		e2eutil.MustPatchEncryptionAtRestSettings(t, kubernetes, cluster, jsonpatch.NewPatchSet().Test("/Config/EncryptionMethod", couchbaseutil.EncryptionMethodNodeSecretManager), 1*time.Minute)
	})

	// Test enabling encryption for logs
	t.Run("EnableLogEncryption", func(t *testing.T) {
		cluster = e2eutil.MustPatchCluster(t, kubernetes, cluster, jsonpatch.NewPatchSet().Replace("/spec/security/encryptionAtRest/log", &couchbasev2.EncryptionAtRestUsageConfiguration{Enabled: true}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.ClusterSettingsEditedEvent(cluster, "log encryption at rest"), 2*time.Minute)
		e2eutil.MustPatchEncryptionAtRestSettings(t, kubernetes, cluster, jsonpatch.NewPatchSet().Test("/Log/EncryptionMethod", couchbaseutil.EncryptionMethodNodeSecretManager), 1*time.Minute)
	})

	t.Run("ConfigureRotationInterval", func(t *testing.T) {
		rotationInterval := time.Hour * 24 * 10
		cluster = e2eutil.MustPatchCluster(t, kubernetes, cluster, jsonpatch.NewPatchSet().Replace("/spec/security/encryptionAtRest/configuration/rotationInterval", &metav1.Duration{Duration: rotationInterval}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.ClusterSettingsEditedEvent(cluster, "configuration encryption at rest"), 2*time.Minute)
		e2eutil.MustPatchEncryptionAtRestSettings(t, kubernetes, cluster, jsonpatch.NewPatchSet().Test("/Config/DEKRotationInterval", int(rotationInterval.Seconds())), 1*time.Minute)
	})

	t.Run("ConfigureKeyLifetime", func(t *testing.T) {
		keyLifetime := time.Hour * 24 * 45
		cluster = e2eutil.MustPatchCluster(t, kubernetes, cluster, jsonpatch.NewPatchSet().Replace("/spec/security/encryptionAtRest/configuration/keyLifetime", &metav1.Duration{Duration: keyLifetime}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.ClusterSettingsEditedEvent(cluster, "configuration encryption at rest"), 2*time.Minute)
		e2eutil.MustPatchEncryptionAtRestSettings(t, kubernetes, cluster, jsonpatch.NewPatchSet().Test("/Config/DEKLifetime", int(keyLifetime.Seconds())), 1*time.Minute)
	})
}

func TestAutoGeneratedEncryptionKey(t *testing.T) {
	// Platform configuration.
	f := framework.Global

	kubernetes, cleanup := f.SetupTest(t)
	defer cleanup()

	framework.Requires(t, kubernetes).AtLeastVersion("8.0.0")

	// Static configuration.
	clusterSize := 1

	// Create the cluster with encryption at rest enabled
	cluster := clusterOptions().WithEphemeralTopology(clusterSize).Generate(kubernetes)
	cluster.Spec.Security.EncryptionAtRest = &couchbasev2.EncryptionAtRestSpec{
		Managed: true,
	}

	cluster = e2eutil.MustNewClusterFromSpec(t, kubernetes, cluster)

	// Create encryption keys
	key := mustCreateAutoGeneratedEncryptionKey(t, kubernetes, "encryption-key")

	e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyCreatedEvent(cluster, key.Name), 2*time.Minute)
	e2eutil.MustAssertEncryptionKeyExists(t, kubernetes, cluster, key.Name)

	t.Run("TestSetConfigurationUsage", func(t *testing.T) {
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/usage", &couchbasev2.CouchbaseEncryptionKeyUsage{
			Configuration: true,
			Key:           false,
			Log:           false,
			Audit:         false,
			AllBuckets:    false,
		}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/Usage", []string{"config-encryption"}), 1*time.Minute)
	})

	t.Run("TestSetKeyUsage", func(t *testing.T) {
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/usage", &couchbasev2.CouchbaseEncryptionKeyUsage{
			Configuration: false,
			Key:           true,
			Log:           false,
			Audit:         false,
			AllBuckets:    false,
		}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/Usage", []string{"KEK-encryption"}), 1*time.Minute)
	})

	t.Run("TestSetLogUsage", func(t *testing.T) {
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/usage", &couchbasev2.CouchbaseEncryptionKeyUsage{
			Configuration: false,
			Key:           false,
			Log:           true,
			Audit:         false,
			AllBuckets:    false,
		}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/Usage", []string{"log-encryption"}), 1*time.Minute)
	})

	t.Run("TestSetAuditUsage", func(t *testing.T) {
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/usage", &couchbasev2.CouchbaseEncryptionKeyUsage{
			Configuration: false,
			Key:           false,
			Log:           false,
			Audit:         true,
			AllBuckets:    false,
		}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/Usage", []string{"audit-encryption"}), 1*time.Minute)
	})

	t.Run("TestSetAllBucketsUsage", func(t *testing.T) {
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/usage", &couchbasev2.CouchbaseEncryptionKeyUsage{
			Configuration: false,
			Key:           false,
			Log:           false,
			Audit:         false,
			AllBuckets:    true,
		}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/Usage", []string{"bucket-encryption"}), 1*time.Minute)
	})

	t.Run("TestAutoGeneratedSettings", func(t *testing.T) {
		// Test 1: Enable auto rotation with 30 day interval and future start time
		futureTime := metav1.NewTime(time.Now().Add(24 * time.Hour))
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/autoGenerated", &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{
			Rotation: &couchbasev2.CouchbaseEncryptionKeyRotation{
				IntervalDays: 30,
				StartTime:    &futureTime,
			},
			CanBeCached: true,
		}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/AutoGenerated/NextRotationTime", futureTime.Format(time.RFC3339)).Test("/EncryptionKey/AutoGenerated/RotationIntervalInDays", 30).Test("/EncryptionKey/AutoGenerated/CanBeCached", true), 1*time.Minute)
	})
}

// mustCreateEncryptedBucketEncryptionKey creates an auto-generated encryption key for bucket encryption testing.
func mustCreateEncryptedBucketEncryptionKey(t *testing.T, k8s *types.Cluster, name string) *couchbasev2.CouchbaseEncryptionKey {
	key := &couchbasev2.CouchbaseEncryptionKey{
		ObjectMeta: metav1.ObjectMeta{
			Name: name,
		},
		Spec: couchbasev2.CouchbaseEncryptionKeySpec{
			KeyType:       couchbasev2.CouchbaseEncryptionKeyTypeAutoGenerated,
			AutoGenerated: &couchbasev2.CouchbaseEncryptionKeyAutoGenerated{},
			Usage: &couchbasev2.CouchbaseEncryptionKeyUsage{
				Configuration:          true,
				Key:                    true,
				Log:                    true,
				Audit:                  true,
				AllBuckets:             false, // We want to specifically assign this key to bucket
				ManagedBucketSelection: true,  // Allow selection for managed buckets
			},
		},
	}

	createdKey, err := k8s.CRClient.CouchbaseV2().CouchbaseEncryptionKeys(k8s.Namespace).Create(context.TODO(), key, metav1.CreateOptions{})
	if err != nil {
		e2eutil.Die(t, fmt.Errorf("failed to create encryption key %s: %w", name, err))
	}

	return createdKey
}

// Tests creation of a cluster with encryption at rest and an encrypted bucket
// 1. Creates an auto-generated encryption key
// 2. Creates a Couchbase cluster with encryption at rest enabled
// 3. Creates a bucket that uses the encryption key
// 4. Validates that the cluster, key, and bucket are properly created.
// 5. Validates that we can edit encryption settings.
func TestCreateEncryptedBucket(t *testing.T) {
	// Platform configuration.
	f := framework.Global

	kubernetes, cleanup := f.SetupTest(t)
	defer cleanup()

	// Encryption at rest requires Couchbase Server 8.0+
	framework.Requires(t, kubernetes).AtLeastVersion("8.0.0")

	// Static configuration.
	clusterSize := 3

	// Create the cluster with encryption at rest enabled
	cluster := clusterOptions().WithEphemeralTopology(clusterSize).Generate(kubernetes)
	cluster.Spec.Security.EncryptionAtRest = &couchbasev2.EncryptionAtRestSpec{
		Managed: true,
		Configuration: &couchbasev2.EncryptionAtRestUsageConfiguration{
			Enabled: true, // Required for auto-generated keys
		},
	}

	cluster = e2eutil.MustNewClusterFromSpec(t, kubernetes, cluster)

	// Create encryption key
	encryptionKeyName := "test-bucket-encryption-key"
	key := mustCreateEncryptedBucketEncryptionKey(t, kubernetes, encryptionKeyName)

	// Wait for the encryption key to be created in the cluster
	e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyCreatedEvent(cluster, key.Name), 2*time.Minute)
	e2eutil.MustAssertEncryptionKeyExists(t, kubernetes, cluster, key.Name)

	// Create an encrypted bucket using the encryption key
	bucket := e2espec.DefaultBucket()
	bucket.Name = "test-encrypted-bucket"
	bucket.Spec.Replicas = 0
	bucket.Spec.EncryptionAtRest = &couchbasev2.BucketEncryptionAtRestConfiguration{
		KeyName: encryptionKeyName,
	}

	createdBucket := e2eutil.MustNewBucket(t, kubernetes, bucket)
	e2eutil.MustWaitUntilBucketExists(t, kubernetes, cluster, createdBucket, 2*time.Minute)

	keyID := e2eutil.MustGetEncryptionKeyID(t, kubernetes, cluster, encryptionKeyName)

	t.Run("TestBucketEncryptedWithKey", func(t *testing.T) {
		time.Sleep(2 * time.Minute)
		e2eutil.MustPatchBucketInfo(t, kubernetes, cluster, createdBucket.GetName(), jsonpatch.NewPatchSet().Test("/EncryptionAtRestKeyID", &keyID), time.Minute)
	})

	rotationInterval := time.Hour * 24 * 11
	rotationIntervalSeconds := int(rotationInterval.Seconds())
	createdBucket = e2eutil.MustPatchBucket(t, kubernetes, createdBucket, jsonpatch.NewPatchSet().Replace("/spec/encryptionAtRest/rotationInterval", &metav1.Duration{Duration: rotationInterval}), time.Minute)
	e2eutil.MustPatchBucketInfo(t, kubernetes, cluster, createdBucket.GetName(), jsonpatch.NewPatchSet().Test("/EncryptionAtRestDekRotationInterval", &rotationIntervalSeconds), 2*time.Minute)

	lifetime := time.Hour * 24 * 44
	lifetimeSeconds := int(lifetime.Seconds())
	createdBucket = e2eutil.MustPatchBucket(t, kubernetes, createdBucket, jsonpatch.NewPatchSet().Replace("/spec/encryptionAtRest/keyLifetime", &metav1.Duration{Duration: lifetime}), time.Minute)
	e2eutil.MustPatchBucketInfo(t, kubernetes, cluster, createdBucket.GetName(), jsonpatch.NewPatchSet().Test("/EncryptionAtRestDekLifetime", &lifetimeSeconds), 2*time.Minute)

	// Check the events match what we expect:
	// * Cluster created
	// * Encryption key created
	// * Bucket created
	expectedEvents := []eventschema.Validatable{
		e2eutil.ClusterCreateSequence(clusterSize),
		eventschema.Event{Reason: k8sutil.EventReasonEncryptionKeyCreated},
		eventschema.Event{Reason: k8sutil.EventReasonBucketCreated},
		// Once the bucket is created the encryption key needs to add a usage for the bucket
		eventschema.Event{Reason: k8sutil.EventReasonEncryptionKeyUpdated},
		// Once the usage is added the bucket can use the key
		eventschema.Event{Reason: k8sutil.EventReasonBucketEdited},

		eventschema.Repeat{Times: 2, Validator: eventschema.Event{Reason: k8sutil.EventReasonBucketEdited}},
	}
	ValidateEvents(t, kubernetes, cluster, expectedEvents)
}

func TestCreateUseDeleteAutoGeneratedEncryptionKey(t *testing.T) {
	// Platform configuration.
	f := framework.Global

	kubernetes, cleanup := f.SetupTest(t)
	defer cleanup()

	framework.Requires(t, kubernetes).AtLeastVersion("8.0.0")

	// Static configuration.
	clusterSize := 1

	// Create the cluster with encryption at rest disabled initially
	cluster := clusterOptions().WithEphemeralTopology(clusterSize).Generate(kubernetes)
	cluster.Spec.Security.EncryptionAtRest = &couchbasev2.EncryptionAtRestSpec{
		Managed: true,
	}

	cluster = e2eutil.MustNewClusterFromSpec(t, kubernetes, cluster)

	// Create encryption key
	key := mustCreateAutoGeneratedEncryptionKey(t, kubernetes, "encryption-key")

	e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyCreatedEvent(cluster, key.Name), 2*time.Minute)
	e2eutil.MustAssertEncryptionKeyExists(t, kubernetes, cluster, key.Name)

	t.Run("TestEncryptionKeyFinalizerExists", func(t *testing.T) {
		e2eutil.MustAssertEncryptionKeyFinalizerExists(t, kubernetes, cluster, key.Name)
	})

	t.Run("TestUseKeyForAuditEncryption", func(t *testing.T) {
		cluster = e2eutil.MustPatchCluster(t, kubernetes, cluster, jsonpatch.NewPatchSet().Replace("/spec/security/encryptionAtRest/audit", &couchbasev2.EncryptionAtRestUsageConfiguration{Enabled: true, KeyName: key.Name}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.ClusterSettingsEditedEvent(cluster, "audit encryption at rest"), 2*time.Minute)
		e2eutil.MustPatchEncryptionAtRestSettings(t, kubernetes, cluster, jsonpatch.NewPatchSet().Test("/Audit/EncryptionMethod", couchbaseutil.EncryptionMethodEncryptionKey), 2*time.Minute)
	})

	t.Run("TestEncryptionKeyFinalizerExists", func(t *testing.T) {
		e2eutil.MustAssertEncryptionKeyFinalizerExists(t, kubernetes, cluster, key.Name)
	})

	t.Run("TestStopUseKeyForAuditEncryption", func(t *testing.T) {
		cluster = e2eutil.MustPatchCluster(t, kubernetes, cluster, jsonpatch.NewPatchSet().Remove("/spec/security/encryptionAtRest/audit"), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.ClusterSettingsEditedEvent(cluster, "audit encryption at rest"), 2*time.Minute)
		e2eutil.MustPatchEncryptionAtRestSettings(t, kubernetes, cluster, jsonpatch.NewPatchSet().Test("/Audit/EncryptionMethod", couchbaseutil.EncryptionMethodDisabled), 2*time.Minute)
	})

	t.Run("TestEncryptionKeyFinalizerExists", func(t *testing.T) {
		e2eutil.MustAssertEncryptionKeyFinalizerExists(t, kubernetes, cluster, key.Name)
	})

	t.Run("TestDeleteEncryptionKey", func(t *testing.T) {
		e2eutil.MustDeleteEncryptionKey(t, kubernetes, key)
		e2eutil.MustWaitForEncryptionKeyDeletion(t, kubernetes, key, 2*time.Minute)
	})
}

func TestCreateUseWithBucketDeleteAutoGeneratedEncryptionKey(t *testing.T) {
	// Platform configuration.
	f := framework.Global

	kubernetes, cleanup := f.SetupTest(t)
	defer cleanup()

	framework.Requires(t, kubernetes).AtLeastVersion("8.0.0")

	// Static configuration.
	clusterSize := 1

	// Create the cluster with encryption at rest disabled initially
	cluster := clusterOptions().WithEphemeralTopology(clusterSize).Generate(kubernetes)
	cluster.Spec.Security.EncryptionAtRest = &couchbasev2.EncryptionAtRestSpec{
		Managed: true,
	}

	cluster = e2eutil.MustNewClusterFromSpec(t, kubernetes, cluster)

	// Create encryption key
	encryptionKeyName := "encryption-key"
	key := mustCreateAutoGeneratedEncryptionKey(t, kubernetes, encryptionKeyName)

	e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyCreatedEvent(cluster, key.Name), 2*time.Minute)
	e2eutil.MustAssertEncryptionKeyExists(t, kubernetes, cluster, key.Name)

	// Create bucket
	bucket := e2espec.DefaultBucket()
	bucket.Name = "test-encrypted-bucket"
	bucket.Spec.Replicas = 0
	bucket.Spec.EncryptionAtRest = &couchbasev2.BucketEncryptionAtRestConfiguration{
		KeyName: encryptionKeyName,
	}

	createdBucket := e2eutil.MustNewBucket(t, kubernetes, bucket)
	e2eutil.MustWaitUntilBucketExists(t, kubernetes, cluster, createdBucket, 2*time.Minute)

	keyID := e2eutil.MustGetEncryptionKeyID(t, kubernetes, cluster, encryptionKeyName)
	e2eutil.MustPatchBucketInfo(t, kubernetes, cluster, bucket.GetName(), jsonpatch.NewPatchSet().Test("/EncryptionAtRestKeyID", &keyID), time.Minute)

	t.Run("TestEncryptionKeyFinalizerExists", func(t *testing.T) {
		e2eutil.MustAssertEncryptionKeyFinalizerExists(t, kubernetes, cluster, key.Name)
	})

	t.Run("TestStopUseKeyForBucket", func(t *testing.T) {
		noKeyID := -1
		createdBucket = e2eutil.MustPatchBucket(t, kubernetes, createdBucket, jsonpatch.NewPatchSet().Remove("/spec/encryptionAtRest"), time.Minute)
		e2eutil.MustPatchBucketInfo(t, kubernetes, cluster, createdBucket.GetName(), jsonpatch.NewPatchSet().Test("/EncryptionAtRestKeyID", &noKeyID), 2*time.Minute)
	})

	t.Run("TestDeleteEncryptionKey", func(t *testing.T) {
		e2eutil.MustDeleteEncryptionKey(t, kubernetes, key)
		time.Sleep(30 * time.Second)

		// If the key is not deleted then the bucket still has data encrypted with the key
		keyDeleted := e2eutil.CheckIfEncryptionKeyIsDeleted(t, kubernetes, key)
		if !keyDeleted {
			e2eutil.MustAssertEncryptionKeyFinalizerExists(t, kubernetes, cluster, key.Name)

			// Delete the bucket
			e2eutil.MustDeleteBucket(t, kubernetes, createdBucket)
			e2eutil.MustWaitUntilBucketNotExists(t, kubernetes, cluster, createdBucket.GetName(), 2*time.Minute)
			time.Sleep(30 * time.Second)
		}

		e2eutil.MustWaitForEncryptionKeyDeletion(t, kubernetes, key, 2*time.Minute)
	})
}

func TestCreateEditAWSKey(t *testing.T) {
	// Platform configuration.
	f := framework.Global

	kubernetes, cleanup := f.SetupTest(t)
	defer cleanup()

	framework.Requires(t, kubernetes).AtLeastVersion("8.0.0")

	// Static configuration.
	clusterSize := 1

	// Create the cluster with encryption at rest enabled
	cluster := clusterOptions().WithEphemeralTopology(clusterSize).Generate(kubernetes)
	cluster.Spec.Security.EncryptionAtRest = &couchbasev2.EncryptionAtRestSpec{
		Managed: true,
	}

	cluster = e2eutil.MustNewClusterFromSpec(t, kubernetes, cluster)

	// Create encryption keys
	key := mustCreateAutoGeneratedAWSKey(t, kubernetes, "aws-key")

	e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyCreatedEvent(cluster, key.Name), 2*time.Minute)
	e2eutil.MustAssertEncryptionKeyExists(t, kubernetes, cluster, key.Name)

	t.Run("TestSetConfigurationUsage", func(t *testing.T) {
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/usage", &couchbasev2.CouchbaseEncryptionKeyUsage{
			Configuration: true,
			Key:           false,
			Log:           false,
			Audit:         false,
			AllBuckets:    false,
		}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/Usage", []string{"config-encryption"}), 1*time.Minute)
	})

	t.Run("TestSetKeyUsage", func(t *testing.T) {
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/usage", &couchbasev2.CouchbaseEncryptionKeyUsage{
			Configuration: false,
			Key:           true,
			Log:           false,
			Audit:         false,
			AllBuckets:    false,
		}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/Usage", []string{"KEK-encryption"}), 1*time.Minute)
	})

	t.Run("TestSetLogUsage", func(t *testing.T) {
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/usage", &couchbasev2.CouchbaseEncryptionKeyUsage{
			Configuration: false,
			Key:           false,
			Log:           true,
			Audit:         false,
			AllBuckets:    false,
		}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/Usage", []string{"log-encryption"}), 1*time.Minute)
	})

	t.Run("TestSetAuditUsage", func(t *testing.T) {
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/usage", &couchbasev2.CouchbaseEncryptionKeyUsage{
			Configuration: false,
			Key:           false,
			Log:           false,
			Audit:         true,
			AllBuckets:    false,
		}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/Usage", []string{"audit-encryption"}), 1*time.Minute)
	})

	t.Run("TestSetAllBucketsUsage", func(t *testing.T) {
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/usage", &couchbasev2.CouchbaseEncryptionKeyUsage{
			Configuration: false,
			Key:           false,
			Log:           false,
			Audit:         false,
			AllBuckets:    true,
		}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/Usage", []string{"bucket-encryption"}), 1*time.Minute)
	})

	t.Run("TestAWSKeyChangeUseIMDS", func(t *testing.T) {
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/awsKey/useIMDS", true), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/AWS/UseIMDS", true), 1*time.Minute)
	})

	t.Run("TestAWSKeyAddCredentialsSecret", func(t *testing.T) {
		credentialsContent := "mock-credentials"

		credentialsSecret := corev1.Secret{
			ObjectMeta: metav1.ObjectMeta{
				Name: "aws-credentials",
			},
			Data: map[string][]byte{
				"credentials": []byte(credentialsContent),
			},
		}

		e2eutil.MustCreateSecret(t, kubernetes, &credentialsSecret)

		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/awsKey/credentialsSecret", "aws-credentials"), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		expectedCredentialsPath := "/opt/couchbase/var/lib/couchbase/key/aws-credentials-credentials"
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/AWS/CredentialsFile", expectedCredentialsPath), 1*time.Minute)

		podName := couchbaseutil.CreateMemberName(cluster.Name, 0)

		mustCheckFileContents(t, kubernetes, podName, credentialsContent, expectedCredentialsPath)
	})
}

func TestCreateEditKMIPKey(t *testing.T) {
	// Platform configuration.
	f := framework.Global

	kubernetes, cleanup := f.SetupTest(t)
	defer cleanup()

	framework.Requires(t, kubernetes).AtLeastVersion("8.0.0")

	// Static configuration.
	clusterSize := 1

	// Create the cluster with encryption at rest enabled
	cluster := clusterOptions().WithEphemeralTopology(clusterSize).Generate(kubernetes)
	cluster.Spec.Security.EncryptionAtRest = &couchbasev2.EncryptionAtRestSpec{
		Managed: true,
	}

	cluster = e2eutil.MustNewClusterFromSpec(t, kubernetes, cluster)

	// Create encryption keys
	key, originalSecret := mustCreateAutoGeneratedKMIPKey(t, kubernetes, "kmip-key")

	e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyCreatedEvent(cluster, key.Name), 2*time.Minute)
	e2eutil.MustAssertEncryptionKeyExists(t, kubernetes, cluster, key.Name)

	t.Run("TestSetConfigurationUsage", func(t *testing.T) {
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/usage", &couchbasev2.CouchbaseEncryptionKeyUsage{
			Configuration: true,
			Key:           false,
			Log:           false,
			Audit:         false,
			AllBuckets:    false,
		}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/Usage", []string{"config-encryption"}), 1*time.Minute)
	})

	t.Run("TestSetKeyUsage", func(t *testing.T) {
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/usage", &couchbasev2.CouchbaseEncryptionKeyUsage{
			Configuration: false,
			Key:           true,
			Log:           false,
			Audit:         false,
			AllBuckets:    false,
		}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/Usage", []string{"KEK-encryption"}), 1*time.Minute)
	})

	t.Run("TestSetLogUsage", func(t *testing.T) {
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/usage", &couchbasev2.CouchbaseEncryptionKeyUsage{
			Configuration: false,
			Key:           false,
			Log:           true,
			Audit:         false,
			AllBuckets:    false,
		}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/Usage", []string{"log-encryption"}), 1*time.Minute)
	})

	t.Run("TestSetAuditUsage", func(t *testing.T) {
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/usage", &couchbasev2.CouchbaseEncryptionKeyUsage{
			Configuration: false,
			Key:           false,
			Log:           false,
			Audit:         true,
			AllBuckets:    false,
		}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/Usage", []string{"audit-encryption"}), 1*time.Minute)
	})

	t.Run("TestSetAllBucketsUsage", func(t *testing.T) {
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/usage", &couchbasev2.CouchbaseEncryptionKeyUsage{
			Configuration: false,
			Key:           false,
			Log:           false,
			Audit:         false,
			AllBuckets:    true,
		}), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/Usage", []string{"bucket-encryption"}), 1*time.Minute)
	})

	t.Run("TestKMIPKeyChangeHost", func(t *testing.T) {
		newHost := "dummy-host"
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/kmipKey/host", newHost), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/KMIP/Host", newHost), 1*time.Minute)
	})

	t.Run("TestKMIPKeyChangePort", func(t *testing.T) {
		newPort := 1637
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/kmipKey/port", newPort), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/KMIP/Port", newPort), 1*time.Minute)
	})

	t.Run("TestKMIPKeyChangeTimeoutInMs", func(t *testing.T) {
		newTimeoutInMs := key.Spec.KMIPKey.TimeoutInMs + 11
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/kmipKey/timeoutInMs", newTimeoutInMs), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/KMIP/ReqTimeoutMs", newTimeoutInMs), 1*time.Minute)
	})

	t.Run("TestKMIPKeyCASkipSelection", func(t *testing.T) {
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/kmipKey/verifyWithSystemCA", false).Replace("/spec/kmipKey/verifyWithCouchbaseCA", false), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/KMIP/CASelection", couchbaseutil.CASelectionSkip), 1*time.Minute)
	})

	t.Run("TestKMIPKeyCASystemSelection", func(t *testing.T) {
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/kmipKey/verifyWithSystemCA", true).Replace("/spec/kmipKey/verifyWithCouchbaseCA", false), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/KMIP/CASelection", couchbaseutil.CASelectionSystem), 1*time.Minute)
	})

	t.Run("TestKMIPKeyCACouchbaseSelection", func(t *testing.T) {
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/kmipKey/verifyWithCouchbaseCA", true).Replace("/spec/kmipKey/verifyWithSystemCA", false), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/KMIP/CASelection", couchbaseutil.CASelectionCouchbase), 1*time.Minute)
	})

	t.Run("TestKMIPKeyCASelectionBothSelection", func(t *testing.T) {
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/kmipKey/verifyWithSystemCA", true).Replace("/spec/kmipKey/verifyWithCouchbaseCA", true), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/KMIP/CASelection", couchbaseutil.CASelectionBoth), 1*time.Minute)
	})

	t.Run("TestKMIPKeyChangeEncryptionApproach", func(t *testing.T) {
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/kmipKey/encryptionApproach", couchbasev2.CouchbaseEncryptionApproachLocalEncrypt), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/KMIP/EncryptionApproach", couchbaseutil.EncryptionApproachLocalEncrypt), 1*time.Minute)
	})

	t.Run("TestKMIPKeyChangeKeyID", func(t *testing.T) {
		newKeyID := "dummy-key-id"
		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/kmipKey/keyID", newKeyID), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, key.Name, jsonpatch.NewPatchSet().Test("/EncryptionKey/KMIP/ActiveKey/KMIPID", newKeyID), 1*time.Minute)
	})

	t.Run("TestKMIPKeyRotateClientSecret", func(t *testing.T) {
		passphrase := "couchbase12"

		clusterKey, clusterCert, err := mustGenerateKeyCertPair(t, passphrase)
		if err != nil {
			e2eutil.Die(t, fmt.Errorf("failed to generate key cert pair: %w", err))
		}

		originalSecret.Data = map[string][]byte{
			"passphrase": []byte(passphrase),
			"tls.crt":    clusterCert,
			"tls.key":    clusterKey,
		}

		e2eutil.MustUpdateSecret(t, kubernetes, originalSecret)

		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/kmipKey/clientSecret", originalSecret.Name), time.Minute)

		validateKMIPKeyAndPassphrase(t, kubernetes, cluster, key.Name, originalSecret)
	})

	t.Run("TestKMIPKeyChangeClientSecret", func(t *testing.T) {
		passphrase := "couchbase"

		clientKey, clientCert, err := mustGenerateKeyCertPair(t, passphrase)
		if err != nil {
			e2eutil.Die(t, fmt.Errorf("failed to generate key cert pair: %w", err))
		}

		newClientSecret := "kmip-client-secret-2"
		secret := &corev1.Secret{
			ObjectMeta: metav1.ObjectMeta{
				Name: newClientSecret,
			},
			Data: map[string][]byte{
				"passphrase": []byte(passphrase),
				"tls.crt":    clientCert,
				"tls.key":    clientKey,
			},
		}

		secret = e2eutil.MustCreateSecret(t, kubernetes, secret)

		key = e2eutil.MustPatchEncryptionKey(t, kubernetes, key, jsonpatch.NewPatchSet().Replace("/spec/kmipKey/clientSecret", newClientSecret), time.Minute)
		e2eutil.MustWaitForClusterEvent(t, kubernetes, cluster, e2eutil.NewEncryptionKeyUpdatedEvent(cluster, key.Name), 2*time.Minute)
		validateKMIPKeyAndPassphrase(t, kubernetes, cluster, key.Name, secret)
	})
}

func validateKMIPKeyAndPassphrase(t *testing.T, kubernetes *types.Cluster, cluster *couchbasev2.CouchbaseCluster, keyName string, secret *corev1.Secret) {
	expectedKeyPath := "/opt/couchbase/var/lib/couchbase/key/" + secret.Name + "-tls.key"
	expectedCertPath := "/opt/couchbase/var/lib/couchbase/key/" + secret.Name + "-tls.crt"

	e2eutil.MustPatchEncryptionKeySettings(t, kubernetes, cluster, keyName, jsonpatch.NewPatchSet().Test("/EncryptionKey/KMIP/KeyPath", expectedKeyPath).Test("/EncryptionKey/KMIP/CertPath", expectedCertPath), 1*time.Minute)

	podName := couchbaseutil.CreateMemberName(cluster.Name, 0)
	mustCheckFileContents(t, kubernetes, podName, string(secret.Data["tls.key"]), expectedKeyPath)
	mustCheckFileContents(t, kubernetes, podName, string(secret.Data["tls.crt"]), expectedCertPath)
}

func mustCheckFileContents(t *testing.T, k8s *types.Cluster, podName string, content string, filePath string) {
	err := retryutil.RetryFor(2*time.Minute, func() error {
		cmd := "cat " + filePath
		stdout, _, err := e2eutil.ExecShellInPod(k8s, podName, cmd)

		if err != nil {
			return err
		}

		// Ignore possible trailing newlines
		if len(content) == (len(stdout)+1) && content[len(content)-1] == '\n' {
			content = content[:len(content)-1]
		}

		if content != stdout {
			return fmt.Errorf("file contents do not match: %s", stdout)
		}

		return nil
	})

	if err != nil {
		e2eutil.Die(t, fmt.Errorf("file contents check failed: %w", err))
	}
}
