#!/usr/bin/env bash

# Copyright 2018-Present Couchbase, Inc.
#
# Use of this software is governed by the Business Source License included in
# the file licenses/BSL-Couchbase.txt.  As of the Change Date specified in that
# file, in accordance with the Business Source License, use of this software
# will be governed by the Apache License, Version 2.0, included in the file
# licenses/APL2.txt.

# Generate go code to report git information
#
# Useful when testers raise defects against unversioned snapshots.
# We can recreate on the specific revision the defect was reported
# against and easily check whether the defect has been fixed upstream

mkdir -p pkg/revision
cat > pkg/revision/revision.go <<EOF
package revision

const (
	gitBranch   = "$(git symbolic-ref --short HEAD 2> /dev/null)"
	gitRevision = "$(git rev-parse HEAD 2> /dev/null)"
)
EOF

# vi: ts=8 noet:
